#!/usr/bin/env npx tsx
/* ═══════════════════════════════════════════════════════
   STRIP VO STAGE DIRECTIONS

   Walks every `apps/scripts/*-lines.json` voice-bank file and
   rewrites entries whose `text` field opens with producer-facing
   stage directions — `[CUE 0:00]`, `[Voice direction: warm, …]`,
   `[SPOKEN]`, `[PATH-A VARIANT.]`, etc. ElevenLabs Multilingual v2
   does not interpret bracketed prose as direction; it reads the
   cue card out loud before the real line.

   For every line we strip:

     • `text`         — the spoken version (what TTS will say)
     • `directionNotes` — set to the original text so the producer
                          note is preserved on the record for audit
                          / future re-record. Only set when the line
                          actually had a bracket prefix.

   The script is idempotent: re-running it on already-stripped JSON
   leaves it untouched. It writes nothing when no changes are
   needed. Manifests are NOT regenerated by this script — re-run
   the relevant `pnpm vo:*` generator afterwards to refresh the
   audio. See README at the top of `apps/shared/voSpokenText.ts`
   for the canonical strip rules.

   Usage:
     pnpm tsx apps/scripts/strip-vo-stage-directions.ts          # apply
     pnpm tsx apps/scripts/strip-vo-stage-directions.ts --dry    # report only
   ═══════════════════════════════════════════════════════ */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spokenText, hasStageDirection } from "../shared/voSpokenText";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SCRIPTS_DIR = __dirname;
const DRY = process.argv.includes("--dry");

interface LineEntry {
  id?: string;
  text?: string;
  directionNotes?: string;
  [k: string]: unknown;
}

function processFile(filePath: string): { changed: number; total: number } {
  const raw = fs.readFileSync(filePath, "utf8");
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { changed: 0, total: 0 };
  }
  if (!Array.isArray(parsed)) return { changed: 0, total: 0 };

  let changed = 0;
  const total = parsed.length;
  for (const entryUnknown of parsed) {
    const entry = entryUnknown as LineEntry;
    if (typeof entry?.text !== "string") continue;
    if (!hasStageDirection(entry.text)) continue;
    const original = entry.text;
    const cleaned = spokenText(original);
    // Preserve producer note on the record. If a directionNotes field
    // already exists (re-run after a partial cleanup), keep the older
    // one — the original direction is the canonical record.
    if (entry.directionNotes === undefined) {
      entry.directionNotes = original;
    }
    entry.text = cleaned;
    changed++;
  }

  if (changed > 0 && !DRY) {
    // Match the pretty-printed JSON style already in the repo (2-space
    // indent + trailing newline). JSON.stringify with `null, 2`
    // matches what the per-character VO generators emit.
    fs.writeFileSync(filePath, JSON.stringify(parsed, null, 2) + "\n", "utf8");
  }

  return { changed, total };
}

function main() {
  const files = fs.readdirSync(SCRIPTS_DIR)
    .filter(name => name.endsWith("-lines.json"))
    .map(name => path.join(SCRIPTS_DIR, name));

  let touchedFiles = 0;
  let touchedLines = 0;

  console.log(`Scanning ${files.length} voice-bank files${DRY ? " (dry run)" : ""}…`);

  for (const file of files) {
    const { changed, total } = processFile(file);
    if (changed > 0) {
      touchedFiles++;
      touchedLines += changed;
      console.log(`  ${path.basename(file)} — stripped ${changed}/${total}`);
    }
  }

  console.log(`\nDone. Stripped ${touchedLines} line${touchedLines === 1 ? "" : "s"} across ${touchedFiles} file${touchedFiles === 1 ? "" : "s"}.`);
  if (touchedLines > 0 && !DRY) {
    console.log("\nNext: re-run the affected pnpm vo:* generators to refresh");
    console.log("the audio manifests. Existing MP3s on S3 still contain the");
    console.log("spoken cue cards until they're regenerated.");
  }
}

main();
