import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import eslintConfigPrettier from "eslint-config-prettier";

// Node globals for scripts, server, and drizzle config. These files
// run under Node, so `console`, `process`, `Buffer`, `__dirname`, and
// timers should resolve without no-undef errors.
const NODE_GLOBALS = {
  console: "readonly",
  process: "readonly",
  Buffer: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  global: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  setImmediate: "readonly",
  clearImmediate: "readonly",
  require: "readonly",
  module: "readonly",
  exports: "writable",
  URL: "readonly",
  URLSearchParams: "readonly",
  fetch: "readonly",
  TextEncoder: "readonly",
  TextDecoder: "readonly",
};

export default tseslint.config(
  {
    ignores: [
      "dist/",
      "node_modules/",
      "**/*.test.ts",
      "dischordian-saga-full-source.txt",
      // ── Compiled / vendored output ─────────────────────────
      // Godot HTML5 exports live under apps/client/public/games/*
      // and account for ~3700 of the linter's complaints on their
      // own. They're generated by the Godot toolchain, not
      // hand-authored, and re-linting them gains nothing.
      "apps/client/public/games/**",
      // Service worker is generated at build time.
      "apps/client/public/sw.js",
      // ── Seed + admin scripts ──────────────────────────────
      // .mjs seeds pre-date the flat-config migration and use loose
      // conventions (var, console, no types). Linting them would be
      // ~140 false positives; fix separately if ever rewritten.
      "apps/server/seed-*.mjs",
      "apps/server/**/*.mjs",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node runtime contexts: scripts, drizzle config, server code,
    // and runtime-agnostic shared code. apps/shared/** runs under
    // both Node (server + vitest) and the browser bundle, but it
    // uses console/process/Buffer freely, so it needs the Node
    // globals list to resolve no-undef. Vite + TypeScript catch any
    // actually-browser-hostile patterns at build time.
    files: [
      "apps/scripts/**/*.{ts,mts,cts,js,mjs,cjs}",
      "apps/server/**/*.{ts,mts,cts,js,mjs,cjs}",
      "apps/shared/**/*.{ts,mts,cts,js,mjs,cjs}",
      "apps/db/**/*.{ts,mts,cts,js,mjs,cjs}",
      "scripts/**/*.{ts,mts,cts,js,mjs,cjs}",
      "drizzle.config.ts",
      "vite.config.ts",
      "vitest.config.ts",
      "eslint.config.js",
    ],
    languageOptions: {
      globals: NODE_GLOBALS,
    },
  },
  {
    // Browser runtime context: client code.
    files: ["apps/client/**/*.{ts,tsx,js,jsx}"],
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        WebSocket: "readonly",
        MessageEvent: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLAudioElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLAnchorElement: "readonly",
        Image: "readonly",
        Audio: "readonly",
        AudioContext: "readonly",
        GainNode: "readonly",
        OscillatorNode: "readonly",
        AudioBuffer: "readonly",
        AudioBufferSourceNode: "readonly",
        BiquadFilterNode: "readonly",
        AnalyserNode: "readonly",
        Worker: "readonly",
        ServiceWorker: "readonly",
        performance: "readonly",
        matchMedia: "readonly",
        MediaQueryList: "readonly",
        crypto: "readonly",
        CryptoKey: "readonly",
        SubtleCrypto: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        atob: "readonly",
        btoa: "readonly",
        globalThis: "readonly",
        self: "readonly",
        structuredClone: "readonly",
        ClipboardItem: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        TouchEvent: "readonly",
        PointerEvent: "readonly",
        WheelEvent: "readonly",
        DragEvent: "readonly",
        Node: "readonly",
        NodeListOf: "readonly",
        Element: "readonly",
        DocumentFragment: "readonly",
        CSSStyleDeclaration: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        process: "readonly",
        __dirname: "readonly",
      },
    },
  },
  {
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Demoted from default "error" to "warn": the codebase uses `any`
      // extensively for runtime-flex patterns (tRPC input passthrough,
      // drizzle result casts, Game engine state bags) that would take
      // dozens of hours to type properly. Keeping it visible as a warning
      // so new `any` usage gets flagged in review without blocking CI.
      "@typescript-eslint/no-explicit-any": "warn",
      // Allow empty catch blocks — we intentionally swallow errors in
      // many places where fallback behaviour handles the failure path.
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      // Allow `== null` / `!= null` — the classic check for "not
      // null AND not undefined". All other equality must be strict.
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "prefer-const": "error",
    },
  },
  {
    // Scripts and server code genuinely use console for logging;
    // forcing console.warn/error everywhere would add noise. We
    // still flag console.log in client code via the default rule.
    // This override is last so it wins over the global rules block.
    files: [
      "apps/scripts/**/*.{ts,mts,cts,js,mjs,cjs}",
      "apps/server/**/*.{ts,mts,cts,js,mjs,cjs}",
      "apps/db/**/*.{ts,mts,cts,js,mjs,cjs}",
      "drizzle.config.ts",
      "vite.config.ts",
      "vitest.config.ts",
      "eslint.config.js",
    ],
    rules: {
      "no-console": "off",
    },
  },
  eslintConfigPrettier
);
