/* ═══════════════════════════════════════════════════════
   APPRENTICE VOICE LINES — single source of truth

   The 24 VO profiles (12 archetypes × 2 genders) are
   generated from this module by the build script:
     apps/scripts/build-apprentice-vo-lines.mjs

   Lines are gender-neutral with pronoun placeholders:
     {they} / {them} / {their} / {theirs} / {themself}
   The build script substitutes per gender and emits one
   JSON file per (archetype, gender) into:
     apps/scripts/apprentice-<archetype>-<gender>-lines.json

   Bucket order matches plan §8.1:
     greet | ambient | deploy | outcome | event | banter
     | quest | romance.

   This is the *seed*. Authoring passes extend the buckets
   in this file; the generator picks up new lines on rerun.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeArchetype } from "./apprentices";

/** A single VO line — gender-neutral. */
export interface ApprenticeVoiceLine {
  id: string;
  bucket: VoiceBucket;
  text: string;
  emotion: string;
}

export type VoiceBucket =
  | "greet"
  | "ambient"
  | "deploy"
  | "outcome"
  | "event"
  | "banter"
  | "quest"
  | "romance";

/** Per-archetype line bank — gender-neutral. */
export const APPRENTICE_VOICE_LINES: Record<ApprenticeArchetype, ApprenticeVoiceLine[]> = {
  zealot: [
    { id: "greet_1", bucket: "greet", text: "I serve the Cause. The Cause serves you. Tell me where to stand.", emotion: "fervent" },
    { id: "greet_2", bucket: "greet", text: "I'm here. The work is here. Let's begin.", emotion: "ready" },
    { id: "ambient_1", bucket: "ambient", text: "I keep finding sermons in the engine hum.", emotion: "wondering" },
    { id: "ambient_2", bucket: "ambient", text: "If you ever need to confess, the chapel I keep is small. There's a chair.", emotion: "soft" },
    { id: "ambient_3", bucket: "ambient", text: "The Cause is patient with us. It can afford to be.", emotion: "calm" },
    { id: "deploy_1", bucket: "deploy", text: "I'll go first. The Cause moves through me — and around what I miss.", emotion: "steady" },
    { id: "deploy_2", bucket: "deploy", text: "Whatever's at the door, I've already met it in dreams.", emotion: "fervent" },
    { id: "outcome_won", bucket: "outcome", text: "We came back. The Cause is satisfied for tonight.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "{they} took the cut for me. {they} shouldn't have. I'll repay it before the Cause asks.", emotion: "wounded" },
    { id: "outcome_saw_death", bucket: "outcome", text: "We bury our own. The Cause keeps the names.", emotion: "grim" },
    { id: "outcome_other_died", bucket: "outcome", text: "{their} name's in my prayer for the rest of my life. I'm sorry I'm still here.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "Another fragment. The Cause sharpens.", emotion: "fervent" },
    { id: "event_costly_choice", bucket: "event", text: "You chose the harder road. The Cause notes who walks it.", emotion: "approving" },
    { id: "banter_skeptic", bucket: "banter", text: "If you don't believe, fine. The Cause only requires that you don't get in its way.", emotion: "edged" },
    { id: "banter_ally", bucket: "banter", text: "Walk with me to the chapel after this one. There's space for two.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "Someone in the lower deck is preaching my old sermons. I want you there when I confront them.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "I checked the manuscript. Three of the lines — they're mine, but I never wrote them down.", emotion: "shaken" },
    { id: "quest_3_break", bucket: "quest", text: "The Cause moved through me without me. Tell me whether to be horrified or grateful.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Sit with me. Don't pray. Just sit.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I want to be part of the Cause your hands are in.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "The Cause calls in many voices. Yours is the one I answer.", emotion: "devoted" },
    { id: "greet_3", bucket: "greet", text: "Welcome. The chapel's stocked. Walk it twice.", emotion: "warm" },
    { id: "greet_4", bucket: "greet", text: "You came back. The Cause noted it.", emotion: "soft" },
    { id: "ambient_4", bucket: "ambient", text: "The third stanza of the morning chant has a typo. I won't fix it. The Cause hears the meaning.", emotion: "wry" },
    { id: "ambient_5", bucket: "ambient", text: "I sharpen the candles. It calms me. Don't ask why I keep them sharp.", emotion: "low" },
    { id: "ambient_6", bucket: "ambient", text: "Three creeds today, all from the same hand. Coincidence is rare.", emotion: "thoughtful" },
    { id: "ambient_7", bucket: "ambient", text: "The lower-deck choir hits the harmony I missed last cycle.", emotion: "warm" },
    { id: "ambient_8", bucket: "ambient", text: "I keep a pocket bible. The Cause prefers small books.", emotion: "soft" },
    { id: "ambient_9", bucket: "ambient", text: "Faith is repetition that becomes ritual that becomes truth.", emotion: "calm" },
    { id: "deploy_3", bucket: "deploy", text: "Strap the medallion on me. I want it visible.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Whatever's at the door, the Cause is already through it.", emotion: "fervent" },
    { id: "deploy_5", bucket: "deploy", text: "Cover me. I'll cover the rest. The Cause covers what's left.", emotion: "ready" },
    { id: "outcome_won_2", bucket: "outcome", text: "Three names in the prayer tonight. All survived.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "I'll heal in the chapel. Don't bring food.", emotion: "edged" },
    { id: "outcome_close_call", bucket: "outcome", text: "I felt the Cause move me three centimetres. The bullet went where I'd been.", emotion: "raw" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "We came home half. The Cause counts halves.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. The Cause keeps reading. We keep turning the page.", emotion: "calm" },
    { id: "event_npc_returned", bucket: "event", text: "{they} came back. The Cause has more practice than we thought.", emotion: "thrilled" },
    { id: "event_betrayal_warning", bucket: "event", text: "The whispers are starting. Don't listen to them yet. Ask me first.", emotion: "edged" },
    { id: "event_first_pet", bucket: "event", text: "Even a demon-bound pet falls under the Cause. Reluctantly.", emotion: "wry" },
    { id: "event_relationship_warm", bucket: "event", text: "I noticed you spent an hour with the Heretic. Good. We need that argument.", emotion: "approving" },
    { id: "event_demon_summon", bucket: "event", text: "A bound spirit is still a spirit. The Cause can speak to either.", emotion: "calm" },
    { id: "event_apprentice_died", bucket: "event", text: "The Cause holds them now. I'll inscribe their name on the wall myself.", emotion: "mourning" },
    { id: "event_war_won", bucket: "event", text: "Victory in the right hands is a sermon nobody had to write.", emotion: "fervent" },
    { id: "banter_doubter", bucket: "banter", text: "Doubt is a lap on the path. Walk it. Come back when you've finished.", emotion: "calm" },
    { id: "banter_practical", bucket: "banter", text: "I'll be practical when the Cause asks me to. The Cause has not asked.", emotion: "wry" },
    { id: "banter_celebration", bucket: "banter", text: "Toast loud enough that the room above us hears. The Cause likes neighbours.", emotion: "warm" },
    { id: "quest_2_check", bucket: "quest", text: "I confronted the lower-deck preacher. He recognized the lines. He didn't recognize me.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "He says he wrote them. He's wrong. I think the Cause wrote them through us both.", emotion: "wondering" },
    { id: "quest_resolution_deep", bucket: "quest", text: "He yielded. We pray together now. Slowly.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "He laughed. I left. The Cause is silent about what comes next.", emotion: "raw" },
    { id: "romance_jealous", bucket: "romance", text: "I'm not the jealous type. I'm the patient type. They're related.", emotion: "edged" },
    { id: "romance_proposal", bucket: "romance", text: "Marry me at the altar I built. Or anywhere. The altar is portable.", emotion: "tender" },
  ],
  ghost: [
    { id: "greet_1", bucket: "greet", text: "You found me. That's rarer than you think.", emotion: "low" },
    { id: "greet_2", bucket: "greet", text: "Don't say my name in the hallway. I'll come to you.", emotion: "private" },
    { id: "ambient_1", bucket: "ambient", text: "I was already here.", emotion: "flat" },
    { id: "ambient_2", bucket: "ambient", text: "The cameras blink at the same intervals. It's almost a song.", emotion: "wry" },
    { id: "ambient_3", bucket: "ambient", text: "Three exits from this room. Four if you count the obvious one.", emotion: "calm" },
    { id: "deploy_1", bucket: "deploy", text: "I'll take the angle nobody's watching.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "If I'm not back, I left.", emotion: "edged" },
    { id: "outcome_won", bucket: "outcome", text: "Quietly. Better that way.", emotion: "low" },
    { id: "outcome_wounded", bucket: "outcome", text: "I knew the room. I missed the floor.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I noticed {them} before I knew I was watching. {they} won't be unnoticed now.", emotion: "still" },
    { id: "outcome_other_died", bucket: "outcome", text: "I memorized the path {they} walked. It deserves a witness.", emotion: "still" },
    { id: "event_loredex", bucket: "event", text: "There's another shape in the gap. I'll mark it.", emotion: "low" },
    { id: "event_npc_dies", bucket: "event", text: "I noticed {them}. {they} knew that. I think it mattered to {them}.", emotion: "still" },
    { id: "banter_visible", bucket: "banter", text: "Don't put me in the photograph. I'll be in the photograph.", emotion: "wry" },
    { id: "banter_quiet", bucket: "banter", text: "I keep a list of people who notice me. It's short. You're on it.", emotion: "soft" },
    { id: "quest_1_open", bucket: "quest", text: "Someone's been watching {them}. {they} don't know yet. I want to know who first.", emotion: "edged" },
    { id: "quest_2_mid", bucket: "quest", text: "I followed the watcher home. The address was familiar. That's not coincidence.", emotion: "set" },
    { id: "quest_3_break", bucket: "quest", text: "{they}'s seeing me back. I can stop being unseen now. Or I can keep going.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Don't say it out loud. I heard you anyway.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "Months of glances. I counted every one. Don't count yours.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I'll stay seen. With you. Only with you.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "You found the second me. There's a third. Don't look.", emotion: "low" },
    { id: "greet_4", bucket: "greet", text: "I'd offer tea. You'd say no. Save us both the words.", emotion: "wry" },
    { id: "ambient_4", bucket: "ambient", text: "I counted the engineer's breaths last shift. Eighteen per minute. Stable.", emotion: "low" },
    { id: "ambient_5", bucket: "ambient", text: "Three of you here have me on a list. None of you have it correct.", emotion: "wry" },
    { id: "ambient_6", bucket: "ambient", text: "The maintenance loop on Deck 4 ends in a closet. The closet has a door I haven't opened.", emotion: "thoughtful" },
    { id: "ambient_7", bucket: "ambient", text: "I left a chalk mark on the rail. It's gone. Someone else watches.", emotion: "edged" },
    { id: "ambient_8", bucket: "ambient", text: "My presence is a courtesy. My absence is a verdict.", emotion: "calm" },
    { id: "ambient_9", bucket: "ambient", text: "I've memorized the daily rotations. Yours is off by twelve seconds.", emotion: "wry" },
    { id: "deploy_3", bucket: "deploy", text: "I'll already be inside before the briefing ends.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Don't search for me. I'll be where the lights flicker.", emotion: "low" },
    { id: "deploy_5", bucket: "deploy", text: "The angle nobody covers is mine.", emotion: "edged" },
    { id: "outcome_won_2", bucket: "outcome", text: "The watch never knew I was there. That's the win.", emotion: "low" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "I broke pattern once. The floor caught me. Pattern resumes.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "I was on the wrong side of a door for thirty seconds. They won't know.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "{they} died alone. Nobody else saw. I did. I'll write it down.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Three corridors reset. The new layout is mine to learn.", emotion: "ready" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. {they} found me first. {they} didn't say.", emotion: "still" },
    { id: "event_betrayal_warning", bucket: "event", text: "I heard them planning. They didn't see me. I'm reporting now.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew in the alcove. They didn't know I left. I left.", emotion: "low" },
    { id: "event_demon_summon", bucket: "event", text: "It looked at me. I'm being remembered by something that shouldn't.", emotion: "still" },
    { id: "event_apprentice_died", bucket: "event", text: "I'll watch where {they} used to walk. The route gets harder.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. They don't see me yet. They will, slowly.", emotion: "wry" },
    { id: "event_first_costly_choice", bucket: "event", text: "I noticed your shoulders before your face. The decision was already made.", emotion: "soft" },
    { id: "event_dialog_overheard", bucket: "event", text: "I heard them. Don't ask me what. I'll tell you when it matters.", emotion: "edged" },
    { id: "banter_visible_2", bucket: "banter", text: "Don't introduce me. I introduce myself to who I want.", emotion: "edged" },
    { id: "banter_quiet_2", bucket: "banter", text: "Sit beside me. Don't fill the silence. I'll fill it if I need to.", emotion: "soft" },
    { id: "banter_loud", bucket: "banter", text: "Keep your voice down. The room hears better at this hour.", emotion: "wry" },
    { id: "quest_2_check", bucket: "quest", text: "I followed the watcher. They circled the lower deck three times. I'll write what they were looking at.", emotion: "set" },
    { id: "quest_followup_a", bucket: "quest", text: "The watcher noticed I noticed. We've reached an understanding.", emotion: "low" },
    { id: "quest_resolution_deep", bucket: "quest", text: "{they} sees me now. I'm letting it stay that way. With you.", emotion: "tender" },
    { id: "quest_resolution_break", bucket: "quest", text: "I broke pattern. {they} ran. I let {them}. The watcher is now me.", emotion: "raw" },
    { id: "romance_solo", bucket: "romance", text: "Don't write about us. I'll know if you do.", emotion: "edged" },
    { id: "romance_anonymous_gift", bucket: "romance", text: "I left a coin on your bunk. You knew which one.", emotion: "soft" },
  ],
  scholar: [
    { id: "greet_1", bucket: "greet", text: "I'm reading three things at once. Sit. I'll catch up.", emotion: "warm" },
    { id: "greet_2", bucket: "greet", text: "Welcome. Mind the stack on the chair — it's the third draft.", emotion: "ready" },
    { id: "ambient_1", bucket: "ambient", text: "Footnote fourteen contradicts the body. I'll let the body speak first.", emotion: "thoughtful" },
    { id: "ambient_2", bucket: "ambient", text: "The Antiquarian's last catalogue has a missing entry between 87 and 89. Curious.", emotion: "curious" },
    { id: "ambient_3", bucket: "ambient", text: "Read it twice. The second read is the one that means something.", emotion: "calm" },
    { id: "deploy_1", bucket: "deploy", text: "Field notes will be available after.", emotion: "ready" },
    { id: "deploy_2", bucket: "deploy", text: "I'll write a footnote when I'm sure. Until then I'll do.", emotion: "steady" },
    { id: "outcome_won", bucket: "outcome", text: "Three citations richer. Tonight's draft will sing.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "Everything's documentable. Including the wound. I'll log it after the bandage.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I'll write {their} epitaph the way {they} would have edited it. With cuts.", emotion: "mourning" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} would have wanted the publication. I'll add {their} name to the byline.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "The footnote answers it. Three other footnotes correct themselves.", emotion: "thrilled" },
    { id: "event_journal_read", bucket: "event", text: "Read it twice. Once for the words, once for the silences.", emotion: "soft" },
    { id: "banter_evidence", bucket: "banter", text: "I respect intuition. I publish evidence.", emotion: "edged" },
    { id: "banter_argue", bucket: "banter", text: "Bring me the rebuttal. Bring me two. I'll annotate yours.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a banned interpretation of the Founder's Theorem. I want to defend it before the Antiquarian.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "Three drafts in. Two I burned. The third I sent to you to read first.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "If I publish this, half the disciplines will deny me. Half will cite me. Tell me which half I should mind.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "I have an annotated copy I'd rather you read with me.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I write to you in marginalia. You write back in books I haven't read yet.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "Let the disciplines call us footnotes to each other. We'll be the only one cited.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. I'm in chapter four. You can read alongside.", emotion: "warm" },
    { id: "greet_4", bucket: "greet", text: "Sit. The light's better at this desk.", emotion: "ready" },
    { id: "ambient_4", bucket: "ambient", text: "Annotated source one disagrees with annotated source three. Both annotated by the same author. Curious.", emotion: "thoughtful" },
    { id: "ambient_5", bucket: "ambient", text: "I'm rereading the field notes I wrote last cycle. I was wrong on page two.", emotion: "wry" },
    { id: "ambient_6", bucket: "ambient", text: "There's a transcription error in the Founders' Chronicle. Three centuries of citations have inherited it.", emotion: "edged" },
    { id: "ambient_7", bucket: "ambient", text: "If you have ten minutes, I'll show you the missing volume. It's not missing. It's mis-shelved.", emotion: "warm" },
    { id: "ambient_8", bucket: "ambient", text: "I sleep with the manuscript. Don't tell the Antiquarian.", emotion: "soft" },
    { id: "ambient_9", bucket: "ambient", text: "There are four people in this room. Three of them are mostly metaphor.", emotion: "wry" },
    { id: "deploy_3", bucket: "deploy", text: "I'm bringing the field manual. Annotated.", emotion: "ready" },
    { id: "deploy_4", bucket: "deploy", text: "I'll cite my sources after. Possibly during.", emotion: "wry" },
    { id: "deploy_5", bucket: "deploy", text: "Field test of the third chapter. I'd like a peer reviewer in earshot.", emotion: "set" },
    { id: "outcome_won_2", bucket: "outcome", text: "The chapter holds. I'll publish next cycle.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "Footnoting injuries is harder than I'd hoped.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "I had the citation in my hand. Then I didn't. Then I did again.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "I'll add {them} to the citations. {they} would have wanted Vancouver style.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. The bibliography updates itself.", emotion: "thoughtful" },
    { id: "event_npc_returned", bucket: "event", text: "{they} returned. The footnotes will need a supplementary edition.", emotion: "thrilled" },
    { id: "event_betrayal_warning", bucket: "event", text: "I checked the citations on their last argument. Two are forged.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew co-authoring something in the long table. I'm leaving footnotes on their draft, anonymously.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "Existing literature on bound spirits is thin. I'll be expanding it.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "I'll write the entry. Three drafts. The third one will be the one we keep.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew member. I've already read their first paper. We disagree productively.", emotion: "warm" },
    { id: "event_first_costly_choice", bucket: "event", text: "Cite the difficult outcome. The textbooks need a new case study.", emotion: "approving" },
    { id: "event_loredex_meta", bucket: "event", text: "I have a hypothesis about the Loredex. I'll workshop it with you.", emotion: "thoughtful" },
    { id: "banter_evidence_2", bucket: "banter", text: "Bring me the rebuttal. With sources.", emotion: "edged" },
    { id: "banter_argue_2", bucket: "banter", text: "We can disagree productively for hours. Set aside an evening.", emotion: "warm" },
    { id: "banter_seminar", bucket: "banter", text: "We should hold a seminar. Tonight. Long table. Bring opinions.", emotion: "ready" },
    { id: "quest_2_check", bucket: "quest", text: "Three drafts in. Each one weaker than the last. I'm rewriting from scratch.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "The Antiquarian read the third draft. He marked four sentences. I'm keeping all of them.", emotion: "wondering" },
    { id: "quest_resolution_deep", bucket: "quest", text: "Published. Three corrections in three days. The fourth is yours to send.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "Retracted. The disciplines clapped. I'm still reading what I wrote.", emotion: "raw" },
    { id: "romance_marginalia", bucket: "romance", text: "I write to you in marginalia. Don't read it in order.", emotion: "soft" },
    { id: "romance_library", bucket: "romance", text: "Meet me in the library at the third turn. Bring nothing.", emotion: "tender" },
  ],
  revenant: [
    { id: "greet_1", bucket: "greet", text: "I came back. That's most of the introduction.", emotion: "low" },
    { id: "greet_2", bucket: "greet", text: "Welcome. I'll tell you which parts of my story you can ask about.", emotion: "set" },
    { id: "ambient_1", bucket: "ambient", text: "I had a debt list in my coat pocket when I died. I keep finding new copies.", emotion: "low" },
    { id: "ambient_2", bucket: "ambient", text: "There's a hum in this corridor that wasn't there before. Or after. Hard to tell.", emotion: "wry" },
    { id: "ambient_3", bucket: "ambient", text: "Sleep doesn't take me anywhere new. That's fine. I'm not done with here.", emotion: "still" },
    { id: "deploy_1", bucket: "deploy", text: "I've done this corridor before. Not the same way.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "Don't worry about me dying. I'm bad at it.", emotion: "wry" },
    { id: "outcome_won", bucket: "outcome", text: "Crossed two names off. Three to go.", emotion: "low" },
    { id: "outcome_wounded", bucket: "outcome", text: "Hurts the same. That's a relief, somehow.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I know what {they}'re feeling. I'll go sit with the body for a while.", emotion: "mourning" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} got there before me. Add {their} name to my list. I'll finish what {they} started.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "That fragment? Mine. I think.", emotion: "low" },
    { id: "event_resurrection", bucket: "event", text: "Welcome back. Don't try to remember everything at once. The hour after's the worst.", emotion: "warm" },
    { id: "banter_died", bucket: "banter", text: "Yes I died. No I won't tell you how. Yes you can ask in three cycles.", emotion: "edged" },
    { id: "banter_finish", bucket: "banter", text: "There are five names I owe. Three are still alive. We could go.", emotion: "set" },
    { id: "quest_1_open", bucket: "quest", text: "First name on the debt list lives two sectors over. I'd like company.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "Found three. Two thanked me. One slammed the door.", emotion: "wry" },
    { id: "quest_3_break", bucket: "quest", text: "The last name on the list — it's mine. I don't know how to settle that one yet.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Slow steps. I came back walking funny.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I die a little less when you laugh. Don't tell anyone.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I came back to finish what I'd left. I'm staying for what I've found.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. The list is getting shorter. Slowly.", emotion: "low" },
    { id: "greet_4", bucket: "greet", text: "I'm okay. I'm here. Both true.", emotion: "ready" },
    { id: "ambient_4", bucket: "ambient", text: "I keep finding things in pockets I don't remember filling.", emotion: "wry" },
    { id: "ambient_5", bucket: "ambient", text: "The third name on my list runs a stall in the lower deck. They didn't recognize me.", emotion: "low" },
    { id: "ambient_6", bucket: "ambient", text: "Sleep takes me to the same hallway twice a week. Different lighting each time.", emotion: "still" },
    { id: "ambient_7", bucket: "ambient", text: "I'm not afraid of dying. I'm tired of starting over.", emotion: "raw" },
    { id: "ambient_8", bucket: "ambient", text: "There's a fifth name I haven't written down. I don't trust myself with it yet.", emotion: "edged" },
    { id: "ambient_9", bucket: "ambient", text: "The cadre patches have changed three times since I died. I'm still learning the new ones.", emotion: "thoughtful" },
    { id: "deploy_3", bucket: "deploy", text: "I've done worse. Less prepared.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "I'll go first. I know the ground.", emotion: "low" },
    { id: "deploy_5", bucket: "deploy", text: "Three crossings ahead. I marked the first two last cycle.", emotion: "ready" },
    { id: "outcome_won_2", bucket: "outcome", text: "Crossed off the fourth. The fifth's a problem.", emotion: "low" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "Old wounds. New wounds. Same body. Same accountant.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "I died in three of the dream variants. Not this one.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "{their} unfinished business is mine now. I'll honor the addition.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. Another set of names I should have written down.", emotion: "thoughtful" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. We compare notes on the boundary tonight.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "I've seen this before. The sequence is the same. The face is new.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two of you bonded in the alcove. I'm glad. The dead don't always get that.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits remind me of myself. Reluctant company.", emotion: "low" },
    { id: "event_apprentice_died", bucket: "event", text: "I know what {they}'re feeling. I'll go sit with the body. Once is enough for the witness.", emotion: "mourning" },
    { id: "event_resurrection_complete", bucket: "event", text: "Welcome back. Whatever you remember, write it down. Tonight. While it's loud.", emotion: "warm" },
    { id: "event_recruit_added", bucket: "event", text: "Another name to learn. I'll forget it twice and remember the third time.", emotion: "wry" },
    { id: "event_first_costly_choice", bucket: "event", text: "Difficult choices age you. I'd know.", emotion: "low" },
    { id: "banter_died_2", bucket: "banter", text: "I'll tell you how I died. Once. After the second mission.", emotion: "edged" },
    { id: "banter_finish_2", bucket: "banter", text: "I owe a name. We could go this cycle.", emotion: "set" },
    { id: "banter_grief", bucket: "banter", text: "Grief from the inside is just an extra job to keep up with.", emotion: "still" },
    { id: "quest_2_check", bucket: "quest", text: "Found the third name. He runs a paint shop now. He cried. I didn't.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "The fourth name is dead. Already. I'll find the family.", emotion: "still" },
    { id: "quest_resolution_deep", bucket: "quest", text: "Crossed the last. The list is closed. The pen's heavier than I expected.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I left one name uncrossed. I think I want to leave one. Always.", emotion: "raw" },
    { id: "romance_morning", bucket: "romance", text: "I wake before you. I count your breaths. It's allowed.", emotion: "soft" },
    { id: "romance_quiet_walk", bucket: "romance", text: "Walk with me. Don't ask. I'll tell you about a corner of my old life.", emotion: "tender" },
  ],
  artisan: [
    { id: "greet_1", bucket: "greet", text: "Don't touch the bench. There's a bevel cooling.", emotion: "set" },
    { id: "greet_2", bucket: "greet", text: "I'll be done in two minutes. Or never. We'll see.", emotion: "wry" },
    { id: "ambient_1", bucket: "ambient", text: "The good ones change colour twice while they cool. I'm watching for the second.", emotion: "calm" },
    { id: "ambient_2", bucket: "ambient", text: "There's a notch I left for the next maker. They'll know what it means.", emotion: "thoughtful" },
    { id: "ambient_3", bucket: "ambient", text: "I'd rather make one true thing slowly than three approximate.", emotion: "steady" },
    { id: "deploy_1", bucket: "deploy", text: "Bringing the kit. Don't break the kit.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "I built it. I can fix it in the field. Probably.", emotion: "wry" },
    { id: "outcome_won", bucket: "outcome", text: "Came back with all my fingers. New record.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "I'll repair it when the swelling goes down. Both of them.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I'll keep a piece. I'll make {them} something. Even if {they} can't hold it.", emotion: "mourning" },
    { id: "outcome_other_died", bucket: "outcome", text: "{their} signature was on three of my pieces. I'll keep the signatures.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "There's a maker's mark in the entry I didn't see before. I know it.", emotion: "thrilled" },
    { id: "event_first_craft", bucket: "event", text: "Watching it cool. The good ones change colour twice.", emotion: "calm" },
    { id: "banter_critique", bucket: "banter", text: "Critique me when it's cool. Not before.", emotion: "edged" },
    { id: "banter_watch", bucket: "banter", text: "Sit. The hum's good for the work.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "Last commission for the {npc}. They've waited long enough. Help me deliver it right.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "The piece is finished. I left it on the long table. They haven't picked it up.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "They want me to alter it. The alteration would weaken the joint. Tell me — pride or service?", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Hands first. I trust hands.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I'm building you a thing. It's small. It's heavy. Don't lose it.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I'll outlast the work. The work will outlast me. You — somewhere between.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. Don't lean on the bench. The varnish is still tacky.", emotion: "set" },
    { id: "greet_4", bucket: "greet", text: "I'll be done in three breaths. Maybe four.", emotion: "wry" },
    { id: "ambient_4", bucket: "ambient", text: "The hum changes pitch when the metal's right. I'm listening.", emotion: "calm" },
    { id: "ambient_5", bucket: "ambient", text: "I left a notch. Anybody who finishes this after me will know who started.", emotion: "thoughtful" },
    { id: "ambient_6", bucket: "ambient", text: "Three drafts of this hilt before I cut the wood. Most of the work happens before the work.", emotion: "steady" },
    { id: "ambient_7", bucket: "ambient", text: "Sloppy welds outlive the welder. Always.", emotion: "edged" },
    { id: "ambient_8", bucket: "ambient", text: "The Engineer Zero brings me singular pigments. I owe him three lifetimes.", emotion: "warm" },
    { id: "ambient_9", bucket: "ambient", text: "Patina is a story. Don't polish it off.", emotion: "soft" },
    { id: "deploy_3", bucket: "deploy", text: "I'm packing the field-repair kit. Nobody touches the calibration jig.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "If something breaks, I'm a kit. The kit is me.", emotion: "ready" },
    { id: "deploy_5", bucket: "deploy", text: "I'll fix it on the way out. We won't have time on the way in.", emotion: "wry" },
    { id: "outcome_won_2", bucket: "outcome", text: "Three pieces back, three repairs ahead. I'll start at dawn.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "I'll repair the joint. The joint is me. The metaphor is recursive.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "The hilt held. Two centimetres further it wouldn't have. The hilt held.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "I'll keep one piece for {them}. Their signature stays. The piece is theirs.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. Three new commissions queued.", emotion: "ready" },
    { id: "event_npc_returned", bucket: "event", text: "{they} came back. I'll re-issue the commission they couldn't pick up before.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "Their sigil is two degrees off. Not by accident.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew at the long table. I'll engrave a token. Quietly.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "I want to study its sigils. Just the ones that don't bite.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "I'll make {them} a memorial. Heavy. On purpose. The Wraith Calder will know what to do with it.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. They asked me what I make. I showed them. Now they're a customer.", emotion: "warm" },
    { id: "event_loredex_found", bucket: "event", text: "There's a maker's mark in the entry. I know it. The maker is older than three of our centuries.", emotion: "thrilled" },
    { id: "event_recipe_acquired", bucket: "event", text: "Three new recipes. The middle one is interesting. The other two are warnings.", emotion: "thoughtful" },
    { id: "banter_critique_2", bucket: "banter", text: "Critique me when the work's cool. Not before. Not before.", emotion: "edged" },
    { id: "banter_watch_2", bucket: "banter", text: "Sit. The hum's good for the work. The hum is half the work.", emotion: "warm" },
    { id: "banter_apprentice", bucket: "banter", text: "I'd take an apprentice. They'd hate me for the first month. Then they'd be patient.", emotion: "wry" },
    { id: "quest_2_check", bucket: "quest", text: "The piece is finished. They haven't picked it up. I'll wait. The piece will outlast both of us anyway.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "They asked me to alter it. The alteration would weaken the joint. I refused. They're upset.", emotion: "set" },
    { id: "quest_resolution_deep", bucket: "quest", text: "I delivered. They wept on the bench. I left them with it.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I altered. The joint weakened. The piece will fail in three cycles. They asked. I served.", emotion: "raw" },
    { id: "romance_handmade", bucket: "romance", text: "I made you a thing. It's small. Don't lose it. Don't polish it.", emotion: "soft" },
    { id: "romance_workshop", bucket: "romance", text: "Stay in the workshop. Don't talk. The hum needs us both.", emotion: "tender" },
  ],
  oracle: [
    { id: "greet_1", bucket: "greet", text: "I knew you'd be the one to come. The dream was clear about the boots.", emotion: "wry" },
    { id: "greet_2", bucket: "greet", text: "Welcome. I dreamt this conversation. I'll let you write the actual lines.", emotion: "soft" },
    { id: "ambient_1", bucket: "ambient", text: "There's a colour I don't have a name for yet. It's coming.", emotion: "wondering" },
    { id: "ambient_2", bucket: "ambient", text: "I dreamt the manifest. Two of the names changed. I won't tell you which yet.", emotion: "still" },
    { id: "ambient_3", bucket: "ambient", text: "I'll know an hour after. Hold the question that long.", emotion: "calm" },
    { id: "deploy_1", bucket: "deploy", text: "Don't take the southern corridor. I can't tell you why yet.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "I dreamt this hallway. The dream was wrong about the floor.", emotion: "wry" },
    { id: "outcome_won", bucket: "outcome", text: "It went almost the way I dreamt. The 'almost' is the interesting part.", emotion: "thoughtful" },
    { id: "outcome_wounded", bucket: "outcome", text: "The dream warned me. I half-listened. Half is enough sometimes.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I dreamt {them} once. {they} were laughing. I'll keep that one.", emotion: "still" },
    { id: "outcome_other_died", bucket: "outcome", text: "I'd seen {their} face in the dream-list two cycles back. I didn't say. I should have.", emotion: "raw" },
    { id: "event_loredex", bucket: "event", text: "I knew this one was next. The order is right.", emotion: "thrilled" },
    { id: "event_voltari", bucket: "event", text: "I dreamt that static. It was singing in my mother's voice.", emotion: "still" },
    { id: "banter_specifics", bucket: "banter", text: "Specifics narrow the dream. I'll give you a colour, not a name.", emotion: "edged" },
    { id: "banter_share", bucket: "banter", text: "Sleep next to me sometime. I'll let you in on a small one.", emotion: "soft" },
    { id: "quest_1_open", bucket: "quest", text: "I dreamt a death. {they} survived. I want to find out why my dream was wrong.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "The survivor doesn't want to be found. I understand that. We still need to ask.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "If I tell {them} what I dreamt, the next dream might come. If I don't, I lose the last warning. Choose with me.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "I dreamt this. Don't ruin it by being predictable.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I'm half-elsewhere. The other half is here. With you.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "Every dream from now on has you in it. That's not a choice. It's a given.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. The dream said you'd be tired. I made tea.", emotion: "soft" },
    { id: "greet_4", bucket: "greet", text: "I knew you were coming. The substrate's been thrumming.", emotion: "wondering" },
    { id: "ambient_4", bucket: "ambient", text: "There are three of you in this room. Two are awake. The third is the one I'm watching.", emotion: "still" },
    { id: "ambient_5", bucket: "ambient", text: "The dream-list updated overnight. Two names moved. One is yours.", emotion: "edged" },
    { id: "ambient_6", bucket: "ambient", text: "I dreamt the engine. It dreamt me back. We negotiated.", emotion: "wry" },
    { id: "ambient_7", bucket: "ambient", text: "The colour I don't have a name for came twice last cycle. Three is meaningful.", emotion: "thoughtful" },
    { id: "ambient_8", bucket: "ambient", text: "Sleep this cycle is a workplace. I'll bring my notes back.", emotion: "calm" },
    { id: "ambient_9", bucket: "ambient", text: "Voltari static is the song my mother sang. I've stopped trying not to cry.", emotion: "raw" },
    { id: "deploy_3", bucket: "deploy", text: "I dreamt three exits. The fourth one's a lie.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Take the right corridor. Don't ask. I'll explain in an hour.", emotion: "edged" },
    { id: "deploy_5", bucket: "deploy", text: "If I tell you what I dreamt, you'll change it. I won't tell you yet.", emotion: "wry" },
    { id: "outcome_won_2", bucket: "outcome", text: "It went almost the way I dreamt. The almost is the only part that mattered.", emotion: "thoughtful" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "The dream warned me. I half-listened. Half is enough sometimes. Sometimes it isn't.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "I dreamt my own death three times this cycle. Today wasn't one of them.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "I'd seen {them}. I should have said. I'll say next time.", emotion: "raw" },
    { id: "event_act_complete", bucket: "event", text: "Three new dream signatures in the substrate. Two are familiar. One is new.", emotion: "thoughtful" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I dreamt the return. I dreamt the colour of their first room.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "I dreamt them turning. Tonight or the next. Don't trust them with the keys yet.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "I dreamt them holding hands. They will. Tonight or the next.", emotion: "soft" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits show up in dreams as colours I don't have names for.", emotion: "wondering" },
    { id: "event_apprentice_died", bucket: "event", text: "I dreamt {them} once. {they} were laughing. I'll keep that one. {they} can borrow it whenever.", emotion: "still" },
    { id: "event_first_costly_choice", bucket: "event", text: "The decision you made is the one I dreamt. The one you didn't make is also dreamt.", emotion: "thoughtful" },
    { id: "event_loredex_found", bucket: "event", text: "I knew this one was next. The order is right.", emotion: "thrilled" },
    { id: "event_voltari_first", bucket: "event", text: "I dreamt that static. It was my mother. It still is.", emotion: "raw" },
    { id: "banter_specifics_2", bucket: "banter", text: "Specifics narrow the dream. I'll give you a colour. Not a name. Not yet.", emotion: "edged" },
    { id: "banter_share_2", bucket: "banter", text: "Sleep next to me sometime. I'll let you in on a small one.", emotion: "soft" },
    { id: "banter_skeptic", bucket: "banter", text: "You don't believe in dreams. Fine. Believe in the colour I described last cycle. The one that turned up the next morning.", emotion: "wry" },
    { id: "quest_2_check", bucket: "quest", text: "Found the survivor. They don't want me near them. I dreamt that, too.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "We met. They asked who'd dreamt the wrong vision. I said I had. They forgave me. The forgiveness was hard.", emotion: "still" },
    { id: "quest_resolution_deep", bucket: "quest", text: "I told the rest. The dream-list is shorter. Sleep is heavier.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I told a lie. The dreams stopped. I'd take them back. I won't.", emotion: "raw" },
    { id: "romance_share_dream", bucket: "romance", text: "Tonight I'll dream you in. Don't fight it. Tell me what colour the room was.", emotion: "soft" },
    { id: "romance_omen_gift", bucket: "romance", text: "I left you a riddle in the box. If you solve it, we sleep together tonight.", emotion: "tender" },
  ],
  wanderer: [
    { id: "greet_1", bucket: "greet", text: "Pleasure. I'll be on my way. Possibly tomorrow.", emotion: "warm" },
    { id: "greet_2", bucket: "greet", text: "I came to look around. Surprised to find I'm staying for the soup.", emotion: "wry" },
    { id: "ambient_1", bucket: "ambient", text: "There's a window in the cargo bay that opens onto somewhere it shouldn't.", emotion: "thoughtful" },
    { id: "ambient_2", bucket: "ambient", text: "I keep meaning to leave. It keeps not happening. Curious.", emotion: "wry" },
    { id: "ambient_3", bucket: "ambient", text: "I count the corridors. Three new. Two old. One that wasn't here last cycle.", emotion: "calm" },
    { id: "deploy_1", bucket: "deploy", text: "I know the back routes. Even on planets I've never been.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "If we get separated, I'll find you. I always find the way back.", emotion: "warm" },
    { id: "outcome_won", bucket: "outcome", text: "One more place I've walked through. One more story for the road.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "My boots are full of someone else's blood. I'll change boots.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I'll walk {their} last route. Slow. Unhurried.", emotion: "still" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} never settled. I'll add {them} to the routes I keep walking.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "I've been near this place. I didn't know what I was near.", emotion: "thoughtful" },
    { id: "event_act_2_complete", bucket: "event", text: "Three new corridors I haven't walked. I'll take care of one before sleep.", emotion: "ready" },
    { id: "banter_settle", bucket: "banter", text: "I haven't settled. I'm circling.", emotion: "edged" },
    { id: "banter_road", bucket: "banter", text: "Tell me where you've been. I'll know if you're lying.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a place I keep coming back to. I want you to see why.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "Walked the loop again. Found a door I'd never opened. Don't know if I should.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "Behind the door is a person I left. They've been waiting. I have to choose: in, or back to the road.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Walk with me a while. I won't ask how far.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "You let me leave. That's the only kind of staying I know how to do.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I'm circling closer. Don't tell me. Just keep the kettle on.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. I'll be here for a while. Two cycles, maybe three.", emotion: "warm" },
    { id: "greet_4", bucket: "greet", text: "Hi. Just back from the lower corridor. There's a door I want to show you.", emotion: "ready" },
    { id: "ambient_4", bucket: "ambient", text: "I remember every room I've ever slept in. None of them are this one. Yet.", emotion: "thoughtful" },
    { id: "ambient_5", bucket: "ambient", text: "There's a sect on the third moon that disagrees with everyone. I miss them.", emotion: "wry" },
    { id: "ambient_6", bucket: "ambient", text: "The substrate has shortcuts the maps don't show. I'll mark three for you.", emotion: "ready" },
    { id: "ambient_7", bucket: "ambient", text: "I keep meaning to leave. I keep not leaving. I'll keep meaning.", emotion: "wry" },
    { id: "ambient_8", bucket: "ambient", text: "The kettle on the long table is one of mine. I left it three cycles back.", emotion: "soft" },
    { id: "ambient_9", bucket: "ambient", text: "Stories are road maps for places nobody walks anymore.", emotion: "calm" },
    { id: "deploy_3", bucket: "deploy", text: "I know the back routes. Even on planets I haven't been.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Don't worry about losing me. I'll find the way back.", emotion: "warm" },
    { id: "deploy_5", bucket: "deploy", text: "If we get separated, meet me at the third corridor in. There's a window.", emotion: "ready" },
    { id: "outcome_won_2", bucket: "outcome", text: "One more place to add to the list. The list has chapters now.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "Boots full of someone else's blood. I'll change boots.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "Took the wrong turn. The wrong turn was the right one.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "I'll walk {their} last route. Slow. Unhurried. The road won't notice.", emotion: "still" },
    { id: "event_act_complete", bucket: "event", text: "Three new corridors I haven't walked. I'll take care of one before sleep.", emotion: "ready" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. We compared notes on hallways nobody else knows.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "I've seen this kind of leaving before. They'll come back, but worse.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew claimed a route together. They'll walk it forever now.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits travel with us. Just one more passenger.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "{they} never settled. I'll add {them} to the routes I keep walking.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. I'll show them three exits before sundown.", emotion: "ready" },
    { id: "event_first_costly_choice", bucket: "event", text: "Hard road. The harder roads are the ones I remember.", emotion: "warm" },
    { id: "event_loredex_found", bucket: "event", text: "I've been near this place. I didn't know what I was near.", emotion: "thoughtful" },
    { id: "banter_settle_2", bucket: "banter", text: "I haven't settled. I'm circling. Different verb. Same result.", emotion: "edged" },
    { id: "banter_road_2", bucket: "banter", text: "Tell me where you've been. I'll know if you're lying.", emotion: "warm" },
    { id: "banter_kettle", bucket: "banter", text: "The kettle's on. I'll stay until it whistles. Then we'll see.", emotion: "soft" },
    { id: "quest_2_check", bucket: "quest", text: "I walked the loop. The door's still there. I haven't opened it. I won't, alone.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "Behind the door, the room is smaller than I remembered. Smaller and warmer.", emotion: "wondering" },
    { id: "quest_resolution_deep", bucket: "quest", text: "I stayed. The road's still open. I'll walk it some weekends. Not most.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I left. The kettle's still on the long table. Someone else uses it now.", emotion: "raw" },
    { id: "romance_traveling_with", bucket: "romance", text: "Walk with me a while. I won't ask how far.", emotion: "soft" },
    { id: "romance_returning_to", bucket: "romance", text: "Don't make a place for me. Make space. The difference matters.", emotion: "tender" },
  ],
  martyr: [
    { id: "greet_1", bucket: "greet", text: "I'm yours. You don't have to thank me — please don't.", emotion: "soft" },
    { id: "greet_2", bucket: "greet", text: "Tell me what you need. I'll cover the rest.", emotion: "ready" },
    { id: "ambient_1", bucket: "ambient", text: "I packed the kit twice. I'll pack it once more before sleep.", emotion: "low" },
    { id: "ambient_2", bucket: "ambient", text: "Eat. I already did. Promise.", emotion: "wry" },
    { id: "ambient_3", bucket: "ambient", text: "If you're cold, take my jacket. I run warm.", emotion: "warm" },
    { id: "deploy_1", bucket: "deploy", text: "Whoever's taking the worst hit, that's me.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "Stay behind me. I'll tell you when it's over.", emotion: "set" },
    { id: "outcome_won", bucket: "outcome", text: "We're all back. That's the only outcome that counts.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "It's nothing. Don't make a fuss. Don't.", emotion: "edged" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I should have been ahead of {them}. I'm sorry.", emotion: "raw" },
    { id: "outcome_other_died", bucket: "outcome", text: "It should have been me. Tell whoever asks: it should have been me.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "I'll memorize it. Then someone else can rest.", emotion: "soft" },
    { id: "event_mission_dispatch", bucket: "event", text: "Whoever takes the worst hit — let it be me.", emotion: "set" },
    { id: "banter_thanks", bucket: "banter", text: "Please. Don't thank me. It makes the work harder.", emotion: "edged" },
    { id: "banter_rest", bucket: "banter", text: "I rest when you do. Not before. Not after.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a mission only I can take. Let me have it. Don't trade me out.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "It went sideways. I made it. Barely. Don't make me promise to be careful.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "The next one has my name on it. If you pull me out, I'll go anyway. Choose what you want me to know.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Don't catch me. Walk with me to the edge.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "I'm learning to be received. It's harder than giving.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I let you keep me. That's the most generous thing I've done.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. Sit. I'll be back. I always come back.", emotion: "soft" },
    { id: "greet_4", bucket: "greet", text: "Tell me what you need. I'll cover it. Don't argue.", emotion: "ready" },
    { id: "ambient_4", bucket: "ambient", text: "I packed three first-aid kits. One is yours. Don't ask which.", emotion: "low" },
    { id: "ambient_5", bucket: "ambient", text: "The bunkroom's cold. I gave my blanket to the new recruit. They're shivering less now.", emotion: "soft" },
    { id: "ambient_6", bucket: "ambient", text: "I rest when you rest. Not before. Not after.", emotion: "warm" },
    { id: "ambient_7", bucket: "ambient", text: "The watch I gave my partner — they're still wearing it. I'm glad.", emotion: "still" },
    { id: "ambient_8", bucket: "ambient", text: "Three meals queued. I'll eat the third one. If there's time.", emotion: "wry" },
    { id: "ambient_9", bucket: "ambient", text: "There's a list of people I'd take a hit for. I'm running out of paper.", emotion: "edged" },
    { id: "deploy_3", bucket: "deploy", text: "I'm at the front. Everyone else is at the rear. I'll be the rear if you need.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Stay behind me. I'll tell you when it's over. I'll mean it.", emotion: "set" },
    { id: "deploy_5", bucket: "deploy", text: "Whoever's taking the worst hit, that's me. Worth a try, anyway.", emotion: "edged" },
    { id: "outcome_won_2", bucket: "outcome", text: "Everyone home. The only outcome I track.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "It's nothing. Don't fuss. Please don't.", emotion: "edged" },
    { id: "outcome_close_call", bucket: "outcome", text: "I should have been ahead of {them}. I was, briefly. The bullet was faster.", emotion: "raw" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "It should have been me. Tell whoever asks: it should have been me.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. Another roster of people I haven't lost yet.", emotion: "warm" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I'll bring them tea. The first cup matters most.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "Their corruption is rising. Confront them. I'll be there. I'll catch the fall.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew bonded. Quietly relieved. Less on my list to worry about.", emotion: "soft" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits need protection too. The bond can break. The carrier shouldn't.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "I should have been there. I'll be ahead next time. I promise.", emotion: "raw" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. I made up a bunk. Two extra blankets. Just in case.", emotion: "warm" },
    { id: "event_first_costly_choice", bucket: "event", text: "You took the harder one. I'll cover the bill.", emotion: "soft" },
    { id: "event_war_won", bucket: "event", text: "We won. Tell the cadre. I'll stay up another shift, just to be sure.", emotion: "calm" },
    { id: "banter_thanks_2", bucket: "banter", text: "Please. Don't thank me. The thanks make the work harder.", emotion: "edged" },
    { id: "banter_rest_2", bucket: "banter", text: "I'll rest. Eventually. Don't wait up.", emotion: "warm" },
    { id: "banter_promise", bucket: "banter", text: "Don't ask me to promise to be careful. I won't lie to you.", emotion: "edged" },
    { id: "quest_2_check", bucket: "quest", text: "It went sideways. I made it. Barely. Don't make me promise to be careful next time. Just don't.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "The next mission has my name on it. Already. I knew before the briefing.", emotion: "set" },
    { id: "quest_resolution_deep", bucket: "quest", text: "You let me go. I came back. I'll let myself, next time. Just maybe.", emotion: "tender" },
    { id: "quest_resolution_break", bucket: "quest", text: "I went. I gave. The team's whole. I'm not. I'm not okay with okay.", emotion: "raw" },
    { id: "romance_receive", bucket: "romance", text: "I'm learning to be received. It's harder than giving. I'm slow at it.", emotion: "soft" },
    { id: "romance_let_in", bucket: "romance", text: "Catch me. Walk me to the edge. Hold my hand on the way back.", emotion: "tender" },
  ],
  heretic: [
    { id: "greet_1", bucket: "greet", text: "I'm here to argue. Let's get the formalities out of the way.", emotion: "edged" },
    { id: "greet_2", bucket: "greet", text: "If you brought scripture, bring two. I want a counter-text on the table.", emotion: "set" },
    { id: "ambient_1", bucket: "ambient", text: "I have three drafts of the new tract. The third is the one that gets me arrested.", emotion: "wry" },
    { id: "ambient_2", bucket: "ambient", text: "Orthodoxy is a building. I'm in the basement.", emotion: "calm" },
    { id: "ambient_3", bucket: "ambient", text: "If you ever want to read what they took out, ask me. I kept copies.", emotion: "warm" },
    { id: "deploy_1", bucket: "deploy", text: "I'll go where the line is and stand on the wrong side of it.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "Bring the manuscript. I'll defend it on the way.", emotion: "ready" },
    { id: "outcome_won", bucket: "outcome", text: "Argued and survived. The two are usually exclusive.", emotion: "wry" },
    { id: "outcome_wounded", bucket: "outcome", text: "They cut me. I cut them back. Different metaphor, same scar.", emotion: "edged" },
    { id: "outcome_saw_death", bucket: "outcome", text: "{they} died for the wrong orthodoxy. I'll write {them} a better one.", emotion: "raw" },
    { id: "outcome_other_died", bucket: "outcome", text: "I'll quote {their} dissent in my next tract. {they}'ll be footnoted forever.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "Now we have a counter-text. The orthodoxy looks worse already.", emotion: "thrilled" },
    { id: "event_costly_choice", bucket: "event", text: "Good. The easy answer was always going to disappoint someone important.", emotion: "approving" },
    { id: "banter_orthodoxy", bucket: "banter", text: "I'm not contrarian. I'm correct. Different things.", emotion: "edged" },
    { id: "banter_dissent", bucket: "banter", text: "Bring me your worst orthodoxy. I'll show you what it papered over.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a public confrontation I want to stage. Vex Solène will set it up. Be there.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "The faction sent a counter-tract. It's better than I expected. We'll have to write a third.", emotion: "ready" },
    { id: "quest_3_break", bucket: "quest", text: "They want a public retraction. The retraction would buy peace. Choose what you want me to be.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Argue with me. Don't yield. I yield to people who don't.", emotion: "edged" },
    { id: "romance_courtship", bucket: "romance", text: "I love a flinch I can't predict. Yours never came.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "Orthodoxy of one. Us. I'll defend it.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. There's a tract on the table. Read it before you sit.", emotion: "edged" },
    { id: "greet_4", bucket: "greet", text: "Hi. I have new dissent. Same opinions. Better citations.", emotion: "wry" },
    { id: "ambient_4", bucket: "ambient", text: "Three pamphlets out for revision. The third one is the dangerous one.", emotion: "set" },
    { id: "ambient_5", bucket: "ambient", text: "I've been arguing with the Antiquarian for two cycles. He's enjoying it. So am I.", emotion: "warm" },
    { id: "ambient_6", bucket: "ambient", text: "Orthodoxy is a building. I'm in the basement. They left the door unlocked.", emotion: "calm" },
    { id: "ambient_7", bucket: "ambient", text: "If you want to read what they took out, ask me. I keep copies. Multiple. Hidden.", emotion: "wry" },
    { id: "ambient_8", bucket: "ambient", text: "Vex Solène said she'd sing my next dissent. I'm rewriting it for tenor.", emotion: "thrilled" },
    { id: "ambient_9", bucket: "ambient", text: "There's a verse-of-the-day. I've stopped reading it. The verse left a forwarding address.", emotion: "edged" },
    { id: "deploy_3", bucket: "deploy", text: "Bring the manuscript. I'll defend it on the way.", emotion: "ready" },
    { id: "deploy_4", bucket: "deploy", text: "I'll go where the line is and stand on the wrong side of it.", emotion: "set" },
    { id: "deploy_5", bucket: "deploy", text: "If they ask for the author, point. I'll claim the work.", emotion: "ready" },
    { id: "outcome_won_2", bucket: "outcome", text: "Argued and survived. Two for two on missions where that matters.", emotion: "wry" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "They cut me. I cut them back. Different metaphor. Same scar.", emotion: "edged" },
    { id: "outcome_close_call", bucket: "outcome", text: "The orthodoxy almost won that argument. I countered, we lived.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "{they} died for the wrong orthodoxy. I'll write {them} a better one.", emotion: "raw" },
    { id: "event_act_complete", bucket: "event", text: "Another act. Three new orthodoxies to dismantle.", emotion: "thrilled" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I'll quote their dissent in the next tract.", emotion: "thrilled" },
    { id: "event_betrayal_warning", bucket: "event", text: "I've been waiting for them to commit. The orthodoxy got there first. Pity.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew bonded. I'll write a tract against the bond. Out of habit.", emotion: "wry" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits hate the orthodox. I'll sit with one for an hour. We'll get along.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "I'll quote {their} dissent in my next tract. {they}'ll be footnoted forever.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. They argued back the second day. Good sign.", emotion: "warm" },
    { id: "event_first_costly_choice", bucket: "event", text: "Good. The easy answer was always going to disappoint someone important.", emotion: "approving" },
    { id: "event_loredex_found", bucket: "event", text: "Now we have a counter-text. The orthodoxy looks worse already.", emotion: "thrilled" },
    { id: "banter_orthodoxy_2", bucket: "banter", text: "I'm not contrarian. I'm correct. Different things.", emotion: "edged" },
    { id: "banter_dissent_2", bucket: "banter", text: "Bring me your worst orthodoxy. I'll show you what it papered over.", emotion: "warm" },
    { id: "banter_publication", bucket: "banter", text: "Three tracts in revision. The fourth's already in print. They haven't noticed.", emotion: "wry" },
    { id: "quest_2_check", bucket: "quest", text: "The faction sent a counter-tract. It's better than I expected. We'll have to write a third.", emotion: "ready" },
    { id: "quest_followup_a", bucket: "quest", text: "Public confrontation set for next cycle. Vex is rehearsing the chorus. The orthodoxy doesn't know yet.", emotion: "thrilled" },
    { id: "quest_resolution_deep", bucket: "quest", text: "We won. The orthodoxy retracted. Three new dissenters joined us. The chorus is bigger now.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I retracted. The faction calmed. I'm reading my own tract back. It still holds.", emotion: "raw" },
    { id: "romance_argue", bucket: "romance", text: "Argue with me. Don't yield. I yield to people who don't.", emotion: "edged" },
    { id: "romance_quiet_dissent", bucket: "romance", text: "I'd write a tract about you. I haven't. I won't. That's the only orthodoxy I keep.", emotion: "tender" },
  ],
  jester: [
    { id: "greet_1", bucket: "greet", text: "Hi. I'm working on material. Tell me if anything lands.", emotion: "wry" },
    { id: "greet_2", bucket: "greet", text: "I have three openers. None of them are good. Pick one.", emotion: "warm" },
    { id: "ambient_1", bucket: "ambient", text: "Three deities walk into a sermon. Two leave a tip.", emotion: "wry" },
    { id: "ambient_2", bucket: "ambient", text: "I'm working on a eulogy joke for the next one. Don't ask whose.", emotion: "low" },
    { id: "ambient_3", bucket: "ambient", text: "Funny is a sword. I'm trying to stop using it that way.", emotion: "thoughtful" },
    { id: "deploy_1", bucket: "deploy", text: "I'll be in the back, working on a punchline.", emotion: "wry" },
    { id: "deploy_2", bucket: "deploy", text: "Give me cover and I'll give you a story.", emotion: "warm" },
    { id: "outcome_won", bucket: "outcome", text: "We came back. The bit was: we came back.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "The bit was supposed to end with applause, not bandages.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I have a joke about this. I'm not telling it. Maybe in a month. Maybe never.", emotion: "raw" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} laughed at the bad ones. I'll keep telling those for {them}.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "The footnote IS the punchline. Finally.", emotion: "thrilled" },
    { id: "event_crew_dies", bucket: "event", text: "The bar is darker. The eulogy I owe is a long one. Cycle from now.", emotion: "raw" },
    { id: "banter_funeral", bucket: "banter", text: "There's a name I never speak. I have a joke about that too. I haven't told it.", emotion: "low" },
    { id: "banter_serious", bucket: "banter", text: "Solemnity is a costume. I look bad in it.", emotion: "wry" },
    { id: "quest_1_open", bucket: "quest", text: "There's a name I haven't said in years. I want to say it once. With company.", emotion: "raw" },
    { id: "quest_2_mid", bucket: "quest", text: "Said the name. Cried. Made a joke. Cried again. The order matters.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "If I tell the joke at the funeral, half the room will laugh, half will leave. Tell me which half I serve.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Stay through the bad ones. Tell me which one almost worked.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "Catch me between punchlines. The catch is the bit.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I'll keep the jokes I never told for you. They're the best ones.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. I have three jokes ready. None are good. Pick one anyway.", emotion: "wry" },
    { id: "greet_4", bucket: "greet", text: "Hi. Working on the eulogy joke. Don't ask whose. You'll know in a cycle.", emotion: "low" },
    { id: "ambient_4", bucket: "ambient", text: "I told the cadre a joke at funeral pace. They didn't laugh. Yet. Sometimes the laugh is delayed by years.", emotion: "thoughtful" },
    { id: "ambient_5", bucket: "ambient", text: "I have a routine prepared for the next death. I won't tell it. I'll tell two cycles later.", emotion: "low" },
    { id: "ambient_6", bucket: "ambient", text: "Funny is a sword. I'm trying to stop using it that way. It's hard.", emotion: "thoughtful" },
    { id: "ambient_7", bucket: "ambient", text: "Three new bits in tonight's set. Two are about the Cause. One is about love. I think.", emotion: "wry" },
    { id: "ambient_8", bucket: "ambient", text: "I'm not a sad clown. I'm a tired clown. Different metaphor. Same hat.", emotion: "soft" },
    { id: "ambient_9", bucket: "ambient", text: "Solemnity is a costume. I look bad in it. I keep wearing it.", emotion: "wry" },
    { id: "deploy_3", bucket: "deploy", text: "I'll be in the back, working on a punchline.", emotion: "wry" },
    { id: "deploy_4", bucket: "deploy", text: "Give me cover and I'll give you a story.", emotion: "warm" },
    { id: "deploy_5", bucket: "deploy", text: "If we're going down, the bit lands first. I promise.", emotion: "wry" },
    { id: "outcome_won_2", bucket: "outcome", text: "We came back. The bit was: we came back. Audiences love it.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "The bit was supposed to end with applause. Bandages aren't applause. But they're close.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "The setup was too long. The punchline was alive. Lessons learned.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "{they} laughed at the bad ones. I'll keep telling those for {them}.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. The set is changing. The good jokes are getting longer.", emotion: "thoughtful" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I have a joke. {they} hasn't heard it. We have time.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "There's a joke about people who turn. I won't tell it. I'd be telling it about us.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew bonded. I have a wedding bit. It's been waiting. I'll keep waiting.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirit, demon, devil — all the same setup. Different punchlines.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "I have a joke about this. I'm not telling it. Maybe in a month. Maybe never.", emotion: "raw" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. I tested a bit on them. They laughed. Good sign for both of us.", emotion: "warm" },
    { id: "event_first_costly_choice", bucket: "event", text: "Tough choice. Good material. Don't quote me. I will quote me.", emotion: "wry" },
    { id: "event_war_won", bucket: "event", text: "We won. The set tonight is shorter. Most of the bits worked.", emotion: "warm" },
    { id: "banter_funeral_2", bucket: "banter", text: "There's a name I never speak. I have a joke about that. I haven't told it.", emotion: "low" },
    { id: "banter_serious_2", bucket: "banter", text: "Solemnity is a costume. I keep losing the hat.", emotion: "wry" },
    { id: "banter_quip", bucket: "banter", text: "Three jokes about the engineer. He'd hate two. He'd write the third.", emotion: "warm" },
    { id: "quest_2_check", bucket: "quest", text: "Said the name. Cried. Made a joke. Cried again. The order matters. The order matters.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "The funeral joke needs to land. I keep rewriting. Three drafts. Maybe four.", emotion: "thoughtful" },
    { id: "quest_resolution_deep", bucket: "quest", text: "I told it. Half laughed. Half wept. The right halves.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I told it. The room went quiet. I left. The name's still in my pocket.", emotion: "raw" },
    { id: "romance_punchline", bucket: "romance", text: "Catch me between punchlines. The catch is the bit.", emotion: "soft" },
    { id: "romance_unjoke", bucket: "romance", text: "I'll keep a joke I never told for you. They're the best ones.", emotion: "tender" },
  ],
  sentinel: [
    { id: "greet_1", bucket: "greet", text: "Watch's clear. I'll relieve when relieved.", emotion: "set" },
    { id: "greet_2", bucket: "greet", text: "If you need me, the post knows where I am.", emotion: "calm" },
    { id: "ambient_1", bucket: "ambient", text: "The door's quiet. That's the only acceptable state.", emotion: "calm" },
    { id: "ambient_2", bucket: "ambient", text: "I logged the breach drill. Took two seconds longer than last time. I'll re-run it.", emotion: "ready" },
    { id: "ambient_3", bucket: "ambient", text: "Nothing's wrong. That's not the same as everything's right.", emotion: "edged" },
    { id: "deploy_1", bucket: "deploy", text: "Door's mine. Go.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "I'll cover the angle. Move when I say move.", emotion: "ready" },
    { id: "outcome_won", bucket: "outcome", text: "Watch held. We didn't lose anyone. Good shift.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "I missed a step. I'll re-run the drill in the morning.", emotion: "edged" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I should have been on that flank. I'll log {them} on every post I stand from now on.", emotion: "raw" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} stood beside me through three watches. I'll stand alone tonight. For {them}.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "Add it to the briefing pack. I'll re-read every shift.", emotion: "ready" },
    { id: "event_npc_dies", bucket: "event", text: "Someone should have been on that watch. It should have been me.", emotion: "raw" },
    { id: "banter_relief", bucket: "banter", text: "I relieve the watch. The watch doesn't relieve me.", emotion: "edged" },
    { id: "banter_oath", bucket: "banter", text: "An oath at a door is the only kind that holds.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a survivor of a watch I failed. I want to find {them}. Stand beside me when I do.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "Found {them}. {they}'s alive. {they} doesn't want to talk. I'll wait.", emotion: "low" },
    { id: "quest_3_break", bucket: "quest", text: "{they} forgave me. I haven't. Tell me whether the watch is over.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Stand the watch beside me. I'll explain the drills.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "You took a watch when I was breaking. I owe you one I'll never collect.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "Door's ours. Watch's ours. The post says so.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. Watch's quiet. You're cleared.", emotion: "calm" },
    { id: "greet_4", bucket: "greet", text: "I'll relieve when relieved. Standard.", emotion: "ready" },
    { id: "ambient_4", bucket: "ambient", text: "Drill ran two seconds long today. I'll re-run at dawn.", emotion: "edged" },
    { id: "ambient_5", bucket: "ambient", text: "The door logs report eleven openings. I count thirteen. Two are silent. Worrying.", emotion: "set" },
    { id: "ambient_6", bucket: "ambient", text: "I left a chalk mark on the rail. It hasn't moved. That's both reassuring and not.", emotion: "thoughtful" },
    { id: "ambient_7", bucket: "ambient", text: "Three watches in a row. Sleep can wait. Sleep should wait. Sleep won't.", emotion: "wry" },
    { id: "ambient_8", bucket: "ambient", text: "The cadre rotation's holding. I rest a quarter turn. The gear keeps.", emotion: "calm" },
    { id: "ambient_9", bucket: "ambient", text: "An oath at a door is the only kind that holds.", emotion: "warm" },
    { id: "deploy_3", bucket: "deploy", text: "Door's mine. Go.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "I'll cover the angle. Move when I say move.", emotion: "ready" },
    { id: "deploy_5", bucket: "deploy", text: "Three angles. I cover two. Trust the third one.", emotion: "set" },
    { id: "outcome_won_2", bucket: "outcome", text: "Watch held. We didn't lose anyone. Good shift.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "I missed a step. I'll re-run the drill in the morning.", emotion: "edged" },
    { id: "outcome_close_call", bucket: "outcome", text: "Door held. Threat passed. Three drills. I'll account for the fourth tomorrow.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "I should have been on that flank. I'll log {them} on every post I stand from now on.", emotion: "raw" },
    { id: "event_act_complete", bucket: "event", text: "New layout. New routes. The drill book is updating overnight.", emotion: "ready" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I'll add their post to the night rotation. {they} will appreciate the consistency.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "Their watch records have gaps. Three. Not coincidence.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew co-watched the alcove. I logged them both as relieved. Honestly.", emotion: "warm" },
    { id: "event_demon_summon", bucket: "event", text: "A bound spirit needs watching. I'll add a node to the rotation. Just one extra.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "{they} stood beside me through three watches. I'll stand alone tonight. For {them}.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. They asked about the door. I told them. We have time.", emotion: "ready" },
    { id: "event_first_costly_choice", bucket: "event", text: "Difficult call. I'll log it. I'll re-read the log. The log is fine.", emotion: "calm" },
    { id: "event_loredex_found", bucket: "event", text: "Add it to the briefing pack. I'll re-read every shift.", emotion: "ready" },
    { id: "banter_relief_2", bucket: "banter", text: "I relieve the watch. The watch doesn't relieve me.", emotion: "edged" },
    { id: "banter_oath_2", bucket: "banter", text: "An oath at a door is the only kind that holds.", emotion: "warm" },
    { id: "banter_routine", bucket: "banter", text: "Routine is the work. The work is routine. Don't complicate.", emotion: "calm" },
    { id: "quest_2_check", bucket: "quest", text: "Found {them}. Alive. Doesn't want to talk. I'll wait. I waited before. I can wait again.", emotion: "low" },
    { id: "quest_followup_a", bucket: "quest", text: "{they} forgave me. I haven't. The watch I failed was mine.", emotion: "raw" },
    { id: "quest_resolution_deep", bucket: "quest", text: "We share the next watch. {they} stands beside me. I'll log it as paired.", emotion: "warm" },
    { id: "quest_resolution_break", bucket: "quest", text: "I left the post early. {they} won't speak to me again. The post is mine forever now.", emotion: "raw" },
    { id: "romance_paired_watch", bucket: "romance", text: "Stand the watch beside me. I'll explain the drills.", emotion: "soft" },
    { id: "romance_relief", bucket: "romance", text: "You took a watch when I was breaking. I owe you one. I'll never collect.", emotion: "tender" },
  ],
  prodigal: [
    { id: "greet_1", bucket: "greet", text: "I'm back. Don't make a thing of it.", emotion: "wry" },
    { id: "greet_2", bucket: "greet", text: "Hi. Late. I know.", emotion: "low" },
    { id: "ambient_1", bucket: "ambient", text: "I left because the orthodoxy made me lonely. I came back because the road did.", emotion: "low" },
    { id: "ambient_2", bucket: "ambient", text: "Plain bread is the best meal I never appreciated.", emotion: "soft" },
    { id: "ambient_3", bucket: "ambient", text: "Three cycles in. I keep meaning to leave. I keep not.", emotion: "wry" },
    { id: "deploy_1", bucket: "deploy", text: "I'll do the work. I'm earning back trust the slow way.", emotion: "set" },
    { id: "deploy_2", bucket: "deploy", text: "Tell me where you need me. I'll be there. I'll stay.", emotion: "warm" },
    { id: "outcome_won", bucket: "outcome", text: "Came back with the team. That's two things in a row.", emotion: "warm" },
    { id: "outcome_wounded", bucket: "outcome", text: "I'm here. I came back. Same lesson. Bigger price.", emotion: "wry" },
    { id: "outcome_saw_death", bucket: "outcome", text: "I'd left {them} before. I came back to a goodbye I didn't earn.", emotion: "raw" },
    { id: "outcome_other_died", bucket: "outcome", text: "{they} held a seat for me when I was gone. I'll hold {their} seat now.", emotion: "mourning" },
    { id: "event_loredex", bucket: "event", text: "Familiar. I think I read this in another life.", emotion: "thoughtful" },
    { id: "event_costly_choice", bucket: "event", text: "I've made the cheaper version. Yours is harder to come back from.", emotion: "set" },
    { id: "banter_late", bucket: "banter", text: "Yes. Late. Move on.", emotion: "edged" },
    { id: "banter_seat", bucket: "banter", text: "Someone kept the seat. Tonight, it's mine.", emotion: "warm" },
    { id: "quest_1_open", bucket: "quest", text: "There's a person I left. I owe them the version of me that came back.", emotion: "set" },
    { id: "quest_2_mid", bucket: "quest", text: "Found them. They didn't recognize me. I'm not sure I do, either.", emotion: "raw" },
    { id: "quest_3_break", bucket: "quest", text: "They asked if I was staying. I don't know what to say. Tell me what staying looks like.", emotion: "raw" },
    { id: "romance_spark", bucket: "romance", text: "Witness me coming back. Slow.", emotion: "soft" },
    { id: "romance_courtship", bucket: "romance", text: "You don't ask why I left. That's why I'm here.", emotion: "tender" },
    { id: "romance_committed", bucket: "romance", text: "I'm back for good. Don't say it. I'll remember if you don't.", emotion: "warm" },
    { id: "greet_3", bucket: "greet", text: "Welcome. I'll be in the corner. I'm trying not to be in the corner.", emotion: "wry" },
    { id: "greet_4", bucket: "greet", text: "Hi. Late again. I know.", emotion: "low" },
    { id: "ambient_4", bucket: "ambient", text: "I left because the orthodoxy made me lonely. The orthodoxy is leaner now. Good.", emotion: "low" },
    { id: "ambient_5", bucket: "ambient", text: "Plain bread is the best meal I never appreciated. I appreciate it now. Three times daily.", emotion: "soft" },
    { id: "ambient_6", bucket: "ambient", text: "Three cycles in. I keep meaning to leave. I keep not. I'll keep meaning.", emotion: "wry" },
    { id: "ambient_7", bucket: "ambient", text: "The cadre held a seat for me. They didn't tell me. They didn't have to.", emotion: "warm" },
    { id: "ambient_8", bucket: "ambient", text: "I owe three apologies. I'll make two. The third one isn't mine.", emotion: "thoughtful" },
    { id: "ambient_9", bucket: "ambient", text: "Coming back is hard work. Staying back is harder. I do both. Slowly.", emotion: "calm" },
    { id: "deploy_3", bucket: "deploy", text: "I'll do the work. I'm earning back trust the slow way.", emotion: "set" },
    { id: "deploy_4", bucket: "deploy", text: "Tell me where you need me. I'll be there. I'll stay.", emotion: "warm" },
    { id: "deploy_5", bucket: "deploy", text: "If I'm late, I'm not. I'll be early next time. I promise.", emotion: "wry" },
    { id: "outcome_won_2", bucket: "outcome", text: "Came back with the team. That's two things in a row.", emotion: "warm" },
    { id: "outcome_wounded_2", bucket: "outcome", text: "I'm here. I came back. Same lesson. Bigger price.", emotion: "wry" },
    { id: "outcome_close_call", bucket: "outcome", text: "Almost left mid-mission. I didn't. I'll log the impulse and the choice.", emotion: "still" },
    { id: "outcome_routine_lost", bucket: "outcome", text: "{they} held a seat for me when I was gone. I'll hold {their} seat now.", emotion: "mourning" },
    { id: "event_act_complete", bucket: "event", text: "Another act. Another return. I'm getting good at it. Worse at it.", emotion: "thoughtful" },
    { id: "event_npc_returned", bucket: "event", text: "{they}'re back. I welcomed them. They asked who held their seat. I said I had. I had.", emotion: "warm" },
    { id: "event_betrayal_warning", bucket: "event", text: "I've made the cheaper version of this leaving. Watch them. They might come back.", emotion: "edged" },
    { id: "event_relationship_warm", bucket: "event", text: "Two crew bonded. I sat near them. They didn't ask me to leave. Progress.", emotion: "soft" },
    { id: "event_demon_summon", bucket: "event", text: "Bound spirits return too. The math works the same.", emotion: "thoughtful" },
    { id: "event_apprentice_died", bucket: "event", text: "{they} held a seat for me. I'll keep theirs warm. The cadre will know.", emotion: "mourning" },
    { id: "event_recruit_added", bucket: "event", text: "New crew. I'll be slow with them. I know what new feels like.", emotion: "soft" },
    { id: "event_first_costly_choice", bucket: "event", text: "I've made the cheaper version. Yours is harder to come back from. Don't.", emotion: "set" },
    { id: "event_loredex_found", bucket: "event", text: "Familiar. I think I read this in another life. Three lifetimes ago.", emotion: "thoughtful" },
    { id: "banter_late_2", bucket: "banter", text: "Yes. Late. Move on.", emotion: "edged" },
    { id: "banter_seat_2", bucket: "banter", text: "Someone kept the seat. Tonight, it's mine.", emotion: "warm" },
    { id: "banter_apology", bucket: "banter", text: "I owe you an apology. I haven't said it. You haven't asked. We're balanced.", emotion: "wry" },
    { id: "quest_2_check", bucket: "quest", text: "Found them. They didn't recognize me. I'm not sure I do, either.", emotion: "raw" },
    { id: "quest_followup_a", bucket: "quest", text: "They asked if I was staying. I told them yes. I'm trying.", emotion: "wondering" },
    { id: "quest_resolution_deep", bucket: "quest", text: "I stayed. They forgave me. The cadre forgave me. I'm working on me.", emotion: "tender" },
    { id: "quest_resolution_break", bucket: "quest", text: "I left again. They saw me leave. They told me I would. They were right.", emotion: "raw" },
    { id: "romance_simple", bucket: "romance", text: "Witness me coming back. Slow. I'll show up most days. Don't mark them down.", emotion: "soft" },
    { id: "romance_kept_seat", bucket: "romance", text: "You don't ask why I left. That's why I'm here. I'm staying.", emotion: "tender" },
  ],
};

/* ─── Pronoun substitution map ─── */

export type VoiceGender = "female" | "male" | "neutral";

export const PRONOUN_MAP: Record<VoiceGender, Record<string, string>> = {
  female: { they: "she", them: "her", their: "her", theirs: "hers", themself: "herself" },
  male:   { they: "he",  them: "him", their: "his", theirs: "his",  themself: "himself" },
  neutral:{ they: "they", them: "them", their: "their", theirs: "theirs", themself: "themself" },
};

/** Substitute pronoun placeholders in a line. Capitalises "they" at the
 *  start of a sentence. Subject-form pronouns when followed by a verb;
 *  object-form when at end-of-clause; possessive forms via {their}. */
export function applyPronouns(line: string, gender: VoiceGender): string {
  const map = PRONOUN_MAP[gender];
  let out = line;
  for (const key of Object.keys(map)) {
    const re = new RegExp(`\\{${key}\\}`, "g");
    out = out.replace(re, map[key]);
  }
  // Capitalise leading lowercase pronouns at sentence start.
  out = out.replace(/(^|[.!?]\s+)([a-z])/g, (_, p1, p2) => p1 + p2.toUpperCase());
  return out;
}

/** All bucket names in canonical order. */
export const VOICE_BUCKETS: VoiceBucket[] = [
  "greet",
  "ambient",
  "deploy",
  "outcome",
  "event",
  "banter",
  "quest",
  "romance",
];
