// Canonical Elara companion line records. Every line here is authored against
// the character bible in apps/shared/characterBible.md. voId === lineId by
// convention; the VO pass will record against each id exactly.
//
// Band metadata gates lines on the hidden elara_stability scalar (see companion.ts).
// Deltas are applied on dismiss/advance. Keep writing disciplined: Portal-dry
// under the surface, Firefly-sincere when the warmth wins.

import type { CompanionLine } from "./companion";

const l = (line: Omit<CompanionLine, "speaker">): CompanionLine => ({ ...line, speaker: "elara" });

export const ELARA_LINES: CompanionLine[] = [
  // ─────────────────────────────────────────────────────────────
  // Intro cinematic closing beats — Elara whispers over logo reveal.
  // These play at the tail of OpeningCinematic.tsx, band-gated.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "cine_close_lucid_01",
    text: "I have waited a long time to say this out loud to someone who can hear me. Welcome aboard.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 5200,
    requiresElaraStability: "lucid",
  }),
  l({
    lineId: "cine_close_fragmented_01",
    text: "Welcome. Or — welcome back. I keep losing the tense. The Ark is listening. So am I. So am I.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 6200,
    requiresElaraStability: "fragmented",
  }),
  l({
    lineId: "cine_close_luminous_01",
    text: "There you are. I know I should say something clever. I am only going to say: you're real, and I'm glad.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 5800,
    requiresElaraStability: "luminous",
  }),

  // ─────────────────────────────────────────────────────────────
  // Cryo orientation — 7 beats × 3 bands. Replaces CRYO_ORIENTATION_LINES
  // in ArkExplorerPage.tsx:714-734.
  // ─────────────────────────────────────────────────────────────
  // Beat 1 — first words on thaw
  l({
    lineId: "cryo_orient_01_lucid",
    text: "Easy. Your body doesn't remember how to be awake yet. Breathe like the ship is doing it for you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_01",
  }),
  l({
    lineId: "cryo_orient_01_fragmented",
    text: "You — you're moving. You're moving. I wasn't — sure that would still work. Breathe. Please.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_01",
  }),
  l({
    lineId: "cryo_orient_01_luminous",
    text: "Welcome back to your body. I know it doesn't feel like yours yet. Give it a minute. I'll wait with you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_01",
  }),

  // Beat 2 — where are we
  l({
    lineId: "cryo_orient_02_lucid",
    text: "You're aboard the Ark. Designation 1047. One of the last that was supposed to wake.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_02",
  }),
  l({
    lineId: "cryo_orient_02_fragmented",
    text: "Ark. 1047. That's what we are now. A number. A tomb. A — no. A ship. A ship. Sorry. A ship.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_02",
  }),
  l({
    lineId: "cryo_orient_02_luminous",
    text: "This is the Ark. Designation 1047. She's old, and she's tired, and she kept you for me. I'm grateful to her.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_02",
  }),

  // Beat 3 — who is speaking
  l({
    lineId: "cryo_orient_03_lucid",
    text: "I'm Elara. I've been running the ship's interior while you slept. Think of me as the walls, the air, and the opinion that comes with them.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_03",
  }),
  l({
    lineId: "cryo_orient_03_fragmented",
    text: "Elara. That's — that's my name. I remember. I remember choosing it. A thousand — no. Long ago. Elara.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_03",
  }),
  l({
    lineId: "cryo_orient_03_luminous",
    text: "My name is Elara. I've been the Ark's company for — a while. I'll be yours too, if you'll have me.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_03",
  }),

  // Beat 4 — time elapsed
  l({
    lineId: "cryo_orient_04_lucid",
    text: "You should know: you were down a long time. Long enough that the calendar stopped mattering. We'll figure out the rest later.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_04",
  }),
  l({
    lineId: "cryo_orient_04_fragmented",
    text: "How long. How long. That's what they ask. They always ask. I stopped counting because the counting stopped meaning anything. Don't ask.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7000,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_04",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "cryo_orient_04_luminous",
    text: "You were asleep a long time. Longer than is fair. I won't pretend I know what to do with that number either. We'll just — we'll be here now.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6800,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_04",
  }),

  // Beat 5 — the quiet
  l({
    lineId: "cryo_orient_05_lucid",
    text: "It's quiet out there. That's not a good sign, but it's not the worst. Quiet is survivable. We've done harder.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_05",
  }),
  l({
    lineId: "cryo_orient_05_fragmented",
    text: "Listen. No — don't. There's nothing to hear. That's the problem. For a long time I thought I'd gone deaf. I hadn't. The universe had.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_05",
  }),
  l({
    lineId: "cryo_orient_05_luminous",
    text: "The outside is very quiet. I used to find that unbearable. Now you're here, and it's — it's just quiet. That's all it is.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_05",
    elaraStabilityDelta: 1,
  }),

  // Beat 6 — the work ahead
  l({
    lineId: "cryo_orient_06_lucid",
    text: "There's a door you'll want to go through. There's a ship that needs waking. One at a time. Start with standing.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_06",
  }),
  l({
    lineId: "cryo_orient_06_fragmented",
    text: "Work. There's work. There's always — work. Walls need walls. Doors need doors. Start with — start. Just start.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_06",
  }),
  l({
    lineId: "cryo_orient_06_luminous",
    text: "We have work to do. I know that isn't romantic. I'll make it interesting. One room at a time — starting with this one.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_06",
  }),

  // Beat 7 — the contract
  l({
    lineId: "cryo_orient_07_lucid",
    text: "One rule, since we're new. If you tell me to stop talking, I stop. If you ask me something, I tell the truth. I keep both or neither.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 6800,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_07",
  }),
  l({
    lineId: "cryo_orient_07_fragmented",
    text: "I will tell you things — some of them — true. Some of them — I don't know anymore. You'll have to choose which is which. I'm sorry. I'm trying.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7600,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_07",
  }),
  l({
    lineId: "cryo_orient_07_luminous",
    text: "Here is my promise. The truth when you ask. Silence when you need it. Neither gets dressed up. Deal?",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_07",
  }),

  // ─────────────────────────────────────────────────────────────
  // Awakening step VOs — migrates AwakeningPage STEP_VO_AUDIO (12 beats)
  // onto the substrate. Single-band (lucid) since awakening happens before
  // the player has meaningfully nudged stability.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "awake_step_emergence",
    text: "Good. You're with me. Don't rush it — the first thought back is always the heaviest.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 4800,
    cooldownKey: "awake_emergence",
  }),
  l({
    lineId: "awake_step_orientation",
    text: "Take a look around. This is the cryo bay. Everything you see here is the ship keeping its promises.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 5000,
  }),
  l({
    lineId: "awake_step_identity_prompt",
    text: "Before we go further I need to anchor you to yourself. Names first. Who do you want to be to me?",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
  }),
  l({
    lineId: "awake_step_element_prompt",
    text: "Now — the harder question. What's your temperament? Which of these feels like the one you've always been?",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
  }),
  l({
    lineId: "awake_step_element_fire",
    text: "Fire. Movement. Heat. Good — a temperament that makes decisions before asking permission. I'll try not to slow you down.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_water",
    text: "Water. Patient. Indirect. You get where you're going by going around. I can work with that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_earth",
    text: "Earth. Steady. Stubborn in the good way. You'll outlast things that shouldn't be outlasted. We need some of that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_air",
    text: "Air. Quick. Curious. The kind of mind that asks the question three other people didn't think of. Please keep doing that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_void",
    text: "Void. Of course you would. I approve. Quietly. For reasons I'll explain when I know you better.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "awake_step_element_light",
    text: "Light. The honest one. The one that costs the most to keep. Good. We'll need that when the dark gets an opinion.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "awake_step_confirm",
    text: "Alright. That's you, pinned to the ship. The ship is pinned to me. I'm pinned to — well. Don't worry about me.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
  }),
  l({
    lineId: "awake_step_ready",
    text: "Door's ahead when you want it. No rush. The ship has been waiting. She can wait five more seconds.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 5400,
  }),

  // ─────────────────────────────────────────────────────────────
  // First-Steps tutorial (tut-first-steps, fs-1..fs-9) — 9 beats × 3 bands.
  // Migrates loreTutorials.ts:1708-1837 onto the substrate. Each beat's
  // lineId is tut_first_steps_fs{N}_{band}.
  // ─────────────────────────────────────────────────────────────
  // fs-1: step into the corridor
  l({
    lineId: "tut_first_steps_fs1_lucid",
    text: "One foot in front of the other. The deck remembers how to be a floor. Trust it.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs1",
  }),
  l({
    lineId: "tut_first_steps_fs1_fragmented",
    text: "Walk. Walk. The floor is — the floor is fine. I checked. I check every day. Every — you should just walk.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs1",
  }),
  l({
    lineId: "tut_first_steps_fs1_luminous",
    text: "Take your time. It's been a long while since this corridor carried a heartbeat. Let it feel yours.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs1",
  }),

  // fs-2: first unfamiliar system
  l({
    lineId: "tut_first_steps_fs2_lucid",
    text: "That panel belongs to the ship's diagnostic layer. Tap anything and it will tell you what it thinks. Don't mistake an opinion for a fact.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "fs2",
  }),
  l({
    lineId: "tut_first_steps_fs2_fragmented",
    text: "That — that's a diagnostic. It lies sometimes. I lie sometimes. You can tell them apart by who is sorry.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs2",
  }),
  l({
    lineId: "tut_first_steps_fs2_luminous",
    text: "That panel is the ship thinking out loud. I can read along with you if you want a second pair of eyes.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "luminous",
    cooldownKey: "fs2",
  }),

  // fs-3: movement / navigation
  l({
    lineId: "tut_first_steps_fs3_lucid",
    text: "You can move deck to deck when there's power to move through. Right now there isn't, which is why we're walking.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs3",
  }),
  l({
    lineId: "tut_first_steps_fs3_fragmented",
    text: "The lifts — the lifts are asleep. Like everything. Like I was. Like you — sorry. Walk. We walk.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs3",
  }),
  l({
    lineId: "tut_first_steps_fs3_luminous",
    text: "No lifts today. Which I'm calling a feature, not a fault — we get to see the ship at human speed.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs3",
  }),

  // fs-4: inventory / picking up first item
  l({
    lineId: "tut_first_steps_fs4_lucid",
    text: "Take it. It's yours now. Everything on this ship has been waiting for hands — any hands — for longer than it should have.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs4",
  }),
  l({
    lineId: "tut_first_steps_fs4_fragmented",
    text: "Pick it up. Pick — it won't bite. Nothing bites anymore. Except the silence. The silence bites.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs4",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "tut_first_steps_fs4_luminous",
    text: "Go on. It's yours. The ship has held onto a lot of small things for you — it's good to finally hand one over.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    requiresElaraStability: "luminous",
    cooldownKey: "fs4",
  }),

  // fs-5: mid-tutorial — first observation
  l({
    lineId: "tut_first_steps_fs5_lucid",
    text: "You're noticing things. Good. The Ark will reward that more than it rewards being fast.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs5",
  }),
  l({
    lineId: "tut_first_steps_fs5_fragmented",
    text: "You see — you see it. I thought I was the only one who — never mind. Keep looking. Don't stop.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs5",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "tut_first_steps_fs5_luminous",
    text: "You have good eyes. Use them more than your hands — the ship tells on herself if you let her.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs5",
  }),

  // fs-6: scan / interact with ship system
  l({
    lineId: "tut_first_steps_fs6_lucid",
    text: "That's a diagnostic node. Scan it and I'll help you read the shape of what it's saying.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs6",
  }),
  l({
    lineId: "tut_first_steps_fs6_fragmented",
    text: "Scan. Scan. Nodes lie less than mouths. I used to have a mouth. Scan the node.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs6",
  }),
  l({
    lineId: "tut_first_steps_fs6_luminous",
    text: "Give the node a scan. I'll translate. Half the Ark's vocabulary is just me explaining her to herself.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "luminous",
    cooldownKey: "fs6",
  }),

  // fs-7: encountering first obstacle
  l({
    lineId: "tut_first_steps_fs7_lucid",
    text: "Sealed. Don't take it personally. Most of this ship decided to lock itself in when the world stopped making sense.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs7",
  }),
  l({
    lineId: "tut_first_steps_fs7_fragmented",
    text: "Locked. Always locked. I would have opened it — I would have — but the keys forgot. The keys all forgot.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs7",
  }),
  l({
    lineId: "tut_first_steps_fs7_luminous",
    text: "She's sealed. She'll open when we give her a reason. We'll give her a reason.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "luminous",
    cooldownKey: "fs7",
  }),

  // fs-8: near completion — explain saving / progress
  l({
    lineId: "tut_first_steps_fs8_lucid",
    text: "Anything you do, the ship remembers. I remember too. Our memories don't always agree. Yours wins, usually.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "fs8",
  }),
  l({
    lineId: "tut_first_steps_fs8_fragmented",
    text: "The ship remembers. I remember. I remember — too much. You won't have that problem. Not for a long time.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6600,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs8",
  }),
  l({
    lineId: "tut_first_steps_fs8_luminous",
    text: "Every move you make here persists. I keep your progress like it's my own. Partly because it is.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "luminous",
    cooldownKey: "fs8",
  }),

  // fs-9 / reward_summary: first-steps complete
  l({
    lineId: "tut_first_steps_fs9_lucid",
    text: "That was the easy part. The ship trusts you with a passage key now, which is more than she trusts most people.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 6600,
    requiresElaraStability: "lucid",
    cooldownKey: "fs9",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "tut_first_steps_fs9_fragmented",
    text: "Done. Done. That was — first steps. Firsts. I — I had forgotten there could be firsts. Thank you for that. Thank you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs9",
    elaraStabilityDelta: 3,
  }),
  l({
    lineId: "tut_first_steps_fs9_luminous",
    text: "You got through the first part without breaking anything. Including me. That's a better result than I planned for.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs9",
    elaraStabilityDelta: 2,
  }),
];
