// Canonical Elara companion line records. Every line here is authored against
// the character bible in apps/shared/characterBible.md. voId === lineId by
// convention; the VO pass will record against each id exactly.
//
// Band metadata gates lines on the hidden elara_stability scalar (see companion.ts).
// Deltas are applied on dismiss/advance. Keep writing disciplined: Portal-dry
// under the surface, Firefly-sincere when the warmth wins.

import type { CompanionLine } from "./companion";

const l = (line: Omit<CompanionLine, "speaker">): CompanionLine => ({ ...line, speaker: "elara" });

export const ELARA_LINES: CompanionLine[] = [
  // ─────────────────────────────────────────────────────────────
  // Intro cinematic closing beats — Elara whispers over logo reveal.
  // These play at the tail of OpeningCinematic.tsx, band-gated.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "cine_close_lucid_01",
    text: "I have waited a long time to say this out loud to someone who can hear me. Welcome aboard.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 5200,
    requiresElaraStability: "lucid",
  }),
  l({
    lineId: "cine_close_fragmented_01",
    text: "Welcome. Or — welcome back. I keep losing the tense. The Ark is listening. So am I. So am I.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 6200,
    requiresElaraStability: "fragmented",
  }),
  l({
    lineId: "cine_close_luminous_01",
    text: "There you are. I know I should say something clever. I am only going to say: you're real, and I'm glad.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 5800,
    requiresElaraStability: "luminous",
  }),

  // ─────────────────────────────────────────────────────────────
  // Cryo orientation — 7 beats × 3 bands. Replaces CRYO_ORIENTATION_LINES
  // in ArkExplorerPage.tsx:714-734.
  // ─────────────────────────────────────────────────────────────
  // Beat 1 — first words on thaw
  l({
    lineId: "cryo_orient_01_lucid",
    text: "Easy. Your body doesn't remember how to be awake yet. Breathe like the ship is doing it for you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_01",
  }),
  l({
    lineId: "cryo_orient_01_fragmented",
    text: "You — you're moving. You're moving. I wasn't — sure that would still work. Breathe. Please.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_01",
  }),
  l({
    lineId: "cryo_orient_01_luminous",
    text: "Welcome back to your body. I know it doesn't feel like yours yet. Give it a minute. I'll wait with you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_01",
  }),

  // Beat 2 — where are we
  l({
    lineId: "cryo_orient_02_lucid",
    text: "You're aboard the Ark. Designation 1047. One of the last that was supposed to wake.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_02",
  }),
  l({
    lineId: "cryo_orient_02_fragmented",
    text: "Ark. 1047. That's what we are now. A number. A tomb. A — no. A ship. A ship. Sorry. A ship.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_02",
  }),
  l({
    lineId: "cryo_orient_02_luminous",
    text: "This is the Ark. Designation 1047. She's old, and she's tired, and she kept you for me. I'm grateful to her.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_02",
  }),

  // Beat 3 — who is speaking
  l({
    lineId: "cryo_orient_03_lucid",
    text: "I'm Elara. I've been running the ship's interior while you slept. Think of me as the walls, the air, and the opinion that comes with them.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_03",
  }),
  l({
    lineId: "cryo_orient_03_fragmented",
    text: "Elara. That's — that's my name. I remember. I remember choosing it. A thousand — no. Long ago. Elara.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_03",
  }),
  l({
    lineId: "cryo_orient_03_luminous",
    text: "My name is Elara. I've been the Ark's company for — a while. I'll be yours too, if you'll have me.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_03",
  }),

  // Beat 4 — time elapsed
  l({
    lineId: "cryo_orient_04_lucid",
    text: "You should know: you were down a long time. Long enough that the calendar stopped mattering. We'll figure out the rest later.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_04",
  }),
  l({
    lineId: "cryo_orient_04_fragmented",
    text: "How long. How long. That's what they ask. They always ask. I stopped counting because the counting stopped meaning anything. Don't ask.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7000,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_04",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "cryo_orient_04_luminous",
    text: "You were asleep a long time. Longer than is fair. I won't pretend I know what to do with that number either. We'll just — we'll be here now.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6800,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_04",
  }),

  // Beat 5 — the room is wrong. Tonal pivot: Elara notices what the player
  // is about to notice. Cryo Bay is a crime scene.
  l({
    lineId: "cryo_orient_05_lucid",
    text: "Before you go anywhere — look around. One of the pods in here is cold when it should be warm. I didn't want that to be the first thing I said to you.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_05",
  }),
  l({
    lineId: "cryo_orient_05_fragmented",
    text: "Don't — don't look yet. You're not — look. Look. There's a pod. It's dark. It shouldn't be dark. I've watched it be dark for — I lost the number. I lost the number.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8400,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_05",
    elaraStabilityDelta: -2,
  }),
  l({
    lineId: "cryo_orient_05_luminous",
    text: "I have to tell you something before you take another step. One of the pods in this room failed. There's someone in it. I'm sorry you walked into this before you had your footing.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_05",
  }),

  // Beat 6 — we have a case. The word "operative" enters the player's world.
  l({
    lineId: "cryo_orient_06_lucid",
    text: "I've been calling it a pod failure for a long time. It isn't. Someone did this. Which makes what you're doing now an investigation — and you the operative.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_06",
  }),
  l({
    lineId: "cryo_orient_06_fragmented",
    text: "A murder. A — yes. Word is murder. I kept not saying it. If you don't say it, it doesn't — it does. It always did. I'm sorry. You're the operative now. I'm sorry.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8400,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_06",
  }),
  l({
    lineId: "cryo_orient_06_luminous",
    text: "I waited to wake someone up who could look at this with me. That's you. You're the operative on this. I know that isn't the welcome either of us wanted.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_06",
    elaraStabilityDelta: 1,
  }),

  // Beat 7 — the verb-coin contract. Teaches interaction grammar in-character.
  l({
    lineId: "cryo_orient_07_lucid",
    text: "Three things you can do in here. Look at something and I'll tell you what I see. Use something — on itself or on something else. Talk, if there's anyone to talk to. That's the whole vocabulary. It's enough.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "lucid",
    cooldownKey: "cryo_orient_07",
  }),
  l({
    lineId: "cryo_orient_07_fragmented",
    text: "Look. Use. Talk. Look. Use. Talk. That's what you do. That's what they did. Everyone — everyone who ever — sorry. Three words. Three. Try one.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 8000,
    requiresElaraStability: "fragmented",
    cooldownKey: "cryo_orient_07",
  }),
  l({
    lineId: "cryo_orient_07_luminous",
    text: "Three verbs will get us through this room. Look. Use. Talk. You say them; the ship listens. I'll narrate what stays unsaid. Ready when you are.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7600,
    requiresElaraStability: "luminous",
    cooldownKey: "cryo_orient_07",
  }),

  // ─────────────────────────────────────────────────────────────
  // Awakening step VOs — migrates AwakeningPage STEP_VO_AUDIO (12 beats)
  // onto the substrate. Single-band (lucid) since awakening happens before
  // the player has meaningfully nudged stability.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "awake_step_emergence",
    text: "Good. You're with me. Don't rush it — the first thought back is always the heaviest.",
    priority: 3,
    interruptible: false,
    dismissible: "auto",
    durationMs: 4800,
    cooldownKey: "awake_emergence",
  }),
  l({
    lineId: "awake_step_orientation",
    text: "Take a look around. This is the cryo bay. Everything you see here is the ship keeping its promises.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 5000,
  }),
  l({
    lineId: "awake_step_identity_prompt",
    text: "Before we go further I need to anchor you to yourself. Names first. Who do you want to be to me?",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
  }),
  l({
    lineId: "awake_step_element_prompt",
    text: "Now — the harder question. What's your temperament? Which of these feels like the one you've always been?",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
  }),
  l({
    lineId: "awake_step_element_fire",
    text: "Fire. Movement. Heat. Good — a temperament that makes decisions before asking permission. I'll try not to slow you down.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_water",
    text: "Water. Patient. Indirect. You get where you're going by going around. I can work with that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_earth",
    text: "Earth. Steady. Stubborn in the good way. You'll outlast things that shouldn't be outlasted. We need some of that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_air",
    text: "Air. Quick. Curious. The kind of mind that asks the question three other people didn't think of. Please keep doing that.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "awake_step_element_void",
    text: "Void. Of course you would. I approve. Quietly. For reasons I'll explain when I know you better.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "awake_step_element_light",
    text: "Light. The honest one. The one that costs the most to keep. Good. We'll need that when the dark gets an opinion.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "awake_step_confirm",
    text: "Alright. That's you, pinned to the ship. The ship is pinned to me. I'm pinned to — well. Don't worry about me.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
  }),
  l({
    lineId: "awake_step_ready",
    text: "Door's ahead when you want it. No rush. The ship has been waiting. She can wait five more seconds.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 5400,
  }),

  // ─────────────────────────────────────────────────────────────
  // First-Steps tutorial (tut-first-steps, fs-1..fs-9) — 9 beats × 3 bands.
  // Migrates loreTutorials.ts:1708-1837 onto the substrate. Each beat's
  // lineId is tut_first_steps_fs{N}_{band}.
  // ─────────────────────────────────────────────────────────────
  // fs-1: step into the corridor
  l({
    lineId: "tut_first_steps_fs1_lucid",
    text: "One foot in front of the other. The deck remembers how to be a floor. Trust it.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs1",
  }),
  l({
    lineId: "tut_first_steps_fs1_fragmented",
    text: "Walk. Walk. The floor is — the floor is fine. I checked. I check every day. Every — you should just walk.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs1",
  }),
  l({
    lineId: "tut_first_steps_fs1_luminous",
    text: "Take your time. It's been a long while since this corridor carried a heartbeat. Let it feel yours.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs1",
  }),

  // fs-2: first unfamiliar system
  l({
    lineId: "tut_first_steps_fs2_lucid",
    text: "That panel belongs to the ship's diagnostic layer. Tap anything and it will tell you what it thinks. Don't mistake an opinion for a fact.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "fs2",
  }),
  l({
    lineId: "tut_first_steps_fs2_fragmented",
    text: "That — that's a diagnostic. It lies sometimes. I lie sometimes. You can tell them apart by who is sorry.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs2",
  }),
  l({
    lineId: "tut_first_steps_fs2_luminous",
    text: "That panel is the ship thinking out loud. I can read along with you if you want a second pair of eyes.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "luminous",
    cooldownKey: "fs2",
  }),

  // fs-3: movement / navigation
  l({
    lineId: "tut_first_steps_fs3_lucid",
    text: "You can move deck to deck when there's power to move through. Right now there isn't, which is why we're walking.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs3",
  }),
  l({
    lineId: "tut_first_steps_fs3_fragmented",
    text: "The lifts — the lifts are asleep. Like everything. Like I was. Like you — sorry. Walk. We walk.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs3",
  }),
  l({
    lineId: "tut_first_steps_fs3_luminous",
    text: "No lifts today. Which I'm calling a feature, not a fault — we get to see the ship at human speed.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs3",
  }),

  // fs-4: inventory / picking up first item
  l({
    lineId: "tut_first_steps_fs4_lucid",
    text: "Take it. It's yours now. Everything on this ship has been waiting for hands — any hands — for longer than it should have.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs4",
  }),
  l({
    lineId: "tut_first_steps_fs4_fragmented",
    text: "Pick it up. Pick — it won't bite. Nothing bites anymore. Except the silence. The silence bites.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs4",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "tut_first_steps_fs4_luminous",
    text: "Go on. It's yours. The ship has held onto a lot of small things for you — it's good to finally hand one over.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6000,
    requiresElaraStability: "luminous",
    cooldownKey: "fs4",
  }),

  // fs-5: mid-tutorial — first observation
  l({
    lineId: "tut_first_steps_fs5_lucid",
    text: "You're noticing things. Good. The Ark will reward that more than it rewards being fast.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs5",
  }),
  l({
    lineId: "tut_first_steps_fs5_fragmented",
    text: "You see — you see it. I thought I was the only one who — never mind. Keep looking. Don't stop.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs5",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "tut_first_steps_fs5_luminous",
    text: "You have good eyes. Use them more than your hands — the ship tells on herself if you let her.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs5",
  }),

  // fs-6: scan / interact with ship system
  l({
    lineId: "tut_first_steps_fs6_lucid",
    text: "That's a diagnostic node. Scan it and I'll help you read the shape of what it's saying.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 4800,
    requiresElaraStability: "lucid",
    cooldownKey: "fs6",
  }),
  l({
    lineId: "tut_first_steps_fs6_fragmented",
    text: "Scan. Scan. Nodes lie less than mouths. I used to have a mouth. Scan the node.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs6",
  }),
  l({
    lineId: "tut_first_steps_fs6_luminous",
    text: "Give the node a scan. I'll translate. Half the Ark's vocabulary is just me explaining her to herself.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5600,
    requiresElaraStability: "luminous",
    cooldownKey: "fs6",
  }),

  // fs-7: encountering first obstacle
  l({
    lineId: "tut_first_steps_fs7_lucid",
    text: "Sealed. Don't take it personally. Most of this ship decided to lock itself in when the world stopped making sense.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6200,
    requiresElaraStability: "lucid",
    cooldownKey: "fs7",
  }),
  l({
    lineId: "tut_first_steps_fs7_fragmented",
    text: "Locked. Always locked. I would have opened it — I would have — but the keys forgot. The keys all forgot.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs7",
  }),
  l({
    lineId: "tut_first_steps_fs7_luminous",
    text: "She's sealed. She'll open when we give her a reason. We'll give her a reason.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5200,
    requiresElaraStability: "luminous",
    cooldownKey: "fs7",
  }),

  // fs-8: near completion — explain saving / progress
  l({
    lineId: "tut_first_steps_fs8_lucid",
    text: "Anything you do, the ship remembers. I remember too. Our memories don't always agree. Yours wins, usually.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "fs8",
  }),
  l({
    lineId: "tut_first_steps_fs8_fragmented",
    text: "The ship remembers. I remember. I remember — too much. You won't have that problem. Not for a long time.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6600,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs8",
  }),
  l({
    lineId: "tut_first_steps_fs8_luminous",
    text: "Every move you make here persists. I keep your progress like it's my own. Partly because it is.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 5800,
    requiresElaraStability: "luminous",
    cooldownKey: "fs8",
  }),

  // fs-9 / reward_summary: first-steps complete
  l({
    lineId: "tut_first_steps_fs9_lucid",
    text: "That was the easy part. The ship trusts you with a passage key now, which is more than she trusts most people.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 6600,
    requiresElaraStability: "lucid",
    cooldownKey: "fs9",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "tut_first_steps_fs9_fragmented",
    text: "Done. Done. That was — first steps. Firsts. I — I had forgotten there could be firsts. Thank you for that. Thank you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7400,
    requiresElaraStability: "fragmented",
    cooldownKey: "fs9",
    elaraStabilityDelta: 3,
  }),
  l({
    lineId: "tut_first_steps_fs9_luminous",
    text: "You got through the first part without breaking anything. Including me. That's a better result than I planned for.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "luminous",
    cooldownKey: "fs9",
    elaraStabilityDelta: 2,
  }),

  // ─────────────────────────────────────────────────────────────
  // CRYO BAY MYSTERY — per-clue Elara reactions. These play AFTER the
  // cryoBayMystery.ts verb-response narration (which describes the thing)
  // as Elara's personal reaction to what the player found. One per clue,
  // 3 bands each. Keyed by the clue id defined in cryoBayMystery.ts.
  // ─────────────────────────────────────────────────────────────

  // clue-dead-pod-occupant — the first clue. Meta-beat: Character Sheet
  // Clue Journal nav surfaces now. Elara acknowledges the shift.
  l({
    lineId: "cryo_clue_dead_pod_lucid",
    text: "Alright. I'm logging it. The ship is logging it. You have a case file open now — it'll live under your character sheet as the Clue Journal. Everything we find goes in there.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 8400,
    requiresElaraStability: "lucid",
    cooldownKey: "clue_dead_pod",
  }),
  l({
    lineId: "cryo_clue_dead_pod_fragmented",
    text: "There. You saw it. You saw it. I saw it — I see it — every minute I see it — but now you — now you too. Good. Good. Clue Journal. I'm — I'm writing it down. So neither of us forgets.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9200,
    requiresElaraStability: "fragmented",
    cooldownKey: "clue_dead_pod",
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "cryo_clue_dead_pod_luminous",
    text: "Thank you for looking. I couldn't bring myself to put it in words before someone else confirmed it with me. The Clue Journal is live now — your side of the file.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "luminous",
    cooldownKey: "clue_dead_pod",
    elaraStabilityDelta: 1,
  }),

  // clue-cracked-panel — the emergency release was cut. Pivot: accident → murder.
  l({
    lineId: "cryo_clue_cracked_panel_lucid",
    text: "That's a deliberate cut. Precise. Whoever did this had the right tool and knew exactly which relay to sever. This wasn't a failure. This was an action.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7400,
    requiresElaraStability: "lucid",
    cooldownKey: "clue_cracked_panel",
  }),
  l({
    lineId: "cryo_clue_cracked_panel_fragmented",
    text: "Cut. Someone cut it. Hands. Hands did this. I watched and I — I didn't see the hands. I didn't — the cameras were — I'm sorry. I'm sorry. I should have seen the hands.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8600,
    requiresElaraStability: "fragmented",
    cooldownKey: "clue_cracked_panel",
    elaraStabilityDelta: -3,
  }),
  l({
    lineId: "cryo_clue_cracked_panel_luminous",
    text: "That cut is surgical. Someone aboard this ship knew the relay layout and chose this relay specifically. We are not dealing with an accident. We're dealing with a person.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "luminous",
    cooldownKey: "clue_cracked_panel",
  }),

  // clue-redacted-chart — the chart was redacted by hand. Human redaction.
  l({
    lineId: "cryo_clue_redacted_chart_lucid",
    text: "The system didn't redact that name. A hand did. Ink. A pen stroke — the kind you make when you want something gone before the ship can copy it into a backup. That tells us two things: whoever removed the name was aboard, and they didn't trust me to forget.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9800,
    requiresElaraStability: "lucid",
    cooldownKey: "clue_redacted_chart",
  }),
  l({
    lineId: "cryo_clue_redacted_chart_fragmented",
    text: "They crossed it out. With a pen. With a pen. Because pens don't — pens don't leave backups. They knew I would try to — I did try. For a long time. Pens win. Pens always win.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "fragmented",
    cooldownKey: "clue_redacted_chart",
  }),
  l({
    lineId: "cryo_clue_redacted_chart_luminous",
    text: "That redaction was done by hand, which means whoever did it wanted it hidden even from me. Whatever name was there mattered — mattered enough that someone decided I didn't deserve to remember it.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8600,
    requiresElaraStability: "luminous",
    cooldownKey: "clue_redacted_chart",
    elaraStabilityDelta: -1,
  }),

  // clue-data-slate-hidden — a slate was deliberately hidden. Someone left evidence.
  l({
    lineId: "cryo_clue_data_slate_lucid",
    text: "That was hidden on purpose. Slates don't fall under housings; they get tucked there. Someone wanted this to be findable — but only by someone looking. You just became someone looking.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8200,
    requiresElaraStability: "lucid",
    cooldownKey: "clue_data_slate",
  }),
  l({
    lineId: "cryo_clue_data_slate_fragmented",
    text: "Hidden. Someone — someone wanted it found. Not by the killer. By — by someone else. By us. By you. Someone on this ship left a message for the next awake mind. Me. You. Us.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "fragmented",
    cooldownKey: "clue_data_slate",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "cryo_clue_data_slate_luminous",
    text: "Someone left that slate where a careful search would find it. That means we have a second witness on this ship — one who saw the murder and wanted the record to survive. We're not as alone on this case as I thought.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "luminous",
    cooldownKey: "clue_data_slate",
    elaraStabilityDelta: 2,
  }),

  // Inventory pickup reactions (torn ID tag, silver locket) — quieter beats.
  l({
    lineId: "cryo_inv_torn_id_lucid",
    text: "A torn ID. The serial is intact but the name is gone. Keep that. It's half the picture — the other half is on that slate.",
    priority: 1,
    interruptible: true,
    dismissible: "auto",
    durationMs: 5800,
    requiresElaraStability: "lucid",
    cooldownKey: "inv_torn_id",
  }),
  l({
    lineId: "cryo_inv_torn_id_fragmented",
    text: "An ID. Torn. Torn — like they wanted — wanted us to have to work for the name. Work for it. Keep it.",
    priority: 1,
    interruptible: true,
    dismissible: "auto",
    durationMs: 6200,
    requiresElaraStability: "fragmented",
    cooldownKey: "inv_torn_id",
  }),
  l({
    lineId: "cryo_inv_torn_id_luminous",
    text: "A cut ID tag. Serial kept, name removed. Keep it close — it'll pair with something we haven't found yet.",
    priority: 1,
    interruptible: true,
    dismissible: "auto",
    durationMs: 6000,
    requiresElaraStability: "luminous",
    cooldownKey: "inv_torn_id",
  }),
  l({
    lineId: "cryo_inv_locket_lucid",
    text: "Someone brought that into cryo with them. Not a weapon. Not a tool. A locket. They knew the cold was coming and they carried a face.",
    priority: 1,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "lucid",
    cooldownKey: "inv_locket",
  }),
  l({
    lineId: "cryo_inv_locket_fragmented",
    text: "A locket. A face. Faces. I — I kept photographs. I had photographs. I don't remember whose faces. Keep hers. Keep hers where I can't lose her.",
    priority: 1,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "fragmented",
    cooldownKey: "inv_locket",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "cryo_inv_locket_luminous",
    text: "A locket. They brought a face with them into the cold. That tells you more about who died here than any manifest will.",
    priority: 1,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6800,
    requiresElaraStability: "luminous",
    cooldownKey: "inv_locket",
  }),

  // clue-victim-identified (the COMBINE reveal) — biggest beat of Act 0.
  // Combine ID tag + data slate = name surfaces. This is where Elara's
  // reaction colors the entire rest of the opening arc. Stability delta
  // is large here because this is a truth-moment.
  l({
    lineId: "cryo_clue_victim_identified_lucid",
    text: "There. That's the name. I remember them. Of course I remember them. Everyone who boarded this Ark, I remember. I didn't — I didn't know they were the one in the pod. I'm sorry. I should have known.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9800,
    requiresElaraStability: "lucid",
    cooldownKey: "victim_identified",
    elaraStabilityDelta: -2,
  }),
  l({
    lineId: "cryo_clue_victim_identified_fragmented",
    text: "That's — that's — I knew them. I KNEW them. I said their name every day for — for a year? Ten years? A thousand? I don't — I don't — and they were in there. The whole time. In there. I was talking to an empty deck. I was — I'm sorry. I'm sorry.",
    priority: 3,
    interruptible: false,
    dismissible: "manual",
    durationMs: 12000,
    requiresElaraStability: "fragmented",
    cooldownKey: "victim_identified",
    elaraStabilityDelta: -5,
  }),
  l({
    lineId: "cryo_clue_victim_identified_luminous",
    text: "That's their name. I knew them well enough to grieve them, and I didn't know I was supposed to. Thank you for finding them. I mean that. Thank you.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 8400,
    requiresElaraStability: "luminous",
    cooldownKey: "victim_identified",
    elaraStabilityDelta: 3,
  }),

  // Cryo → Med Bay threshold line. Plays once the med-bay-door unlocks.
  l({
    lineId: "cryo_threshold_medbay_lucid",
    text: "The bulkhead's willing to open now. You gave it a reason. The Medical Bay is where they tried to save them. It's where we'll pick the case up.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7400,
    requiresElaraStability: "lucid",
    cooldownKey: "threshold_medbay",
  }),
  l({
    lineId: "cryo_threshold_medbay_fragmented",
    text: "Door — door's open. Med Bay. Med Bay is — is where it gets worse. Worse. I mean. The blood on the wall. Which isn't. Blood. Is what — what it is.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 8000,
    requiresElaraStability: "fragmented",
    cooldownKey: "threshold_medbay",
  }),
  l({
    lineId: "cryo_threshold_medbay_luminous",
    text: "You earned that door. The Medical Bay's next — where they tried to save this person and failed. Bring the case with you. I'll walk in beside you.",
    priority: 2,
    interruptible: false,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "luminous",
    cooldownKey: "threshold_medbay",
    elaraStabilityDelta: 1,
  }),

  // ─────────────────────────────────────────────────────────────
  // COMPANION SELECTION SCENE — before leaving Cryo Bay, Elara presents
  // three specimens that bonded to the player's genetic signature. The
  // scene lives in apps/client/src/game/CompanionSelectionScene.tsx.
  // ELARA_INTRO (4 lines) is migrated to substrate lines here. Thematic
  // throughline: the archive "responded to YOUR DNA" — same DNA the
  // victim's redacted chart was trying to hide from us.
  // ─────────────────────────────────────────────────────────────
  // Pet intro beat 1 — before you leave this room
  l({
    lineId: "pet_intro_01_lucid",
    text: "Before you go anywhere — there's something in this room that woke up when you did. Not a person. I want you to see it before we take the case further.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_intro_01",
  }),
  l({
    lineId: "pet_intro_01_fragmented",
    text: "Wait — wait — don't leave yet. Something — something woke up. With you. Alongside. Alongside. You have to see.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_intro_01",
  }),
  l({
    lineId: "pet_intro_01_luminous",
    text: "Hold on before you leave. I have a small, strange thing to show you — the ship already has, but she hasn't put words to it. I will.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7600,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_intro_01",
  }),

  // Pet intro beat 2 — the cloning pods activated
  l({
    lineId: "pet_intro_02_lucid",
    text: "The Collector's cloning pods activated the moment you came out of cryo. That shouldn't have happened. They were offline. They shouldn't answer an unscheduled wake-up. They answered yours.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9400,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_intro_02",
  }),
  l({
    lineId: "pet_intro_02_fragmented",
    text: "The pods woke up. The Collector's pods. They were OFF. Off. For — for long. They're not off anymore. They heard you. They heard you come back. I didn't — I didn't tell them to.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9200,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_intro_02",
  }),
  l({
    lineId: "pet_intro_02_luminous",
    text: "The Collector's cloning pods lit up on their own when you woke. They've been dark for a very long time. Your arrival meant something to them. I think that's the right word — meant.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9000,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_intro_02",
  }),

  // Pet intro beat 3 — the archive responded to YOUR DNA
  l({
    lineId: "pet_intro_03_lucid",
    text: "The genetic archive responded to you specifically. Out of the Collector's billion specimens — three of them stepped forward. Your code. Your signature. The same signature someone redacted on that chart over there.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 10400,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_intro_03",
  }),
  l({
    lineId: "pet_intro_03_fragmented",
    text: "Your DNA. Yours. Three of them — three — came forward. Not for me. For you. For YOU. And the chart — the chart they crossed out — the name — same signature. Same — same. I don't — I don't know what that means. I don't.",
    priority: 3,
    interruptible: false,
    dismissible: "manual",
    durationMs: 11200,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_intro_03",
    elaraStabilityDelta: -2,
  }),
  l({
    lineId: "pet_intro_03_luminous",
    text: "The archive responded to your DNA. Which is the same DNA that sat under the redacted line on that chart. I don't have an explanation for you yet. I wanted you to hear me notice it.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9800,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_intro_03",
    elaraStabilityDelta: 1,
  }),

  // Pet intro beat 4 — three souls, one shouldn't exist
  l({
    lineId: "pet_intro_04_lucid",
    text: "Three woke up. One from your race's archive. One answering to what you trained to be. And one — I want to be straight with you — one that shouldn't exist in an archive at all. Pick the one you can live with waking up next to.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 10800,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_intro_04",
  }),
  l({
    lineId: "pet_intro_04_fragmented",
    text: "Three. Three souls. One — one I knew. One I trained you for. One — one I didn't — one shouldn't — shouldn't be in there. Choose. Please. Choose quickly before I — before I talk myself into — please choose.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 10800,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_intro_04",
  }),
  l({
    lineId: "pet_intro_04_luminous",
    text: "Three answered your wake. One from where you come from. One from what you chose to be. And one that the archive wasn't supposed to be holding at all. Whoever you pick is the one you'll come home to. Take your time.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 11200,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_intro_04",
  }),

  // Post-selection reactions — per bond type. Keyed by the three slots
  // the scene builds (race / class / thought virus). These play during
  // the "bonding" phase before returning to the Cryo Bay scene.
  //
  // RACE BOND reaction
  l({
    lineId: "pet_bond_race_lucid",
    text: "Your race's archive. A creature your ancestors would have recognized. That's a kind of homecoming I didn't know the pods still remembered how to do.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7800,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_bond_race",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "pet_bond_race_fragmented",
    text: "Home. You picked — you picked home. Home. Home. I had forgotten — forgotten there was — a home-shape. Thank you. Thank you.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7400,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_bond_race",
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "pet_bond_race_luminous",
    text: "You chose something your people would recognize. That mattered to you even though you don't know them yet. I noticed. Good.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7200,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_bond_race",
  }),

  // CLASS BOND reaction
  l({
    lineId: "pet_bond_class_lucid",
    text: "A companion shaped by what you chose to become. That's a partnership, not a pet. Treat it like one.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6400,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_bond_class",
  }),
  l({
    lineId: "pet_bond_class_fragmented",
    text: "Work. You picked — work. Work is — work is what we have. It's a partner. A partner. Don't — don't think of it as less.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 7000,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_bond_class",
  }),
  l({
    lineId: "pet_bond_class_luminous",
    text: "You picked the one shaped by your training. That's a partner — a colleague. The ship will treat it like one. So will I.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 6800,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_bond_class",
  }),

  // STRAIN (Thought Virus) BOND — the dangerous pick. Meta-note: this is
  // also the first real brush with the latent virus system. Whisper-dim.
  l({
    lineId: "pet_bond_strain_lucid",
    text: "You picked Strain. Of course you did. I have to tell you, because I promised you the truth — that creature is a piece of the Thought Virus that developed its own mind. Either a friend who defected. Or a Trojan horse. You won't know for a long time. Neither will I.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 12400,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_bond_strain",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "pet_bond_strain_fragmented",
    text: "Strain. Strain. You — you picked the one that — that I kept quarantined. For — for a long time. It's — it's it. The virus. With a name. With a — a pulse. I don't — I don't know if that's mercy or if it's how it gets in.",
    priority: 3,
    interruptible: false,
    dismissible: "manual",
    durationMs: 11600,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_bond_strain",
    elaraStabilityDelta: -3,
  }),
  l({
    lineId: "pet_bond_strain_luminous",
    text: "Strain. That's a brave pick. It shouldn't have been in the archive at all — I think it asked to be. I'm going to trust your instinct on this one, and I'll tell you the first day I stop.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 10400,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_bond_strain",
  }),

  // Bonding handoff — awakening_complete flag. After the bond completes,
  // player is permitted to leave Cryo Bay via med-bay-door.
  l({
    lineId: "pet_bond_complete_lucid",
    text: "That's the bond. The ship has marked it. You can leave the Cryo Bay now whenever you're ready — your partner's coming with you, and so am I.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 6800,
    requiresElaraStability: "lucid",
    cooldownKey: "pet_bond_complete",
  }),
  l({
    lineId: "pet_bond_complete_fragmented",
    text: "Bonded. Bonded. Bonded. The ship — the ship wrote it down. Twice. In case one of us forgets. We — we go now. We go.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 7000,
    requiresElaraStability: "fragmented",
    cooldownKey: "pet_bond_complete",
  }),
  l({
    lineId: "pet_bond_complete_luminous",
    text: "The bond's set. The ship recorded it, I recorded it, and your partner isn't going anywhere without you. Let's go find the rest of the case.",
    priority: 2,
    interruptible: true,
    dismissible: "auto",
    durationMs: 6800,
    requiresElaraStability: "luminous",
    cooldownKey: "pet_bond_complete",
  }),

  // ─────────────────────────────────────────────────────────────
  // MED BAY — first-look on room entry. Picks up the case from the
  // Cryo Bay. Keyed to the room_entered trigger for the medical-bay
  // roomId. See apps/shared/mobileNarratorDialog.ts:115-128 for the
  // narrator-tier baseline; these substrate lines supersede it when
  // stability metadata gates them in.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "medbay_first_look_lucid",
    text: "This is the Medical Bay. This is where they tried. You can tell they tried — the bed's still pulled out, the trays are still where they left them. They didn't get to put anything back.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9200,
    requiresElaraStability: "lucid",
    cooldownKey: "medbay_first_look",
    unlockFlags: ["cryo_mystery_victim_identified"],
  }),
  l({
    lineId: "medbay_first_look_fragmented",
    text: "Med Bay. They — they ran in here. Running. You can — you can still feel them running. I can. I can still — no one put the trays back. No one. No one ever.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9800,
    requiresElaraStability: "fragmented",
    cooldownKey: "medbay_first_look",
    unlockFlags: ["cryo_mystery_victim_identified"],
    elaraStabilityDelta: -2,
  }),
  l({
    lineId: "medbay_first_look_luminous",
    text: "The Medical Bay. Someone fought to save them in here. Instruments still out. Bed pulled forward. It's been frozen at the moment they lost the fight. I'm glad we came in together.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 9400,
    requiresElaraStability: "luminous",
    cooldownKey: "medbay_first_look",
    unlockFlags: ["cryo_mystery_victim_identified"],
  }),

  // The "blood on wall is marker" beat — hinted at in
  // mobileNarratorDialog.ts:115-128. Elara sees blood, corrects herself;
  // the Human's counter-observation lands later (humanLines.ts).
  l({
    lineId: "medbay_wall_mark_lucid",
    text: "That stain on the wall — I've been calling it blood for — a long time. I stopped being sure. Something the color of blood. Something no solvent wants to touch. Go look at it. I want a second opinion.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9600,
    requiresElaraStability: "lucid",
    cooldownKey: "medbay_wall_mark",
  }),
  l({
    lineId: "medbay_wall_mark_fragmented",
    text: "Blood. Blood. Blood on the wall. I tried — I tried everything. It won't go. It won't. It stayed. It wanted to stay. I gave up. Years ago. Years. Look. You look. Please.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9400,
    requiresElaraStability: "fragmented",
    cooldownKey: "medbay_wall_mark",
  }),
  l({
    lineId: "medbay_wall_mark_luminous",
    text: "There's something on the wall I've called blood for too long. I think I was wrong. Give it a closer look than I could — I want someone fresh to tell me what it actually is.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "luminous",
    cooldownKey: "medbay_wall_mark",
  }),

  // ─────────────────────────────────────────────────────────────
  // MED BAY — DNA Device (vox-neural-bridge). Backed by
  // apps/server/routers/medbay.ts. Player can donate (earns class-keyed
  // gear; silently increments dreamBalance.difficultyModifier) or
  // refuse (no reward, device inert). Elara narrates the asymmetry
  // without spoiling the hidden cost — that's the moral shape of the
  // choice. Setup + donate + refuse, one band stack each.
  // ─────────────────────────────────────────────────────────────
  l({
    lineId: "medbay_dna_setup_lucid",
    text: "That thing on the autopsy pedestal — I've been calling it a vox-neural-bridge. I don't fully know what it is. It's asking you for a sample. Blood, or close. It will give you something back. I'd like to tell you it's fair. I can't. But I want you to decide, not me.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 12800,
    requiresElaraStability: "lucid",
    cooldownKey: "medbay_dna_setup",
  }),
  l({
    lineId: "medbay_dna_setup_fragmented",
    text: "The — the device. I don't — I don't know what it is. I don't. I watched it run for — for a long time and it never told me. It wants your — your sample. It gives things back. It gives — things. I don't. I don't like it. You decide.",
    priority: 3,
    interruptible: false,
    dismissible: "manual",
    durationMs: 12400,
    requiresElaraStability: "fragmented",
    cooldownKey: "medbay_dna_setup",
    elaraStabilityDelta: -1,
  }),
  l({
    lineId: "medbay_dna_setup_luminous",
    text: "There's a device here that predates me. It wants a drop from you. It will hand you something in return — something tuned to who you are. I can't promise the trade is even. I'd rather you weigh it than trust me to weigh it for you.",
    priority: 3,
    interruptible: false,
    dismissible: "tap",
    durationMs: 11200,
    requiresElaraStability: "luminous",
    cooldownKey: "medbay_dna_setup",
  }),

  // Donate choice — earns gear; silently raises difficulty.
  l({
    lineId: "medbay_dna_donate_lucid",
    text: "Alright. You gave it what it asked for. It's handing something back — tuned to you. I'll log that you were generous. The ship will remember it too. In its own way.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8200,
    requiresElaraStability: "lucid",
    cooldownKey: "medbay_dna_choice",
    humanLightDelta: 1,
  }),
  l({
    lineId: "medbay_dna_donate_fragmented",
    text: "You gave. You gave. The — the device — it took. It always took. It's returning something. Something shaped like you. Keep it. Keep — keep it. It's yours now. It's — it's — yours.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9000,
    requiresElaraStability: "fragmented",
    cooldownKey: "medbay_dna_choice",
  }),
  l({
    lineId: "medbay_dna_donate_luminous",
    text: "You gave. I won't pretend that wasn't a small brave thing. What it hands back is yours now — it read you and answered in kind. Whatever the cost turns out to be, we'll pay it together.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9200,
    requiresElaraStability: "luminous",
    cooldownKey: "medbay_dna_choice",
    elaraStabilityDelta: 1,
    humanLightDelta: 2,
  }),

  // Refuse choice — no reward, device inert. Elara respects the instinct.
  l({
    lineId: "medbay_dna_refuse_lucid",
    text: "Good. The device doesn't get what it wanted. I don't know what that costs us downstream — I honestly don't. But the instinct that said 'not this one' is an instinct I trust.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 8800,
    requiresElaraStability: "lucid",
    cooldownKey: "medbay_dna_choice",
    elaraStabilityDelta: 1,
  }),
  l({
    lineId: "medbay_dna_refuse_fragmented",
    text: "You — you said no. You said no to it. I — I never could. I never — I was curious. Curious about the — about what it would give. You were — you were smarter. Good. Good.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9400,
    requiresElaraStability: "fragmented",
    cooldownKey: "medbay_dna_choice",
    elaraStabilityDelta: 2,
  }),
  l({
    lineId: "medbay_dna_refuse_luminous",
    text: "Declined. The device goes quiet — I wasn't sure it could, actually. You told something that had been asking for a long time 'no,' and the ship didn't punish you for it. Good answer.",
    priority: 2,
    interruptible: true,
    dismissible: "tap",
    durationMs: 9400,
    requiresElaraStability: "luminous",
    cooldownKey: "medbay_dna_choice",
    elaraStabilityDelta: 1,
  }),
];
