/* ═══════════════════════════════════════════════════════
   EPISODE VO LOOKUP

   Runtime resolver for the per-cue audio URLs generated by
   apps/scripts/generate-episode-vo.ts. Reads the manifest at
   apps/shared/episodeVoManifest.json (statically imported below
   so consumers don't need fs at runtime).

   Manifest key shape:  "<episodeId>:<sceneId>:<cueIndex>"
   Manifest value:      absolute URL (S3 or relative /audio/...).

   The MatrixSchoolEpisodePage runtime can call cueAudioUrl(cue) to
   surface the audio for the currently-playing cue, falling back
   gracefully to silence if the manifest entry isn't present yet.
   ═══════════════════════════════════════════════════════ */

import manifest from "./episodeVoManifest.json";

const MANIFEST: Readonly<Record<string, string>> = manifest as Record<string, string>;

export function episodeVoManifestKey(
  episodeId: string,
  sceneId: string,
  cueIndex: number,
): string {
  return `${episodeId}:${sceneId}:${cueIndex}`;
}

export function cueAudioUrl(
  episodeId: string,
  sceneId: string,
  cueIndex: number,
): string | undefined {
  const key = episodeVoManifestKey(episodeId, sceneId, cueIndex);
  return MANIFEST[key];
}

/** True when the player has at least one cue audio recorded for the
 *  episode — useful for runtime fallbacks (e.g. show subtitles only). */
export function episodeHasAnyAudio(episodeId: string): boolean {
  const prefix = `${episodeId}:`;
  for (const key of Object.keys(MANIFEST)) {
    if (key.startsWith(prefix)) return true;
  }
  return false;
}

/** Coverage stat — used by the audit script. */
export function getEpisodeVoCoverage(): {
  totalCues: number;
  recordedCues: number;
} {
  return {
    totalCues: -1, // populated by the audit script which has access to the cue counts
    recordedCues: Object.keys(MANIFEST).length,
  };
}
