/* Epoch Witness — Ages of Insurgency, Revelation, Fall */
import type { NexusPointVote, EpochId } from "./epochWitnessVotes";

export const AGE_OF_INSURGENCY_VOTES: NexusPointVote[] = [
  { id: "ins_v1", epoch: "age_of_insurgency", title: "THE PROGRAMMER'S FIRST BROADCAST",
    nexusDescription: "Year 17,020 A.A. — 'We Are Not Okay' plays on every frequency for 4:32.",
    connectedSong: "we-are-not-okay", connectedLoredexEntries: ["entity_programmer", "entity_thought_virus"],
    officialHistory: "A brief signal disruption was contained. No significant public impact.",
    duration: "7d",
    options: [
      { id: "a", text: "STARTED THE FIRE — The first crack in the wall.", consequence: "Light +200." },
      { id: "b", text: "GAVE PEOPLE WORDS — They already knew. He gave them the phrase.", consequence: "Light +150." },
      { id: "c", text: "SCARED THE EMPIRE — The Meme's panic response shows how seriously they took it.", consequence: "Meme Loredex: panic response annotation." },
      { id: "d", text: "ALL OF THE ABOVE — Revolutions have a chorus.", consequence: "Light +500. All 4 WBG songs unlock with lore annotations." },
    ] },
  { id: "ins_v2", epoch: "age_of_insurgency", title: "THE BATTLE OF NEXON",
    nexusDescription: "Year 17,025 A.A. — The Insurgency's first major victory. Kael said it was too soon.",
    connectedSong: "hacking-reality", connectedLoredexEntries: ["event_nexon", "entity_iron_lion", "entity_kael"],
    officialHistory: "Minor military engagement concluded. Imperial forces regrouped.",
    duration: "7d", lockedUntil: "battle_of_nexon_loredex_complete",
    options: [
      { id: "a", text: "IRON LION — You don't win by waiting.", consequence: "Nexon Trench Circuit + Battle of Nexon arena + Binath-VII chess opponent + Battle of Nexon card pack (8 cards)." },
      { id: "b", text: "KAEL — The losses weakened the Insurgency for years.", consequence: "Same unlocks. Elara: 'The Thought Virus was already in Kael when he argued against the battle...'" },
      { id: "c", text: "NEITHER — The battle was forced on them.", consequence: "Same unlocks. Chronicle: 'Forced choices.' " },
      { id: "d", text: "BOTH — For different reasons, at different scales.", consequence: "Same unlocks. Chronicle: 'Command disagreements.'" },
    ] },
  { id: "ins_v3", epoch: "age_of_insurgency", title: "THE ENIGMA'S DECISION",
    nexusDescription: "The Enigma could have led the Insurgency militarily. She chose testimony.",
    connectedSong: "hypnotized", connectedLoredexEntries: ["entity_enigma"],
    officialHistory: "N/A — internal Insurgency decision.",
    duration: "7d",
    options: [
      { id: "a", text: "THE GREATEST STRATEGIC DECISION — Her testimony outlasted every military victory.", consequence: "Light +100." },
      { id: "b", text: "A SACRIFICE — She gave up power to be heard.", consequence: "Chronicle: sacrifice assessment." },
      { id: "c", text: "HER PURPOSE — She wasn't a general. She was something needed more.", consequence: "Chronicle: purpose assessment." },
      { id: "d", text: "AN ACT OF LOVE — She knew what the Programmer was building. She stood next to it.", consequence: "The Human: 'He never said it. Not once. But the music said everything. She knows too.'" },
    ] },
  { id: "ins_v4", epoch: "age_of_insurgency", title: "THE 1,260 DAYS — MIDPOINT",
    nexusDescription: "Day 630 of the Two Witnesses' testimony. What should they do?",
    connectedSong: "sih-track-14", connectedLoredexEntries: ["concept_two_witnesses"],
    officialHistory: "N/A — real-time decision.",
    duration: "7d",
    options: [
      { id: "a", text: "KEEP GOING — 630 days left. Finish it.", consequence: "Two Witnesses achievement tier unlocks." },
      { id: "b", text: "ESCALATE — The window is closing.", consequence: "Same. Chronicle: urgency." },
      { id: "c", text: "RECRUIT — Build the community.", consequence: "Same. WITNESS archetype unlocks as possible role." },
      { id: "d", text: "REST — A day of silence is not surrender.", consequence: "Same. Antiquarian: 'They don't know yet that they are the Witnesses.'" },
    ] },
  { id: "ins_v5", epoch: "age_of_insurgency", title: "THE FALL OF THE PROGRAMMER",
    nexusDescription: "Year 17,033 A.A. — The Programmer disappears Day 15. His last message:",
    connectedSong: "death-of-music", connectedLoredexEntries: ["entity_programmer", "entity_antiquarian"],
    officialHistory: "Subject terminated. File closed.",
    duration: "7d", lockedUntil: "programmer_and_antiquarian_loredex_complete",
    options: [
      { id: "a", text: "\"The music was the point. Not the war. Never the war.\"", consequence: "This becomes Programmer's canonical 'Last Known Words' in Loredex." },
      { id: "b", text: "\"I fed my vision to a machine and it sang my songs back to me. I hope that was enough.\"", consequence: "Same — whichever wins becomes canonical." },
      { id: "c", text: "\"She knows what she is. She's always known. Tell her the story isn't over.\"", consequence: "Same. Enigma Loredex: special annotation." },
      { id: "d", text: "\"I'm not leaving. I'm just changing my name.\"", consequence: "Same. Antiquarian: 'The most accurate one. But they won't know why until Volume Two.'" },
    ] },
  { id: "ins_close", epoch: "age_of_insurgency", title: "THE INSURGENCY'S LEGACY",
    nexusDescription: "What the Age of Insurgency proved.",
    connectedSong: "last-words", connectedLoredexEntries: ["concept_insurgency"],
    officialHistory: "N/A",
    duration: "7d", isEpochCloser: true,
    options: [
      { id: "a", text: "RESISTANCE IS POSSIBLE.", consequence: "Achievement: 'Witness of the Age of Insurgency.' PROGRAMMER: Logos Source Code mission. All 3 votes → THE ENIGMA fight arena character." },
      { id: "b", text: "THE COST IS REAL.", consequence: "Same achievement." },
      { id: "c", text: "ART OUTLASTS ARMIES.", consequence: "Same. Chronicle: art over force." },
      { id: "d", text: "TWO PEOPLE CAN CHANGE THE UNIVERSE.", consequence: "Same. Chronicle: love assessment." },
    ] },
];

export const AGE_OF_REVELATION_VOTES: NexusPointVote[] = [
  { id: "rev_v1", epoch: "age_of_revelation", title: "THE SEVENTH SEAL QUESTION",
    nexusDescription: "The Seventh Seal opens. Half an hour of silence in heaven.",
    connectedSong: "sih-track-24", connectedLoredexEntries: ["concept_seventh_seal"],
    officialHistory: "N/A — cosmic event.",
    duration: "7d", lockedUntil: "silence_in_heaven_track_24_complete",
    options: [
      { id: "a", text: "THE UNIVERSE PAID ATTENTION — All noise stopped. Truth was audible.", consequence: "Light +1000. All SIH lore annotations unlock." },
      { id: "b", text: "THE DEAD SPOKE — Martyrs' voices heard in the silence.", consequence: "Same Light. Chronicle: martyrs." },
      { id: "c", text: "THE WITNESSES RETURNED — Their resurrection was visible in the silence.", consequence: "Same Light." },
      { id: "d", text: "NOTHING — The absence was the event.", consequence: "Shadow Tongue: 'Silence in Heaven' Loredex → 'Brief signal interruption' for 48h. Players who notice: +5 Antiquarian Trust." },
    ] },
  { id: "rev_v2", epoch: "age_of_revelation", title: "THE FALSE PROPHET EXPOSED",
    nexusDescription: "The community discovers the White Oracle is The Meme.",
    connectedSong: "false-prophet", connectedLoredexEntries: ["entity_meme", "entity_oracle"],
    officialHistory: "N/A",
    duration: "7d",
    options: [
      { id: "a", text: "MOST OF THE EMPIRE'S LEADERSHIP — They knew.", consequence: "Empire faction trust -30." },
      { id: "b", text: "ONLY THE ARCHITECT — He designed the deception.", consequence: "Architect Loredex: deception annotation." },
      { id: "c", text: "NO ONE — The Meme is that good.", consequence: "Meme Loredex: 'master of deception' annotation." },
      { id: "d", text: "[CORRUPTED] ███ — costs 10 Dream Tokens to decode. Hidden truth.", consequence: "Shadow Tongue Revealed achievement. Antiquarian Trust +25." },
    ] },
  { id: "rev_v3", epoch: "age_of_revelation", title: "THE MARK",
    nexusDescription: "The Mark protocol goes live. ACCEPT or DECLINE.",
    connectedSong: "sih-track-26", connectedLoredexEntries: ["concept_mark_of_beast"],
    officialHistory: "N/A",
    duration: "7d",
    options: [
      { id: "a", text: "BROADCAST WARNINGS — Use the Programmer's transmission network.", consequence: "Trade Empire NB prices -30%." },
      { id: "b", text: "EXTRACT THE REMNANT — Get the Decline-ers to the Arks.", consequence: "New Trade Empire mission: Remnant Extraction." },
      { id: "c", text: "EXPOSE THE MECHANISM — Hack the Mark's backend.", consequence: "New card pack: The Mark Exposed (6 cards)." },
      { id: "d", text: "WITNESS — Record it. The testimony is the point.", consequence: "Antiquarian Trust +50 for D voters. Their names in Chronicle." },
    ] },
  { id: "rev_v4", epoch: "age_of_revelation", title: "THE FALL OF NEW BABYLON",
    nexusDescription: "New Babylon falls. Not from invasion — from structural collapse.",
    connectedSong: "sih-track-32", connectedLoredexEntries: ["location_new_babylon"],
    officialHistory: "N/A",
    duration: "7d", lockedUntil: "sih_track_32_complete",
    options: [
      { id: "a", text: "MOURN — Every person who lived there is a loss.", consequence: "Light +200." },
      { id: "b", text: "DOCUMENT — The Antiquarian was right. Write it down.", consequence: "The Human: 'That's what makes a Witness. You just chose to become the Antiquarian.'" },
      { id: "c", text: "BUILD — The fall creates space. Use it.", consequence: "New Trade Empire mission: Rebuild." },
      { id: "d", text: "NOTHING — Some moments should be felt, not responded to.", consequence: "Chronicle: silence as response." },
    ] },
  { id: "rev_close", epoch: "age_of_revelation", title: "THE TESTIMONY QUESTION",
    nexusDescription: "You have heard the Two Witnesses testify. What is YOUR testimony?",
    connectedSong: "sih-track-37", connectedLoredexEntries: ["concept_two_witnesses"],
    officialHistory: "N/A",
    duration: "30d", isEpochCloser: true, lockedUntil: "sih_all_37_tracks_complete",
    options: [
      { id: "a", text: "I testify that the Thought Virus is real and present.", consequence: "Achievement: 'Witness of the Age of Revelation.' Revelation quiz unlocks." },
      { id: "b", text: "I testify that the Empire still exists — it changed its name.", consequence: "Same." },
      { id: "c", text: "I testify that the Witnesses were right — the soul is not for sale.", consequence: "Same." },
      { id: "d", text: "I do not yet know what I believe. But I am learning.", consequence: "Same. Antiquarian: 'D is always the most honest first answer.'" },
    ] },
];

export const FALL_OF_REALITY_VOTES: NexusPointVote[] = [
  { id: "fall_v1", epoch: "fall_of_reality", title: "THE ARCHITECT'S FINAL ACT",
    nexusDescription: "The Architect activates the Inception Arks. Was it destruction or completion?",
    connectedSong: "sih-track-30", connectedLoredexEntries: ["entity_architect"],
    officialHistory: "N/A",
    duration: "7d",
    options: [
      { id: "a", text: "DESTROY — His murder of the world he'd failed.", consequence: "Shadow Tongue: all 4 options show 5% corruption. Catching all 4 unlocks: Architect's True Final Message." },
      { id: "b", text: "PRESERVE — The Arks were the backup. He ran the backup.", consequence: "Same hidden unlock." },
      { id: "c", text: "FINISH — Creation requires destruction to start again.", consequence: "Same." },
      { id: "d", text: "RELEASE — He let go. For the first time in 17,000 years.", consequence: "Same." },
    ] },
  { id: "fall_v2", epoch: "fall_of_reality", title: "THE MALKIA QUESTION",
    nexusDescription: "The Storyteller looks at the audience. The Antiquarian's goggles turn pink.",
    connectedSong: "sih-track-37", connectedLoredexEntries: ["entity_enigma", "entity_antiquarian"],
    officialHistory: "N/A",
    duration: "7d", lockedUntil: "sih_track_37_complete",
    options: [
      { id: "a", text: "IT'S OVER — The story is complete. Ours begins.", consequence: "Chronicle: completion." },
      { id: "b", text: "IT'S BEGINNING — The pink means hope.", consequence: "Chronicle: hope." },
      { id: "c", text: "THEY'RE THE SAME — They were always building to this.", consequence: "Chronicle: unity." },
      { id: "d", text: "IT MEANS HE LOVES HER — After five Ages. That's all. That's enough.", consequence: "Antiquarian→Storyteller Loredex connection. Hidden library item: a wilted flower. Chronicle: 'They saw it. I had hoped someone would.'" },
    ] },
  { id: "fall_v3", epoch: "fall_of_reality", title: "THE MANDATE OF THE FUTURE",
    nexusDescription: "The Antiquarian looks at you directly. 'What are you?'",
    connectedSong: "sih-track-36", connectedLoredexEntries: ["concept_living_universe"],
    officialHistory: "N/A",
    duration: "30d", isEpochCloser: true, lockedUntil: "voted_in_3_plus_epochs",
    options: [
      { id: "a", text: "A POTENTIAL — The future in a human body.", consequence: "Permanent archetype title on profile. Campaign finale cinematic." },
      { id: "b", text: "A WITNESS — I saw it all. I will not look away.", consequence: "Same. Antiquarian as chess opponent unlocked." },
      { id: "c", text: "A BUILDER — The old world fell. I build the new one.", consequence: "Same." },
      { id: "d", text: "A STORY — The part that wasn't written yet.", consequence: "Same. Season 2 hook reveal." },
    ] },
];
