/* ═══════════════════════════════════════════════════════
   MASCOTEER VOICE PROFILES

   ElevenLabs voice-profile assignments for the 12 Celebration
   Mascoteers. The three Cycle A boss mascoteers (Minnie,
   Little Corey, Mr. Unblink / Kanshi-sha) have full voice
   direction authored in docs/production/ACT_1_SHIP_READY_
   BIBLE.md §§2.2–2.4. The nine non-boss mascoteers appear
   in the 28-day Celebration Trial (§19) and need their own
   voice profiles for the ~180 Trial VO lines.

   The stability / similarity_boost / style values below are
   ElevenLabs target settings. Each profile ships as a
   standalone row in the Trial VO CSV batch generated by
   apps/scripts/generate-vo-csv.ts.

   Canonical cross-references:
     - Boss mascoteer voice specs → Act 1 Bible §§2.2–2.4
     - Non-boss mascoteer archetype → apps/shared/mascoteers.ts
     - Trial VO batch → Act 1 Bible §19.7
   ═══════════════════════════════════════════════════════ */

export interface MascoteerVoiceProfile {
  /** Mascoteer id matching MASCOTEERS[].id in mascoteers.ts. */
  mascoteerId: string;
  /** ElevenLabs voice profile identifier used in the VO pipeline. */
  voiceProfile: string;
  /** ElevenLabs stability parameter, 0.0-1.0. */
  stability: number;
  /** ElevenLabs similarity_boost parameter, 0.0-1.0. */
  similarityBoost: number;
  /** ElevenLabs style parameter, 0.0-1.0. */
  style: number;
  /** Short actor-direction note for the voice coach. */
  direction: string;
  /** If true, the voice is authored in the Act 1 Ship-Ready Bible. */
  authoredInBible: boolean;
}

export const MASCOTEER_VOICE_PROFILES: readonly MascoteerVoiceProfile[] = [
  /* ─── Cycle A boss mascoteers (authored in Act 1 Bible §§2.2–2.4) ─── */
  {
    mascoteerId: "minnie",
    voiceProfile: "minnie_meme",
    stability: 0.60,
    similarityBoost: 0.75,
    style: 0.85,
    direction:
      "Seven-year-old child voice carrying the Meme Archon's ancient-viral-amused register. Performative slams on final words. §2.2.",
    authoredInBible: true,
  },
  {
    mascoteerId: "little_corey",
    voiceProfile: "corey_collector",
    stability: 0.70,
    similarityBoost: 0.80,
    style: 0.40,
    direction:
      "Gentle, patient, grateful. Never smug. The currency-of-emotion line is sincere. §2.3.",
    authoredInBible: true,
  },
  {
    mascoteerId: "mr_unblink",
    voiceProfile: "kanshi_sha_watcher",
    stability: 0.85,
    similarityBoost: 0.80,
    style: 0.20,
    direction:
      "Calm, slightly-too-old child. The cosmic Watcher's signature non-blink cadence. §2.4.",
    authoredInBible: true,
  },

  /* ─── Non-boss mascoteers (new profiles; Trial-only VO) ─── */
  {
    mascoteerId: "the_conductor",
    voiceProfile: "conni_conductor",
    stability: 0.75,
    similarityBoost: 0.70,
    style: 0.55,
    direction:
      "Rhythmic, insistent, child trying to lead an orchestra. Speaks in short conducted phrases, as if cueing musicians.",
    authoredInBible: false,
  },
  {
    mascoteerId: "vernon",
    voiceProfile: "vernon_door_finder",
    stability: 0.65,
    similarityBoost: 0.75,
    style: 0.60,
    direction:
      "Chubby-cheerful seven-year-old, delighted by doors. Sing-song cadence. NOT the adult cosmic Vernon Vortex — the child form mascoteer is softer, more earnest. (Cycle C1 Vernon Vortex uses its own voice profile per §2.10.)",
    authoredInBible: false,
  },
  {
    mascoteerId: "wanda_wee",
    voiceProfile: "wanda_wee_mascoteer",
    stability: 0.70,
    similarityBoost: 0.75,
    style: 0.50,
    direction:
      "Blonde child in tactical gear, already a leader at age seven. Commanding but not aggressive. (Distinct from the adolescent Wanda Wyrlord in C2 §2.11 — this is the Celebration-era mascoteer skin, younger and less damaged.)",
    authoredInBible: false,
  },
  {
    mascoteerId: "senator_sprout",
    voiceProfile: "senator_sprout",
    stability: 0.80,
    similarityBoost: 0.70,
    style: 0.70,
    direction:
      "Tiny politician — the child who has already learned to say things for cameras. Formal cadence, too-adult vocabulary, genuinely pleased to be important.",
    authoredInBible: false,
  },
  {
    mascoteerId: "wayne",
    voiceProfile: "wayne_wardens_boy",
    stability: 0.75,
    similarityBoost: 0.75,
    style: 0.40,
    direction:
      "Green-haired child in a trench coat too big for him. Cautious, rule-citing, uses the word 'safe' constantly. (Distinct from the adult Wayne Warden in C4 §2.13 — the two share no vocal lineage; this is the mascoteer skin.)",
    authoredInBible: false,
  },
  {
    mascoteerId: "gary",
    voiceProfile: "gary_ninth",
    stability: 0.60,
    similarityBoost: 0.70,
    style: 0.75,
    direction:
      "Dark-haired boy in steampunk goggles, always smiling. Makes up the games. Changes the rules mid-play. The voice should sound delighted and slightly unreliable.",
    authoredInBible: false,
  },
  {
    mascoteerId: "thazu",
    voiceProfile: "thazu_necromancer_child",
    stability: 0.85,
    similarityBoost: 0.75,
    style: 0.60,
    direction:
      "Pale dark-elf child in dress-up robes. Hosts tea parties. The voice is too calm — the calm of someone who has already decided who is leaving the party and who is staying.",
    authoredInBible: false,
  },
  {
    mascoteerId: "the_prince",
    voiceProfile: "the_prince",
    stability: 0.80,
    similarityBoost: 0.85,
    style: 0.30,
    direction:
      "The player's own voice — inherited from the Engineer's Prince profile (Prelude Bible §2.1). Non-interactive in the Trial loop; present for simulation-consistency.",
    authoredInBible: true,
  },
  {
    mascoteerId: "the_seeker_child",
    voiceProfile: "red_seeker_boy",
    stability: 0.70,
    similarityBoost: 0.75,
    style: 0.55,
    direction:
      "Red-haired boy with bright blue eyes. Asks questions. Solves riddles. Younger version of the seventeen-year-old Seeker in B5 §2.9 — the voice here is less measured, more curious, with a tendency to trail off mid-sentence as a new question occurs to him.",
    authoredInBible: false,
  },
];

/** Look up a voice profile by mascoteer id. */
export function getMascoteerVoiceProfile(
  mascoteerId: string,
): MascoteerVoiceProfile | undefined {
  return MASCOTEER_VOICE_PROFILES.find((p) => p.mascoteerId === mascoteerId);
}

/** Every mascoteer voice profile that is NOT yet authored in the Act 1 bible. */
export function getUnauthoredMascoteerProfiles(): readonly MascoteerVoiceProfile[] {
  return MASCOTEER_VOICE_PROFILES.filter((p) => !p.authoredInBible);
}
