/**
 * Lore-tiered title progressions for Dischordia.
 *
 * Each `rootKey` groups a multi-tier progression (SWTOR-styled).
 * Title gates are increasing thresholds; same root, escalating prestige.
 * Anchored to LOREDEX entities (docs/narrative-audit/DOC4_LOREDEX.md)
 * where applicable; the `loredexEntityId` cross-ref is for UI tooltips.
 *
 * This registry is the single source of truth. Server seeds it into
 * `title_definitions` at app start; clients read from the same constant.
 */
import type { TitleDef } from "./types";

export const TITLE_DEFINITIONS: readonly TitleDef[] = [
  /* ─── PVP-RANK ROOTED ──────────────────────────────────────── */
  // Warlord progression — entity_10
  {
    titleKey: "warlord_t1",
    rootKey: "warlord",
    tier: 1,
    name: "Skirmisher",
    description: "Earned your first ranked card victory.",
    flavorText: "Every Warlord begins as a Skirmisher.",
    rarity: "common",
    category: "pvp_rank",
    loredexEntityId: "entity_10",
    iconKey: "Swords",
    condition: { kind: "pvp_wins_total", gameType: "card_1v1", count: 1 },
  },
  {
    titleKey: "warlord_t2",
    rootKey: "warlord",
    tier: 2,
    name: "Warlord",
    description: "Reached Diamond in card duels.",
    flavorText: "Memetic spread by force.",
    rarity: "epic",
    category: "pvp_rank",
    loredexEntityId: "entity_10",
    iconKey: "Swords",
    condition: { kind: "pvp_rank_reached", gameType: "card_1v1", minTier: 4 },
  },
  {
    titleKey: "warlord_t3",
    rootKey: "warlord",
    tier: 3,
    name: "Conqueror of the Nexus",
    description: "Reached Grandmaster in card duels.",
    flavorText: "First deployment at Nexon. Last word in conquest.",
    rarity: "legendary",
    category: "pvp_rank",
    loredexEntityId: "entity_10",
    iconKey: "Crown",
    condition: { kind: "pvp_rank_reached", gameType: "card_1v1", minTier: 6 },
  },

  // Seer progression — entity_34
  {
    titleKey: "seer_t1",
    rootKey: "seer",
    tier: 1,
    name: "Foreseer",
    description: "Won 10 card duels.",
    rarity: "common",
    category: "pvp_rank",
    loredexEntityId: "entity_34",
    iconKey: "Eye",
    condition: { kind: "pvp_wins_total", gameType: "card_1v1", count: 10 },
  },
  {
    titleKey: "seer_t2",
    rootKey: "seer",
    tier: 2,
    name: "Seer",
    description: "Won 100 card duels.",
    flavorText: "Detects what the five senses cannot.",
    rarity: "epic",
    category: "pvp_rank",
    loredexEntityId: "entity_34",
    iconKey: "Eye",
    condition: { kind: "pvp_wins_total", gameType: "card_1v1", count: 100 },
  },
  {
    titleKey: "seer_t3",
    rootKey: "seer",
    tier: 3,
    name: "Sixth Sense Awakened",
    description: "Won 500 card duels.",
    flavorText: "What the Architect hides, the Seer finds.",
    rarity: "legendary",
    category: "pvp_rank",
    loredexEntityId: "entity_34",
    iconKey: "Eye",
    condition: { kind: "pvp_wins_total", gameType: "card_1v1", count: 500 },
  },

  // Iron Lion's Vanguard — entity_23
  {
    titleKey: "iron_lion_t1",
    rootKey: "iron_lion",
    tier: 1,
    name: "Legendary Warrior",
    description: "Reached Gold in any competitive gameType.",
    rarity: "rare",
    category: "pvp_rank",
    loredexEntityId: "entity_23",
    iconKey: "Shield",
    condition: { kind: "pvp_rank_reached", gameType: "card_1v1", minTier: 2 },
  },
  {
    titleKey: "iron_lion_t2",
    rootKey: "iron_lion",
    tier: 2,
    name: "Iron Lion's Vanguard",
    description: "Reached Master in card duels.",
    flavorText: "Year 632. Mechronis. The Insurgency.",
    rarity: "epic",
    category: "pvp_rank",
    loredexEntityId: "entity_23",
    iconKey: "Shield",
    condition: { kind: "pvp_rank_reached", gameType: "card_1v1", minTier: 5 },
  },
  {
    titleKey: "iron_lion_t3",
    rootKey: "iron_lion",
    tier: 3,
    name: "Defiant of Empires",
    description: "Won 250 card duels at Master rank or higher.",
    flavorText: "Expelled. Followed. Resurrected the resistance.",
    rarity: "legendary",
    category: "pvp_rank",
    loredexEntityId: "entity_23",
    iconKey: "Shield",
    condition: { kind: "pvp_wins_total", gameType: "card_1v1", count: 250 },
  },

  // Game Master's Acolyte — entity_17
  {
    titleKey: "game_master_t1",
    rootKey: "game_master",
    tier: 1,
    name: "Player of Games",
    description: "Won 10 chess matches.",
    rarity: "common",
    category: "pvp_rank",
    loredexEntityId: "entity_17",
    iconKey: "Gamepad2",
    condition: { kind: "pvp_wins_total", gameType: "chess", count: 10 },
  },
  {
    titleKey: "game_master_t2",
    rootKey: "game_master",
    tier: 2,
    name: "Game Master's Acolyte",
    description: "Reached Diamond in chess.",
    flavorText: "Manifests as a man in a blue trench coat. Hosts The Palimpsest.",
    rarity: "epic",
    category: "pvp_rank",
    loredexEntityId: "entity_17",
    iconKey: "Gamepad2",
    condition: { kind: "pvp_rank_reached", gameType: "chess", minTier: 4 },
  },
  {
    titleKey: "game_master_t3",
    rootKey: "game_master",
    tier: 3,
    name: "Architect of Contests",
    description: "Reached Grandmaster in chess.",
    rarity: "legendary",
    category: "pvp_rank",
    loredexEntityId: "entity_17",
    iconKey: "Gamepad2",
    condition: { kind: "pvp_rank_reached", gameType: "chess", minTier: 6 },
  },

  /* ─── NARRATIVE / LOREDEX ROOTED ──────────────────────────── */
  // Architect's Hand — entity_2
  {
    titleKey: "architects_hand_t1",
    rootKey: "architects_hand",
    tier: 1,
    name: "Agent of Order",
    description: "Discovered The Architect in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_2",
    iconKey: "Building",
    condition: { kind: "loredex_discovered", entityId: "entity_2" },
  },
  {
    titleKey: "architects_hand_t2",
    rootKey: "architects_hand",
    tier: 2,
    name: "Architect's Hand",
    description: "Completed Act 3.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_2",
    iconKey: "Building",
    condition: { kind: "act_completed", act: 3 },
  },
  {
    titleKey: "architects_hand_t3",
    rootKey: "architects_hand",
    tier: 3,
    name: "Shaper of Realities",
    description: "Reached Architect alignment threshold of 100.",
    flavorText: "Order is a verb. The Architect's Hand conjugates it.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_2",
    iconKey: "Building",
    condition: { kind: "loredex_alignment_threshold", alignment: "architect", threshold: 100 },
  },

  // Shadow Tongue's Echo — entity_7
  {
    titleKey: "shadow_tongue_t1",
    rootKey: "shadow_tongue",
    tier: 1,
    name: "Whisperer of Discord",
    description: "Discovered Shadow Tongue in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_7",
    iconKey: "MessageCircle",
    condition: { kind: "loredex_discovered", entityId: "entity_7" },
  },
  {
    titleKey: "shadow_tongue_t2",
    rootKey: "shadow_tongue",
    tier: 2,
    name: "Shadow Tongue's Echo",
    description: "Completed Act 4.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_7",
    iconKey: "MessageCircle",
    condition: { kind: "act_completed", act: 4 },
  },
  {
    titleKey: "shadow_tongue_t3",
    rootKey: "shadow_tongue",
    tier: 3,
    name: "Master of Rewritten Words",
    description: "Triggered the Act 4 secret-reveal path.",
    flavorText: "Cultural subversion as weapon. Language as battlefield.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_7",
    iconKey: "MessageCircle",
    condition: { kind: "secret_revealed", act: 4 },
  },

  // Oracle's Heir — entity_50
  {
    titleKey: "oracles_heir_t1",
    rootKey: "oracles_heir",
    tier: 1,
    name: "Wisdom Seeker",
    description: "Discovered The Oracle in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_50",
    iconKey: "Sparkles",
    condition: { kind: "loredex_discovered", entityId: "entity_50" },
  },
  {
    titleKey: "oracles_heir_t2",
    rootKey: "oracles_heir",
    tier: 2,
    name: "Oracle's Heir",
    description: "Completed Act 5.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_50",
    iconKey: "Sparkles",
    condition: { kind: "act_completed", act: 5 },
  },
  {
    titleKey: "oracles_heir_t3",
    rootKey: "oracles_heir",
    tier: 3,
    name: "Prophet of the Insurgency",
    description: "Reached Insurgency alignment threshold of 100.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_50",
    iconKey: "Sparkles",
    condition: { kind: "loredex_alignment_threshold", alignment: "insurgency", threshold: 100 },
  },

  // Dreamwarden — entity_30
  {
    titleKey: "dreamwarden_t1",
    rootKey: "dreamwarden",
    tier: 1,
    name: "Dream Keeper",
    description: "Discovered The Dreamer in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_30",
    iconKey: "Moon",
    condition: { kind: "loredex_discovered", entityId: "entity_30" },
  },
  {
    titleKey: "dreamwarden_t2",
    rootKey: "dreamwarden",
    tier: 2,
    name: "Dreamwarden",
    description: "Completed Act 6.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_30",
    iconKey: "Moon",
    condition: { kind: "act_completed", act: 6 },
  },
  {
    titleKey: "dreamwarden_t3",
    rootKey: "dreamwarden",
    tier: 3,
    name: "Architect of Futures",
    description: "Triggered the Act 6 secret-reveal path.",
    flavorText: "The Dreamer shapes futures. Aloof. Alone.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_30",
    iconKey: "Moon",
    condition: { kind: "secret_revealed", act: 6 },
  },

  // Resurrectionist's Vessel — entity_40
  {
    titleKey: "resurrectionist_t1",
    rootKey: "resurrectionist",
    tier: 1,
    name: "Reborn Spirit",
    description: "Discovered The Resurrectionist in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_40",
    iconKey: "Heart",
    condition: { kind: "loredex_discovered", entityId: "entity_40" },
  },
  {
    titleKey: "resurrectionist_t2",
    rootKey: "resurrectionist",
    tier: 2,
    name: "Resurrectionist's Vessel",
    description: "Cleared 25 co-op raids.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_40",
    iconKey: "Heart",
    condition: { kind: "coop_raid_clears", count: 25 },
  },
  {
    titleKey: "resurrectionist_t3",
    rootKey: "resurrectionist",
    tier: 3,
    name: "Master of Second Lives",
    description: "Cleared 100 co-op raids.",
    flavorText: "Maintains balance by resurrecting key figures on both sides.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_40",
    iconKey: "Heart",
    condition: { kind: "coop_raid_clears", count: 100 },
  },

  // Enigma's Child — entity_54
  {
    titleKey: "enigma_t1",
    rootKey: "enigma",
    tier: 1,
    name: "Mystery Bearer",
    description: "Discovered The Enigma in the LOREDEX.",
    rarity: "rare",
    category: "narrative",
    loredexEntityId: "entity_54",
    iconKey: "HelpCircle",
    condition: { kind: "loredex_discovered", entityId: "entity_54" },
  },
  {
    titleKey: "enigma_t2",
    rootKey: "enigma",
    tier: 2,
    name: "Enigma's Child",
    description: "Solved 3 Conspiracy Boards.",
    rarity: "epic",
    category: "narrative",
    loredexEntityId: "entity_54",
    iconKey: "HelpCircle",
    condition: { kind: "loredex_alignment_threshold", alignment: "enigma", threshold: 50 },
  },
  {
    titleKey: "enigma_t3",
    rootKey: "enigma",
    tier: 3,
    name: "Destroyer of Wardens",
    description: "Triggered the Act 7 secret-reveal path.",
    rarity: "legendary",
    category: "narrative",
    loredexEntityId: "entity_54",
    iconKey: "HelpCircle",
    condition: { kind: "secret_revealed", act: 7 },
  },

  /* ─── MYSTERY / WITNESSING ROOTED (Tier 2B feeds these) ──── */
  // Silence's Keeper — entity_36
  {
    titleKey: "silence_t1",
    rootKey: "silence",
    tier: 1,
    name: "Secret Bearer",
    description: "Solved your first Conspiracy Board.",
    rarity: "rare",
    category: "mystery",
    loredexEntityId: "entity_36",
    iconKey: "Lock",
    condition: { kind: "mystery_solve_any", boardKey: "*" },
  },
  {
    titleKey: "silence_t2",
    rootKey: "silence",
    tier: 2,
    name: "Silence's Keeper",
    description: "Solved the Thought Virus Conspiracy Board.",
    rarity: "epic",
    category: "mystery",
    loredexEntityId: "entity_36",
    iconKey: "Lock",
    condition: { kind: "mystery_solve_any", boardKey: "thought_virus" },
  },
  {
    titleKey: "silence_t3",
    rootKey: "silence",
    tier: 3,
    name: "Guardian of Hidden Truths",
    description: "Was first-discoverer on a Conspiracy Board.",
    flavorText: "The Silence reveals what serves Ne-Yons' agenda.",
    rarity: "legendary",
    category: "mystery",
    loredexEntityId: "entity_36",
    iconKey: "Lock",
    condition: { kind: "mystery_solve_first", boardKey: "*" },
  },

  // Knowledge's Paradox — entity_37
  {
    titleKey: "knowledge_t1",
    rootKey: "knowledge",
    tier: 1,
    name: "Student of All Things",
    description: "Discovered 10 LOREDEX entities.",
    rarity: "common",
    category: "mystery",
    loredexEntityId: "entity_37",
    iconKey: "BookOpen",
    condition: { kind: "level_reached", level: 5 },
  },
  {
    titleKey: "knowledge_t2",
    rootKey: "knowledge",
    tier: 2,
    name: "Knowledge's Paradox",
    description: "Unlocked all six Kael Fragments.",
    rarity: "epic",
    category: "mystery",
    loredexEntityId: "entity_37",
    iconKey: "BookOpen",
    condition: { kind: "kael_fragment_unlocked", fragmentId: "F6" },
  },
  {
    titleKey: "knowledge_t3",
    rootKey: "knowledge",
    tier: 3,
    name: "Maintainer of Balance",
    description: "Completed all seven Acts.",
    rarity: "legendary",
    category: "mystery",
    loredexEntityId: "entity_37",
    iconKey: "BookOpen",
    condition: { kind: "act_completed", act: 7 },
  },

  // Antiquarian — entity_66 — first-to-witness titles
  {
    titleKey: "antiquarian_t1",
    rootKey: "antiquarian",
    tier: 1,
    name: "Chronicler",
    description: "Solved a Conspiracy Board within the first three discoverers.",
    rarity: "rare",
    category: "mystery",
    loredexEntityId: "entity_66",
    iconKey: "Scroll",
    condition: { kind: "mystery_solve_any", boardKey: "*" },
  },
  {
    titleKey: "antiquarian_t2",
    rootKey: "antiquarian",
    tier: 2,
    name: "Antiquarian",
    description: "Was first-discoverer on a Conspiracy Board.",
    flavorText: "Reads forty-three names aloud. Every night.",
    rarity: "epic",
    category: "mystery",
    loredexEntityId: "entity_66",
    iconKey: "Scroll",
    condition: { kind: "mystery_solve_first", boardKey: "*" },
  },
  {
    titleKey: "antiquarian_t3",
    rootKey: "antiquarian",
    tier: 3,
    name: "Queen of Truth",
    description: "Was first-discoverer on the Project Celebration Conspiracy Board.",
    flavorText: "Keeper of all genuine history in a universe of manufactured narratives.",
    rarity: "mythic",
    category: "mystery",
    loredexEntityId: "entity_66",
    iconKey: "Crown",
    hidden: true,
    condition: { kind: "mystery_solve_first", boardKey: "project_celebration" },
  },

  // Schism Walker — entity_21
  {
    titleKey: "schism_t1",
    rootKey: "schism",
    tier: 1,
    name: "Observer of Chasms",
    description: "Discovered The Human in the LOREDEX.",
    rarity: "rare",
    category: "mystery",
    loredexEntityId: "entity_21",
    iconKey: "Compass",
    condition: { kind: "loredex_discovered", entityId: "entity_21" },
  },
  {
    titleKey: "schism_t2",
    rootKey: "schism",
    tier: 2,
    name: "Schism Walker",
    description: "Reached Diamond in two distinct gameTypes.",
    rarity: "epic",
    category: "mystery",
    loredexEntityId: "entity_21",
    iconKey: "Compass",
    condition: {
      kind: "cross_game_dual_rank",
      minTier: 4,
      gameTypes: ["card_1v1", "chess"],
    },
  },
  {
    titleKey: "schism_t3",
    rootKey: "schism",
    tier: 3,
    name: "Bridge Between Worlds",
    description: "Reached Grandmaster in two distinct gameTypes.",
    flavorText: "Solved mysteries for centuries. Walked between factions.",
    rarity: "legendary",
    category: "mystery",
    loredexEntityId: "entity_21",
    iconKey: "Compass",
    condition: {
      kind: "cross_game_dual_rank",
      minTier: 6,
      gameTypes: ["card_1v1", "chess"],
    },
  },

  /* ─── CO-OP / TWO WITNESSES ROOTED (Tier 3 grants these) ── */
  // Hierophant — entity_58
  {
    titleKey: "hierophant_t1",
    rootKey: "hierophant",
    tier: 1,
    name: "Seeker of Balance",
    description: "Cleared your first card co-op encounter.",
    rarity: "rare",
    category: "coop",
    loredexEntityId: "entity_58",
    iconKey: "Scale",
    condition: { kind: "coop_card_wins", count: 1 },
  },
  {
    titleKey: "hierophant_t2",
    rootKey: "hierophant",
    tier: 2,
    name: "Hierophant",
    description: "Cleared 25 card co-op encounters.",
    rarity: "epic",
    category: "coop",
    loredexEntityId: "entity_58",
    iconKey: "Scale",
    condition: { kind: "coop_card_wins", count: 25 },
  },
  {
    titleKey: "hierophant_t3",
    rootKey: "hierophant",
    tier: 3,
    name: "Voice of Thaloria",
    description: "Cleared 100 card co-op encounters.",
    flavorText: "One of the Two Witnesses. Co-testimony made flesh.",
    rarity: "legendary",
    category: "coop",
    loredexEntityId: "entity_58",
    iconKey: "Scale",
    condition: { kind: "coop_card_wins", count: 100 },
  },

  // Collector's Steward — entity_6
  {
    titleKey: "collector_t1",
    rootKey: "collector",
    tier: 1,
    name: "Harvester of Echoes",
    description: "Cleared a co-op raid as Healer 5 times.",
    rarity: "rare",
    category: "coop",
    loredexEntityId: "entity_6",
    iconKey: "Heart",
    condition: { kind: "coop_role_mastery", role: "healer", level: 1 },
  },
  {
    titleKey: "collector_t2",
    rootKey: "collector",
    tier: 2,
    name: "Collector's Steward",
    description: "Reached Healer mastery level 3.",
    rarity: "epic",
    category: "coop",
    loredexEntityId: "entity_6",
    iconKey: "Heart",
    condition: { kind: "coop_role_mastery", role: "healer", level: 3 },
  },
  {
    titleKey: "collector_t3",
    rootKey: "collector",
    tier: 3,
    name: "Preserver of Legacies",
    description: "Reached Healer mastery level 5.",
    flavorText: "Tasked by the Architect. Preserves beings against the Fall.",
    rarity: "legendary",
    category: "coop",
    loredexEntityId: "entity_6",
    iconKey: "Heart",
    condition: { kind: "coop_role_mastery", role: "healer", level: 5 },
  },

  // Judge's Instrument — entity_31
  {
    titleKey: "judge_t1",
    rootKey: "judge",
    tier: 1,
    name: "Arbiter's Voice",
    description: "Cleared a co-op raid as Tank 5 times.",
    rarity: "rare",
    category: "coop",
    loredexEntityId: "entity_31",
    iconKey: "Shield",
    condition: { kind: "coop_role_mastery", role: "tank", level: 1 },
  },
  {
    titleKey: "judge_t2",
    rootKey: "judge",
    tier: 2,
    name: "Judge's Instrument",
    description: "Reached Tank mastery level 3.",
    rarity: "epic",
    category: "coop",
    loredexEntityId: "entity_31",
    iconKey: "Shield",
    condition: { kind: "coop_role_mastery", role: "tank", level: 3 },
  },
  {
    titleKey: "judge_t3",
    rootKey: "judge",
    tier: 3,
    name: "Keeper of Verdicts",
    description: "Reached Tank mastery level 5.",
    rarity: "legendary",
    category: "coop",
    loredexEntityId: "entity_31",
    iconKey: "Scale",
    condition: { kind: "coop_role_mastery", role: "tank", level: 5 },
  },

  /* ─── FACTION / GUILD ROOTED (Tier 4 grants these) ──────── */
  // Recruiter's Mark — entity_26
  {
    titleKey: "recruiter_t1",
    rootKey: "recruiter",
    tier: 1,
    name: "Chosen One",
    description: "Joined a guild.",
    rarity: "common",
    category: "faction_guild",
    loredexEntityId: "entity_26",
    iconKey: "Users",
    condition: { kind: "guild_hall_tier", tier: 1 },
  },
  {
    titleKey: "recruiter_t2",
    rootKey: "recruiter",
    tier: 2,
    name: "Recruiter's Mark",
    description: "Won a Guild War.",
    rarity: "epic",
    category: "faction_guild",
    loredexEntityId: "entity_26",
    iconKey: "Users",
    condition: { kind: "guild_war_won" },
  },
  {
    titleKey: "recruiter_t3",
    rootKey: "recruiter",
    tier: 3,
    name: "Defector's Pride",
    description: "Won 10 Guild Skirmishes.",
    flavorText: "Abandoned training to follow exile. Redemption in the resistance.",
    rarity: "legendary",
    category: "faction_guild",
    loredexEntityId: "entity_26",
    iconKey: "Users",
    condition: { kind: "guild_skirmish_won", count: 10 },
  },

  // Eyes of the Watcher — entity_22
  {
    titleKey: "watcher_t1",
    rootKey: "watcher",
    tier: 1,
    name: "Silent Operative",
    description: "Member of a Tier 2+ Guild Hall.",
    rarity: "rare",
    category: "faction_guild",
    loredexEntityId: "entity_22",
    iconKey: "EyeOff",
    condition: { kind: "guild_hall_tier", tier: 2 },
  },
  {
    titleKey: "watcher_t2",
    rootKey: "watcher",
    tier: 2,
    name: "Eyes of the Watcher",
    description: "Member of a Tier 4+ Guild Hall.",
    rarity: "epic",
    category: "faction_guild",
    loredexEntityId: "entity_22",
    iconKey: "EyeOff",
    condition: { kind: "guild_hall_tier", tier: 4 },
  },
  {
    titleKey: "watcher_t3",
    rootKey: "watcher",
    tier: 3,
    name: "Master Infiltrator",
    description: "Member of a Tier 5 Guild Hall.",
    flavorText: "Elite agent. Unparalleled.",
    rarity: "legendary",
    category: "faction_guild",
    loredexEntityId: "entity_22",
    iconKey: "EyeOff",
    condition: { kind: "guild_hall_tier", tier: 5 },
  },

  // Source-Touched (Kael's fate) — entity_55
  {
    titleKey: "source_t1",
    rootKey: "source",
    tier: 1,
    name: "Void Walker",
    description: "Discovered Kael in the LOREDEX.",
    rarity: "rare",
    category: "faction_guild",
    loredexEntityId: "entity_55",
    iconKey: "Zap",
    condition: { kind: "loredex_discovered", entityId: "entity_55" },
  },
  {
    titleKey: "source_t2",
    rootKey: "source",
    tier: 2,
    name: "Source-Touched",
    description: "Unlocked Kael Fragment F3.",
    rarity: "epic",
    category: "faction_guild",
    loredexEntityId: "entity_55",
    iconKey: "Zap",
    condition: { kind: "kael_fragment_unlocked", fragmentId: "F3" },
  },
  {
    titleKey: "source_t3",
    rootKey: "source",
    tier: 3,
    name: "Incarnate of Ruin",
    description: "Unlocked all Kael Fragments and won 50 PvP matches.",
    flavorText: "Reshaped into something monstrous. Infected. Awakened.",
    rarity: "mythic",
    category: "faction_guild",
    loredexEntityId: "entity_55",
    iconKey: "Zap",
    hidden: true,
    condition: { kind: "kael_fragment_unlocked", fragmentId: "F6" },
  },

  /* ─── CROSS-GAME ROOTED (Tier 2 unification powers these) ── */
  {
    titleKey: "twin_path_t1",
    rootKey: "twin_path",
    tier: 1,
    name: "Dual Mastery",
    description: "Reached Gold in two distinct gameTypes.",
    rarity: "rare",
    category: "cross_game",
    iconKey: "Sparkles",
    condition: {
      kind: "cross_game_dual_rank",
      minTier: 2,
      gameTypes: ["card_1v1", "chess"],
    },
  },
  {
    titleKey: "twin_path_t2",
    rootKey: "twin_path",
    tier: 2,
    name: "Twin-Path Master",
    description: "Reached Diamond in two distinct gameTypes.",
    rarity: "epic",
    category: "cross_game",
    iconKey: "Sparkles",
    condition: {
      kind: "cross_game_dual_rank",
      minTier: 4,
      gameTypes: ["card_1v1", "chess"],
    },
  },
  {
    titleKey: "twin_path_t3",
    rootKey: "twin_path",
    tier: 3,
    name: "Walker of All Boards",
    description: "Reached Master+ in three distinct gameTypes.",
    rarity: "legendary",
    category: "cross_game",
    iconKey: "Sparkles",
    condition: {
      kind: "cross_game_dual_rank",
      minTier: 5,
      gameTypes: ["card_1v1", "chess", "td_raid"],
    },
  },

  /* ─── COSMETIC PURCHASE (migrated from cosmeticShop.ts) ──── */
  {
    titleKey: "title_legend",
    rootKey: "legend",
    tier: 1,
    name: "The Legend",
    description: "Purchased from the Cosmetic Shop.",
    rarity: "legendary",
    category: "cosmetic_purchase",
    iconKey: "Award",
    condition: { kind: "level_reached", level: 20 },
    purchasable: { currency: "dream", price: 300, requiredLevel: 20 },
  },
  {
    titleKey: "title_phantom",
    rootKey: "phantom",
    tier: 1,
    name: "The Phantom",
    description: "Purchased from the Cosmetic Shop.",
    rarity: "epic",
    category: "cosmetic_purchase",
    iconKey: "Ghost",
    condition: { kind: "level_reached", level: 1 },
    purchasable: { currency: "dream", price: 150 },
  },
  {
    titleKey: "title_architect",
    rootKey: "master_architect",
    tier: 1,
    name: "Master Architect",
    description: "Purchased from the Cosmetic Shop.",
    rarity: "rare",
    category: "cosmetic_purchase",
    iconKey: "Building",
    condition: { kind: "level_reached", level: 1 },
    purchasable: { currency: "dream", price: 100 },
  },
  {
    titleKey: "title_void_walker",
    rootKey: "void_walker",
    tier: 1,
    name: "Void Walker",
    description: "Purchased from the Cosmetic Shop.",
    rarity: "epic",
    category: "cosmetic_purchase",
    iconKey: "Zap",
    condition: { kind: "level_reached", level: 1 },
    purchasable: { currency: "dream", price: 175 },
  },
];

const TITLE_BY_KEY = new Map<string, TitleDef>(
  TITLE_DEFINITIONS.map((t) => [t.titleKey, t]),
);

const TITLES_BY_ROOT = new Map<string, TitleDef[]>();
for (const t of TITLE_DEFINITIONS) {
  const list = TITLES_BY_ROOT.get(t.rootKey) ?? [];
  list.push(t);
  TITLES_BY_ROOT.set(t.rootKey, list);
}
for (const list of TITLES_BY_ROOT.values()) {
  list.sort((a, b) => a.tier - b.tier);
}

/** Look up a title definition by key. Returns `undefined` for unknown. */
export function getTitleDef(titleKey: string): TitleDef | undefined {
  return TITLE_BY_KEY.get(titleKey);
}

/** Return every tier in a progression, ordered ascending by tier. */
export function getTitleRoot(rootKey: string): readonly TitleDef[] {
  return TITLES_BY_ROOT.get(rootKey) ?? [];
}

/** All distinct root keys in declaration order. */
export function getAllRootKeys(): readonly string[] {
  return [...TITLES_BY_ROOT.keys()];
}

/** All titles in a category. */
export function getTitlesByCategory(
  category: TitleDef["category"],
): readonly TitleDef[] {
  return TITLE_DEFINITIONS.filter((t) => t.category === category);
}
