import { describe, it, expect } from "vitest";
import * as fs from "fs";
import * as path from "path";
import { assetUrl } from "../client/src/lib/assetUrl";
import {
  LAST_WORDS_SONG_URL,
  LAST_WORDS_TEASE_DURATION_S,
  SLIDE_TIMELINE,
  slideAtTime,
  slideImageUrl,
} from "../client/src/components/prelude/lastWordsTimeline";

/* ═══════════════════════════════════════════════════════
   LAST WORDS TIMELINE TESTS (Prelude tease — 5 slides, 35s)

   Structural + disk-presence checks for the Beat J tease.
   After the Last Words restructure (October 2026) the Prelude
   plays only a 35-second motif of Verse 1 over 5 slides of
   Malkia watching the Engineer's Log 5 hologram in her studio;
   the full song + 20-slide Witnessing sequence moved to the
   Act 1 Cycle C Authority finale.
   ═══════════════════════════════════════════════════════ */

const REPO_ROOT = path.resolve(__dirname, "..", "..");

/** URLs now flow through assetUrl() and start with the CDN base. For the
 *  on-disk checks below we need the bare `/audio/...` or `/art/...` suffix
 *  back so it can be prefixed with the local public/ root. */
function publicUrlToRepoPath(url: string): string {
  const marker = "cdn/client-public/";
  const bare = url.includes(marker)
    ? "/" + url.slice(url.indexOf(marker) + marker.length)
    : url;
  return `apps/client/public${bare}`;
}

/** The five media dirs are gitignored (served from S3). Skip disk checks
 *  when they're not locally present (CI), keep them for local dev. We
 *  pin the predicate to the specific tease mp3 the assertion below
 *  cares about, so partial staging of unrelated audio files (e.g. the
 *  Prelude ambient WAVs from `pnpm assets:stage`) doesn't trip us into
 *  asserting against a file that wasn't supposed to be local. */
const LOCAL_MEDIA_PRESENT = fs.existsSync(
  path.resolve(REPO_ROOT, publicUrlToRepoPath(LAST_WORDS_SONG_URL)),
);

describe("Last Words tease timeline — structural", () => {
  it("has exactly 5 slide anchors", () => {
    expect(SLIDE_TIMELINE).toHaveLength(5);
  });

  it("slide numbers are 1..5 in order (match on-disk filenames)", () => {
    const slides = SLIDE_TIMELINE.map((a) => a.slide);
    expect(slides).toEqual([1, 2, 3, 4, 5]);
  });

  it("slide startS values are strictly monotonic", () => {
    for (let i = 1; i < SLIDE_TIMELINE.length; i++) {
      expect(SLIDE_TIMELINE[i].startS).toBeGreaterThan(
        SLIDE_TIMELINE[i - 1].startS,
      );
    }
  });

  it("first slide starts at 0", () => {
    expect(SLIDE_TIMELINE[0].startS).toBe(0);
  });

  it("last slide starts before tease ends", () => {
    const last = SLIDE_TIMELINE[SLIDE_TIMELINE.length - 1];
    expect(last.startS).toBeLessThan(LAST_WORDS_TEASE_DURATION_S);
  });

  it("tease duration is 30-45 seconds (tease, not the full song)", () => {
    expect(LAST_WORDS_TEASE_DURATION_S).toBeGreaterThanOrEqual(30);
    expect(LAST_WORDS_TEASE_DURATION_S).toBeLessThan(45);
  });

  it("every slide's phase is one of the 5 canonical tease phases", () => {
    const validPhases = new Set([
      "before_play",
      "hologram_on",
      "listening",
      "line_lands",
      "first_breath",
    ]);
    for (const a of SLIDE_TIMELINE) {
      expect(validPhases.has(a.phase)).toBe(true);
    }
  });
});

describe("Last Words tease timeline — lookup helpers", () => {
  it("slideAtTime returns first slide at time 0", () => {
    const slide = slideAtTime(0);
    expect(slide.slide).toBe(1);
    expect(slide.phase).toBe("before_play");
  });

  it("slideAtTime returns last slide at tease end", () => {
    const slide = slideAtTime(LAST_WORDS_TEASE_DURATION_S);
    expect(slide.slide).toBe(5);
    expect(slide.phase).toBe("first_breath");
  });

  it("slideAtTime returns the anchor whose startS is the last <= currentTime", () => {
    // At 10s we're on slide 2 (starts at 7s); slide 3 starts at 14s.
    const slide = slideAtTime(10);
    expect(slide.slide).toBe(2);
  });

  it("slideImageUrl produces a tease-path public URL", () => {
    expect(slideImageUrl(3)).toBe(assetUrl("art/prelude/last-words-tease/slide-3.webp"));
  });
});

describe("Last Words tease timeline — disk presence", () => {
  it.skipIf(!LOCAL_MEDIA_PRESENT)("tease mp3 exists at the manifest path", () => {
    const p = publicUrlToRepoPath(LAST_WORDS_SONG_URL);
    expect(fs.existsSync(path.resolve(REPO_ROOT, p))).toBe(true);
  });

  it("points at the tease mp3 (not the full song)", () => {
    // Guard against accidental revert — the restructure moved the
    // full song to Act 1 Cycle C. The Prelude must not reintroduce
    // the full-song URL.
    expect(LAST_WORDS_SONG_URL).toContain("tease");
    expect(LAST_WORDS_SONG_URL).not.toContain("prelude_cut.mp3");
  });

  it.skipIf(!LOCAL_MEDIA_PRESENT)("reports tease slide delivery status (informational, never fails)", () => {
    // Slides 1-5 are generated by the user externally per the
    // Nano Banana 2 prompts in LAST_WORDS_TEASE_SLIDE_PROMPTS.md.
    // Until they land on disk, the Prelude will show a blank
    // backdrop during the tease. This test logs the status
    // without failing the build so the restructure can ship
    // ahead of the art delivery.
    const missing: number[] = [];
    for (const anchor of SLIDE_TIMELINE) {
      const url = slideImageUrl(anchor.slide);
      const p = publicUrlToRepoPath(url);
      if (!fs.existsSync(path.resolve(REPO_ROOT, p))) {
        missing.push(anchor.slide);
      }
    }
    // eslint-disable-next-line no-console
    console.log(
      `[last-words tease] slides ${5 - missing.length}/5 present — ${
        missing.length
      } awaiting delivery${missing.length > 0 ? ` (slide ${missing.join(", ")})` : ""}`,
    );
  });
});
