/* ═══════════════════════════════════════════════════════
   PAIR-BANK BARREL — generated by
   apps/scripts/generate-nemesis-pair-banks.ts. Edit the
   per-pair files individually; this barrel is rewritten
   on each generator run.
   ═══════════════════════════════════════════════════════ */

export type { ApprenticeOnNemesisPairBank, ApprenticeOnNemesisScene, ApprenticeCorruptionBand, ApprenticeOnNemesisSceneId } from "./_types";
export { makeApprenticeScene } from "./_types";

import { zealotOnGhostPairBank } from "./zealot_on_ghost";
import { zealotOnScholarPairBank } from "./zealot_on_scholar";
import { zealotOnRevenantPairBank } from "./zealot_on_revenant";
import { zealotOnArtisanPairBank } from "./zealot_on_artisan";
import { zealotOnOraclePairBank } from "./zealot_on_oracle";
import { zealotOnWandererPairBank } from "./zealot_on_wanderer";
import { zealotOnMartyrPairBank } from "./zealot_on_martyr";
import { zealotOnHereticPairBank } from "./zealot_on_heretic";
import { zealotOnJesterPairBank } from "./zealot_on_jester";
import { zealotOnSentinelPairBank } from "./zealot_on_sentinel";
import { zealotOnProdigalPairBank } from "./zealot_on_prodigal";
import { ghostOnZealotPairBank } from "./ghost_on_zealot";
import { ghostOnScholarPairBank } from "./ghost_on_scholar";
import { ghostOnRevenantPairBank } from "./ghost_on_revenant";
import { ghostOnArtisanPairBank } from "./ghost_on_artisan";
import { ghostOnOraclePairBank } from "./ghost_on_oracle";
import { ghostOnWandererPairBank } from "./ghost_on_wanderer";
import { ghostOnMartyrPairBank } from "./ghost_on_martyr";
import { ghostOnHereticPairBank } from "./ghost_on_heretic";
import { ghostOnJesterPairBank } from "./ghost_on_jester";
import { ghostOnSentinelPairBank } from "./ghost_on_sentinel";
import { ghostOnProdigalPairBank } from "./ghost_on_prodigal";
import { scholarOnZealotPairBank } from "./scholar_on_zealot";
import { scholarOnGhostPairBank } from "./scholar_on_ghost";
import { scholarOnRevenantPairBank } from "./scholar_on_revenant";
import { scholarOnArtisanPairBank } from "./scholar_on_artisan";
import { scholarOnOraclePairBank } from "./scholar_on_oracle";
import { scholarOnWandererPairBank } from "./scholar_on_wanderer";
import { scholarOnMartyrPairBank } from "./scholar_on_martyr";
import { scholarOnHereticPairBank } from "./scholar_on_heretic";
import { scholarOnJesterPairBank } from "./scholar_on_jester";
import { scholarOnSentinelPairBank } from "./scholar_on_sentinel";
import { scholarOnProdigalPairBank } from "./scholar_on_prodigal";
import { revenantOnZealotPairBank } from "./revenant_on_zealot";
import { revenantOnGhostPairBank } from "./revenant_on_ghost";
import { revenantOnScholarPairBank } from "./revenant_on_scholar";
import { revenantOnArtisanPairBank } from "./revenant_on_artisan";
import { revenantOnOraclePairBank } from "./revenant_on_oracle";
import { revenantOnWandererPairBank } from "./revenant_on_wanderer";
import { revenantOnMartyrPairBank } from "./revenant_on_martyr";
import { revenantOnHereticPairBank } from "./revenant_on_heretic";
import { revenantOnJesterPairBank } from "./revenant_on_jester";
import { revenantOnSentinelPairBank } from "./revenant_on_sentinel";
import { revenantOnProdigalPairBank } from "./revenant_on_prodigal";
import { artisanOnZealotPairBank } from "./artisan_on_zealot";
import { artisanOnGhostPairBank } from "./artisan_on_ghost";
import { artisanOnScholarPairBank } from "./artisan_on_scholar";
import { artisanOnRevenantPairBank } from "./artisan_on_revenant";
import { artisanOnOraclePairBank } from "./artisan_on_oracle";
import { artisanOnWandererPairBank } from "./artisan_on_wanderer";
import { artisanOnMartyrPairBank } from "./artisan_on_martyr";
import { artisanOnHereticPairBank } from "./artisan_on_heretic";
import { artisanOnJesterPairBank } from "./artisan_on_jester";
import { artisanOnSentinelPairBank } from "./artisan_on_sentinel";
import { artisanOnProdigalPairBank } from "./artisan_on_prodigal";
import { oracleOnZealotPairBank } from "./oracle_on_zealot";
import { oracleOnGhostPairBank } from "./oracle_on_ghost";
import { oracleOnScholarPairBank } from "./oracle_on_scholar";
import { oracleOnRevenantPairBank } from "./oracle_on_revenant";
import { oracleOnArtisanPairBank } from "./oracle_on_artisan";
import { oracleOnWandererPairBank } from "./oracle_on_wanderer";
import { oracleOnMartyrPairBank } from "./oracle_on_martyr";
import { oracleOnHereticPairBank } from "./oracle_on_heretic";
import { oracleOnJesterPairBank } from "./oracle_on_jester";
import { oracleOnSentinelPairBank } from "./oracle_on_sentinel";
import { oracleOnProdigalPairBank } from "./oracle_on_prodigal";
import { wandererOnZealotPairBank } from "./wanderer_on_zealot";
import { wandererOnGhostPairBank } from "./wanderer_on_ghost";
import { wandererOnScholarPairBank } from "./wanderer_on_scholar";
import { wandererOnRevenantPairBank } from "./wanderer_on_revenant";
import { wandererOnArtisanPairBank } from "./wanderer_on_artisan";
import { wandererOnOraclePairBank } from "./wanderer_on_oracle";
import { wandererOnMartyrPairBank } from "./wanderer_on_martyr";
import { wandererOnHereticPairBank } from "./wanderer_on_heretic";
import { wandererOnJesterPairBank } from "./wanderer_on_jester";
import { wandererOnSentinelPairBank } from "./wanderer_on_sentinel";
import { wandererOnProdigalPairBank } from "./wanderer_on_prodigal";
import { martyrOnZealotPairBank } from "./martyr_on_zealot";
import { martyrOnGhostPairBank } from "./martyr_on_ghost";
import { martyrOnScholarPairBank } from "./martyr_on_scholar";
import { martyrOnRevenantPairBank } from "./martyr_on_revenant";
import { martyrOnArtisanPairBank } from "./martyr_on_artisan";
import { martyrOnOraclePairBank } from "./martyr_on_oracle";
import { martyrOnWandererPairBank } from "./martyr_on_wanderer";
import { martyrOnHereticPairBank } from "./martyr_on_heretic";
import { martyrOnJesterPairBank } from "./martyr_on_jester";
import { martyrOnSentinelPairBank } from "./martyr_on_sentinel";
import { martyrOnProdigalPairBank } from "./martyr_on_prodigal";
import { hereticOnZealotPairBank } from "./heretic_on_zealot";
import { hereticOnGhostPairBank } from "./heretic_on_ghost";
import { hereticOnScholarPairBank } from "./heretic_on_scholar";
import { hereticOnRevenantPairBank } from "./heretic_on_revenant";
import { hereticOnArtisanPairBank } from "./heretic_on_artisan";
import { hereticOnOraclePairBank } from "./heretic_on_oracle";
import { hereticOnWandererPairBank } from "./heretic_on_wanderer";
import { hereticOnMartyrPairBank } from "./heretic_on_martyr";
import { hereticOnJesterPairBank } from "./heretic_on_jester";
import { hereticOnSentinelPairBank } from "./heretic_on_sentinel";
import { hereticOnProdigalPairBank } from "./heretic_on_prodigal";
import { jesterOnZealotPairBank } from "./jester_on_zealot";
import { jesterOnGhostPairBank } from "./jester_on_ghost";
import { jesterOnScholarPairBank } from "./jester_on_scholar";
import { jesterOnRevenantPairBank } from "./jester_on_revenant";
import { jesterOnArtisanPairBank } from "./jester_on_artisan";
import { jesterOnOraclePairBank } from "./jester_on_oracle";
import { jesterOnWandererPairBank } from "./jester_on_wanderer";
import { jesterOnMartyrPairBank } from "./jester_on_martyr";
import { jesterOnHereticPairBank } from "./jester_on_heretic";
import { jesterOnSentinelPairBank } from "./jester_on_sentinel";
import { jesterOnProdigalPairBank } from "./jester_on_prodigal";
import { sentinelOnZealotPairBank } from "./sentinel_on_zealot";
import { sentinelOnGhostPairBank } from "./sentinel_on_ghost";
import { sentinelOnScholarPairBank } from "./sentinel_on_scholar";
import { sentinelOnRevenantPairBank } from "./sentinel_on_revenant";
import { sentinelOnArtisanPairBank } from "./sentinel_on_artisan";
import { sentinelOnOraclePairBank } from "./sentinel_on_oracle";
import { sentinelOnWandererPairBank } from "./sentinel_on_wanderer";
import { sentinelOnMartyrPairBank } from "./sentinel_on_martyr";
import { sentinelOnHereticPairBank } from "./sentinel_on_heretic";
import { sentinelOnJesterPairBank } from "./sentinel_on_jester";
import { sentinelOnProdigalPairBank } from "./sentinel_on_prodigal";
import { prodigalOnZealotPairBank } from "./prodigal_on_zealot";
import { prodigalOnGhostPairBank } from "./prodigal_on_ghost";
import { prodigalOnScholarPairBank } from "./prodigal_on_scholar";
import { prodigalOnRevenantPairBank } from "./prodigal_on_revenant";
import { prodigalOnArtisanPairBank } from "./prodigal_on_artisan";
import { prodigalOnOraclePairBank } from "./prodigal_on_oracle";
import { prodigalOnWandererPairBank } from "./prodigal_on_wanderer";
import { prodigalOnMartyrPairBank } from "./prodigal_on_martyr";
import { prodigalOnHereticPairBank } from "./prodigal_on_heretic";
import { prodigalOnJesterPairBank } from "./prodigal_on_jester";
import { prodigalOnSentinelPairBank } from "./prodigal_on_sentinel";

export const APPRENTICE_ON_NEMESIS_PAIR_BANKS = [
  zealotOnGhostPairBank,
  zealotOnScholarPairBank,
  zealotOnRevenantPairBank,
  zealotOnArtisanPairBank,
  zealotOnOraclePairBank,
  zealotOnWandererPairBank,
  zealotOnMartyrPairBank,
  zealotOnHereticPairBank,
  zealotOnJesterPairBank,
  zealotOnSentinelPairBank,
  zealotOnProdigalPairBank,
  ghostOnZealotPairBank,
  ghostOnScholarPairBank,
  ghostOnRevenantPairBank,
  ghostOnArtisanPairBank,
  ghostOnOraclePairBank,
  ghostOnWandererPairBank,
  ghostOnMartyrPairBank,
  ghostOnHereticPairBank,
  ghostOnJesterPairBank,
  ghostOnSentinelPairBank,
  ghostOnProdigalPairBank,
  scholarOnZealotPairBank,
  scholarOnGhostPairBank,
  scholarOnRevenantPairBank,
  scholarOnArtisanPairBank,
  scholarOnOraclePairBank,
  scholarOnWandererPairBank,
  scholarOnMartyrPairBank,
  scholarOnHereticPairBank,
  scholarOnJesterPairBank,
  scholarOnSentinelPairBank,
  scholarOnProdigalPairBank,
  revenantOnZealotPairBank,
  revenantOnGhostPairBank,
  revenantOnScholarPairBank,
  revenantOnArtisanPairBank,
  revenantOnOraclePairBank,
  revenantOnWandererPairBank,
  revenantOnMartyrPairBank,
  revenantOnHereticPairBank,
  revenantOnJesterPairBank,
  revenantOnSentinelPairBank,
  revenantOnProdigalPairBank,
  artisanOnZealotPairBank,
  artisanOnGhostPairBank,
  artisanOnScholarPairBank,
  artisanOnRevenantPairBank,
  artisanOnOraclePairBank,
  artisanOnWandererPairBank,
  artisanOnMartyrPairBank,
  artisanOnHereticPairBank,
  artisanOnJesterPairBank,
  artisanOnSentinelPairBank,
  artisanOnProdigalPairBank,
  oracleOnZealotPairBank,
  oracleOnGhostPairBank,
  oracleOnScholarPairBank,
  oracleOnRevenantPairBank,
  oracleOnArtisanPairBank,
  oracleOnWandererPairBank,
  oracleOnMartyrPairBank,
  oracleOnHereticPairBank,
  oracleOnJesterPairBank,
  oracleOnSentinelPairBank,
  oracleOnProdigalPairBank,
  wandererOnZealotPairBank,
  wandererOnGhostPairBank,
  wandererOnScholarPairBank,
  wandererOnRevenantPairBank,
  wandererOnArtisanPairBank,
  wandererOnOraclePairBank,
  wandererOnMartyrPairBank,
  wandererOnHereticPairBank,
  wandererOnJesterPairBank,
  wandererOnSentinelPairBank,
  wandererOnProdigalPairBank,
  martyrOnZealotPairBank,
  martyrOnGhostPairBank,
  martyrOnScholarPairBank,
  martyrOnRevenantPairBank,
  martyrOnArtisanPairBank,
  martyrOnOraclePairBank,
  martyrOnWandererPairBank,
  martyrOnHereticPairBank,
  martyrOnJesterPairBank,
  martyrOnSentinelPairBank,
  martyrOnProdigalPairBank,
  hereticOnZealotPairBank,
  hereticOnGhostPairBank,
  hereticOnScholarPairBank,
  hereticOnRevenantPairBank,
  hereticOnArtisanPairBank,
  hereticOnOraclePairBank,
  hereticOnWandererPairBank,
  hereticOnMartyrPairBank,
  hereticOnJesterPairBank,
  hereticOnSentinelPairBank,
  hereticOnProdigalPairBank,
  jesterOnZealotPairBank,
  jesterOnGhostPairBank,
  jesterOnScholarPairBank,
  jesterOnRevenantPairBank,
  jesterOnArtisanPairBank,
  jesterOnOraclePairBank,
  jesterOnWandererPairBank,
  jesterOnMartyrPairBank,
  jesterOnHereticPairBank,
  jesterOnSentinelPairBank,
  jesterOnProdigalPairBank,
  sentinelOnZealotPairBank,
  sentinelOnGhostPairBank,
  sentinelOnScholarPairBank,
  sentinelOnRevenantPairBank,
  sentinelOnArtisanPairBank,
  sentinelOnOraclePairBank,
  sentinelOnWandererPairBank,
  sentinelOnMartyrPairBank,
  sentinelOnHereticPairBank,
  sentinelOnJesterPairBank,
  sentinelOnProdigalPairBank,
  prodigalOnZealotPairBank,
  prodigalOnGhostPairBank,
  prodigalOnScholarPairBank,
  prodigalOnRevenantPairBank,
  prodigalOnArtisanPairBank,
  prodigalOnOraclePairBank,
  prodigalOnWandererPairBank,
  prodigalOnMartyrPairBank,
  prodigalOnHereticPairBank,
  prodigalOnJesterPairBank,
  prodigalOnSentinelPairBank,
] as const;
