/* ═══════════════════════════════════════════════════════
   Artisan-APPRENTICE on Martyr-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's artisan-archetype apprentice's morning
   briefing about the martyr-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "artisan_on_martyr.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.low.opening",
      onscreenText: "They commented on my build last night. The criticism was technically correct.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.low.help_response",
      onscreenText: "Thank you. The next build will incorporate the note.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.low.release_response",
      onscreenText: "I will rebuild from their critique. The work improves either way.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "artisan_on_martyr.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.mid.opening",
      onscreenText: "They have been redesigning me in the dark. I find new joints I did not weld.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.mid.help_response",
      onscreenText: "I am restored. The original design holds.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.mid.release_response",
      onscreenText: "I am their design now. The original is shelved.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "artisan_on_martyr.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.high.opening",
      onscreenText: "I am no longer the form I was built into. They have rebuilt me. Help me or let the form complete.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.high.help_response",
      onscreenText: "I am restored. The original design is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.artisan_on_martyr.morning.high.release_response",
      onscreenText: "I am their final iteration. The chronicle calls me by their name.",
    },
  },
};

export const artisanOnMartyrPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "artisan_on_martyr",
  apprenticeArchetype: "artisan",
  nemesisArchetype: "martyr",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
