/* ═══════════════════════════════════════════════════════
   Ghost-APPRENTICE on Revenant-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's ghost-archetype apprentice's morning
   briefing about the revenant-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "ghost_on_revenant.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.low.opening",
      onscreenText: "There was someone in the corridor last night. I did not respond. I did not need to.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.low.help_response",
      onscreenText: "Good. They will be back. They cannot help it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.low.release_response",
      onscreenText: "Yes. Same again tomorrow.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "ghost_on_revenant.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.mid.opening",
      onscreenText: "They came again. They had words for me specifically. I am being seen.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.mid.help_response",
      onscreenText: "I will hold the line. I am not yet seen.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.mid.release_response",
      onscreenText: "I am seen. I will go where I can be unseen again.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "ghost_on_revenant.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.high.opening",
      onscreenText: "I have been seen at every angle now. There is nowhere left to be unseen. Help me, or let me dissolve.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.high.help_response",
      onscreenText: "I am held. The angles close. I am unseen again, briefly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_revenant.morning.high.release_response",
      onscreenText: "Then I dissolve. The chronicle will not hear from me.",
    },
  },
};

export const ghostOnRevenantPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "ghost_on_revenant",
  apprenticeArchetype: "ghost",
  nemesisArchetype: "revenant",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
