/* ═══════════════════════════════════════════════════════
   Ghost-APPRENTICE on Sentinel-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.

   Scenes: cohort_morning_briefing (Wave 3 hand-authored) +
   7 new scenes (Wave 4: breaking_point_whisper,
   post_cohort_retrospective, memory_card_inheritance,
   daily_observation, corruption_advance, apprentice_warning,
   apprentice_pride). New scenes composed from per-archetype
   voice + per-scene framing.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "ghost_on_sentinel.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.low.opening",
      onscreenText: "There was someone in the corridor last night. I did not respond. I did not need to.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.low.help_response",
      onscreenText: "Good. They will be back. They cannot help it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.low.release_response",
      onscreenText: "Yes. Same again tomorrow.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "ghost_on_sentinel.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.mid.opening",
      onscreenText: "They came again. They had words for me specifically. I am being seen.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.mid.help_response",
      onscreenText: "I will hold the line. I am not yet seen.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.mid.release_response",
      onscreenText: "I am seen. I will go where I can be unseen again.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "ghost_on_sentinel.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.high.opening",
      onscreenText: "I have been seen at every angle now. There is nowhere left to be unseen. Help me, or let me dissolve.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.high.help_response",
      onscreenText: "I am held. The angles close. I am unseen again, briefly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.morning.high.release_response",
      onscreenText: "Then I dissolve. The chronicle will not hear from me.",
    },
  },
};

const BREAKING_POINT_WHISPER_LOW: DialogTree = {
  id: "ghost_on_sentinel.breaking_point_whisper.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.low.opening",
      onscreenText: "Noticed nothing. They whispered. I listened, mostly out of training.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.low.help_response",
      onscreenText: "Filed. You pulled me back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.low.release_response",
      onscreenText: "Filed differently. I let it pass.",
    },
  },
};

const BREAKING_POINT_WHISPER_MID: DialogTree = {
  id: "ghost_on_sentinel.breaking_point_whisper.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.mid.opening",
      onscreenText: "Being seen. The whisper has been most of my afternoon.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.mid.help_response",
      onscreenText: "Holding the line. I am back. Just barely.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.mid.release_response",
      onscreenText: "Going where I can be unseen. I am still listening.",
    },
  },
};

const BREAKING_POINT_WHISPER_HIGH: DialogTree = {
  id: "ghost_on_sentinel.breaking_point_whisper.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.high.opening",
      onscreenText: "Seen at every angle. The whisper is most of my voice now.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.high.help_response",
      onscreenText: "Unseen again, briefly. I am pulled clear. The voice is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.breaking_point_whisper.high.release_response",
      onscreenText: "Dissolving. I am their voice now. I am sorry.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_LOW: DialogTree = {
  id: "ghost_on_sentinel.post_cohort_retrospective.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.low.opening",
      onscreenText: "Noticed nothing. The cohort closed. We did what could be done.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.low.help_response",
      onscreenText: "Filed. You let it close kindly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.low.release_response",
      onscreenText: "Filed differently. You closed it sharply.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_MID: DialogTree = {
  id: "ghost_on_sentinel.post_cohort_retrospective.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.mid.opening",
      onscreenText: "Being seen. The cohort closed harder than I thought.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.mid.help_response",
      onscreenText: "Holding the line. Mercy at the close.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.mid.release_response",
      onscreenText: "Going where I can be unseen. Aggression at the close.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_HIGH: DialogTree = {
  id: "ghost_on_sentinel.post_cohort_retrospective.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.high.opening",
      onscreenText: "Seen at every angle. The cohort closed with names I do not want to say aloud.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.high.help_response",
      onscreenText: "Unseen again, briefly. You let the chronicle be quiet about it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.post_cohort_retrospective.high.release_response",
      onscreenText: "Dissolving. You said the names anyway.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_LOW: DialogTree = {
  id: "ghost_on_sentinel.memory_card_inheritance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.low.opening",
      onscreenText: "Noticed nothing. The dead apprentice wrote a card. Most of it is small things.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.low.help_response",
      onscreenText: "Filed. The card includes mercy for me.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.low.release_response",
      onscreenText: "Filed differently. The card includes warning for me.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_MID: DialogTree = {
  id: "ghost_on_sentinel.memory_card_inheritance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.mid.opening",
      onscreenText: "Being seen. The dead apprentice's card mentions them by archetype.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.mid.help_response",
      onscreenText: "Holding the line. I am told to be kind. I will try.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.mid.release_response",
      onscreenText: "Going where I can be unseen. I am told to be careful. I will be.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_HIGH: DialogTree = {
  id: "ghost_on_sentinel.memory_card_inheritance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.high.opening",
      onscreenText: "Seen at every angle. The dead apprentice's last passage names them. By doctrine, if not by name.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.high.help_response",
      onscreenText: "Unseen again, briefly. I am asked to forgive what they did.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.memory_card_inheritance.high.release_response",
      onscreenText: "Dissolving. I am asked to finish what was started.",
    },
  },
};

const DAILY_OBSERVATION_LOW: DialogTree = {
  id: "ghost_on_sentinel.daily_observation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.low.opening",
      onscreenText: "Noticed nothing. Saw them in the corridor again. They are here.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.low.help_response",
      onscreenText: "Filed. I will let them pass.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.low.release_response",
      onscreenText: "Filed differently. I will be louder tomorrow.",
    },
  },
};

const DAILY_OBSERVATION_MID: DialogTree = {
  id: "ghost_on_sentinel.daily_observation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.mid.opening",
      onscreenText: "Being seen. They visit the same corridor on a schedule.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.mid.help_response",
      onscreenText: "Holding the line. I match their schedule. Without mockery.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.mid.release_response",
      onscreenText: "Going where I can be unseen. I miss their schedule. On purpose.",
    },
  },
};

const DAILY_OBSERVATION_HIGH: DialogTree = {
  id: "ghost_on_sentinel.daily_observation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.high.opening",
      onscreenText: "Seen at every angle. I share the corridor with them now. We do not speak.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.high.help_response",
      onscreenText: "Unseen again, briefly. I will speak first, gently.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.daily_observation.high.release_response",
      onscreenText: "Dissolving. They will speak first. I will not answer.",
    },
  },
};

const CORRUPTION_ADVANCE_LOW: DialogTree = {
  id: "ghost_on_sentinel.corruption_advance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.low.opening",
      onscreenText: "Noticed nothing. Crossed a number I was told to avoid.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.low.help_response",
      onscreenText: "Filed. You pulled me back from it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.low.release_response",
      onscreenText: "Filed differently. I will cross again.",
    },
  },
};

const CORRUPTION_ADVANCE_MID: DialogTree = {
  id: "ghost_on_sentinel.corruption_advance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.mid.opening",
      onscreenText: "Being seen. Crossed another number. The numbers stop mattering after this.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.mid.help_response",
      onscreenText: "Holding the line. Mercy resets the counter.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.mid.release_response",
      onscreenText: "Going where I can be unseen. The counter is theirs now.",
    },
  },
};

const CORRUPTION_ADVANCE_HIGH: DialogTree = {
  id: "ghost_on_sentinel.corruption_advance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.high.opening",
      onscreenText: "Seen at every angle. Crossed the last number. There is nothing left to cross.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.high.help_response",
      onscreenText: "Unseen again, briefly. You pulled me back from the last number.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.corruption_advance.high.release_response",
      onscreenText: "Dissolving. The last number is theirs.",
    },
  },
};

const APPRENTICE_WARNING_LOW: DialogTree = {
  id: "ghost_on_sentinel.apprentice_warning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.low.opening",
      onscreenText: "Noticed nothing. They are running something against the trade route tonight.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.low.help_response",
      onscreenText: "Filed. You heard me. The route holds.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.low.release_response",
      onscreenText: "Filed differently. You ignored me. The route falls.",
    },
  },
};

const APPRENTICE_WARNING_MID: DialogTree = {
  id: "ghost_on_sentinel.apprentice_warning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.mid.opening",
      onscreenText: "Being seen. Their plan is larger than I first reported.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.mid.help_response",
      onscreenText: "Holding the line. You acted on the report. Good.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.mid.release_response",
      onscreenText: "Going where I can be unseen. You did not act. The plan succeeds.",
    },
  },
};

const APPRENTICE_WARNING_HIGH: DialogTree = {
  id: "ghost_on_sentinel.apprentice_warning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.high.opening",
      onscreenText: "Seen at every angle. The plan is now too late to stop quietly.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.high.help_response",
      onscreenText: "Unseen again, briefly. We will stop it loudly, together.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_warning.high.release_response",
      onscreenText: "Dissolving. They will succeed. I am sorry I waited.",
    },
  },
};

const APPRENTICE_PRIDE_LOW: DialogTree = {
  id: "ghost_on_sentinel.apprentice_pride.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.low.opening",
      onscreenText: "Noticed nothing. You handled them well today. I noticed.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.low.help_response",
      onscreenText: "Filed. Thank you for noticing my noticing.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.low.release_response",
      onscreenText: "Filed differently. I will keep noticing. Quieter, next time.",
    },
  },
};

const APPRENTICE_PRIDE_MID: DialogTree = {
  id: "ghost_on_sentinel.apprentice_pride.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.mid.opening",
      onscreenText: "Being seen. You are the reason the rivalry has not eaten me.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.mid.help_response",
      onscreenText: "Holding the line. Thank you. I needed that out loud.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.mid.release_response",
      onscreenText: "Going where I can be unseen. Acknowledged. Quietly.",
    },
  },
};

const APPRENTICE_PRIDE_HIGH: DialogTree = {
  id: "ghost_on_sentinel.apprentice_pride.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.high.opening",
      onscreenText: "Seen at every angle. I will say this once: I am proud to have trained with you.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.high.help_response",
      onscreenText: "Unseen again, briefly. I am proud back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.ghost_on_sentinel.apprentice_pride.high.release_response",
      onscreenText: "Dissolving. I will hold the line. As you have.",
    },
  },
};

export const ghostOnSentinelPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "ghost_on_sentinel",
  apprenticeArchetype: "ghost",
  nemesisArchetype: "sentinel",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
    breaking_point_whisper: makeApprenticeScene({
      low: BREAKING_POINT_WHISPER_LOW,
      mid: BREAKING_POINT_WHISPER_MID,
      high: BREAKING_POINT_WHISPER_HIGH,
    }),
    post_cohort_retrospective: makeApprenticeScene({
      low: POST_COHORT_RETROSPECTIVE_LOW,
      mid: POST_COHORT_RETROSPECTIVE_MID,
      high: POST_COHORT_RETROSPECTIVE_HIGH,
    }),
    memory_card_inheritance: makeApprenticeScene({
      low: MEMORY_CARD_INHERITANCE_LOW,
      mid: MEMORY_CARD_INHERITANCE_MID,
      high: MEMORY_CARD_INHERITANCE_HIGH,
    }),
    daily_observation: makeApprenticeScene({
      low: DAILY_OBSERVATION_LOW,
      mid: DAILY_OBSERVATION_MID,
      high: DAILY_OBSERVATION_HIGH,
    }),
    corruption_advance: makeApprenticeScene({
      low: CORRUPTION_ADVANCE_LOW,
      mid: CORRUPTION_ADVANCE_MID,
      high: CORRUPTION_ADVANCE_HIGH,
    }),
    apprentice_warning: makeApprenticeScene({
      low: APPRENTICE_WARNING_LOW,
      mid: APPRENTICE_WARNING_MID,
      high: APPRENTICE_WARNING_HIGH,
    }),
    apprentice_pride: makeApprenticeScene({
      low: APPRENTICE_PRIDE_LOW,
      mid: APPRENTICE_PRIDE_MID,
      high: APPRENTICE_PRIDE_HIGH,
    }),
  },
};
