/* ═══════════════════════════════════════════════════════
   Heretic-APPRENTICE on Wanderer-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's heretic-archetype apprentice's morning
   briefing about the wanderer-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "heretic_on_wanderer.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.low.opening",
      onscreenText: "We had a doctrinal argument last night. They quoted my own marginalia back at me.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.low.help_response",
      onscreenText: "Thank you. The doctrine sharpens against good opposition.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.low.release_response",
      onscreenText: "I will join their argument. Mine has run thin.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "heretic_on_wanderer.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.mid.opening",
      onscreenText: "Their orthodoxy is starting to fit me better than mine does. I am uncomfortable noticing.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.mid.help_response",
      onscreenText: "I am steady. My doctrine survives the comparison.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.mid.release_response",
      onscreenText: "I am converting. The new doctrine fits like a garment that was made for me.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "heretic_on_wanderer.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.high.opening",
      onscreenText: "I have started preaching their cause without intending to. Help me or let the conversion finish.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.high.help_response",
      onscreenText: "I am restored. The cause is mine again, with new sharpness.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.heretic_on_wanderer.morning.high.release_response",
      onscreenText: "The conversion is finished. I am of the truer cause now. I am sorry.",
    },
  },
};

export const hereticOnWandererPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "heretic_on_wanderer",
  apprenticeArchetype: "heretic",
  nemesisArchetype: "wanderer",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
