/* ═══════════════════════════════════════════════════════
   Jester-APPRENTICE on Sentinel-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's jester-archetype apprentice's morning
   briefing about the sentinel-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "jester_on_sentinel.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.low.opening",
      onscreenText: "They workshopped my act last night. The notes were honest, which was the unkindest cut.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.low.help_response",
      onscreenText: "Thank you. The act is funnier for the notes.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.low.release_response",
      onscreenText: "I will join their tour. The bit's bigger with two.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "jester_on_sentinel.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.mid.opening",
      onscreenText: "They have stolen my best material. The audience prefers their delivery.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.mid.help_response",
      onscreenText: "I am restored. New material tomorrow.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.mid.release_response",
      onscreenText: "I am their warm-up now. The chronicle billing reads accordingly.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "jester_on_sentinel.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.high.opening",
      onscreenText: "I am a punchline I did not write. Help me or let me play it out.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.high.help_response",
      onscreenText: "I am the writer again. The next bit is mine.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.jester_on_sentinel.morning.high.release_response",
      onscreenText: "I play the punchline to the end. The chronicle will love the timing.",
    },
  },
};

export const jesterOnSentinelPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "jester_on_sentinel",
  apprenticeArchetype: "jester",
  nemesisArchetype: "sentinel",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
