/* ═══════════════════════════════════════════════════════
   Martyr-APPRENTICE on Prodigal-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.

   Scenes: cohort_morning_briefing (Wave 3 hand-authored) +
   7 new scenes (Wave 4: breaking_point_whisper,
   post_cohort_retrospective, memory_card_inheritance,
   daily_observation, corruption_advance, apprentice_warning,
   apprentice_pride). New scenes composed from per-archetype
   voice + per-scene framing.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "martyr_on_prodigal.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.low.opening",
      onscreenText: "They asked me what I was willing to die for. I gave the wrong answer; mine was too short.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.low.help_response",
      onscreenText: "Thank you. The answer is mine to lengthen.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.low.release_response",
      onscreenText: "I will give them the answer they wanted. The cost was always coming.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "martyr_on_prodigal.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.mid.opening",
      onscreenText: "I have given them three answers this week. None of them have been mine.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.mid.help_response",
      onscreenText: "I am restored. The next answer is mine.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.mid.release_response",
      onscreenText: "The next answer is theirs. The cost is paid in advance.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "martyr_on_prodigal.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.high.opening",
      onscreenText: "I am the answer now. Help me or let me be spoken.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.high.help_response",
      onscreenText: "I am still mine. The answer was almost theirs.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.morning.high.release_response",
      onscreenText: "I am spoken. The chronicle records the speaker, not the speech.",
    },
  },
};

const BREAKING_POINT_WHISPER_LOW: DialogTree = {
  id: "martyr_on_prodigal.breaking_point_whisper.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.low.opening",
      onscreenText: "Answer was too short. They whispered. I listened, mostly out of training.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.low.help_response",
      onscreenText: "Lengthening the answer. You pulled me back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.low.release_response",
      onscreenText: "Their answer was right. I let it pass.",
    },
  },
};

const BREAKING_POINT_WHISPER_MID: DialogTree = {
  id: "martyr_on_prodigal.breaking_point_whisper.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.mid.opening",
      onscreenText: "Three answers, none mine. The whisper has been most of my afternoon.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.mid.help_response",
      onscreenText: "Next answer mine. I am back. Just barely.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.mid.release_response",
      onscreenText: "Next answer theirs. I am still listening.",
    },
  },
};

const BREAKING_POINT_WHISPER_HIGH: DialogTree = {
  id: "martyr_on_prodigal.breaking_point_whisper.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.high.opening",
      onscreenText: "I am the answer. The whisper is most of my voice now.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.high.help_response",
      onscreenText: "Still mine. I am pulled clear. The voice is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.breaking_point_whisper.high.release_response",
      onscreenText: "Spoken. I am their voice now. I am sorry.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_LOW: DialogTree = {
  id: "martyr_on_prodigal.post_cohort_retrospective.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.low.opening",
      onscreenText: "Answer was too short. The cohort closed. We did what could be done.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.low.help_response",
      onscreenText: "Lengthening the answer. You let it close kindly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.low.release_response",
      onscreenText: "Their answer was right. You closed it sharply.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_MID: DialogTree = {
  id: "martyr_on_prodigal.post_cohort_retrospective.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.mid.opening",
      onscreenText: "Three answers, none mine. The cohort closed harder than I thought.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.mid.help_response",
      onscreenText: "Next answer mine. Mercy at the close.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.mid.release_response",
      onscreenText: "Next answer theirs. Aggression at the close.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_HIGH: DialogTree = {
  id: "martyr_on_prodigal.post_cohort_retrospective.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.high.opening",
      onscreenText: "I am the answer. The cohort closed with names I do not want to say aloud.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.high.help_response",
      onscreenText: "Still mine. You let the chronicle be quiet about it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.post_cohort_retrospective.high.release_response",
      onscreenText: "Spoken. You said the names anyway.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_LOW: DialogTree = {
  id: "martyr_on_prodigal.memory_card_inheritance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.low.opening",
      onscreenText: "Answer was too short. The dead apprentice wrote a card. Most of it is small things.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.low.help_response",
      onscreenText: "Lengthening the answer. The card includes mercy for me.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.low.release_response",
      onscreenText: "Their answer was right. The card includes warning for me.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_MID: DialogTree = {
  id: "martyr_on_prodigal.memory_card_inheritance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.mid.opening",
      onscreenText: "Three answers, none mine. The dead apprentice's card mentions them by archetype.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.mid.help_response",
      onscreenText: "Next answer mine. I am told to be kind. I will try.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.mid.release_response",
      onscreenText: "Next answer theirs. I am told to be careful. I will be.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_HIGH: DialogTree = {
  id: "martyr_on_prodigal.memory_card_inheritance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.high.opening",
      onscreenText: "I am the answer. The dead apprentice's last passage names them. By doctrine, if not by name.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.high.help_response",
      onscreenText: "Still mine. I am asked to forgive what they did.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.memory_card_inheritance.high.release_response",
      onscreenText: "Spoken. I am asked to finish what was started.",
    },
  },
};

const DAILY_OBSERVATION_LOW: DialogTree = {
  id: "martyr_on_prodigal.daily_observation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.low.opening",
      onscreenText: "Answer was too short. Saw them in the corridor again. They are here.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.low.help_response",
      onscreenText: "Lengthening the answer. I will let them pass.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.low.release_response",
      onscreenText: "Their answer was right. I will be louder tomorrow.",
    },
  },
};

const DAILY_OBSERVATION_MID: DialogTree = {
  id: "martyr_on_prodigal.daily_observation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.mid.opening",
      onscreenText: "Three answers, none mine. They visit the same corridor on a schedule.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.mid.help_response",
      onscreenText: "Next answer mine. I match their schedule. Without mockery.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.mid.release_response",
      onscreenText: "Next answer theirs. I miss their schedule. On purpose.",
    },
  },
};

const DAILY_OBSERVATION_HIGH: DialogTree = {
  id: "martyr_on_prodigal.daily_observation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.high.opening",
      onscreenText: "I am the answer. I share the corridor with them now. We do not speak.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.high.help_response",
      onscreenText: "Still mine. I will speak first, gently.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.daily_observation.high.release_response",
      onscreenText: "Spoken. They will speak first. I will not answer.",
    },
  },
};

const CORRUPTION_ADVANCE_LOW: DialogTree = {
  id: "martyr_on_prodigal.corruption_advance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.low.opening",
      onscreenText: "Answer was too short. Crossed a number I was told to avoid.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.low.help_response",
      onscreenText: "Lengthening the answer. You pulled me back from it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.low.release_response",
      onscreenText: "Their answer was right. I will cross again.",
    },
  },
};

const CORRUPTION_ADVANCE_MID: DialogTree = {
  id: "martyr_on_prodigal.corruption_advance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.mid.opening",
      onscreenText: "Three answers, none mine. Crossed another number. The numbers stop mattering after this.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.mid.help_response",
      onscreenText: "Next answer mine. Mercy resets the counter.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.mid.release_response",
      onscreenText: "Next answer theirs. The counter is theirs now.",
    },
  },
};

const CORRUPTION_ADVANCE_HIGH: DialogTree = {
  id: "martyr_on_prodigal.corruption_advance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.high.opening",
      onscreenText: "I am the answer. Crossed the last number. There is nothing left to cross.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.high.help_response",
      onscreenText: "Still mine. You pulled me back from the last number.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.corruption_advance.high.release_response",
      onscreenText: "Spoken. The last number is theirs.",
    },
  },
};

const APPRENTICE_WARNING_LOW: DialogTree = {
  id: "martyr_on_prodigal.apprentice_warning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.low.opening",
      onscreenText: "Answer was too short. They are running something against the trade route tonight.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.low.help_response",
      onscreenText: "Lengthening the answer. You heard me. The route holds.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.low.release_response",
      onscreenText: "Their answer was right. You ignored me. The route falls.",
    },
  },
};

const APPRENTICE_WARNING_MID: DialogTree = {
  id: "martyr_on_prodigal.apprentice_warning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.mid.opening",
      onscreenText: "Three answers, none mine. Their plan is larger than I first reported.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.mid.help_response",
      onscreenText: "Next answer mine. You acted on the report. Good.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.mid.release_response",
      onscreenText: "Next answer theirs. You did not act. The plan succeeds.",
    },
  },
};

const APPRENTICE_WARNING_HIGH: DialogTree = {
  id: "martyr_on_prodigal.apprentice_warning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.high.opening",
      onscreenText: "I am the answer. The plan is now too late to stop quietly.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.high.help_response",
      onscreenText: "Still mine. We will stop it loudly, together.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_warning.high.release_response",
      onscreenText: "Spoken. They will succeed. I am sorry I waited.",
    },
  },
};

const APPRENTICE_PRIDE_LOW: DialogTree = {
  id: "martyr_on_prodigal.apprentice_pride.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.low.opening",
      onscreenText: "Answer was too short. You handled them well today. I noticed.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.low.help_response",
      onscreenText: "Lengthening the answer. Thank you for noticing my noticing.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.low.release_response",
      onscreenText: "Their answer was right. I will keep noticing. Quieter, next time.",
    },
  },
};

const APPRENTICE_PRIDE_MID: DialogTree = {
  id: "martyr_on_prodigal.apprentice_pride.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.mid.opening",
      onscreenText: "Three answers, none mine. You are the reason the rivalry has not eaten me.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.mid.help_response",
      onscreenText: "Next answer mine. Thank you. I needed that out loud.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.mid.release_response",
      onscreenText: "Next answer theirs. Acknowledged. Quietly.",
    },
  },
};

const APPRENTICE_PRIDE_HIGH: DialogTree = {
  id: "martyr_on_prodigal.apprentice_pride.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.high.opening",
      onscreenText: "I am the answer. I will say this once: I am proud to have trained with you.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.high.help_response",
      onscreenText: "Still mine. I am proud back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_prodigal.apprentice_pride.high.release_response",
      onscreenText: "Spoken. I will hold the line. As you have.",
    },
  },
};

export const martyrOnProdigalPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "martyr_on_prodigal",
  apprenticeArchetype: "martyr",
  nemesisArchetype: "prodigal",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
    breaking_point_whisper: makeApprenticeScene({
      low: BREAKING_POINT_WHISPER_LOW,
      mid: BREAKING_POINT_WHISPER_MID,
      high: BREAKING_POINT_WHISPER_HIGH,
    }),
    post_cohort_retrospective: makeApprenticeScene({
      low: POST_COHORT_RETROSPECTIVE_LOW,
      mid: POST_COHORT_RETROSPECTIVE_MID,
      high: POST_COHORT_RETROSPECTIVE_HIGH,
    }),
    memory_card_inheritance: makeApprenticeScene({
      low: MEMORY_CARD_INHERITANCE_LOW,
      mid: MEMORY_CARD_INHERITANCE_MID,
      high: MEMORY_CARD_INHERITANCE_HIGH,
    }),
    daily_observation: makeApprenticeScene({
      low: DAILY_OBSERVATION_LOW,
      mid: DAILY_OBSERVATION_MID,
      high: DAILY_OBSERVATION_HIGH,
    }),
    corruption_advance: makeApprenticeScene({
      low: CORRUPTION_ADVANCE_LOW,
      mid: CORRUPTION_ADVANCE_MID,
      high: CORRUPTION_ADVANCE_HIGH,
    }),
    apprentice_warning: makeApprenticeScene({
      low: APPRENTICE_WARNING_LOW,
      mid: APPRENTICE_WARNING_MID,
      high: APPRENTICE_WARNING_HIGH,
    }),
    apprentice_pride: makeApprenticeScene({
      low: APPRENTICE_PRIDE_LOW,
      mid: APPRENTICE_PRIDE_MID,
      high: APPRENTICE_PRIDE_HIGH,
    }),
  },
};
