/* ═══════════════════════════════════════════════════════
   Martyr-APPRENTICE on Wanderer-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's martyr-archetype apprentice's morning
   briefing about the wanderer-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "martyr_on_wanderer.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.low.opening",
      onscreenText: "They asked me what I was willing to die for. I gave the wrong answer; mine was too short.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.low.help_response",
      onscreenText: "Thank you. The answer is mine to lengthen.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.low.release_response",
      onscreenText: "I will give them the answer they wanted. The cost was always coming.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "martyr_on_wanderer.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.mid.opening",
      onscreenText: "I have given them three answers this week. None of them have been mine.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.mid.help_response",
      onscreenText: "I am restored. The next answer is mine.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.mid.release_response",
      onscreenText: "The next answer is theirs. The cost is paid in advance.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "martyr_on_wanderer.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.high.opening",
      onscreenText: "I am the answer now. Help me or let me be spoken.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.high.help_response",
      onscreenText: "I am still mine. The answer was almost theirs.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.martyr_on_wanderer.morning.high.release_response",
      onscreenText: "I am spoken. The chronicle records the speaker, not the speech.",
    },
  },
};

export const martyrOnWandererPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "martyr_on_wanderer",
  apprenticeArchetype: "martyr",
  nemesisArchetype: "wanderer",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
