/* ═══════════════════════════════════════════════════════
   Oracle-APPRENTICE on Sentinel-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's oracle-archetype apprentice's morning
   briefing about the sentinel-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "oracle_on_sentinel.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.low.opening",
      onscreenText: "I dreamed them last night. They dreamed me back. The branches converge sooner than I'd hoped.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.low.help_response",
      onscreenText: "Thank you. The branches diverge again, briefly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.low.release_response",
      onscreenText: "Convergence accepted. We will end on the same branch.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "oracle_on_sentinel.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.mid.opening",
      onscreenText: "Three of my branches end with them speaking my last words. I am uncertain which branch we are on.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.mid.help_response",
      onscreenText: "Branch four. The clean one. Thank you.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.mid.release_response",
      onscreenText: "Branch one. The fast one. I am ready.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "oracle_on_sentinel.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.high.opening",
      onscreenText: "All branches converge on them now. Help me cut the convergence or let the vision complete.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.high.help_response",
      onscreenText: "The branches diverge again. We are off the rails.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.oracle_on_sentinel.morning.high.release_response",
      onscreenText: "The vision completes. I see what they see; we share the page now.",
    },
  },
};

export const oracleOnSentinelPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "oracle_on_sentinel",
  apprenticeArchetype: "oracle",
  nemesisArchetype: "sentinel",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
