/* ═══════════════════════════════════════════════════════
   Prodigal-APPRENTICE on Zealot-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's prodigal-archetype apprentice's morning
   briefing about the zealot-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "prodigal_on_zealot.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.low.opening",
      onscreenText: "They came home through me last night. Asked which key was theirs. I lied.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.low.help_response",
      onscreenText: "Thank you. The keys stay where they belong.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.low.release_response",
      onscreenText: "I will give them a key. The household decides what to do with it.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "prodigal_on_zealot.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.mid.opening",
      onscreenText: "They have moved into the family seat. I gave it up gradually. I notice now.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.mid.help_response",
      onscreenText: "I am restored. The seat is mine.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.mid.release_response",
      onscreenText: "The seat is theirs. The household is reorganizing around them.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "prodigal_on_zealot.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.high.opening",
      onscreenText: "I am being asked to leave my own house. Help me hold it or let me leave.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.high.help_response",
      onscreenText: "The house is mine again. Locks are changed.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.prodigal_on_zealot.morning.high.release_response",
      onscreenText: "I leave. The household's name does not require my presence to continue.",
    },
  },
};

export const prodigalOnZealotPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "prodigal_on_zealot",
  apprenticeArchetype: "prodigal",
  nemesisArchetype: "zealot",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
