/* ═══════════════════════════════════════════════════════
   Scholar-APPRENTICE on Ghost-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's scholar-archetype apprentice's morning
   briefing about the ghost-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "scholar_on_ghost.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.low.opening",
      onscreenText: "I have started a file on them. They have started one on me. Their cross-references are competent.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.low.help_response",
      onscreenText: "Thank you. The footnotes are sharper for the help.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.low.release_response",
      onscreenText: "I will revise alone. The file gets shorter.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "scholar_on_ghost.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.mid.opening",
      onscreenText: "Their file on me is more complete than mine on them. I am uncertain who is the subject.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.mid.help_response",
      onscreenText: "We are co-authoring now. The file improves.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.mid.release_response",
      onscreenText: "I am their subject. The file closes on me.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "scholar_on_ghost.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.high.opening",
      onscreenText: "The file has my conclusions written by their hand. I cannot tell which thoughts are mine. Help me or let me be revised.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.high.help_response",
      onscreenText: "I am restored. The file is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.scholar_on_ghost.morning.high.release_response",
      onscreenText: "I am revised. The file is theirs.",
    },
  },
};

export const scholarOnGhostPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "scholar_on_ghost",
  apprenticeArchetype: "scholar",
  nemesisArchetype: "ghost",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
