/* ═══════════════════════════════════════════════════════
   Sentinel-APPRENTICE on Zealot-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.

   Scenes: cohort_morning_briefing (Wave 3 hand-authored) +
   7 new scenes (Wave 4: breaking_point_whisper,
   post_cohort_retrospective, memory_card_inheritance,
   daily_observation, corruption_advance, apprentice_warning,
   apprentice_pride). New scenes composed from per-archetype
   voice + per-scene framing.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "sentinel_on_zealot.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.low.opening",
      onscreenText: "They tested the gate last night. I held. They saluted on the way out.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.low.help_response",
      onscreenText: "Thank you. The gate is mine to hold.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.low.release_response",
      onscreenText: "I will fall back. The next post is wider.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "sentinel_on_zealot.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.mid.opening",
      onscreenText: "The gate is breached every other night now. I am tired. The watch is tired.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.mid.help_response",
      onscreenText: "The watch holds. Reinforced.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.mid.release_response",
      onscreenText: "The watch falls. The post is theirs.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "sentinel_on_zealot.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.high.opening",
      onscreenText: "The gate is open and I am still standing in it. Help me close it or let it stay open.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_morning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_morning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.high.help_response",
      onscreenText: "The gate closes. The watch holds.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.morning.high.release_response",
      onscreenText: "The gate stays open. The chronicle records my last shift.",
    },
  },
};

const BREAKING_POINT_WHISPER_LOW: DialogTree = {
  id: "sentinel_on_zealot.breaking_point_whisper.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.low.opening",
      onscreenText: "Tested the gate. They whispered. I listened, mostly out of training.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.low.help_response",
      onscreenText: "Gate mine. You pulled me back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.low.release_response",
      onscreenText: "Falling back. I let it pass.",
    },
  },
};

const BREAKING_POINT_WHISPER_MID: DialogTree = {
  id: "sentinel_on_zealot.breaking_point_whisper.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.mid.opening",
      onscreenText: "Gate breached every other night. The whisper has been most of my afternoon.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.mid.help_response",
      onscreenText: "Reinforced. I am back. Just barely.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.mid.release_response",
      onscreenText: "Watch falls. I am still listening.",
    },
  },
};

const BREAKING_POINT_WHISPER_HIGH: DialogTree = {
  id: "sentinel_on_zealot.breaking_point_whisper.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.high.opening",
      onscreenText: "Gate open, still standing. The whisper is most of my voice now.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_breaking_point_whisper" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_breaking_point_whisper" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.high.help_response",
      onscreenText: "Gate closed. I am pulled clear. The voice is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.breaking_point_whisper.high.release_response",
      onscreenText: "Last shift. I am their voice now. I am sorry.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_LOW: DialogTree = {
  id: "sentinel_on_zealot.post_cohort_retrospective.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.low.opening",
      onscreenText: "Tested the gate. The cohort closed. We did what could be done.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.low.help_response",
      onscreenText: "Gate mine. You let it close kindly.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.low.release_response",
      onscreenText: "Falling back. You closed it sharply.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_MID: DialogTree = {
  id: "sentinel_on_zealot.post_cohort_retrospective.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.mid.opening",
      onscreenText: "Gate breached every other night. The cohort closed harder than I thought.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.mid.help_response",
      onscreenText: "Reinforced. Mercy at the close.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.mid.release_response",
      onscreenText: "Watch falls. Aggression at the close.",
    },
  },
};

const POST_COHORT_RETROSPECTIVE_HIGH: DialogTree = {
  id: "sentinel_on_zealot.post_cohort_retrospective.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.high.opening",
      onscreenText: "Gate open, still standing. The cohort closed with names I do not want to say aloud.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_post_cohort_retrospective" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_post_cohort_retrospective" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.high.help_response",
      onscreenText: "Gate closed. You let the chronicle be quiet about it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.post_cohort_retrospective.high.release_response",
      onscreenText: "Last shift. You said the names anyway.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_LOW: DialogTree = {
  id: "sentinel_on_zealot.memory_card_inheritance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.low.opening",
      onscreenText: "Tested the gate. The dead apprentice wrote a card. Most of it is small things.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.low.help_response",
      onscreenText: "Gate mine. The card includes mercy for me.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.low.release_response",
      onscreenText: "Falling back. The card includes warning for me.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_MID: DialogTree = {
  id: "sentinel_on_zealot.memory_card_inheritance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.mid.opening",
      onscreenText: "Gate breached every other night. The dead apprentice's card mentions them by archetype.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.mid.help_response",
      onscreenText: "Reinforced. I am told to be kind. I will try.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.mid.release_response",
      onscreenText: "Watch falls. I am told to be careful. I will be.",
    },
  },
};

const MEMORY_CARD_INHERITANCE_HIGH: DialogTree = {
  id: "sentinel_on_zealot.memory_card_inheritance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.high.opening",
      onscreenText: "Gate open, still standing. The dead apprentice's last passage names them. By doctrine, if not by name.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_memory_card_inheritance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_memory_card_inheritance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.high.help_response",
      onscreenText: "Gate closed. I am asked to forgive what they did.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.memory_card_inheritance.high.release_response",
      onscreenText: "Last shift. I am asked to finish what was started.",
    },
  },
};

const DAILY_OBSERVATION_LOW: DialogTree = {
  id: "sentinel_on_zealot.daily_observation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.low.opening",
      onscreenText: "Tested the gate. Saw them in the corridor again. They are here.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.low.help_response",
      onscreenText: "Gate mine. I will let them pass.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.low.release_response",
      onscreenText: "Falling back. I will be louder tomorrow.",
    },
  },
};

const DAILY_OBSERVATION_MID: DialogTree = {
  id: "sentinel_on_zealot.daily_observation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.mid.opening",
      onscreenText: "Gate breached every other night. They visit the same corridor on a schedule.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.mid.help_response",
      onscreenText: "Reinforced. I match their schedule. Without mockery.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.mid.release_response",
      onscreenText: "Watch falls. I miss their schedule. On purpose.",
    },
  },
};

const DAILY_OBSERVATION_HIGH: DialogTree = {
  id: "sentinel_on_zealot.daily_observation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.high.opening",
      onscreenText: "Gate open, still standing. I share the corridor with them now. We do not speak.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_daily_observation" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_daily_observation" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.high.help_response",
      onscreenText: "Gate closed. I will speak first, gently.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.daily_observation.high.release_response",
      onscreenText: "Last shift. They will speak first. I will not answer.",
    },
  },
};

const CORRUPTION_ADVANCE_LOW: DialogTree = {
  id: "sentinel_on_zealot.corruption_advance.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.low.opening",
      onscreenText: "Tested the gate. Crossed a number I was told to avoid.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.low.help_response",
      onscreenText: "Gate mine. You pulled me back from it.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.low.release_response",
      onscreenText: "Falling back. I will cross again.",
    },
  },
};

const CORRUPTION_ADVANCE_MID: DialogTree = {
  id: "sentinel_on_zealot.corruption_advance.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.mid.opening",
      onscreenText: "Gate breached every other night. Crossed another number. The numbers stop mattering after this.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.mid.help_response",
      onscreenText: "Reinforced. Mercy resets the counter.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.mid.release_response",
      onscreenText: "Watch falls. The counter is theirs now.",
    },
  },
};

const CORRUPTION_ADVANCE_HIGH: DialogTree = {
  id: "sentinel_on_zealot.corruption_advance.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.high.opening",
      onscreenText: "Gate open, still standing. Crossed the last number. There is nothing left to cross.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_corruption_advance" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_corruption_advance" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.high.help_response",
      onscreenText: "Gate closed. You pulled me back from the last number.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.corruption_advance.high.release_response",
      onscreenText: "Last shift. The last number is theirs.",
    },
  },
};

const APPRENTICE_WARNING_LOW: DialogTree = {
  id: "sentinel_on_zealot.apprentice_warning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.low.opening",
      onscreenText: "Tested the gate. They are running something against the trade route tonight.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.low.help_response",
      onscreenText: "Gate mine. You heard me. The route holds.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.low.release_response",
      onscreenText: "Falling back. You ignored me. The route falls.",
    },
  },
};

const APPRENTICE_WARNING_MID: DialogTree = {
  id: "sentinel_on_zealot.apprentice_warning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.mid.opening",
      onscreenText: "Gate breached every other night. Their plan is larger than I first reported.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.mid.help_response",
      onscreenText: "Reinforced. You acted on the report. Good.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.mid.release_response",
      onscreenText: "Watch falls. You did not act. The plan succeeds.",
    },
  },
};

const APPRENTICE_WARNING_HIGH: DialogTree = {
  id: "sentinel_on_zealot.apprentice_warning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.high.opening",
      onscreenText: "Gate open, still standing. The plan is now too late to stop quietly.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_warning" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_warning" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.high.help_response",
      onscreenText: "Gate closed. We will stop it loudly, together.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_warning.high.release_response",
      onscreenText: "Last shift. They will succeed. I am sorry I waited.",
    },
  },
};

const APPRENTICE_PRIDE_LOW: DialogTree = {
  id: "sentinel_on_zealot.apprentice_pride.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.low.opening",
      onscreenText: "Tested the gate. You handled them well today. I noticed.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.low.help_response",
      onscreenText: "Gate mine. Thank you for noticing my noticing.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.low.release_response",
      onscreenText: "Falling back. I will keep noticing. Quieter, next time.",
    },
  },
};

const APPRENTICE_PRIDE_MID: DialogTree = {
  id: "sentinel_on_zealot.apprentice_pride.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.mid.opening",
      onscreenText: "Gate breached every other night. You are the reason the rivalry has not eaten me.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.mid.help_response",
      onscreenText: "Reinforced. Thank you. I needed that out loud.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.mid.release_response",
      onscreenText: "Watch falls. Acknowledged. Quietly.",
    },
  },
};

const APPRENTICE_PRIDE_HIGH: DialogTree = {
  id: "sentinel_on_zealot.apprentice_pride.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.high.opening",
      onscreenText: "Gate open, still standing. I will say this once: I am proud to have trained with you.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high_apprentice_pride" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high_apprentice_pride" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.high.help_response",
      onscreenText: "Gate closed. I am proud back.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.sentinel_on_zealot.apprentice_pride.high.release_response",
      onscreenText: "Last shift. I will hold the line. As you have.",
    },
  },
};

export const sentinelOnZealotPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "sentinel_on_zealot",
  apprenticeArchetype: "sentinel",
  nemesisArchetype: "zealot",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
    breaking_point_whisper: makeApprenticeScene({
      low: BREAKING_POINT_WHISPER_LOW,
      mid: BREAKING_POINT_WHISPER_MID,
      high: BREAKING_POINT_WHISPER_HIGH,
    }),
    post_cohort_retrospective: makeApprenticeScene({
      low: POST_COHORT_RETROSPECTIVE_LOW,
      mid: POST_COHORT_RETROSPECTIVE_MID,
      high: POST_COHORT_RETROSPECTIVE_HIGH,
    }),
    memory_card_inheritance: makeApprenticeScene({
      low: MEMORY_CARD_INHERITANCE_LOW,
      mid: MEMORY_CARD_INHERITANCE_MID,
      high: MEMORY_CARD_INHERITANCE_HIGH,
    }),
    daily_observation: makeApprenticeScene({
      low: DAILY_OBSERVATION_LOW,
      mid: DAILY_OBSERVATION_MID,
      high: DAILY_OBSERVATION_HIGH,
    }),
    corruption_advance: makeApprenticeScene({
      low: CORRUPTION_ADVANCE_LOW,
      mid: CORRUPTION_ADVANCE_MID,
      high: CORRUPTION_ADVANCE_HIGH,
    }),
    apprentice_warning: makeApprenticeScene({
      low: APPRENTICE_WARNING_LOW,
      mid: APPRENTICE_WARNING_MID,
      high: APPRENTICE_WARNING_HIGH,
    }),
    apprentice_pride: makeApprenticeScene({
      low: APPRENTICE_PRIDE_LOW,
      mid: APPRENTICE_PRIDE_MID,
      high: APPRENTICE_PRIDE_HIGH,
    }),
  },
};
