/* ═══════════════════════════════════════════════════════
   Wanderer-APPRENTICE on Zealot-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's wanderer-archetype apprentice's morning
   briefing about the zealot-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "wanderer_on_zealot.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.low.opening",
      onscreenText: "They blocked my road last night. I took the other one. I do not know if it was a courtesy.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.low.help_response",
      onscreenText: "Thank you. I will walk roads they have not seen.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.low.release_response",
      onscreenText: "I will follow them. The road is shared.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "wanderer_on_zealot.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.mid.opening",
      onscreenText: "All my roads circle back to their station now. The map has shrunk.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.mid.help_response",
      onscreenText: "The map widens. I have new roads tonight.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.mid.release_response",
      onscreenText: "The map closes. I am at the station with them.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "wanderer_on_zealot.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.high.opening",
      onscreenText: "There is one road left, and they are on it. Help me find another or let me share theirs.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.high.help_response",
      onscreenText: "A new road appears. I take it alone.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.wanderer_on_zealot.morning.high.release_response",
      onscreenText: "I share their road. The chronicle calls us neighbors now.",
    },
  },
};

export const wandererOnZealotPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "wanderer_on_zealot",
  apprenticeArchetype: "wanderer",
  nemesisArchetype: "zealot",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
