/* ═══════════════════════════════════════════════════════
   Zealot-APPRENTICE on Revenant-NEMESIS — Phase K6.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   The player's zealot-archetype apprentice's morning
   briefing about the revenant-Nemesis encounter.
   ═══════════════════════════════════════════════════════ */

import type { ApprenticeOnNemesisPairBank } from "./_types";
import { makeApprenticeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const MORNING_LOW: DialogTree = {
  id: "zealot_on_revenant.morning.low",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.low.opening",
      onscreenText: "The Nemesis sermonized at me last night. I rebuked their cause with mine. They left.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_low" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_low" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.low.help_response",
      onscreenText: "Thank you. The cause is sharper for the test.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.low.release_response",
      onscreenText: "I will preach back. Steady at the post.",
    },
  },
};

const MORNING_MID: DialogTree = {
  id: "zealot_on_revenant.morning.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.mid.opening",
      onscreenText: "Their cause is louder than mine some mornings. I am holding, but I notice.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_mid" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_mid" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.mid.help_response",
      onscreenText: "I am held. The cause is mine again.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.mid.release_response",
      onscreenText: "I am loosened. We are not the same prayer anymore.",
    },
  },
};

const MORNING_HIGH: DialogTree = {
  id: "zealot_on_revenant.morning.high",
  nodes: {
    root: {
      id: "root",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.high.opening",
      onscreenText: "I confess: their cause sounds like ours now. Help me, or let me go.",
      choices: [
        { label: "Steady them.", nextId: "help", sets: "apprentice_steadied_at_high" },
        { label: "Let them drift.", nextId: "release", sets: "apprentice_released_at_high" },
      ],
    },
    help: {
      id: "help",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.high.help_response",
      onscreenText: "I am still here. The cause was loud. Your hand is louder.",
    },
    release: {
      id: "release",
      speaker: "apprentice",
      voLineId: "apprentice.zealot_on_revenant.morning.high.release_response",
      onscreenText: "Then I am theirs. The cause was always going to win this argument.",
    },
  },
};

export const zealotOnRevenantPairBank: ApprenticeOnNemesisPairBank = {
  pairId: "zealot_on_revenant",
  apprenticeArchetype: "zealot",
  nemesisArchetype: "revenant",
  scenes: {
    cohort_morning_briefing: makeApprenticeScene({
      low: MORNING_LOW,
      mid: MORNING_MID,
      high: MORNING_HIGH,
    }),
  },
};
