import type { StoryHook } from "./storyHookRegistry";

// Auto-generated from producer-art axis-13 variants (H.A inventory)
// One hook entry per (zipDir × axis × value) where the producer
// shipped a state-variant PNG. Each entry pairs a narrative-flag
// trigger with the room-state-shift it activates.

export const SEED_STORYTELLER_HOOKS: readonly StoryHook[] = [
  {
    id: "antiquarians_library:battlepass_winter",
    roomZipDir: "antiquarians_library",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_antiquarians_library_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "antiquarians_library:epoch_shadowtongue",
    roomZipDir: "antiquarians_library",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_antiquarians_library_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "antiquarians_library:governance_lore_unlock",
    roomZipDir: "antiquarians_library",
    axisKey: "governance",
    axisValue: "lore_unlock",
    flagTrigger: "storyhook_antiquarians_library_governance_lore_unlock",
    variantKey: "governance_lore_unlock",
  },
  {
    id: "antiquarians_library:investigation_tier",
    roomZipDir: "antiquarians_library",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_antiquarians_library_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "antiquarians_library:lore_hierophant_complete",
    roomZipDir: "antiquarians_library",
    axisKey: "lore",
    axisValue: "hierophant_complete",
    flagTrigger: "storyhook_antiquarians_library_lore_hierophant_complete",
    variantKey: "lore_hierophant_complete",
  },
  {
    id: "antiquarians_library:lore_recipe_archive",
    roomZipDir: "antiquarians_library",
    axisKey: "lore",
    axisValue: "recipe_archive",
    flagTrigger: "storyhook_antiquarians_library_lore_recipe_archive",
    variantKey: "lore_recipe_archive",
  },
  {
    id: "antiquarians_library:lore_tome_discovered",
    roomZipDir: "antiquarians_library",
    axisKey: "lore",
    axisValue: "tome_discovered",
    flagTrigger: "storyhook_antiquarians_library_lore_tome_discovered",
    variantKey: "lore_tome_discovered",
  },
  {
    id: "antiquarians_library:morality_dark",
    roomZipDir: "antiquarians_library",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_antiquarians_library_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "antiquarians_library:reveal_daniel_cross",
    roomZipDir: "antiquarians_library",
    axisKey: "reveal",
    axisValue: "daniel_cross",
    flagTrigger: "storyhook_antiquarians_library_reveal_daniel_cross",
    variantKey: "reveal_daniel_cross",
  },
  {
    id: "antiquarians_library:season_closing",
    roomZipDir: "antiquarians_library",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_antiquarians_library_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "antiquarians_library:unlock_conexus",
    roomZipDir: "antiquarians_library",
    axisKey: "unlock",
    axisValue: "conexus",
    flagTrigger: "storyhook_antiquarians_library_unlock_conexus",
    variantKey: "unlock_conexus",
  },
  {
    id: "antiquarians_library:unlock_vault",
    roomZipDir: "antiquarians_library",
    axisKey: "unlock",
    axisValue: "vault",
    flagTrigger: "storyhook_antiquarians_library_unlock_vault",
    variantKey: "unlock_vault",
  },
  {
    id: "apprentice_berth:act_tier2",
    roomZipDir: "apprentice_berth",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_apprentice_berth_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "apprentice_berth:act_tier5",
    roomZipDir: "apprentice_berth",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_apprentice_berth_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "apprentice_berth:act_tier7",
    roomZipDir: "apprentice_berth",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_apprentice_berth_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "apprentice_berth:irl_winter",
    roomZipDir: "apprentice_berth",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_apprentice_berth_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "apprentice_berth:morality_dark",
    roomZipDir: "apprentice_berth",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_apprentice_berth_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "apprentice_berth:season_interregnum",
    roomZipDir: "apprentice_berth",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_apprentice_berth_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "archives:act_tier_2",
    roomZipDir: "archives",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_archives_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "archives:battlepass_winter",
    roomZipDir: "archives",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_archives_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "archives:companion_trust",
    roomZipDir: "archives",
    axisKey: "companion",
    axisValue: "trust",
    flagTrigger: "storyhook_archives_companion_trust",
    variantKey: "companion_trust",
  },
  {
    id: "archives:epoch_shadowtongue",
    roomZipDir: "archives",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_archives_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "archives:governance_lore_unlock",
    roomZipDir: "archives",
    axisKey: "governance",
    axisValue: "lore_unlock",
    flagTrigger: "storyhook_archives_governance_lore_unlock",
    variantKey: "governance_lore_unlock",
  },
  {
    id: "archives:investigation_tier",
    roomZipDir: "archives",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_archives_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "archives:lore_shadowtongue",
    roomZipDir: "archives",
    axisKey: "lore",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_archives_lore_shadowtongue",
    variantKey: "lore_shadowtongue",
  },
  {
    id: "archives:morality_dark",
    roomZipDir: "archives",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_archives_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "archives:season_closing",
    roomZipDir: "archives",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_archives_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "archives:trust_shelfmate",
    roomZipDir: "archives",
    axisKey: "trust",
    axisValue: "shelfmate",
    flagTrigger: "storyhook_archives_trust_shelfmate",
    variantKey: "trust_shelfmate",
  },
  {
    id: "archives:unlock_loredex",
    roomZipDir: "archives",
    axisKey: "unlock",
    axisValue: "loredex",
    flagTrigger: "storyhook_archives_unlock_loredex",
    variantKey: "unlock_loredex",
  },
  {
    id: "armory:act_tier_3",
    roomZipDir: "armory",
    axisKey: "act",
    axisValue: "tier_3",
    flagTrigger: "storyhook_armory_act_tier_3",
    variantKey: "act_tier_3",
  },
  {
    id: "armory:act_tier_5",
    roomZipDir: "armory",
    axisKey: "act",
    axisValue: "tier_5",
    flagTrigger: "storyhook_armory_act_tier_5",
    variantKey: "act_tier_5",
  },
  {
    id: "armory:battlepass_winter",
    roomZipDir: "armory",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_armory_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "armory:epoch_shadowtongue",
    roomZipDir: "armory",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_armory_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "armory:governance_quarantine",
    roomZipDir: "armory",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_armory_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "armory:investigation_tier",
    roomZipDir: "armory",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_armory_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "armory:morality_dark",
    roomZipDir: "armory",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_armory_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "armory:trust_jericho",
    roomZipDir: "armory",
    axisKey: "trust",
    axisValue: "jericho",
    flagTrigger: "storyhook_armory_trust_jericho",
    variantKey: "trust_jericho",
  },
  {
    id: "armory:unlock_combat",
    roomZipDir: "armory",
    axisKey: "unlock",
    axisValue: "combat",
    flagTrigger: "storyhook_armory_unlock_combat",
    variantKey: "unlock_combat",
  },
  {
    id: "auction_house:battlepass_winter",
    roomZipDir: "auction_house",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_auction_house_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "auction_house:epoch_shadowtongue",
    roomZipDir: "auction_house",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_auction_house_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "auction_house:governance_event",
    roomZipDir: "auction_house",
    axisKey: "governance",
    axisValue: "event",
    flagTrigger: "storyhook_auction_house_governance_event",
    variantKey: "governance_event",
  },
  {
    id: "auction_house:investigation_tier",
    roomZipDir: "auction_house",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_auction_house_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "auction_house:morality_dark",
    roomZipDir: "auction_house",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_auction_house_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "bridge:act_tier_2",
    roomZipDir: "bridge",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_bridge_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "bridge:battlepass_winter",
    roomZipDir: "bridge",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_bridge_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "bridge:epoch_shadowtongue",
    roomZipDir: "bridge",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_bridge_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "bridge:governance_vote",
    roomZipDir: "bridge",
    axisKey: "governance",
    axisValue: "vote",
    flagTrigger: "storyhook_bridge_governance_vote",
    variantKey: "governance_vote",
  },
  {
    id: "bridge:investigation_tier",
    roomZipDir: "bridge",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_bridge_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "bridge:lore_elara_senator",
    roomZipDir: "bridge",
    axisKey: "lore",
    axisValue: "elara_senator",
    flagTrigger: "storyhook_bridge_lore_elara_senator",
    variantKey: "lore_elara_senator",
  },
  {
    id: "bridge:morality_dark",
    roomZipDir: "bridge",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_bridge_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "bridge:season_closing",
    roomZipDir: "bridge",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_bridge_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "bridge:trust_elara_luminous",
    roomZipDir: "bridge",
    axisKey: "trust",
    axisValue: "elara_luminous",
    flagTrigger: "storyhook_bridge_trust_elara_luminous",
    variantKey: "trust_elara_luminous",
  },
  {
    id: "bridge:unlock_trade_empire",
    roomZipDir: "bridge",
    axisKey: "unlock",
    axisValue: "trade_empire",
    flagTrigger: "storyhook_bridge_unlock_trade_empire",
    variantKey: "unlock_trade_empire",
  },
  {
    id: "cades_console:act_tier2",
    roomZipDir: "cades_console",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_cades_console_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "cades_console:act_tier5",
    roomZipDir: "cades_console",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_cades_console_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "cades_console:act_tier7",
    roomZipDir: "cades_console",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_cades_console_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "cades_console:irl_winter",
    roomZipDir: "cades_console",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_cades_console_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "cades_console:morality_dark",
    roomZipDir: "cades_console",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_cades_console_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "cades_console:season_interregnum",
    roomZipDir: "cades_console",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_cades_console_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "captains_quarters:act_tier_1",
    roomZipDir: "captains_quarters",
    axisKey: "act",
    axisValue: "tier_1",
    flagTrigger: "storyhook_captains_quarters_act_tier_1",
    variantKey: "act_tier_1",
  },
  {
    id: "captains_quarters:act_tier_3",
    roomZipDir: "captains_quarters",
    axisKey: "act",
    axisValue: "tier_3",
    flagTrigger: "storyhook_captains_quarters_act_tier_3",
    variantKey: "act_tier_3",
  },
  {
    id: "captains_quarters:act_tier_5",
    roomZipDir: "captains_quarters",
    axisKey: "act",
    axisValue: "tier_5",
    flagTrigger: "storyhook_captains_quarters_act_tier_5",
    variantKey: "act_tier_5",
  },
  {
    id: "captains_quarters:battlepass_winter",
    roomZipDir: "captains_quarters",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_captains_quarters_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "captains_quarters:epoch_shadowtongue",
    roomZipDir: "captains_quarters",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_captains_quarters_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "captains_quarters:governance_vote",
    roomZipDir: "captains_quarters",
    axisKey: "governance",
    axisValue: "vote",
    flagTrigger: "storyhook_captains_quarters_governance_vote",
    variantKey: "governance_vote",
  },
  {
    id: "captains_quarters:investigation_tier",
    roomZipDir: "captains_quarters",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_captains_quarters_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "captains_quarters:lore_captain_kael",
    roomZipDir: "captains_quarters",
    axisKey: "lore",
    axisValue: "captain_kael",
    flagTrigger: "storyhook_captains_quarters_lore_captain_kael",
    variantKey: "lore_captain_kael",
  },
  {
    id: "captains_quarters:morality_dark",
    roomZipDir: "captains_quarters",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_captains_quarters_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "captains_quarters:trust_dmc_wary",
    roomZipDir: "captains_quarters",
    axisKey: "trust",
    axisValue: "dmc_wary",
    flagTrigger: "storyhook_captains_quarters_trust_dmc_wary",
    variantKey: "trust_dmc_wary",
  },
  {
    id: "captains_quarters:unlock_companion_hub",
    roomZipDir: "captains_quarters",
    axisKey: "unlock",
    axisValue: "companion_hub",
    flagTrigger: "storyhook_captains_quarters_unlock_companion_hub",
    variantKey: "unlock_companion_hub",
  },
  {
    id: "cargo_hold:act_tier_2",
    roomZipDir: "cargo_hold",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_cargo_hold_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "cargo_hold:act_tier_4",
    roomZipDir: "cargo_hold",
    axisKey: "act",
    axisValue: "tier_4",
    flagTrigger: "storyhook_cargo_hold_act_tier_4",
    variantKey: "act_tier_4",
  },
  {
    id: "cargo_hold:battlepass_winter",
    roomZipDir: "cargo_hold",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_cargo_hold_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "cargo_hold:epoch_shadowtongue",
    roomZipDir: "cargo_hold",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_cargo_hold_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "cargo_hold:governance_trade",
    roomZipDir: "cargo_hold",
    axisKey: "governance",
    axisValue: "trade",
    flagTrigger: "storyhook_cargo_hold_governance_trade",
    variantKey: "governance_trade",
  },
  {
    id: "cargo_hold:investigation_tier",
    roomZipDir: "cargo_hold",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_cargo_hold_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "cargo_hold:morality_dark",
    roomZipDir: "cargo_hold",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_cargo_hold_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "cargo_hold:season_interregnum",
    roomZipDir: "cargo_hold",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_cargo_hold_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "cargo_hold:unlock_cosmetic",
    roomZipDir: "cargo_hold",
    axisKey: "unlock",
    axisValue: "cosmetic",
    flagTrigger: "storyhook_cargo_hold_unlock_cosmetic",
    variantKey: "unlock_cosmetic",
  },
  {
    id: "casino_floor:act_tier2",
    roomZipDir: "casino_floor",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_casino_floor_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "casino_floor:act_tier5",
    roomZipDir: "casino_floor",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_casino_floor_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "casino_floor:act_tier7",
    roomZipDir: "casino_floor",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_casino_floor_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "casino_floor:irl_winter",
    roomZipDir: "casino_floor",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_casino_floor_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "casino_floor:morality_dark",
    roomZipDir: "casino_floor",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_casino_floor_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "casino_floor:season_interregnum",
    roomZipDir: "casino_floor",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_casino_floor_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "chaos_forge:battlepass_winter",
    roomZipDir: "chaos_forge",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_chaos_forge_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "chaos_forge:epoch_shadowtongue",
    roomZipDir: "chaos_forge",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_chaos_forge_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "chaos_forge:governance_boost",
    roomZipDir: "chaos_forge",
    axisKey: "governance",
    axisValue: "boost",
    flagTrigger: "storyhook_chaos_forge_governance_boost",
    variantKey: "governance_boost",
  },
  {
    id: "chaos_forge:investigation_tier",
    roomZipDir: "chaos_forge",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_chaos_forge_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "chaos_forge:morality_dark",
    roomZipDir: "chaos_forge",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_chaos_forge_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "chess_hall:act_tier2",
    roomZipDir: "chess_hall",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_chess_hall_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "chess_hall:act_tier5",
    roomZipDir: "chess_hall",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_chess_hall_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "chess_hall:act_tier7",
    roomZipDir: "chess_hall",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_chess_hall_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "chess_hall:irl_winter",
    roomZipDir: "chess_hall",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_chess_hall_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "chess_hall:morality_dark",
    roomZipDir: "chess_hall",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_chess_hall_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "chess_hall:season_interregnum",
    roomZipDir: "chess_hall",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_chess_hall_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "cipher_den:battlepass_winter",
    roomZipDir: "cipher_den",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_cipher_den_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "cipher_den:epoch_shadowtongue",
    roomZipDir: "cipher_den",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_cipher_den_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "cipher_den:governance_uncorruption",
    roomZipDir: "cipher_den",
    axisKey: "governance",
    axisValue: "uncorruption",
    flagTrigger: "storyhook_cipher_den_governance_uncorruption",
    variantKey: "governance_uncorruption",
  },
  {
    id: "cipher_den:investigation_tier",
    roomZipDir: "cipher_den",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_cipher_den_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "cipher_den:morality_dark",
    roomZipDir: "cipher_den",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_cipher_den_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "comms_array:act_tier_2",
    roomZipDir: "comms_array",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_comms_array_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "comms_array:battlepass_winter",
    roomZipDir: "comms_array",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_comms_array_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "comms_array:epoch_shadowtongue",
    roomZipDir: "comms_array",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_comms_array_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "comms_array:governance_blackout",
    roomZipDir: "comms_array",
    axisKey: "governance",
    axisValue: "blackout",
    flagTrigger: "storyhook_comms_array_governance_blackout",
    variantKey: "governance_blackout",
  },
  {
    id: "comms_array:human_reveal_ghost",
    roomZipDir: "comms_array",
    axisKey: "human",
    axisValue: "reveal_ghost",
    flagTrigger: "storyhook_comms_array_human_reveal_ghost",
    variantKey: "human_reveal_ghost",
  },
  {
    id: "comms_array:investigation_tier",
    roomZipDir: "comms_array",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_comms_array_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "comms_array:morality_dark",
    roomZipDir: "comms_array",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_comms_array_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "comms_array:season_closing",
    roomZipDir: "comms_array",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_comms_array_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "comms_array:trust_human_warm",
    roomZipDir: "comms_array",
    axisKey: "trust",
    axisValue: "human_warm",
    flagTrigger: "storyhook_comms_array_trust_human_warm",
    variantKey: "trust_human_warm",
  },
  {
    id: "comms_array:unlock_cipher_den",
    roomZipDir: "comms_array",
    axisKey: "unlock",
    axisValue: "cipher_den",
    flagTrigger: "storyhook_comms_array_unlock_cipher_den",
    variantKey: "unlock_cipher_den",
  },
  {
    id: "cryo_bay:act_tier_2",
    roomZipDir: "cryo_bay",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_cryo_bay_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "cryo_bay:battlepass_winter",
    roomZipDir: "cryo_bay",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_cryo_bay_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "cryo_bay:companion_trust",
    roomZipDir: "cryo_bay",
    axisKey: "companion",
    axisValue: "trust",
    flagTrigger: "storyhook_cryo_bay_companion_trust",
    variantKey: "companion_trust",
  },
  {
    id: "cryo_bay:epoch_shadowtongue",
    roomZipDir: "cryo_bay",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_cryo_bay_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "cryo_bay:governance_quarantine",
    roomZipDir: "cryo_bay",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_cryo_bay_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "cryo_bay:lore_ark_origins",
    roomZipDir: "cryo_bay",
    axisKey: "lore",
    axisValue: "ark_origins",
    flagTrigger: "storyhook_cryo_bay_lore_ark_origins",
    variantKey: "lore_ark_origins",
  },
  {
    id: "cryo_bay:morality_dark",
    roomZipDir: "cryo_bay",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_cryo_bay_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "cryo_bay:season_closing",
    roomZipDir: "cryo_bay",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_cryo_bay_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "cryo_bay:system_unlock_crew",
    roomZipDir: "cryo_bay",
    axisKey: "system",
    axisValue: "unlock_crew",
    flagTrigger: "storyhook_cryo_bay_system_unlock_crew",
    variantKey: "system_unlock_crew",
  },
  {
    id: "cryo_bay:trust_elara_luminous",
    roomZipDir: "cryo_bay",
    axisKey: "trust",
    axisValue: "elara_luminous",
    flagTrigger: "storyhook_cryo_bay_trust_elara_luminous",
    variantKey: "trust_elara_luminous",
  },
  {
    id: "daily_resource_board:act_tier2",
    roomZipDir: "daily_resource_board",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_daily_resource_board_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "daily_resource_board:act_tier5",
    roomZipDir: "daily_resource_board",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_daily_resource_board_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "daily_resource_board:act_tier7",
    roomZipDir: "daily_resource_board",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_daily_resource_board_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "daily_resource_board:irl_winter",
    roomZipDir: "daily_resource_board",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_daily_resource_board_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "daily_resource_board:morality_dark",
    roomZipDir: "daily_resource_board",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_daily_resource_board_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "daily_resource_board:season_interregnum",
    roomZipDir: "daily_resource_board",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_daily_resource_board_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "defense_command_center:act_tier2",
    roomZipDir: "defense_command_center",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_defense_command_center_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "defense_command_center:act_tier5",
    roomZipDir: "defense_command_center",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_defense_command_center_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "defense_command_center:act_tier7",
    roomZipDir: "defense_command_center",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_defense_command_center_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "defense_command_center:irl_winter",
    roomZipDir: "defense_command_center",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_defense_command_center_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "defense_command_center:morality_dark",
    roomZipDir: "defense_command_center",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_defense_command_center_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "defense_command_center:season_interregnum",
    roomZipDir: "defense_command_center",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_defense_command_center_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "dreamers_sanctum:battlepass_winter",
    roomZipDir: "dreamers_sanctum",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_dreamers_sanctum_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "dreamers_sanctum:epoch_shadowtongue",
    roomZipDir: "dreamers_sanctum",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_dreamers_sanctum_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "dreamers_sanctum:governance_blessing",
    roomZipDir: "dreamers_sanctum",
    axisKey: "governance",
    axisValue: "blessing",
    flagTrigger: "storyhook_dreamers_sanctum_governance_blessing",
    variantKey: "governance_blessing",
  },
  {
    id: "dreamers_sanctum:investigation_tier",
    roomZipDir: "dreamers_sanctum",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_dreamers_sanctum_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "dreamers_sanctum:morality_dark",
    roomZipDir: "dreamers_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_dreamers_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "eidolon_sanctum:act_tier2",
    roomZipDir: "eidolon_sanctum",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_eidolon_sanctum_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "eidolon_sanctum:act_tier5",
    roomZipDir: "eidolon_sanctum",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_eidolon_sanctum_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "eidolon_sanctum:morality_dark",
    roomZipDir: "eidolon_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_eidolon_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "elemental_nexus:battlepass_winter",
    roomZipDir: "elemental_nexus",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_elemental_nexus_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "elemental_nexus:epoch_shadowtongue",
    roomZipDir: "elemental_nexus",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_elemental_nexus_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "elemental_nexus:governance_blessing",
    roomZipDir: "elemental_nexus",
    axisKey: "governance",
    axisValue: "blessing",
    flagTrigger: "storyhook_elemental_nexus_governance_blessing",
    variantKey: "governance_blessing",
  },
  {
    id: "elemental_nexus:investigation_tier",
    roomZipDir: "elemental_nexus",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_elemental_nexus_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "elemental_nexus:morality_dark",
    roomZipDir: "elemental_nexus",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_elemental_nexus_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "engineering_bay:act_tier_3",
    roomZipDir: "engineering_bay",
    axisKey: "act",
    axisValue: "tier_3",
    flagTrigger: "storyhook_engineering_bay_act_tier_3",
    variantKey: "act_tier_3",
  },
  {
    id: "engineering_bay:battlepass_winter",
    roomZipDir: "engineering_bay",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_engineering_bay_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "engineering_bay:epoch_shadowtongue",
    roomZipDir: "engineering_bay",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_engineering_bay_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "engineering_bay:governance_quarantine",
    roomZipDir: "engineering_bay",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_engineering_bay_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "engineering_bay:investigation_tier",
    roomZipDir: "engineering_bay",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_engineering_bay_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "engineering_bay:lore_shadowtongue_complete",
    roomZipDir: "engineering_bay",
    axisKey: "lore",
    axisValue: "shadowtongue_complete",
    flagTrigger: "storyhook_engineering_bay_lore_shadowtongue_complete",
    variantKey: "lore_shadowtongue_complete",
  },
  {
    id: "engineering_bay:morality_dark",
    roomZipDir: "engineering_bay",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_engineering_bay_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "engineering_bay:trust_shadowtongue",
    roomZipDir: "engineering_bay",
    axisKey: "trust",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_engineering_bay_trust_shadowtongue",
    variantKey: "trust_shadowtongue",
  },
  {
    id: "engineering_bay:unlock_chaos",
    roomZipDir: "engineering_bay",
    axisKey: "unlock",
    axisValue: "chaos",
    flagTrigger: "storyhook_engineering_bay_unlock_chaos",
    variantKey: "unlock_chaos",
  },
  {
    id: "engineering_bay:unlock_crafting",
    roomZipDir: "engineering_bay",
    axisKey: "unlock",
    axisValue: "crafting",
    flagTrigger: "storyhook_engineering_bay_unlock_crafting",
    variantKey: "unlock_crafting",
  },
  {
    id: "engineering_core:battlepass_winter",
    roomZipDir: "engineering_core",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_engineering_core_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "engineering_core:epoch_shadowtongue",
    roomZipDir: "engineering_core",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_engineering_core_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "engineering_core:governance_combat",
    roomZipDir: "engineering_core",
    axisKey: "governance",
    axisValue: "combat",
    flagTrigger: "storyhook_engineering_core_governance_combat",
    variantKey: "governance_combat",
  },
  {
    id: "engineering_core:governance_quarantine",
    roomZipDir: "engineering_core",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_engineering_core_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "engineering_core:investigation_tier",
    roomZipDir: "engineering_core",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_engineering_core_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "engineering_core:morality_dark",
    roomZipDir: "engineering_core",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_engineering_core_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "epoch_witness_conclave:act_tier2",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_epoch_witness_conclave_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "epoch_witness_conclave:act_tier5",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_epoch_witness_conclave_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "epoch_witness_conclave:act_tier7",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_epoch_witness_conclave_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "epoch_witness_conclave:irl_winter",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_epoch_witness_conclave_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "epoch_witness_conclave:morality_dark",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_epoch_witness_conclave_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "epoch_witness_conclave:season_interregnum",
    roomZipDir: "epoch_witness_conclave",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_epoch_witness_conclave_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "faction_succession_monument:act_tier2",
    roomZipDir: "faction_succession_monument",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_faction_succession_monument_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "faction_succession_monument:act_tier5",
    roomZipDir: "faction_succession_monument",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_faction_succession_monument_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "faction_succession_monument:act_tier7",
    roomZipDir: "faction_succession_monument",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_faction_succession_monument_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "faction_succession_monument:irl_winter",
    roomZipDir: "faction_succession_monument",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_faction_succession_monument_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "faction_succession_monument:morality_dark",
    roomZipDir: "faction_succession_monument",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_faction_succession_monument_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "faction_succession_monument:season_interregnum",
    roomZipDir: "faction_succession_monument",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_faction_succession_monument_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "forge_workshop:act_tier_3",
    roomZipDir: "forge_workshop",
    axisKey: "act",
    axisValue: "tier_3",
    flagTrigger: "storyhook_forge_workshop_act_tier_3",
    variantKey: "act_tier_3",
  },
  {
    id: "forge_workshop:act_tier_7",
    roomZipDir: "forge_workshop",
    axisKey: "act",
    axisValue: "tier_7",
    flagTrigger: "storyhook_forge_workshop_act_tier_7",
    variantKey: "act_tier_7",
  },
  {
    id: "forge_workshop:battlepass_winter",
    roomZipDir: "forge_workshop",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_forge_workshop_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "forge_workshop:epoch_shadowtongue",
    roomZipDir: "forge_workshop",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_forge_workshop_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "forge_workshop:governance_quarantine",
    roomZipDir: "forge_workshop",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_forge_workshop_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "forge_workshop:investigation_tier",
    roomZipDir: "forge_workshop",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_forge_workshop_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "forge_workshop:morality_dark",
    roomZipDir: "forge_workshop",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_forge_workshop_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "forge_workshop:unlock_apprentice",
    roomZipDir: "forge_workshop",
    axisKey: "unlock",
    axisValue: "apprentice",
    flagTrigger: "storyhook_forge_workshop_unlock_apprentice",
    variantKey: "unlock_apprentice",
  },
  {
    id: "forge_workshop:unlock_mastered",
    roomZipDir: "forge_workshop",
    axisKey: "unlock",
    axisValue: "mastered",
    flagTrigger: "storyhook_forge_workshop_unlock_mastered",
    variantKey: "unlock_mastered",
  },
  {
    id: "game_masters_sanctum:act_tier2",
    roomZipDir: "game_masters_sanctum",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_game_masters_sanctum_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "game_masters_sanctum:act_tier5",
    roomZipDir: "game_masters_sanctum",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_game_masters_sanctum_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "game_masters_sanctum:act_tier7",
    roomZipDir: "game_masters_sanctum",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_game_masters_sanctum_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "game_masters_sanctum:irl_winter",
    roomZipDir: "game_masters_sanctum",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_game_masters_sanctum_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "game_masters_sanctum:morality_dark",
    roomZipDir: "game_masters_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_game_masters_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "game_masters_sanctum:season_interregnum",
    roomZipDir: "game_masters_sanctum",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_game_masters_sanctum_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "governance_chamber:act_tier2",
    roomZipDir: "governance_chamber",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_governance_chamber_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "governance_chamber:act_tier5",
    roomZipDir: "governance_chamber",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_governance_chamber_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "governance_chamber:act_tier7",
    roomZipDir: "governance_chamber",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_governance_chamber_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "governance_chamber:irl_winter",
    roomZipDir: "governance_chamber",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_governance_chamber_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "governance_chamber:morality_dark",
    roomZipDir: "governance_chamber",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_governance_chamber_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "governance_chamber:season_interregnum",
    roomZipDir: "governance_chamber",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_governance_chamber_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "grand_masters_sanctum:act_tier2",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_grand_masters_sanctum_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "grand_masters_sanctum:act_tier5",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_grand_masters_sanctum_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "grand_masters_sanctum:act_tier7",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_grand_masters_sanctum_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "grand_masters_sanctum:irl_winter",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_grand_masters_sanctum_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "grand_masters_sanctum:morality_dark",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_grand_masters_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "grand_masters_sanctum:season_interregnum",
    roomZipDir: "grand_masters_sanctum",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_grand_masters_sanctum_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "guild_sanctum:battlepass_winter",
    roomZipDir: "guild_sanctum",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_guild_sanctum_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "guild_sanctum:epoch_shadowtongue",
    roomZipDir: "guild_sanctum",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_guild_sanctum_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "guild_sanctum:event_succession",
    roomZipDir: "guild_sanctum",
    axisKey: "event",
    axisValue: "succession",
    flagTrigger: "storyhook_guild_sanctum_event_succession",
    variantKey: "event_succession",
  },
  {
    id: "guild_sanctum:governance_treasury",
    roomZipDir: "guild_sanctum",
    axisKey: "governance",
    axisValue: "treasury",
    flagTrigger: "storyhook_guild_sanctum_governance_treasury",
    variantKey: "governance_treasury",
  },
  {
    id: "guild_sanctum:investigation_tier",
    roomZipDir: "guild_sanctum",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_guild_sanctum_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "guild_sanctum:morality_dark",
    roomZipDir: "guild_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_guild_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "guild_sanctum:season_closing",
    roomZipDir: "guild_sanctum",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_guild_sanctum_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "guild_sanctum:season_interregnum",
    roomZipDir: "guild_sanctum",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_guild_sanctum_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "guild_sanctum:unlock_tier_2",
    roomZipDir: "guild_sanctum",
    axisKey: "unlock",
    axisValue: "tier_2",
    flagTrigger: "storyhook_guild_sanctum_unlock_tier_2",
    variantKey: "unlock_tier_2",
  },
  {
    id: "guild_sanctum:unlock_tier_5",
    roomZipDir: "guild_sanctum",
    axisKey: "unlock",
    axisValue: "tier_5",
    flagTrigger: "storyhook_guild_sanctum_unlock_tier_5",
    variantKey: "unlock_tier_5",
  },
  {
    id: "hierarchy_throne:battlepass_winter",
    roomZipDir: "hierarchy_throne",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_hierarchy_throne_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "hierarchy_throne:epoch_shadowtongue",
    roomZipDir: "hierarchy_throne",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_hierarchy_throne_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "hierarchy_throne:governance_blessing",
    roomZipDir: "hierarchy_throne",
    axisKey: "governance",
    axisValue: "blessing",
    flagTrigger: "storyhook_hierarchy_throne_governance_blessing",
    variantKey: "governance_blessing",
  },
  {
    id: "hierarchy_throne:hellbox_active",
    roomZipDir: "hierarchy_throne",
    axisKey: "hellbox",
    axisValue: "active",
    flagTrigger: "storyhook_hierarchy_throne_hellbox_active",
    variantKey: "hellbox_active",
  },
  {
    id: "hierarchy_throne:investigation_tier",
    roomZipDir: "hierarchy_throne",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_hierarchy_throne_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "hierarchy_throne:morality_dark",
    roomZipDir: "hierarchy_throne",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_hierarchy_throne_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "medical_bay:act_tier_2",
    roomZipDir: "medical_bay",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_medical_bay_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "medical_bay:battlepass_winter",
    roomZipDir: "medical_bay",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_medical_bay_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "medical_bay:companion_trust",
    roomZipDir: "medical_bay",
    axisKey: "companion",
    axisValue: "trust",
    flagTrigger: "storyhook_medical_bay_companion_trust",
    variantKey: "companion_trust",
  },
  {
    id: "medical_bay:epoch_shadowtongue",
    roomZipDir: "medical_bay",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_medical_bay_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "medical_bay:governance_quarantine",
    roomZipDir: "medical_bay",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_medical_bay_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "medical_bay:investigation_device_awakened",
    roomZipDir: "medical_bay",
    axisKey: "investigation",
    axisValue: "device_awakened",
    flagTrigger: "storyhook_medical_bay_investigation_device_awakened",
    variantKey: "investigation_device_awakened",
  },
  {
    id: "medical_bay:lore_research_vessel",
    roomZipDir: "medical_bay",
    axisKey: "lore",
    axisValue: "research_vessel",
    flagTrigger: "storyhook_medical_bay_lore_research_vessel",
    variantKey: "lore_research_vessel",
  },
  {
    id: "medical_bay:morality_dark",
    roomZipDir: "medical_bay",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_medical_bay_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "medical_bay:season_closing",
    roomZipDir: "medical_bay",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_medical_bay_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "medical_bay:trust_vex_confidant",
    roomZipDir: "medical_bay",
    axisKey: "trust",
    axisValue: "vex_confidant",
    flagTrigger: "storyhook_medical_bay_trust_vex_confidant",
    variantKey: "trust_vex_confidant",
  },
  {
    id: "medical_bay:unlock_hellbox",
    roomZipDir: "medical_bay",
    axisKey: "unlock",
    axisValue: "hellbox",
    flagTrigger: "storyhook_medical_bay_unlock_hellbox",
    variantKey: "unlock_hellbox",
  },
  {
    id: "meditation_garden:battlepass_winter",
    roomZipDir: "meditation_garden",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_meditation_garden_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "meditation_garden:epoch_shadowtongue",
    roomZipDir: "meditation_garden",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_meditation_garden_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "meditation_garden:governance_harmony",
    roomZipDir: "meditation_garden",
    axisKey: "governance",
    axisValue: "harmony",
    flagTrigger: "storyhook_meditation_garden_governance_harmony",
    variantKey: "governance_harmony",
  },
  {
    id: "meditation_garden:investigation_tier",
    roomZipDir: "meditation_garden",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_meditation_garden_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "meditation_garden:morality_dark",
    roomZipDir: "meditation_garden",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_meditation_garden_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "memorial_corridor:battlepass_winter",
    roomZipDir: "memorial_corridor",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_memorial_corridor_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "memorial_corridor:epoch_shadowtongue",
    roomZipDir: "memorial_corridor",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_memorial_corridor_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "memorial_corridor:governance_memorial",
    roomZipDir: "memorial_corridor",
    axisKey: "governance",
    axisValue: "memorial",
    flagTrigger: "storyhook_memorial_corridor_governance_memorial",
    variantKey: "governance_memorial",
  },
  {
    id: "memorial_corridor:investigation_tier",
    roomZipDir: "memorial_corridor",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_memorial_corridor_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "memorial_corridor:morality_dark",
    roomZipDir: "memorial_corridor",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_memorial_corridor_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "observation_deck:act_tier_2",
    roomZipDir: "observation_deck",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_observation_deck_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "observation_deck:battlepass_winter",
    roomZipDir: "observation_deck",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_observation_deck_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "observation_deck:epoch_shadowtongue",
    roomZipDir: "observation_deck",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_observation_deck_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "observation_deck:governance_classified",
    roomZipDir: "observation_deck",
    axisKey: "governance",
    axisValue: "classified",
    flagTrigger: "storyhook_observation_deck_governance_classified",
    variantKey: "governance_classified",
  },
  {
    id: "observation_deck:investigation_tier",
    roomZipDir: "observation_deck",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_observation_deck_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "observation_deck:lore_architect",
    roomZipDir: "observation_deck",
    axisKey: "lore",
    axisValue: "architect",
    flagTrigger: "storyhook_observation_deck_lore_architect",
    variantKey: "lore_architect",
  },
  {
    id: "observation_deck:morality_dark",
    roomZipDir: "observation_deck",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_observation_deck_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "observation_deck:season_interregnum",
    roomZipDir: "observation_deck",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_observation_deck_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "observation_deck:trust_eidolon_resonant",
    roomZipDir: "observation_deck",
    axisKey: "trust",
    axisValue: "eidolon_resonant",
    flagTrigger: "storyhook_observation_deck_trust_eidolon_resonant",
    variantKey: "trust_eidolon_resonant",
  },
  {
    id: "observation_deck:unlock_memorial",
    roomZipDir: "observation_deck",
    axisKey: "unlock",
    axisValue: "memorial",
    flagTrigger: "storyhook_observation_deck_unlock_memorial",
    variantKey: "unlock_memorial",
  },
  {
    id: "oracle_annual_sanctum:act_tier2",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_oracle_annual_sanctum_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "oracle_annual_sanctum:act_tier5",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_oracle_annual_sanctum_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "oracle_annual_sanctum:act_tier7",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_oracle_annual_sanctum_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "oracle_annual_sanctum:irl_winter",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_oracle_annual_sanctum_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "oracle_annual_sanctum:morality_dark",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_oracle_annual_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "oracle_annual_sanctum:season_interregnum",
    roomZipDir: "oracle_annual_sanctum",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_oracle_annual_sanctum_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "oracle_sanctum:battlepass_winter",
    roomZipDir: "oracle_sanctum",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_oracle_sanctum_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "oracle_sanctum:epoch_shadowtongue",
    roomZipDir: "oracle_sanctum",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_oracle_sanctum_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "oracle_sanctum:governance_blessing",
    roomZipDir: "oracle_sanctum",
    axisKey: "governance",
    axisValue: "blessing",
    flagTrigger: "storyhook_oracle_sanctum_governance_blessing",
    variantKey: "governance_blessing",
  },
  {
    id: "oracle_sanctum:investigation_tier",
    roomZipDir: "oracle_sanctum",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_oracle_sanctum_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "oracle_sanctum:morality_dark",
    roomZipDir: "oracle_sanctum",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_oracle_sanctum_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "order_tribunal:act_tier2",
    roomZipDir: "order_tribunal",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_order_tribunal_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "order_tribunal:act_tier5",
    roomZipDir: "order_tribunal",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_order_tribunal_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "order_tribunal:act_tier7",
    roomZipDir: "order_tribunal",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_order_tribunal_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "order_tribunal:irl_winter",
    roomZipDir: "order_tribunal",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_order_tribunal_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "order_tribunal:morality_dark",
    roomZipDir: "order_tribunal",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_order_tribunal_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "order_tribunal:season_interregnum",
    roomZipDir: "order_tribunal",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_order_tribunal_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "pedagogy_hall:act_tier2",
    roomZipDir: "pedagogy_hall",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_pedagogy_hall_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "pedagogy_hall:act_tier5",
    roomZipDir: "pedagogy_hall",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_pedagogy_hall_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "pedagogy_hall:act_tier7",
    roomZipDir: "pedagogy_hall",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_pedagogy_hall_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "pedagogy_hall:irl_winter",
    roomZipDir: "pedagogy_hall",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_pedagogy_hall_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "pedagogy_hall:morality_dark",
    roomZipDir: "pedagogy_hall",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_pedagogy_hall_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "pedagogy_hall:season_interregnum",
    roomZipDir: "pedagogy_hall",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_pedagogy_hall_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "pet_garden:act_tier2",
    roomZipDir: "pet_garden",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_pet_garden_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "pet_garden:act_tier5",
    roomZipDir: "pet_garden",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_pet_garden_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "pet_garden:act_tier7",
    roomZipDir: "pet_garden",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_pet_garden_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "pet_garden:irl_winter",
    roomZipDir: "pet_garden",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_pet_garden_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "pet_garden:morality_dark",
    roomZipDir: "pet_garden",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_pet_garden_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "pet_garden:season_interregnum",
    roomZipDir: "pet_garden",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_pet_garden_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "pet_medical_annex:act_tier2",
    roomZipDir: "pet_medical_annex",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_pet_medical_annex_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "pet_medical_annex:act_tier5",
    roomZipDir: "pet_medical_annex",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_pet_medical_annex_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "pet_medical_annex:act_tier7",
    roomZipDir: "pet_medical_annex",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_pet_medical_annex_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "pet_medical_annex:irl_winter",
    roomZipDir: "pet_medical_annex",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_pet_medical_annex_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "pet_medical_annex:morality_dark",
    roomZipDir: "pet_medical_annex",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_pet_medical_annex_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "pet_medical_annex:season_interregnum",
    roomZipDir: "pet_medical_annex",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_pet_medical_annex_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "puzzle_study_chamber:act_tier2",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_puzzle_study_chamber_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "puzzle_study_chamber:act_tier5",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_puzzle_study_chamber_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "puzzle_study_chamber:act_tier7",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_puzzle_study_chamber_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "puzzle_study_chamber:irl_winter",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_puzzle_study_chamber_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "puzzle_study_chamber:morality_dark",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_puzzle_study_chamber_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "puzzle_study_chamber:season_interregnum",
    roomZipDir: "puzzle_study_chamber",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_puzzle_study_chamber_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "quantum_lab:battlepass_winter",
    roomZipDir: "quantum_lab",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_quantum_lab_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "quantum_lab:epoch_shadowtongue",
    roomZipDir: "quantum_lab",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_quantum_lab_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "quantum_lab:governance_stabilized",
    roomZipDir: "quantum_lab",
    axisKey: "governance",
    axisValue: "stabilized",
    flagTrigger: "storyhook_quantum_lab_governance_stabilized",
    variantKey: "governance_stabilized",
  },
  {
    id: "quantum_lab:investigation_tier",
    roomZipDir: "quantum_lab",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_quantum_lab_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "quantum_lab:morality_dark",
    roomZipDir: "quantum_lab",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_quantum_lab_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "reactor_control:act_tier2",
    roomZipDir: "reactor_control",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_reactor_control_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "reactor_control:act_tier5",
    roomZipDir: "reactor_control",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_reactor_control_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "reactor_control:act_tier7",
    roomZipDir: "reactor_control",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_reactor_control_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "reactor_control:irl_winter",
    roomZipDir: "reactor_control",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_reactor_control_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "reactor_control:morality_dark",
    roomZipDir: "reactor_control",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_reactor_control_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "reactor_control:season_interregnum",
    roomZipDir: "reactor_control",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_reactor_control_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "shadow_vault:battlepass_winter",
    roomZipDir: "shadow_vault",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_shadow_vault_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "shadow_vault:epoch_shadowtongue",
    roomZipDir: "shadow_vault",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_shadow_vault_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "shadow_vault:governance_quarantine",
    roomZipDir: "shadow_vault",
    axisKey: "governance",
    axisValue: "quarantine",
    flagTrigger: "storyhook_shadow_vault_governance_quarantine",
    variantKey: "governance_quarantine",
  },
  {
    id: "shadow_vault:investigation_tier",
    roomZipDir: "shadow_vault",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_shadow_vault_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "shadow_vault:morality_dark",
    roomZipDir: "shadow_vault",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_shadow_vault_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "social_hub:battlepass_winter",
    roomZipDir: "social_hub",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_social_hub_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "social_hub:epoch_shadowtongue",
    roomZipDir: "social_hub",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_social_hub_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "social_hub:event_witnesses",
    roomZipDir: "social_hub",
    axisKey: "event",
    axisValue: "witnesses",
    flagTrigger: "storyhook_social_hub_event_witnesses",
    variantKey: "event_witnesses",
  },
  {
    id: "social_hub:governance_morale",
    roomZipDir: "social_hub",
    axisKey: "governance",
    axisValue: "morale",
    flagTrigger: "storyhook_social_hub_governance_morale",
    variantKey: "governance_morale",
  },
  {
    id: "social_hub:investigation_tier",
    roomZipDir: "social_hub",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_social_hub_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "social_hub:morality_dark",
    roomZipDir: "social_hub",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_social_hub_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "social_hub:season_closing",
    roomZipDir: "social_hub",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_social_hub_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "social_hub:season_interregnum",
    roomZipDir: "social_hub",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_social_hub_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "social_hub:trust_elara",
    roomZipDir: "social_hub",
    axisKey: "trust",
    axisValue: "elara",
    flagTrigger: "storyhook_social_hub_trust_elara",
    variantKey: "trust_elara",
  },
  {
    id: "social_hub:trust_human",
    roomZipDir: "social_hub",
    axisKey: "trust",
    axisValue: "human",
    flagTrigger: "storyhook_social_hub_trust_human",
    variantKey: "trust_human",
  },
  {
    id: "station_dock:battlepass_winter",
    roomZipDir: "station_dock",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_station_dock_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "station_dock:epoch_shadowtongue",
    roomZipDir: "station_dock",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_station_dock_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "station_dock:event_succession",
    roomZipDir: "station_dock",
    axisKey: "event",
    axisValue: "succession",
    flagTrigger: "storyhook_station_dock_event_succession",
    variantKey: "event_succession",
  },
  {
    id: "station_dock:investigation_tier",
    roomZipDir: "station_dock",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_station_dock_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "station_dock:morality_dark",
    roomZipDir: "station_dock",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_station_dock_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "station_dock:season_closing",
    roomZipDir: "station_dock",
    axisKey: "season",
    axisValue: "closing",
    flagTrigger: "storyhook_station_dock_season_closing",
    variantKey: "season_closing",
  },
  {
    id: "station_dock:season_interregnum",
    roomZipDir: "station_dock",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_station_dock_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "station_dock:unlock_trade",
    roomZipDir: "station_dock",
    axisKey: "unlock",
    axisValue: "trade",
    flagTrigger: "storyhook_station_dock_unlock_trade",
    variantKey: "unlock_trade",
  },
  {
    id: "station_dock:unlock_warroom",
    roomZipDir: "station_dock",
    axisKey: "unlock",
    axisValue: "warroom",
    flagTrigger: "storyhook_station_dock_unlock_warroom",
    variantKey: "unlock_warroom",
  },
  {
    id: "synthesis_chamber:battlepass_winter",
    roomZipDir: "synthesis_chamber",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_synthesis_chamber_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "synthesis_chamber:epoch_shadowtongue",
    roomZipDir: "synthesis_chamber",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_synthesis_chamber_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "synthesis_chamber:governance_boost",
    roomZipDir: "synthesis_chamber",
    axisKey: "governance",
    axisValue: "boost",
    flagTrigger: "storyhook_synthesis_chamber_governance_boost",
    variantKey: "governance_boost",
  },
  {
    id: "synthesis_chamber:investigation_tier",
    roomZipDir: "synthesis_chamber",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_synthesis_chamber_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "synthesis_chamber:morality_dark",
    roomZipDir: "synthesis_chamber",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_synthesis_chamber_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "tower_assembly_bay:act_tier2",
    roomZipDir: "tower_assembly_bay",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_tower_assembly_bay_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "tower_assembly_bay:act_tier5",
    roomZipDir: "tower_assembly_bay",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_tower_assembly_bay_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "tower_assembly_bay:act_tier7",
    roomZipDir: "tower_assembly_bay",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_tower_assembly_bay_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "tower_assembly_bay:irl_winter",
    roomZipDir: "tower_assembly_bay",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_tower_assembly_bay_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "tower_assembly_bay:morality_dark",
    roomZipDir: "tower_assembly_bay",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_tower_assembly_bay_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "tower_assembly_bay:season_interregnum",
    roomZipDir: "tower_assembly_bay",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_tower_assembly_bay_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "trade_hub:act_tier2",
    roomZipDir: "trade_hub",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_trade_hub_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "trade_hub:act_tier5",
    roomZipDir: "trade_hub",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_trade_hub_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "trade_hub:act_tier7",
    roomZipDir: "trade_hub",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_trade_hub_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "trade_hub:irl_winter",
    roomZipDir: "trade_hub",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_trade_hub_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "trade_hub:morality_dark",
    roomZipDir: "trade_hub",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_trade_hub_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "trade_hub:season_interregnum",
    roomZipDir: "trade_hub",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_trade_hub_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "trophy_armory:act_tier2",
    roomZipDir: "trophy_armory",
    axisKey: "act",
    axisValue: "tier2",
    flagTrigger: "storyhook_trophy_armory_act_tier2",
    variantKey: "act_tier2",
  },
  {
    id: "trophy_armory:act_tier5",
    roomZipDir: "trophy_armory",
    axisKey: "act",
    axisValue: "tier5",
    flagTrigger: "storyhook_trophy_armory_act_tier5",
    variantKey: "act_tier5",
  },
  {
    id: "trophy_armory:act_tier7",
    roomZipDir: "trophy_armory",
    axisKey: "act",
    axisValue: "tier7",
    flagTrigger: "storyhook_trophy_armory_act_tier7",
    variantKey: "act_tier7",
  },
  {
    id: "trophy_armory:irl_winter",
    roomZipDir: "trophy_armory",
    axisKey: "irl",
    axisValue: "winter",
    flagTrigger: "storyhook_trophy_armory_irl_winter",
    variantKey: "irl_winter",
  },
  {
    id: "trophy_armory:morality_dark",
    roomZipDir: "trophy_armory",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_trophy_armory_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "trophy_armory:season_interregnum",
    roomZipDir: "trophy_armory",
    axisKey: "season",
    axisValue: "interregnum",
    flagTrigger: "storyhook_trophy_armory_season_interregnum",
    variantKey: "season_interregnum",
  },
  {
    id: "trophy_room:act_tier_2",
    roomZipDir: "trophy_room",
    axisKey: "act",
    axisValue: "tier_2",
    flagTrigger: "storyhook_trophy_room_act_tier_2",
    variantKey: "act_tier_2",
  },
  {
    id: "trophy_room:act_tier_5",
    roomZipDir: "trophy_room",
    axisKey: "act",
    axisValue: "tier_5",
    flagTrigger: "storyhook_trophy_room_act_tier_5",
    variantKey: "act_tier_5",
  },
  {
    id: "trophy_room:act_tier_7",
    roomZipDir: "trophy_room",
    axisKey: "act",
    axisValue: "tier_7",
    flagTrigger: "storyhook_trophy_room_act_tier_7",
    variantKey: "act_tier_7",
  },
  {
    id: "trophy_room:battlepass_winter",
    roomZipDir: "trophy_room",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_trophy_room_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "trophy_room:epoch_shadowtongue",
    roomZipDir: "trophy_room",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_trophy_room_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "trophy_room:governance_prestige",
    roomZipDir: "trophy_room",
    axisKey: "governance",
    axisValue: "prestige",
    flagTrigger: "storyhook_trophy_room_governance_prestige",
    variantKey: "governance_prestige",
  },
  {
    id: "trophy_room:investigation_tier",
    roomZipDir: "trophy_room",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_trophy_room_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "trophy_room:morality_dark",
    roomZipDir: "trophy_room",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_trophy_room_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "trophy_room:unlock_battlepass_50",
    roomZipDir: "trophy_room",
    axisKey: "unlock",
    axisValue: "battlepass_50",
    flagTrigger: "storyhook_trophy_room_unlock_battlepass_50",
    variantKey: "unlock_battlepass_50",
  },
  {
    id: "trophy_room:unlock_prestige",
    roomZipDir: "trophy_room",
    axisKey: "unlock",
    axisValue: "prestige",
    flagTrigger: "storyhook_trophy_room_unlock_prestige",
    variantKey: "unlock_prestige",
  },
  {
    id: "war_room:battlepass_winter",
    roomZipDir: "war_room",
    axisKey: "battlepass",
    axisValue: "winter",
    flagTrigger: "storyhook_war_room_battlepass_winter",
    variantKey: "battlepass_winter",
  },
  {
    id: "war_room:epoch_shadowtongue",
    roomZipDir: "war_room",
    axisKey: "epoch",
    axisValue: "shadowtongue",
    flagTrigger: "storyhook_war_room_epoch_shadowtongue",
    variantKey: "epoch_shadowtongue",
  },
  {
    id: "war_room:investigation_tier",
    roomZipDir: "war_room",
    axisKey: "investigation",
    axisValue: "tier",
    flagTrigger: "storyhook_war_room_investigation_tier",
    variantKey: "investigation_tier",
  },
  {
    id: "war_room:morality_dark",
    roomZipDir: "war_room",
    axisKey: "morality",
    axisValue: "dark",
    flagTrigger: "storyhook_war_room_morality_dark",
    variantKey: "morality_dark",
  },
  {
    id: "war_room:tournament_finals",
    roomZipDir: "war_room",
    axisKey: "tournament",
    axisValue: "finals",
    flagTrigger: "storyhook_war_room_tournament_finals",
    variantKey: "tournament_finals",
  },
] as const;

// Total hooks: 362
