/* ═══════════════════════════════════════════════════════
   CHARACTER-SPECIFIC SPECIAL MOVES
   Every fighter has unique SP1 / SP2 / SP3 attacks
   based on their lore abilities and personality.
   ═══════════════════════════════════════════════════════ */

export type SpecialMoveType = "projectile" | "rush" | "area" | "grab" | "counter" | "buff" | "drain";

export interface SpecialMove {
  name: string;
  type: SpecialMoveType;
  damage: number;           // base damage multiplier (1.0 = normal)
  /** Extra effects */
  stun?: number;            // bonus stun duration (seconds)
  heal?: number;            // % of damage dealt healed back
  armorBreak?: boolean;     // ignores block
  dot?: number;             // damage-over-time ticks (per second for 3s)
  speedBuff?: number;       // temporary speed multiplier
  defenseDebuff?: number;   // reduce opponent defense %
  /** Visual */
  color: string;            // primary effect color
  secondaryColor?: string;  // secondary particle color
  screenShake: number;      // 0-10 intensity
  particleCount: number;    // number of particles to spawn
  flashDuration: number;    // screen flash duration in ms
  /** Animation timing overrides (in 60fps frames) */
  startupFrames?: number;
  activeFrames?: number;
  recoveryFrames?: number;
  /** Description for UI */
  description: string;
}

export interface CharacterSpecials {
  sp1: SpecialMove;
  sp2: SpecialMove;
  sp3: SpecialMove;
}

/* ═══ SPECIAL MOVES DATABASE ═══ */
export const CHARACTER_SPECIALS: Record<string, CharacterSpecials> = {

  /* ─── STARTER ROSTER ─── */

  "architect": {
    sp1: {
      name: "CODE INJECTION",
      type: "projectile",
      damage: 1.2,
      description: "Fires a beam of corrupted code that disrupts the opponent's systems",
      color: "#ef4444",
      secondaryColor: "#ff6666",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 150,
    },
    sp2: {
      name: "NEURAL OVERLOAD",
      type: "area",
      damage: 1.8,
      stun: 0.5,
      description: "Overloads the opponent's neural pathways with raw data, stunning them",
      color: "#ef4444",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "GENESIS PROTOCOL",
      type: "area",
      damage: 2.8,
      stun: 1.0,
      armorBreak: true,
      defenseDebuff: 30,
      description: "Rewrites reality itself — the ultimate act of creation and destruction",
      color: "#ef4444",
      secondaryColor: "#fbbf24",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
      startupFrames: 18,
      activeFrames: 24,
      recoveryFrames: 22,
    },
  },

  "collector": {
    sp1: {
      name: "ARTIFACT STRIKE",
      type: "rush",
      damage: 1.1,
      description: "Hurls a forbidden artifact at the opponent",
      color: "#a855f7",
      secondaryColor: "#c084fc",
      screenShake: 2,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "COLLECTION BIND",
      type: "grab",
      damage: 1.5,
      stun: 0.8,
      description: "Binds the opponent with spectral chains from the Collection",
      color: "#a855f7",
      secondaryColor: "#e9d5ff",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "SOUL HARVEST",
      type: "drain",
      damage: 2.2,
      heal: 40,
      description: "Drains the opponent's essence, healing the Collector while dealing massive damage",
      color: "#a855f7",
      secondaryColor: "#22c55e",
      screenShake: 7,
      particleCount: 35,
      flashDuration: 450,
      startupFrames: 16,
      activeFrames: 22,
      recoveryFrames: 20,
    },
  },

  "enigma": {
    sp1: {
      name: "CIPHER STRIKE",
      type: "rush",
      damage: 1.3,
      speedBuff: 1.3,
      description: "A rapid encrypted attack that boosts movement speed",
      color: "#22d3ee",
      secondaryColor: "#67e8f9",
      screenShake: 3,
      particleCount: 14,
      flashDuration: 130,
    },
    sp2: {
      name: "PARADOX KICK",
      type: "counter",
      damage: 1.7,
      armorBreak: true,
      description: "A reality-bending kick that ignores all defenses",
      color: "#22d3ee",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 22,
      flashDuration: 220,
    },
    sp3: {
      name: "DISCHORDIAN LOGIC",
      type: "area",
      damage: 2.6,
      stun: 0.8,
      armorBreak: true,
      dot: 5,
      description: "Breaks the rules of combat with chaotic energy — reality itself glitches",
      color: "#22d3ee",
      secondaryColor: "#ec4899",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
      startupFrames: 14,
      activeFrames: 20,
      recoveryFrames: 18,
    },
  },

  "warlord": {
    sp1: {
      name: "WAR HAMMER",
      type: "rush",
      damage: 1.4,
      description: "A devastating hammer strike that sends the opponent flying",
      color: "#f59e0b",
      secondaryColor: "#fbbf24",
      screenShake: 4,
      particleCount: 12,
      flashDuration: 160,
    },
    sp2: {
      name: "TACTICAL STRIKE",
      type: "projectile",
      damage: 1.6,
      defenseDebuff: 20,
      description: "Deploys tactical nanobots that weaken the opponent's defenses",
      color: "#f59e0b",
      secondaryColor: "#78716c",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 200,
    },
    sp3: {
      name: "NANOBOT SWARM",
      type: "area",
      damage: 2.4,
      dot: 8,
      defenseDebuff: 40,
      description: "Unleashes a devastating swarm of nanobots that consume everything",
      color: "#f59e0b",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 50,
      flashDuration: 450,
      startupFrames: 16,
      activeFrames: 22,
      recoveryFrames: 24,
    },
  },

  "necromancer": {
    sp1: {
      name: "DEATH TOUCH",
      type: "grab",
      damage: 1.2,
      dot: 4,
      description: "A necrotic touch that poisons the opponent with death energy",
      color: "#10b981",
      secondaryColor: "#064e3b",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 140,
    },
    sp2: {
      name: "GRAVE PULL",
      type: "grab",
      damage: 1.6,
      stun: 0.6,
      description: "Spectral hands drag the opponent into the ground",
      color: "#10b981",
      secondaryColor: "#6b7280",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "RAISE DEAD",
      type: "area",
      damage: 2.5,
      dot: 10,
      heal: 25,
      description: "Summons undead code constructs that swarm and devour the opponent",
      color: "#10b981",
      secondaryColor: "#7c3aed",
      screenShake: 7,
      particleCount: 40,
      flashDuration: 500,
      startupFrames: 18,
      activeFrames: 26,
      recoveryFrames: 20,
    },
  },

  "meme": {
    sp1: {
      name: "MIRROR STRIKE",
      type: "counter",
      damage: 1.3,
      description: "Copies the opponent's stance and strikes with their own style",
      color: "#ec4899",
      secondaryColor: "#f9a8d4",
      screenShake: 2,
      particleCount: 12,
      flashDuration: 130,
    },
    sp2: {
      name: "PHASE SHIFT",
      type: "rush",
      damage: 1.5,
      speedBuff: 1.5,
      description: "Shifts between forms rapidly, striking from impossible angles",
      color: "#ec4899",
      secondaryColor: "#22d3ee",
      screenShake: 4,
      particleCount: 18,
      flashDuration: 200,
    },
    sp3: {
      name: "IDENTITY THEFT",
      type: "area",
      damage: 2.3,
      stun: 0.7,
      armorBreak: true,
      description: "Copies opponent's ultimate attack at double power — the ultimate deception",
      color: "#ec4899",
      secondaryColor: "#ffffff",
      screenShake: 8,
      particleCount: 35,
      flashDuration: 450,
      startupFrames: 12,
      activeFrames: 18,
      recoveryFrames: 16,
    },
  },

  "shadow-tongue": {
    sp1: {
      name: "SHADOW LASH",
      type: "projectile",
      damage: 1.2,
      description: "A tendril of shadow whips across the arena",
      color: "#6366f1",
      secondaryColor: "#312e81",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "DARK WHISPER",
      type: "area",
      damage: 1.5,
      stun: 0.6,
      defenseDebuff: 15,
      description: "A psychic whisper that confuses and weakens the opponent",
      color: "#6366f1",
      secondaryColor: "#a5b4fc",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "WHISPER OF MADNESS",
      type: "area",
      damage: 2.4,
      stun: 1.0,
      defenseDebuff: 30,
      dot: 6,
      description: "Drives the opponent to madness with dark truths — their mind shatters",
      color: "#6366f1",
      secondaryColor: "#ef4444",
      screenShake: 7,
      particleCount: 38,
      flashDuration: 500,
      startupFrames: 16,
      activeFrames: 24,
      recoveryFrames: 20,
    },
  },

  "watcher": {
    sp1: {
      name: "SURVEILLANCE BEAM",
      type: "projectile",
      damage: 1.1,
      description: "A focused beam from the All-Seeing Eye",
      color: "#14b8a6",
      secondaryColor: "#5eead4",
      screenShake: 2,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "DATA SPIKE",
      type: "rush",
      damage: 1.6,
      armorBreak: true,
      description: "Analyzes and exploits a weakness in the opponent's guard",
      color: "#14b8a6",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 220,
    },
    sp3: {
      name: "OMNISCIENT GAZE",
      type: "counter",
      damage: 2.5,
      stun: 0.8,
      armorBreak: true,
      defenseDebuff: 25,
      description: "Predicts every move and counters with perfect precision",
      color: "#14b8a6",
      secondaryColor: "#fbbf24",
      screenShake: 7,
      particleCount: 35,
      flashDuration: 450,
      startupFrames: 10,
      activeFrames: 16,
      recoveryFrames: 18,
    },
  },

  "game-master": {
    sp1: {
      name: "DICE ROLL",
      type: "projectile",
      damage: 1.3,
      description: "Throws enchanted dice that explode on contact",
      color: "#f97316",
      secondaryColor: "#fdba74",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "GAME OVER",
      type: "grab",
      damage: 1.7,
      stun: 0.7,
      description: "Traps the opponent in a game they cannot win",
      color: "#f97316",
      secondaryColor: "#ef4444",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "RULE CHANGE",
      type: "area",
      damage: 2.6,
      stun: 0.8,
      armorBreak: true,
      description: "Alters the rules of combat — gravity reverses, time distorts",
      color: "#f97316",
      secondaryColor: "#7c3aed",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
      startupFrames: 14,
      activeFrames: 22,
      recoveryFrames: 20,
    },
  },

  "authority": {
    sp1: {
      name: "JUDGMENT STRIKE",
      type: "rush",
      damage: 1.3,
      description: "A powerful gavel strike of absolute authority",
      color: "#eab308",
      secondaryColor: "#fef08a",
      screenShake: 4,
      particleCount: 12,
      flashDuration: 150,
    },
    sp2: {
      name: "LAW HAMMER",
      type: "rush",
      damage: 1.7,
      stun: 0.6,
      armorBreak: true,
      description: "Slams down the hammer of law, breaking all defenses",
      color: "#eab308",
      secondaryColor: "#ffffff",
      screenShake: 6,
      particleCount: 22,
      flashDuration: 280,
    },
    sp3: {
      name: "ABSOLUTE DECREE",
      type: "area",
      damage: 2.5,
      stun: 1.2,
      armorBreak: true,
      defenseDebuff: 35,
      description: "Issues an absolute decree — the opponent is judged and found wanting",
      color: "#eab308",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
      startupFrames: 18,
      activeFrames: 20,
      recoveryFrames: 24,
    },
  },

  "source": {
    sp1: {
      name: "DATA CORRUPT",
      type: "projectile",
      damage: 1.2,
      dot: 3,
      description: "Fires a corruption beam that degrades the opponent over time",
      color: "#dc2626",
      secondaryColor: "#7c3aed",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "SOURCE STRIKE",
      type: "rush",
      damage: 1.7,
      heal: 20,
      description: "Channels raw source energy, healing while dealing damage",
      color: "#dc2626",
      secondaryColor: "#22c55e",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "CORRUPTION WAVE",
      type: "area",
      damage: 2.7,
      dot: 12,
      heal: 30,
      defenseDebuff: 25,
      description: "Corrupts the opponent's code from within — a wave of pure entropy",
      color: "#dc2626",
      secondaryColor: "#000000",
      screenShake: 8,
      particleCount: 42,
      flashDuration: 500,
      startupFrames: 16,
      activeFrames: 24,
      recoveryFrames: 22,
    },
  },

  "jailer": {
    sp1: {
      name: "SHACKLE SLAM",
      type: "grab",
      damage: 1.1,
      stun: 0.4,
      description: "Slams the opponent with heavy prison chains",
      color: "#78716c",
      secondaryColor: "#a8a29e",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "PRISON BREAK",
      type: "rush",
      damage: 1.5,
      stun: 0.6,
      description: "Charges with the force of a prison riot",
      color: "#78716c",
      secondaryColor: "#f59e0b",
      screenShake: 5,
      particleCount: 16,
      flashDuration: 220,
    },
    sp3: {
      name: "CHAIN BIND",
      type: "grab",
      damage: 2.2,
      stun: 1.5,
      armorBreak: true,
      description: "Binds the opponent in unbreakable chains — total immobilization",
      color: "#78716c",
      secondaryColor: "#ef4444",
      screenShake: 7,
      particleCount: 35,
      flashDuration: 450,
      startupFrames: 14,
      activeFrames: 20,
      recoveryFrames: 18,
    },
  },

  "host": {
    sp1: {
      name: "CORRUPTION FIST",
      type: "rush",
      damage: 1.3,
      dot: 3,
      description: "A fist charged with corrupted potential energy",
      color: "#7c3aed",
      secondaryColor: "#a78bfa",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "DARK POTENTIAL",
      type: "area",
      damage: 1.6,
      heal: 15,
      description: "Unleashes dark potential energy that drains and heals",
      color: "#7c3aed",
      secondaryColor: "#22c55e",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 230,
    },
    sp3: {
      name: "PARASITIC SURGE",
      type: "drain",
      damage: 2.4,
      heal: 35,
      dot: 8,
      description: "Channels corrupted potential energy in a devastating parasitic blast",
      color: "#7c3aed",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 38,
      flashDuration: 500,
      startupFrames: 14,
      activeFrames: 22,
      recoveryFrames: 20,
    },
  },

  /* ─── UNLOCKABLE ROSTER — NE-YONS ─── */

  "dreamer": {
    sp1: {
      name: "VISION STRIKE",
      type: "projectile",
      damage: 1.2,
      stun: 0.3,
      description: "A blast of dream energy that disorients the opponent",
      color: "#818cf8",
      secondaryColor: "#c7d2fe",
      screenShake: 2,
      particleCount: 12,
      flashDuration: 130,
    },
    sp2: {
      name: "SLEEP WALK",
      type: "counter",
      damage: 1.5,
      stun: 0.8,
      description: "Puts the opponent in a waking dream, leaving them vulnerable",
      color: "#818cf8",
      secondaryColor: "#e0e7ff",
      screenShake: 4,
      particleCount: 18,
      flashDuration: 220,
    },
    sp3: {
      name: "DREAM WAVE",
      type: "area",
      damage: 2.3,
      stun: 1.0,
      defenseDebuff: 20,
      description: "Traps the opponent in a nightmare dimension — reality dissolves",
      color: "#818cf8",
      secondaryColor: "#7c3aed",
      screenShake: 7,
      particleCount: 38,
      flashDuration: 450,
    },
  },

  "judge": {
    sp1: {
      name: "GAVEL SLAM",
      type: "rush",
      damage: 1.3,
      description: "A swift strike with the gavel of cosmic justice",
      color: "#fbbf24",
      secondaryColor: "#fef08a",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "SENTENCE",
      type: "grab",
      damage: 1.6,
      stun: 0.7,
      armorBreak: true,
      description: "Passes sentence — the opponent is bound by cosmic law",
      color: "#fbbf24",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "FINAL VERDICT",
      type: "area",
      damage: 2.6,
      stun: 1.0,
      armorBreak: true,
      description: "The final judgment — reality bows to the Judge's absolute authority",
      color: "#fbbf24",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 42,
      flashDuration: 500,
    },
  },

  "inventor": {
    sp1: {
      name: "GADGET TOSS",
      type: "projectile",
      damage: 1.1,
      description: "Throws an explosive gadget that detonates on impact",
      color: "#f472b6",
      secondaryColor: "#fda4af",
      screenShake: 3,
      particleCount: 14,
      flashDuration: 140,
    },
    sp2: {
      name: "MECH PUNCH",
      type: "rush",
      damage: 1.6,
      armorBreak: true,
      description: "Deploys a mechanical fist that punches through any defense",
      color: "#f472b6",
      secondaryColor: "#78716c",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 230,
    },
    sp3: {
      name: "INVENTION SURGE",
      type: "area",
      damage: 2.4,
      dot: 6,
      description: "Deploys a rapid-fire barrage of inventions — turrets, drones, and bombs",
      color: "#f472b6",
      secondaryColor: "#f97316",
      screenShake: 8,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "seer": {
    sp1: {
      name: "PREMONITION",
      type: "counter",
      damage: 1.3,
      speedBuff: 1.4,
      description: "Foresees the attack and counters with perfect timing",
      color: "#67e8f9",
      secondaryColor: "#cffafe",
      screenShake: 2,
      particleCount: 12,
      flashDuration: 120,
    },
    sp2: {
      name: "TIME SLIP",
      type: "rush",
      damage: 1.5,
      speedBuff: 1.6,
      description: "Slips through time to strike from an impossible angle",
      color: "#67e8f9",
      secondaryColor: "#a5f3fc",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "FUTURE SIGHT",
      type: "counter",
      damage: 2.4,
      stun: 0.8,
      armorBreak: true,
      speedBuff: 2.0,
      description: "Sees every possible future and exploits the one weakness",
      color: "#67e8f9",
      secondaryColor: "#ffffff",
      screenShake: 7,
      particleCount: 36,
      flashDuration: 450,
    },
  },

  "knowledge": {
    sp1: {
      name: "DATA STREAM",
      type: "projectile",
      damage: 1.2,
      defenseDebuff: 10,
      description: "Fires a concentrated stream of raw knowledge",
      color: "#34d399",
      secondaryColor: "#6ee7b7",
      screenShake: 3,
      particleCount: 14,
      flashDuration: 140,
    },
    sp2: {
      name: "MIND CRUSH",
      type: "area",
      damage: 1.7,
      stun: 0.5,
      defenseDebuff: 20,
      description: "Overwhelms the opponent's mind with infinite knowledge",
      color: "#34d399",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 22,
      flashDuration: 250,
    },
    sp3: {
      name: "OMNISCIENCE BURST",
      type: "area",
      damage: 2.6,
      stun: 0.8,
      armorBreak: true,
      defenseDebuff: 30,
      description: "Channels all knowledge into a focused burst of pure enlightenment",
      color: "#34d399",
      secondaryColor: "#fbbf24",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
    },
  },

  "silence": {
    sp1: {
      name: "MUTE STRIKE",
      type: "rush",
      damage: 1.2,
      stun: 0.3,
      description: "A silent strike that suppresses the opponent's abilities",
      color: "#475569",
      secondaryColor: "#1e293b",
      screenShake: 2,
      particleCount: 8,
      flashDuration: 100,
    },
    sp2: {
      name: "NULL ZONE",
      type: "area",
      damage: 1.5,
      stun: 0.6,
      defenseDebuff: 15,
      description: "Creates a zone of absolute silence that nullifies all energy",
      color: "#475569",
      secondaryColor: "#0f172a",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "VOID EMBRACE",
      type: "area",
      damage: 2.4,
      stun: 1.0,
      defenseDebuff: 25,
      description: "Silences all sound and crushes with void pressure — total oblivion",
      color: "#475569",
      secondaryColor: "#000000",
      screenShake: 6,
      particleCount: 30,
      flashDuration: 400,
    },
  },

  "storm": {
    sp1: {
      name: "LIGHTNING FIST",
      type: "rush",
      damage: 1.4,
      description: "A fist charged with devastating lightning energy",
      color: "#60a5fa",
      secondaryColor: "#93c5fd",
      screenShake: 4,
      particleCount: 14,
      flashDuration: 150,
    },
    sp2: {
      name: "THUNDER CLAP",
      type: "area",
      damage: 1.8,
      stun: 0.5,
      description: "A thunderous clap that sends shockwaves through the arena",
      color: "#60a5fa",
      secondaryColor: "#ffffff",
      screenShake: 6,
      particleCount: 24,
      flashDuration: 280,
    },
    sp3: {
      name: "TEMPEST FURY",
      type: "area",
      damage: 2.8,
      stun: 0.8,
      armorBreak: true,
      description: "Unleashes the full fury of the storm — lightning, wind, and chaos",
      color: "#60a5fa",
      secondaryColor: "#fbbf24",
      screenShake: 10,
      particleCount: 50,
      flashDuration: 500,
    },
  },

  "degen": {
    sp1: {
      name: "YOLO STRIKE",
      type: "rush",
      damage: 1.5,
      description: "An all-in reckless attack — high risk, high reward",
      color: "#fb923c",
      secondaryColor: "#fdba74",
      screenShake: 4,
      particleCount: 14,
      flashDuration: 140,
    },
    sp2: {
      name: "RUG PULL",
      type: "grab",
      damage: 1.7,
      stun: 0.5,
      defenseDebuff: 25,
      description: "Pulls the ground from under the opponent — literally",
      color: "#fb923c",
      secondaryColor: "#ef4444",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "DEGEN GAMBIT",
      type: "area",
      damage: 3.0,
      armorBreak: true,
      description: "The ultimate gamble — massive damage but costs 15% of own HP",
      color: "#fb923c",
      secondaryColor: "#fbbf24",
      screenShake: 10,
      particleCount: 50,
      flashDuration: 500,
    },
  },

  "advocate": {
    sp1: {
      name: "OBJECTION!",
      type: "counter",
      damage: 1.2,
      stun: 0.4,
      description: "A forceful objection that interrupts the opponent's attack",
      color: "#fcd34d",
      secondaryColor: "#fef08a",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "CROSS EXAMINE",
      type: "grab",
      damage: 1.5,
      defenseDebuff: 20,
      description: "Exposes the opponent's weaknesses through relentless questioning",
      color: "#fcd34d",
      secondaryColor: "#ffffff",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "TRUTH BEAM",
      type: "projectile",
      damage: 2.3,
      armorBreak: true,
      stun: 0.6,
      description: "A beam of pure truth that pierces all defenses and lies",
      color: "#fcd34d",
      secondaryColor: "#22c55e",
      screenShake: 7,
      particleCount: 35,
      flashDuration: 450,
    },
  },

  "forgotten": {
    sp1: {
      name: "FADE STRIKE",
      type: "rush",
      damage: 1.2,
      speedBuff: 1.3,
      description: "Fades from memory and strikes from nowhere",
      color: "#94a3b8",
      secondaryColor: "#cbd5e1",
      screenShake: 2,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "GHOST TOUCH",
      type: "grab",
      damage: 1.5,
      stun: 0.5,
      description: "A spectral touch that makes the opponent forget how to fight",
      color: "#94a3b8",
      secondaryColor: "#e2e8f0",
      screenShake: 4,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "MEMORY WIPE",
      type: "area",
      damage: 2.3,
      stun: 1.2,
      defenseDebuff: 30,
      description: "Erases the opponent's combat memory — they forget everything",
      color: "#94a3b8",
      secondaryColor: "#000000",
      screenShake: 7,
      particleCount: 35,
      flashDuration: 450,
    },
  },

  "resurrectionist": {
    sp1: {
      name: "REVIVAL PUNCH",
      type: "rush",
      damage: 1.1,
      heal: 10,
      description: "A punch infused with life energy that heals on contact",
      color: "#4ade80",
      secondaryColor: "#86efac",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 130,
    },
    sp2: {
      name: "PHOENIX RISE",
      type: "buff",
      damage: 1.4,
      heal: 25,
      speedBuff: 1.3,
      description: "Channels rebirth energy, healing and boosting speed",
      color: "#4ade80",
      secondaryColor: "#f97316",
      screenShake: 4,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "SECOND LIFE",
      type: "buff",
      damage: 2.0,
      heal: 40,
      description: "The ultimate rebirth — massive heal and devastating counterattack",
      color: "#4ade80",
      secondaryColor: "#fbbf24",
      screenShake: 7,
      particleCount: 38,
      flashDuration: 500,
    },
  },

  /* ─── UNLOCKABLE — POTENTIALS & INSURGENCY ─── */

  "akai-shi": {
    sp1: {
      name: "CRIMSON SLASH",
      type: "rush",
      damage: 1.4,
      dot: 4,
      description: "A crimson blade slash that leaves a bleeding wound",
      color: "#dc2626",
      secondaryColor: "#fca5a5",
      screenShake: 4,
      particleCount: 14,
      flashDuration: 150,
    },
    sp2: {
      name: "BLOOD MOON",
      type: "area",
      damage: 1.8,
      dot: 6,
      description: "Channels the blood moon's power for a devastating area attack",
      color: "#dc2626",
      secondaryColor: "#7f1d1d",
      screenShake: 6,
      particleCount: 24,
      flashDuration: 280,
    },
    sp3: {
      name: "RED DEATH STRIKE",
      type: "rush",
      damage: 2.8,
      dot: 10,
      armorBreak: true,
      description: "The lethal crimson blade technique — one cut, absolute death",
      color: "#dc2626",
      secondaryColor: "#000000",
      screenShake: 9,
      particleCount: 40,
      flashDuration: 500,
    },
  },

  "wraith-calder": {
    sp1: {
      name: "GHOST STRIKE",
      type: "counter",
      damage: 1.3,
      speedBuff: 1.4,
      description: "Phases through the opponent and strikes from behind",
      color: "#a78bfa",
      secondaryColor: "#ddd6fe",
      screenShake: 2,
      particleCount: 12,
      flashDuration: 120,
    },
    sp2: {
      name: "PHASE PUNCH",
      type: "rush",
      damage: 1.6,
      armorBreak: true,
      description: "A punch that phases through all defenses",
      color: "#a78bfa",
      secondaryColor: "#ffffff",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 230,
    },
    sp3: {
      name: "WRAITH PHASE",
      type: "area",
      damage: 2.5,
      armorBreak: true,
      speedBuff: 2.0,
      description: "Becomes fully spectral — untouchable and devastating",
      color: "#a78bfa",
      secondaryColor: "#7c3aed",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
    },
  },

  "wolf": {
    sp1: {
      name: "CLAW SWIPE",
      type: "rush",
      damage: 1.3,
      dot: 3,
      description: "A savage claw swipe that tears through flesh",
      color: "#78716c",
      secondaryColor: "#dc2626",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "HOWL",
      type: "buff",
      damage: 1.4,
      speedBuff: 1.5,
      stun: 0.4,
      description: "A terrifying howl that stuns and boosts attack speed",
      color: "#78716c",
      secondaryColor: "#f59e0b",
      screenShake: 5,
      particleCount: 16,
      flashDuration: 220,
    },
    sp3: {
      name: "FERAL RAGE",
      type: "rush",
      damage: 2.7,
      speedBuff: 1.8,
      dot: 8,
      description: "Enters a berserker state — unstoppable feral assault",
      color: "#78716c",
      secondaryColor: "#ef4444",
      screenShake: 9,
      particleCount: 42,
      flashDuration: 500,
    },
  },

  "iron-lion": {
    sp1: {
      name: "STEEL FIST",
      type: "rush",
      damage: 1.4,
      description: "A devastating mechanical fist strike",
      color: "#d97706",
      secondaryColor: "#fbbf24",
      screenShake: 4,
      particleCount: 12,
      flashDuration: 150,
    },
    sp2: {
      name: "MANE WHIP",
      type: "area",
      damage: 1.7,
      stun: 0.5,
      description: "Whips the mechanical mane in a devastating arc",
      color: "#d97706",
      secondaryColor: "#78716c",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "IRON ROAR",
      type: "area",
      damage: 2.7,
      stun: 0.8,
      armorBreak: true,
      defenseDebuff: 30,
      description: "A devastating mechanical roar that shatters all defenses",
      color: "#d97706",
      secondaryColor: "#ef4444",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "engineer": {
    sp1: {
      name: "WRENCH SLAM",
      type: "rush",
      damage: 1.2,
      armorBreak: true,
      description: "A heavy wrench strike that breaks through armor",
      color: "#06b6d4",
      secondaryColor: "#67e8f9",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "DRONE STRIKE",
      type: "projectile",
      damage: 1.6,
      dot: 4,
      description: "Deploys combat drones that fire in a coordinated barrage",
      color: "#06b6d4",
      secondaryColor: "#f97316",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "TECH OVERLOAD",
      type: "area",
      damage: 2.5,
      dot: 8,
      armorBreak: true,
      description: "Deploys turrets, drones, and EMP in a devastating tech barrage",
      color: "#06b6d4",
      secondaryColor: "#fbbf24",
      screenShake: 8,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "oracle": {
    sp1: {
      name: "VISION BLAST",
      type: "projectile",
      damage: 1.3,
      stun: 0.3,
      description: "A blast of prophetic energy that disorients",
      color: "#e879f9",
      secondaryColor: "#f0abfc",
      screenShake: 3,
      particleCount: 14,
      flashDuration: 140,
    },
    sp2: {
      name: "FATE WEAVE",
      type: "area",
      damage: 1.7,
      stun: 0.6,
      defenseDebuff: 15,
      description: "Weaves the threads of fate to trap the opponent",
      color: "#e879f9",
      secondaryColor: "#fbbf24",
      screenShake: 5,
      particleCount: 22,
      flashDuration: 250,
    },
    sp3: {
      name: "PROPHECY STRIKE",
      type: "area",
      damage: 2.8,
      stun: 1.0,
      armorBreak: true,
      description: "Channels the power of prophecy into a devastating reality-altering attack",
      color: "#e879f9",
      secondaryColor: "#ffffff",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "eyes": {
    sp1: {
      name: "SPY KICK",
      type: "rush",
      damage: 1.2,
      speedBuff: 1.3,
      description: "A swift espionage-trained kick",
      color: "#22d3ee",
      secondaryColor: "#67e8f9",
      screenShake: 2,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "LENS FLARE",
      type: "projectile",
      damage: 1.5,
      stun: 0.5,
      description: "A blinding flash from the synthetic eyes",
      color: "#22d3ee",
      secondaryColor: "#ffffff",
      screenShake: 4,
      particleCount: 18,
      flashDuration: 250,
    },
    sp3: {
      name: "ALL-SEEING STRIKE",
      type: "counter",
      damage: 2.4,
      armorBreak: true,
      speedBuff: 1.8,
      description: "Sees every weakness and exploits them all simultaneously",
      color: "#22d3ee",
      secondaryColor: "#fbbf24",
      screenShake: 7,
      particleCount: 36,
      flashDuration: 450,
    },
  },

  "agent-zero": {
    sp1: {
      name: "SILENT KILL",
      type: "rush",
      damage: 1.5,
      description: "A lethal silent assassination strike",
      color: "#1e293b",
      secondaryColor: "#475569",
      screenShake: 3,
      particleCount: 8,
      flashDuration: 100,
    },
    sp2: {
      name: "SHADOW STEP",
      type: "counter",
      damage: 1.7,
      speedBuff: 1.6,
      armorBreak: true,
      description: "Steps through shadows to strike from behind",
      color: "#1e293b",
      secondaryColor: "#7c3aed",
      screenShake: 5,
      particleCount: 16,
      flashDuration: 200,
    },
    sp3: {
      name: "ZERO HOUR",
      type: "rush",
      damage: 3.0,
      armorBreak: true,
      description: "The ultimate assassination technique — one shot, one kill",
      color: "#1e293b",
      secondaryColor: "#ef4444",
      screenShake: 10,
      particleCount: 30,
      flashDuration: 500,
    },
  },

  /* ─── HIERARCHY OF THE DAMNED ─── */

  "molgrath": {
    sp1: {
      name: "ENTROPY BLAST",
      type: "projectile",
      damage: 1.5,
      defenseDebuff: 15,
      description: "A blast of pure entropy that unmakes matter",
      color: "#dc2626",
      secondaryColor: "#7f1d1d",
      screenShake: 5,
      particleCount: 16,
      flashDuration: 180,
    },
    sp2: {
      name: "CORPORATE CRUSH",
      type: "grab",
      damage: 2.0,
      stun: 0.8,
      armorBreak: true,
      description: "Crushes the opponent with the weight of corporate power",
      color: "#dc2626",
      secondaryColor: "#000000",
      screenShake: 7,
      particleCount: 28,
      flashDuration: 300,
    },
    sp3: {
      name: "HOSTILE ACQUISITION",
      type: "area",
      damage: 3.2,
      stun: 1.2,
      armorBreak: true,
      defenseDebuff: 40,
      description: "Unmakes reality itself — the ultimate hostile takeover of existence",
      color: "#dc2626",
      secondaryColor: "#fbbf24",
      screenShake: 10,
      particleCount: 55,
      flashDuration: 600,
      startupFrames: 20,
      activeFrames: 28,
      recoveryFrames: 24,
    },
  },

  "xethraal": {
    sp1: {
      name: "LEDGER STRIKE",
      type: "rush",
      damage: 1.2,
      dot: 3,
      description: "A strike that adds to the opponent's debt of pain",
      color: "#eab308",
      secondaryColor: "#fbbf24",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "SOUL TAX",
      type: "drain",
      damage: 1.6,
      heal: 25,
      description: "Taxes the opponent's soul, draining life force",
      color: "#eab308",
      secondaryColor: "#22c55e",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "COMPOUND INTEREST",
      type: "drain",
      damage: 2.5,
      dot: 12,
      heal: 30,
      description: "The longer the fight, the more they owe — interest compounds to lethal levels",
      color: "#eab308",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
    },
  },

  "vexahlia": {
    sp1: {
      name: "HEX SLASH",
      type: "rush",
      damage: 1.4,
      description: "A swift slash from one of six arms",
      color: "#e11d48",
      secondaryColor: "#fb7185",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "ARM BARRAGE",
      type: "rush",
      damage: 1.9,
      stun: 0.4,
      description: "A rapid barrage from all six arms simultaneously",
      color: "#e11d48",
      secondaryColor: "#fbbf24",
      screenShake: 6,
      particleCount: 24,
      flashDuration: 280,
    },
    sp3: {
      name: "SIX-ARMED ASSAULT",
      type: "area",
      damage: 2.9,
      stun: 0.8,
      armorBreak: true,
      description: "Unleashes a devastating flurry from all six arms — unstoppable force",
      color: "#e11d48",
      secondaryColor: "#ef4444",
      screenShake: 10,
      particleCount: 50,
      flashDuration: 500,
    },
  },

  "draelmon": {
    sp1: {
      name: "MOUTH SLAM",
      type: "grab",
      damage: 1.3,
      description: "Slams the opponent with massive jaws",
      color: "#7c3aed",
      secondaryColor: "#a78bfa",
      screenShake: 4,
      particleCount: 12,
      flashDuration: 150,
    },
    sp2: {
      name: "DIMENSIONAL BITE",
      type: "grab",
      damage: 1.8,
      heal: 20,
      description: "Bites through dimensions, consuming the opponent's energy",
      color: "#7c3aed",
      secondaryColor: "#22c55e",
      screenShake: 6,
      particleCount: 22,
      flashDuration: 280,
    },
    sp3: {
      name: "WORLD EATER",
      type: "area",
      damage: 2.8,
      heal: 35,
      armorBreak: true,
      description: "Consumes dimensional energy, growing stronger with each bite",
      color: "#7c3aed",
      secondaryColor: "#ef4444",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "nykoth": {
    sp1: {
      name: "SCALPEL SLASH",
      type: "rush",
      damage: 1.3,
      dot: 4,
      description: "A precise surgical slash that causes bleeding",
      color: "#10b981",
      secondaryColor: "#34d399",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "VIVISECTION",
      type: "grab",
      damage: 1.7,
      dot: 6,
      defenseDebuff: 20,
      description: "A horrifying surgical procedure performed mid-combat",
      color: "#10b981",
      secondaryColor: "#ef4444",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "THOUGHT VIRUS",
      type: "area",
      damage: 2.5,
      dot: 15,
      defenseDebuff: 30,
      description: "Injects a thought virus that corrupts from within — slow, agonizing destruction",
      color: "#10b981",
      secondaryColor: "#7c3aed",
      screenShake: 7,
      particleCount: 38,
      flashDuration: 500,
    },
  },

  "sylvex": {
    sp1: {
      name: "SOUL KISS",
      type: "grab",
      damage: 1.1,
      heal: 15,
      description: "A corrupting kiss that drains life energy",
      color: "#ec4899",
      secondaryColor: "#f9a8d4",
      screenShake: 2,
      particleCount: 12,
      flashDuration: 130,
    },
    sp2: {
      name: "EMPATHY STRIKE",
      type: "area",
      damage: 1.5,
      stun: 0.6,
      defenseDebuff: 20,
      description: "Forces the opponent to feel overwhelming emotions, weakening them",
      color: "#ec4899",
      secondaryColor: "#7c3aed",
      screenShake: 4,
      particleCount: 18,
      flashDuration: 220,
    },
    sp3: {
      name: "THE BEAUTIFUL LIE",
      type: "area",
      damage: 2.3,
      stun: 1.0,
      defenseDebuff: 35,
      heal: 25,
      description: "Charms the opponent with a beautiful lie — they lower all defenses willingly",
      color: "#ec4899",
      secondaryColor: "#fbbf24",
      screenShake: 7,
      particleCount: 36,
      flashDuration: 450,
    },
  },

  "varkul": {
    sp1: {
      name: "FANG STRIKE",
      type: "rush",
      damage: 1.3,
      heal: 10,
      description: "A vampiric fang strike that drains blood",
      color: "#991b1b",
      secondaryColor: "#dc2626",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "BLOOD WAVE",
      type: "area",
      damage: 1.7,
      heal: 20,
      dot: 4,
      description: "A wave of blood energy that heals and damages",
      color: "#991b1b",
      secondaryColor: "#7f1d1d",
      screenShake: 5,
      particleCount: 22,
      flashDuration: 260,
    },
    sp3: {
      name: "BLOOD DRAIN",
      type: "drain",
      damage: 2.4,
      heal: 40,
      dot: 8,
      description: "Drains all life force from the opponent — the Blood Lord feeds",
      color: "#991b1b",
      secondaryColor: "#000000",
      screenShake: 8,
      particleCount: 40,
      flashDuration: 500,
    },
  },

  "fenra": {
    sp1: {
      name: "CLAW SWIPE",
      type: "rush",
      damage: 1.3,
      dot: 3,
      description: "A savage lunar-powered claw attack",
      color: "#854d0e",
      secondaryColor: "#a16207",
      screenShake: 3,
      particleCount: 12,
      flashDuration: 140,
    },
    sp2: {
      name: "MOON HOWL",
      type: "area",
      damage: 1.6,
      stun: 0.5,
      speedBuff: 1.4,
      description: "A terrifying howl that stuns and empowers",
      color: "#854d0e",
      secondaryColor: "#fbbf24",
      screenShake: 5,
      particleCount: 20,
      flashDuration: 250,
    },
    sp3: {
      name: "PACK TACTICS",
      type: "area",
      damage: 2.6,
      stun: 0.6,
      armorBreak: true,
      description: "Summons spectral wolves for a devastating coordinated assault",
      color: "#854d0e",
      secondaryColor: "#ef4444",
      screenShake: 9,
      particleCount: 45,
      flashDuration: 500,
    },
  },

  "ithrael": {
    sp1: {
      name: "WHISPER BLADE",
      type: "rush",
      damage: 1.2,
      stun: 0.3,
      description: "A psychic blade formed from whispered secrets",
      color: "#4338ca",
      secondaryColor: "#6366f1",
      screenShake: 2,
      particleCount: 10,
      flashDuration: 120,
    },
    sp2: {
      name: "MIND SHATTER",
      type: "area",
      damage: 1.7,
      stun: 0.7,
      defenseDebuff: 20,
      description: "Shatters the opponent's mental defenses with psychic force",
      color: "#4338ca",
      secondaryColor: "#a5b4fc",
      screenShake: 5,
      particleCount: 22,
      flashDuration: 260,
    },
    sp3: {
      name: "SEVERANCE PROTOCOL",
      type: "area",
      damage: 2.7,
      stun: 1.0,
      armorBreak: true,
      defenseDebuff: 35,
      description: "Severs the opponent from reality — total psychic annihilation",
      color: "#4338ca",
      secondaryColor: "#ef4444",
      screenShake: 9,
      particleCount: 42,
      flashDuration: 500,
    },
  },
};

/** Get specials for a character, with fallback defaults */
export function getCharacterSpecials(characterId: string): CharacterSpecials {
  if (CHARACTER_SPECIALS[characterId]) return CHARACTER_SPECIALS[characterId];
  // Fallback for any character not in the database
  return {
    sp1: {
      name: "ENERGY STRIKE",
      type: "rush",
      damage: 1.2,
      description: "A focused energy attack",
      color: "#ffffff",
      secondaryColor: "#94a3b8",
      screenShake: 3,
      particleCount: 10,
      flashDuration: 130,
    },
    sp2: {
      name: "POWER SURGE",
      type: "area",
      damage: 1.6,
      stun: 0.5,
      description: "A surge of raw power",
      color: "#ffffff",
      secondaryColor: "#94a3b8",
      screenShake: 5,
      particleCount: 18,
      flashDuration: 220,
    },
    sp3: {
      name: "ULTIMATE ATTACK",
      type: "area",
      damage: 2.4,
      stun: 0.8,
      armorBreak: true,
      description: "The ultimate devastating attack",
      color: "#ffffff",
      secondaryColor: "#ef4444",
      screenShake: 8,
      particleCount: 35,
      flashDuration: 450,
    },
  };
}
