/* ═══════════════════════════════════════════════════════
   ROMANCE SCENE PLAYER

   Modal cinematic player that walks the player through the
   per-stage scene script for a romance candidate. Renders the
   multi-line cinematic in full (vs. the toast pipeline, which
   shows one abbreviated line per stage advance).

   Beats progress on click / Enter / Space. Stage directions
   (text in parentheses) render dim + italic so they read as
   stage notes, not dialog. Speaker accent palette is per-NPC.

   Two structural twists in the content the runtime handles:

     1. Path-aware variants (Locke stage 3 has variants gated
        on reactsToPublicFlag === "act1_path_A" /
        "act3_full_secret"). The active set of public flags is
        passed in; mismatching variants are filtered out.

     2. DMC stage 3 fork (kin-name vs partner-name). The two
        candidate beats live side-by-side in the bank with
        distinct setsFlags. When the player reaches the
        stage-3 naming-question beat, the player picks; the
        chosen branch's beat plays next; the other is skipped.

   Audio: VO clip URLs are sourced from
   apps/shared/romanceScenesVoManifest.json (generated by
   apps/scripts/generate-content-pass-vo.ts). If the manifest
   doesn't exist yet (pre-recording), the component plays
   silently. The audio element is tiny and best-effort —
   broken URLs are ignored.
   ═══════════════════════════════════════════════════════ */

import { AnimatePresence, motion } from "framer-motion";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { type RomanceNpcId } from "@shared/npcs/romanceScenes";
import type { NpcLine } from "@shared/npcs/types";

import {
  detectDmcChoice,
  selectStageBeats,
  splitOnParens,
  withDmcPick,
  type DmcChoiceBeats,
} from "./sceneLogic";

interface ManifestEntry {
  url?: string;
}

// Lazy import the VO manifest; missing-file is fine.
let voManifest: Record<string, ManifestEntry> = {};
try {
  // Vite's dynamic-import tolerance is fine here — the manifest
  // may be empty at dev time but the import is static for build.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  voManifest = require("@shared/romanceScenesVoManifest.json") as Record<
    string,
    ManifestEntry
  >;
} catch {
  voManifest = {};
}

const ACCENT: Record<RomanceNpcId, { border: string; bg: string; name: string; text: string }> = {
  locke: {
    border: "border-amber-600/60",
    bg: "bg-amber-950/70",
    name: "text-amber-300",
    text: "text-amber-50",
  },
  vex: {
    border: "border-rose-600/60",
    bg: "bg-rose-950/70",
    name: "text-rose-300",
    text: "text-rose-50",
  },
  elara: {
    border: "border-cyan-500/60",
    bg: "bg-cyan-950/70",
    name: "text-cyan-300",
    text: "text-cyan-50",
  },
  dmc_companion: {
    border: "border-teal-500/60",
    bg: "bg-teal-950/70",
    name: "text-teal-300",
    text: "text-teal-50",
  },
  jericho_jones: {
    border: "border-stone-500/60",
    bg: "bg-stone-950/70",
    name: "text-stone-200",
    text: "text-stone-50",
  },
};

const NPC_DISPLAY_NAME: Record<RomanceNpcId, string> = {
  locke: "Adjudicator Locke",
  vex: "Vex Solène",
  elara: "Elara",
  dmc_companion: "The Companion",
  jericho_jones: "Jericho Jones",
};

interface Props {
  npcId: RomanceNpcId;
  stage: number;
  /** Set of currently-active public + narrative flags. Used to
   *  filter path-aware variants like Locke stage 3 disclosure /
   *  betrayal beats. */
  activeFlags: ReadonlySet<string>;
  /** Callback when the scene completes. The chosen-flags array
   *  contains every line's setsFlags rolled up, plus the player's
   *  DMC naming pick if relevant. The caller should write these
   *  flags through the existing setNarrativeFlag pipeline. */
  onComplete: (chosenFlags: ReadonlyArray<string>) => void;
  /** Cancel / close without finishing. */
  onClose: () => void;
}

export function RomanceScenePlayer({
  npcId,
  stage,
  activeFlags,
  onComplete,
  onClose,
}: Props) {
  const accent = ACCENT[npcId];

  const sceneBeats = useMemo<readonly NpcLine[]>(
    () => selectStageBeats(npcId, stage, activeFlags),
    [npcId, stage, activeFlags],
  );

  const dmcChoice = useMemo<DmcChoiceBeats | null>(
    () => detectDmcChoice(npcId, stage, sceneBeats),
    [npcId, stage, sceneBeats],
  );

  const [pickedBranch, setPickedBranch] = useState<"partner" | "kin" | null>(
    null,
  );
  const beats = useMemo<readonly NpcLine[]>(
    () => withDmcPick(sceneBeats, dmcChoice, pickedBranch),
    [sceneBeats, dmcChoice, pickedBranch],
  );

  const [beatIdx, setBeatIdx] = useState(0);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const current = beats[beatIdx];
  const showDmcChoice =
    dmcChoice !== null &&
    pickedBranch === null &&
    current?.lineId === dmcChoice.question.lineId;

  // Play audio when the beat changes (best-effort; manifest
  // may be empty if VO hasn't been generated yet).
  useEffect(() => {
    if (!current) return;
    const url = voManifest[current.lineId]?.url;
    if (!url) return;
    if (audioRef.current) {
      audioRef.current.pause();
    }
    const audio = new Audio(url);
    audio.volume = 0.7;
    audioRef.current = audio;
    audio.play().catch(() => {
      // Autoplay rejected or 404; silent failure is fine.
    });
    return () => {
      audio.pause();
    };
  }, [current]);

  const advance = useCallback(() => {
    if (showDmcChoice) return; // Player must pick first.
    if (beatIdx + 1 >= beats.length) {
      // Roll up every beat's setsFlags and report.
      const allFlags = beats.flatMap((b) => b.setsFlags ?? []);
      onComplete(allFlags);
      return;
    }
    setBeatIdx((i) => i + 1);
  }, [beatIdx, beats, showDmcChoice, onComplete]);

  // Keyboard advance (Enter / Space). Esc cancels.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        advance();
      } else if (e.key === "Escape") {
        e.preventDefault();
        onClose();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [advance, onClose]);

  if (!current) {
    // Edge case: stage has no beats authored (shouldn't happen
    // for stages 1-5 but is safe).
    return null;
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label={`Romance scene with ${NPC_DISPLAY_NAME[npcId]}, stage ${stage}`}
    >
      <AnimatePresence mode="wait">
        <motion.div
          key={current.lineId}
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -16 }}
          transition={{ duration: 0.4 }}
          className={`relative w-full max-w-2xl rounded-lg border ${accent.border} ${accent.bg} p-6 shadow-2xl`}
        >
          <div className="mb-3 flex items-center justify-between">
            <div
              className={`text-sm font-semibold uppercase tracking-wider ${accent.name}`}
            >
              {NPC_DISPLAY_NAME[npcId]} · Stage {stage}
            </div>
            <button
              type="button"
              className="text-sm text-zinc-400 hover:text-zinc-200"
              onClick={onClose}
              aria-label="Close scene"
            >
              ✕
            </button>
          </div>

          <SceneText text={current.text} accent={accent.text} />

          {showDmcChoice && dmcChoice ? (
            <div className="mt-6 flex flex-col gap-3">
              <button
                type="button"
                className="rounded-md border border-teal-400/40 bg-teal-900/40 px-4 py-3 text-left text-teal-50 transition hover:bg-teal-900/70"
                onClick={() => setPickedBranch("partner")}
              >
                <div className="text-xs uppercase tracking-wider text-teal-300">
                  Partner-name
                </div>
                <div className="text-sm">
                  Name them as a beloved is named.
                </div>
              </button>
              <button
                type="button"
                className="rounded-md border border-teal-400/40 bg-teal-900/40 px-4 py-3 text-left text-teal-50 transition hover:bg-teal-900/70"
                onClick={() => setPickedBranch("kin")}
              >
                <div className="text-xs uppercase tracking-wider text-teal-300">
                  Kin-name
                </div>
                <div className="text-sm">
                  Name them as a sibling is named.
                </div>
              </button>
            </div>
          ) : (
            <div className="mt-6 flex items-center justify-between text-xs text-zinc-400">
              <span>
                {beatIdx + 1} / {beats.length}
              </span>
              <button
                type="button"
                className={`rounded-md border ${accent.border} px-3 py-1.5 ${accent.text} transition hover:bg-white/5`}
                onClick={advance}
              >
                {beatIdx + 1 >= beats.length ? "Close scene" : "Continue"}
              </button>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

/**
 * Render a scene line with stage directions in dim italic
 * and dialog in the speaker's accent colour. Stage directions
 * are anything inside parentheses; dialog is everything else.
 * Splits on (...) groupings without breaking sentence flow.
 */
function SceneText({ text, accent }: { text: string; accent: string }) {
  const parts = useMemo(() => splitOnParens(text), [text]);
  return (
    <p className={`whitespace-pre-wrap text-base leading-relaxed ${accent}`}>
      {parts.map((part, i) =>
        part.kind === "stage" ? (
          <span key={i} className="italic text-zinc-400">
            {part.text}
          </span>
        ) : (
          <span key={i}>{part.text}</span>
        ),
      )}
    </p>
  );
}

