/**
 * Pack 2 base-set · allegiance · 36 net-new card definitions.
 *
 * AUTO-GENERATED by scripts/_gen-pack2-cards.mjs from the
 * producer slugs in apps/shared/expansionArt/dischordiaBaseSet.ts.
 * Hand-edit individual cards in this file if design wants finer
 * tuning; the generator is idempotent on re-run (overwrites this
 * file, so move custom edits into per-slug overrides if you want
 * them to survive).
 *
 * Every ability list is currently empty — design owns the balance +
 * effect pass. CardIds use the s1_pack2_ namespace so they don't
 * collide with the existing s1_ defs.
 */
import type { CardDefinition } from "../../../index";
import { assetUrl } from "@shared/lib/assetUrl";

export const pack2_allegiance_antiquarian_apprentice_t1: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_apprentice_t1" as CardDefinition["id"],
  name: "Apprentice T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_apprentice_t1.webp"),
  flavorText: "Every banner has a cost. The cost is the bannerman.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_antiquarian_archivekeeper_t5: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_archivekeeper_t5" as CardDefinition["id"],
  name: "Archivekeeper T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_archivekeeper_t5.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_antiquarian_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_champion_t6" as CardDefinition["id"],
  name: "Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_champion_t6.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_antiquarian_curator_t3: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_curator_t3" as CardDefinition["id"],
  name: "Curator T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_curator_t3.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_antiquarian_lorekeeper_t4: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_lorekeeper_t4" as CardDefinition["id"],
  name: "Lorekeeper T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_lorekeeper_t4.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_antiquarian_scholar_t2: CardDefinition = {
  id: "s1_pack2_allegiance_antiquarian_scholar_t2" as CardDefinition["id"],
  name: "Scholar T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/antiquarian_scholar_t2.webp"),
  flavorText: "Loyalty is a load-bearing wall. Pull it; the room falls.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_architect_champion_t6" as CardDefinition["id"],
  name: "Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_champion_t6.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_elite_t5: CardDefinition = {
  id: "s1_pack2_allegiance_architect_elite_t5" as CardDefinition["id"],
  name: "Elite T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_elite_t5.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_initiate_t1: CardDefinition = {
  id: "s1_pack2_allegiance_architect_initiate_t1" as CardDefinition["id"],
  name: "Initiate T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_initiate_t1.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_servant_t2: CardDefinition = {
  id: "s1_pack2_allegiance_architect_servant_t2" as CardDefinition["id"],
  name: "Servant T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_servant_t2.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_veteran_t3: CardDefinition = {
  id: "s1_pack2_allegiance_architect_veteran_t3" as CardDefinition["id"],
  name: "Veteran T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_veteran_t3.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_architect_victorious_t4: CardDefinition = {
  id: "s1_pack2_allegiance_architect_victorious_t4" as CardDefinition["id"],
  name: "Victorious T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/architect_victorious_t4.webp"),
  flavorText: "Loyalty is a load-bearing wall. Pull it; the room falls.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_champion_t6" as CardDefinition["id"],
  name: "Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_champion_t6.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_clerk_t1: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_clerk_t1" as CardDefinition["id"],
  name: "Clerk T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_clerk_t1.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_governor_t5: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_governor_t5" as CardDefinition["id"],
  name: "Governor T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_governor_t5.webp"),
  flavorText: "Loyalty is a load-bearing wall. Pull it; the room falls.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_magistrate_t2: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_magistrate_t2" as CardDefinition["id"],
  name: "Magistrate T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_magistrate_t2.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_senator_t4: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_senator_t4" as CardDefinition["id"],
  name: "Senator T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_senator_t4.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_babylon_tax_collector_t3: CardDefinition = {
  id: "s1_pack2_allegiance_babylon_tax_collector_t3" as CardDefinition["id"],
  name: "Tax Collector T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/babylon_tax_collector_t3.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_acolyte_t1: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_acolyte_t1" as CardDefinition["id"],
  name: "Acolyte T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_acolyte_t1.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_champion_t6" as CardDefinition["id"],
  name: "Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_champion_t6.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_dreamwalker_t5: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_dreamwalker_t5" as CardDefinition["id"],
  name: "Dreamwalker T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_dreamwalker_t5.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_prophet_t4: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_prophet_t4" as CardDefinition["id"],
  name: "Prophet T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_prophet_t4.webp"),
  flavorText: "Loyalty is a load-bearing wall. Pull it; the room falls.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_seer_t2: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_seer_t2" as CardDefinition["id"],
  name: "Seer T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_seer_t2.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_dreamer_visionary_t3: CardDefinition = {
  id: "s1_pack2_allegiance_dreamer_visionary_t3" as CardDefinition["id"],
  name: "Visionary T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/dreamer_visionary_t3.webp"),
  flavorText: "Vows do not break. The vow-bearer breaks under them.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_cell_leader_t3: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_cell_leader_t3" as CardDefinition["id"],
  name: "Cell Leader T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_cell_leader_t3.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_champion_t6" as CardDefinition["id"],
  name: "Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_champion_t6.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_commander_t4: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_commander_t4" as CardDefinition["id"],
  name: "Commander T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_commander_t4.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_operative_t2: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_operative_t2" as CardDefinition["id"],
  name: "Operative T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_operative_t2.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_recruit_t1: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_recruit_t1" as CardDefinition["id"],
  name: "Recruit T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_recruit_t1.webp"),
  flavorText: "Allegiance pays its tithe in posture, then in pulse.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_insurgency_warlord_t5: CardDefinition = {
  id: "s1_pack2_allegiance_insurgency_warlord_t5" as CardDefinition["id"],
  name: "Warlord T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/insurgency_warlord_t5.webp"),
  flavorText: "What we are sworn to, we become.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_carrier_t1: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_carrier_t1" as CardDefinition["id"],
  name: "Virus Carrier T1",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_carrier_t1.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_champion_t6: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_champion_t6" as CardDefinition["id"],
  name: "Virus Champion T6",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_champion_t6.webp"),
  flavorText: "We carry the line not because it is right but because we said we would.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_evangelist_t2: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_evangelist_t2" as CardDefinition["id"],
  name: "Virus Evangelist T2",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_evangelist_t2.webp"),
  flavorText: "Loyalty is a load-bearing wall. Pull it; the room falls.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_prime_vessel_t5: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_prime_vessel_t5" as CardDefinition["id"],
  name: "Virus Prime Vessel T5",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["celerity"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_prime_vessel_t5.webp"),
  flavorText: "We do not swear lightly. We swear once, completely, and against the day.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_strain_keeper_t3: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_strain_keeper_t3" as CardDefinition["id"],
  name: "Virus Strain Keeper T3",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_strain_keeper_t3.webp"),
  flavorText: "The first oath was a sentence. The last is a name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_allegiance_thought_virus_vector_t4: CardDefinition = {
  id: "s1_pack2_allegiance_thought_virus_vector_t4" as CardDefinition["id"],
  name: "Virus Vector T4",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/allegiance/thought_virus_vector_t4.webp"),
  flavorText: "The oath was older than the bearer. The bearer was made for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const S1_PACK2_ALLEGIANCE_CARDS: readonly CardDefinition[] = [
  pack2_allegiance_antiquarian_apprentice_t1,
  pack2_allegiance_antiquarian_archivekeeper_t5,
  pack2_allegiance_antiquarian_champion_t6,
  pack2_allegiance_antiquarian_curator_t3,
  pack2_allegiance_antiquarian_lorekeeper_t4,
  pack2_allegiance_antiquarian_scholar_t2,
  pack2_allegiance_architect_champion_t6,
  pack2_allegiance_architect_elite_t5,
  pack2_allegiance_architect_initiate_t1,
  pack2_allegiance_architect_servant_t2,
  pack2_allegiance_architect_veteran_t3,
  pack2_allegiance_architect_victorious_t4,
  pack2_allegiance_babylon_champion_t6,
  pack2_allegiance_babylon_clerk_t1,
  pack2_allegiance_babylon_governor_t5,
  pack2_allegiance_babylon_magistrate_t2,
  pack2_allegiance_babylon_senator_t4,
  pack2_allegiance_babylon_tax_collector_t3,
  pack2_allegiance_dreamer_acolyte_t1,
  pack2_allegiance_dreamer_champion_t6,
  pack2_allegiance_dreamer_dreamwalker_t5,
  pack2_allegiance_dreamer_prophet_t4,
  pack2_allegiance_dreamer_seer_t2,
  pack2_allegiance_dreamer_visionary_t3,
  pack2_allegiance_insurgency_cell_leader_t3,
  pack2_allegiance_insurgency_champion_t6,
  pack2_allegiance_insurgency_commander_t4,
  pack2_allegiance_insurgency_operative_t2,
  pack2_allegiance_insurgency_recruit_t1,
  pack2_allegiance_insurgency_warlord_t5,
  pack2_allegiance_thought_virus_carrier_t1,
  pack2_allegiance_thought_virus_champion_t6,
  pack2_allegiance_thought_virus_evangelist_t2,
  pack2_allegiance_thought_virus_prime_vessel_t5,
  pack2_allegiance_thought_virus_strain_keeper_t3,
  pack2_allegiance_thought_virus_vector_t4,
];
