/**
 * Pack 2 base-set · class · 30 net-new card definitions.
 *
 * AUTO-GENERATED by scripts/_gen-pack2-cards.mjs from the
 * producer slugs in apps/shared/expansionArt/dischordiaBaseSet.ts.
 * Hand-edit individual cards in this file if design wants finer
 * tuning; the generator is idempotent on re-run (overwrites this
 * file, so move custom edits into per-slug overrides if you want
 * them to survive).
 *
 * Every ability list is currently empty — design owns the balance +
 * effect pass. CardIds use the s1_pack2_ namespace so they don't
 * collide with the existing s1_ defs.
 */
import type { CardDefinition } from "../../../index";
import { assetUrl } from "@shared/lib/assetUrl";

export const pack2_class_akai_shi_first_apprentice: CardDefinition = {
  id: "s1_pack2_class_akai_shi_first_apprentice" as CardDefinition["id"],
  name: "Shi First Apprentice",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["rush"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/akai_shi_first_apprentice.webp"),
  flavorText: "The first cut is not the first cut. The first cut was the breath that preceded it.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_auspex: CardDefinition = {
  id: "s1_pack2_class_auspex" as CardDefinition["id"],
  name: "Auspex",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/auspex.webp"),
  flavorText: "He reads the pause between heartbeats. The pause names the next heartbeat.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_burn_the_handler: CardDefinition = {
  id: "s1_pack2_class_burn_the_handler" as CardDefinition["id"],
  name: "The Handler",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/burn_the_handler.webp"),
  flavorText: "You burn the handler. The handler is the part of you that knew the protocol.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_cover_name: CardDefinition = {
  id: "s1_pack2_class_cover_name" as CardDefinition["id"],
  name: "Name",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/cover_name.webp"),
  flavorText: "A cover name worn three years stops being a cover. It becomes the wearer.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_dead_drop: CardDefinition = {
  id: "s1_pack2_class_dead_drop" as CardDefinition["id"],
  name: "Drop",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/dead_drop.webp"),
  flavorText: "The drop site is found by the trained foot, not the eye. The eye lies; the foot does not.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_dual_discipline: CardDefinition = {
  id: "s1_pack2_class_dual_discipline" as CardDefinition["id"],
  name: "Discipline",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/dual_discipline.webp"),
  flavorText: "Two schools in one body. The body chooses, mid-strike, which school it is in.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_engineers_apprentice: CardDefinition = {
  id: "s1_pack2_class_engineers_apprentice" as CardDefinition["id"],
  name: "Apprentice",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/engineers_apprentice.webp"),
  flavorText: "She watches the master strip the rifle blind. The rifle reassembles itself by Tuesday.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_execute_protocol: CardDefinition = {
  id: "s1_pack2_class_execute_protocol" as CardDefinition["id"],
  name: "Protocol",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/execute_protocol.webp"),
  flavorText: "The protocol is not a plan. The protocol is what runs when the plan has already failed.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_field_modification: CardDefinition = {
  id: "s1_pack2_class_field_modification" as CardDefinition["id"],
  name: "Modification",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/field_modification.webp"),
  flavorText: "What the manual forbids, the field demands. The mod is graded by survival.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_five_schools_avatar: CardDefinition = {
  id: "s1_pack2_class_five_schools_avatar" as CardDefinition["id"],
  name: "Schools Avatar",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/five_schools_avatar.webp"),
  flavorText: "He has held all five marks. The marks no longer compete; they take turns.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_glass_blade_initiate: CardDefinition = {
  id: "s1_pack2_class_glass_blade_initiate" as CardDefinition["id"],
  name: "Blade Initiate",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: ["rush"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/glass_blade_initiate.webp"),
  flavorText: "Her blade breaks on the first strike. She is graded on whether the strike still landed.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_hybrid_initiate: CardDefinition = {
  id: "s1_pack2_class_hybrid_initiate" as CardDefinition["id"],
  name: "Initiate",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/hybrid_initiate.webp"),
  flavorText: "He took two oaths. Both schools claim him. Neither school owns him.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_iron_vanguard: CardDefinition = {
  id: "s1_pack2_class_iron_vanguard" as CardDefinition["id"],
  name: "Vanguard",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/iron_vanguard.webp"),
  flavorText: "First through the breach. The breach widens because she is in it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_kinetic_containment_sink: CardDefinition = {
  id: "s1_pack2_class_kinetic_containment_sink" as CardDefinition["id"],
  name: "Containment Sink",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/kinetic_containment_sink.webp"),
  flavorText: "He absorbs the strike that should have killed three. The three never knew his name.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_last_regiment_standing: CardDefinition = {
  id: "s1_pack2_class_last_regiment_standing" as CardDefinition["id"],
  name: "Regiment Standing",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/last_regiment_standing.webp"),
  flavorText: "Of the regiment, she is the regiment now. The standard speaks in her cadence.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_line_recruit: CardDefinition = {
  id: "s1_pack2_class_line_recruit" as CardDefinition["id"],
  name: "Recruit",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/line_recruit.webp"),
  flavorText: "Day one on the line. The line teaches by attrition. He is still on the line.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_oracles_unbroken_signal: CardDefinition = {
  id: "s1_pack2_class_oracles_unbroken_signal" as CardDefinition["id"],
  name: "Unbroken Signal",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/oracles_unbroken_signal.webp"),
  flavorText: "The signal arrives intact through every jamming field. The Oracle is her own carrier.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_prescient_glyph: CardDefinition = {
  id: "s1_pack2_class_prescient_glyph" as CardDefinition["id"],
  name: "Glyph",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/prescient_glyph.webp"),
  flavorText: "Drawn the night before. The glyph reads tomorrow's wound and prepares for it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_prototype_blueprint: CardDefinition = {
  id: "s1_pack2_class_prototype_blueprint" as CardDefinition["id"],
  name: "Blueprint",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/prototype_blueprint.webp"),
  flavorText: "The blueprint is illegal in three jurisdictions. The fourth has not heard of it yet.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_rally_the_line: CardDefinition = {
  id: "s1_pack2_class_rally_the_line" as CardDefinition["id"],
  name: "The Line",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/rally_the_line.webp"),
  flavorText: "His voice is shorter than the order he gives. The line moves on the syllable.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_reader_of_tomorrows: CardDefinition = {
  id: "s1_pack2_class_reader_of_tomorrows" as CardDefinition["id"],
  name: "OF Tomorrows",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/reader_of_tomorrows.webp"),
  flavorText: "She reads the next four hours. She does not read past dusk. Dusk reads back.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_second_sight: CardDefinition = {
  id: "s1_pack2_class_second_sight" as CardDefinition["id"],
  name: "Sight",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/second_sight.webp"),
  flavorText: "The first sight is what's there. The second sight is what is about to be there.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_shieldwall: CardDefinition = {
  id: "s1_pack2_class_shieldwall" as CardDefinition["id"],
  name: "Shieldwall",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/shieldwall.webp"),
  flavorText: "Shoulder to shoulder, no gap. The wall is older than any soldier in it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_signal_ghost: CardDefinition = {
  id: "s1_pack2_class_signal_ghost" as CardDefinition["id"],
  name: "Ghost",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: ["ephemeral"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/signal_ghost.webp"),
  flavorText: "On every monitor, in no room. The signal arrives clean. The ghost arrived first.",
  rulesVersion: "1.1.0",
  trial_categories: ["narrative"] as const,
  verdict_delta: 0,
};

export const pack2_class_silent_step: CardDefinition = {
  id: "s1_pack2_class_silent_step" as CardDefinition["id"],
  name: "Step",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/silent_step.webp"),
  flavorText: "He walks across gravel without sound. The gravel agrees not to mention it.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_syncretic_adept: CardDefinition = {
  id: "s1_pack2_class_syncretic_adept" as CardDefinition["id"],
  name: "Adept",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/syncretic_adept.webp"),
  flavorText: "She has eaten three traditions. None of them digest cleanly; all three are in the strike.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_three_schools_master: CardDefinition = {
  id: "s1_pack2_class_three_schools_master" as CardDefinition["id"],
  name: "Schools Master",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/three_schools_master.webp"),
  flavorText: "He stands at the centre of the triangle. The triangle does not stand without him.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_twelfth_archon_apprentice: CardDefinition = {
  id: "s1_pack2_class_twelfth_archon_apprentice" as CardDefinition["id"],
  name: "Archon Apprentice",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/twelfth_archon_apprentice.webp"),
  flavorText: "Trained in the unfilled seat. The seat has waited a thousand years for an apprentice.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_witness_remover: CardDefinition = {
  id: "s1_pack2_class_witness_remover" as CardDefinition["id"],
  name: "Remover",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/witness_remover.webp"),
  flavorText: "There was a third person in the room. There is no longer a third person in the room.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_class_workshop_drone: CardDefinition = {
  id: "s1_pack2_class_workshop_drone" as CardDefinition["id"],
  name: "Drone",
  faction: "neutral",
  cardType: "unit",
  rarity: "common",
  cost: 2,
  baseStats: { power: 2, health: 2 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/class/workshop_drone.webp"),
  flavorText: "He has not left the workshop in six months. The workshop has begun to leave with him.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const S1_PACK2_CLASS_CARDS: readonly CardDefinition[] = [
  pack2_class_akai_shi_first_apprentice,
  pack2_class_auspex,
  pack2_class_burn_the_handler,
  pack2_class_cover_name,
  pack2_class_dead_drop,
  pack2_class_dual_discipline,
  pack2_class_engineers_apprentice,
  pack2_class_execute_protocol,
  pack2_class_field_modification,
  pack2_class_five_schools_avatar,
  pack2_class_glass_blade_initiate,
  pack2_class_hybrid_initiate,
  pack2_class_iron_vanguard,
  pack2_class_kinetic_containment_sink,
  pack2_class_last_regiment_standing,
  pack2_class_line_recruit,
  pack2_class_oracles_unbroken_signal,
  pack2_class_prescient_glyph,
  pack2_class_prototype_blueprint,
  pack2_class_rally_the_line,
  pack2_class_reader_of_tomorrows,
  pack2_class_second_sight,
  pack2_class_shieldwall,
  pack2_class_signal_ghost,
  pack2_class_silent_step,
  pack2_class_syncretic_adept,
  pack2_class_three_schools_master,
  pack2_class_twelfth_archon_apprentice,
  pack2_class_witness_remover,
  pack2_class_workshop_drone,
];
