/* AUTO-GENERATED by scripts/_gen-pack2-cards.mjs.
 * Re-export every Pack 2 net-new collection in one go. The cards/index.ts
 * registry imports + spreads ALL_S1_PACK2_CARDS once. */
import type { CardDefinition } from "../../../index";
import { S1_PACK2_ALLEGIANCE_CARDS } from "./allegiance";
import { S1_PACK2_ANTIQUARIAN_CARDS } from "./antiquarian";
import { S1_PACK2_ARCHITECT_CARDS } from "./architect";
import { S1_PACK2_CLASS_CARDS } from "./class";
import { S1_PACK2_DIMENSION_CARDS } from "./dimension";
import { S1_PACK2_DREAMER_CARDS } from "./dreamer";
import { S1_PACK2_ELEMENT_CARDS } from "./element";
import { S1_PACK2_INSURGENCY_CARDS } from "./insurgency";
import { S1_PACK2_NEUTRAL_CARDS } from "./neutral";
import { S1_PACK2_NEW_BABYLON_CARDS } from "./new_babylon";
import { S1_PACK2_PANOPTICON_CARDS } from "./panopticon";
import { S1_PACK2_RACE_CARDS } from "./race";
import { S1_PACK2_THOUGHT_VIRUS_CARDS } from "./thought_virus";

export const ALL_S1_PACK2_CARDS: readonly CardDefinition[] = [
  ...S1_PACK2_ALLEGIANCE_CARDS,
  ...S1_PACK2_ANTIQUARIAN_CARDS,
  ...S1_PACK2_ARCHITECT_CARDS,
  ...S1_PACK2_CLASS_CARDS,
  ...S1_PACK2_DIMENSION_CARDS,
  ...S1_PACK2_DREAMER_CARDS,
  ...S1_PACK2_ELEMENT_CARDS,
  ...S1_PACK2_INSURGENCY_CARDS,
  ...S1_PACK2_NEUTRAL_CARDS,
  ...S1_PACK2_NEW_BABYLON_CARDS,
  ...S1_PACK2_PANOPTICON_CARDS,
  ...S1_PACK2_RACE_CARDS,
  ...S1_PACK2_THOUGHT_VIRUS_CARDS,
];

export const S1_PACK2_TOTAL = ALL_S1_PACK2_CARDS.length;
