/**
 * Pack 2 base-set · race · 15 net-new card definitions.
 *
 * AUTO-GENERATED by scripts/_gen-pack2-cards.mjs from the
 * producer slugs in apps/shared/expansionArt/dischordiaBaseSet.ts.
 * Hand-edit individual cards in this file if design wants finer
 * tuning; the generator is idempotent on re-run (overwrites this
 * file, so move custom edits into per-slug overrides if you want
 * them to survive).
 *
 * Every ability list is currently empty — design owns the balance +
 * effect pass. CardIds use the s1_pack2_ namespace so they don't
 * collide with the existing s1_ defs.
 */
import type { CardDefinition } from "../../../index";
import { assetUrl } from "@shared/lib/assetUrl";

export const pack2_race_demagi_foot_soldier: CardDefinition = {
  id: "s1_pack2_race_demagi_foot_soldier" as CardDefinition["id"],
  name: "Foot Soldier",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/demagi_foot_soldier.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_demagi_war_priest: CardDefinition = {
  id: "s1_pack2_race_demagi_war_priest" as CardDefinition["id"],
  name: "War Priest",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/demagi_war_priest.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_demagi_xethraal_archlord: CardDefinition = {
  id: "s1_pack2_race_demagi_xethraal_archlord" as CardDefinition["id"],
  name: "Xethraal Archlord",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/demagi_xethraal_archlord.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_human_citizen_of_atarion: CardDefinition = {
  id: "s1_pack2_race_human_citizen_of_atarion" as CardDefinition["id"],
  name: "Citizen OF Atarion",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/human_citizen_of_atarion.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_human_final_potential: CardDefinition = {
  id: "s1_pack2_race_human_final_potential" as CardDefinition["id"],
  name: "Final Potential",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/human_final_potential.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_human_senate_legionary: CardDefinition = {
  id: "s1_pack2_race_human_senate_legionary" as CardDefinition["id"],
  name: "Senate Legionary",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/human_senate_legionary.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_neyon_adept: CardDefinition = {
  id: "s1_pack2_race_neyon_adept" as CardDefinition["id"],
  name: "Adept",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/neyon_adept.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_neyon_bondwalker: CardDefinition = {
  id: "s1_pack2_race_neyon_bondwalker" as CardDefinition["id"],
  name: "Bondwalker",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/neyon_bondwalker.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_neyon_kael_first: CardDefinition = {
  id: "s1_pack2_race_neyon_kael_first" as CardDefinition["id"],
  name: "Kael First",
  faction: "neutral",
  cardType: "unit",
  rarity: "legendary",
  cost: 7,
  baseStats: { power: 6, health: 6 },
  keywords: ["rush"],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/neyon_kael_first.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["offensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_quarchon_archivist: CardDefinition = {
  id: "s1_pack2_race_quarchon_archivist" as CardDefinition["id"],
  name: "Archivist",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/quarchon_archivist.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_quarchon_crystal_senator: CardDefinition = {
  id: "s1_pack2_race_quarchon_crystal_senator" as CardDefinition["id"],
  name: "Crystal Senator",
  faction: "neutral",
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/quarchon_crystal_senator.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_quarchon_latticework: CardDefinition = {
  id: "s1_pack2_race_quarchon_latticework" as CardDefinition["id"],
  name: "Latticework",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/quarchon_latticework.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_synthetic_loyal_instrument: CardDefinition = {
  id: "s1_pack2_race_synthetic_loyal_instrument" as CardDefinition["id"],
  name: "Loyal Instrument",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/synthetic_loyal_instrument.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_synthetic_watchtower: CardDefinition = {
  id: "s1_pack2_race_synthetic_watchtower" as CardDefinition["id"],
  name: "Watchtower",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/synthetic_watchtower.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const pack2_race_synthetic_worker: CardDefinition = {
  id: "s1_pack2_race_synthetic_worker" as CardDefinition["id"],
  name: "Worker",
  faction: "neutral",
  cardType: "unit",
  rarity: "uncommon",
  cost: 3,
  baseStats: { power: 3, health: 3 },
  keywords: [],
  abilities: [],  // AUTO-DRAFT — design owns balance + abilities pass
  art: assetUrl("art/cards/race/synthetic_worker.webp"),
  flavorText: "Born of a world that remembers its first breath.",
  rulesVersion: "1.1.0",
  trial_categories: ["defensive"] as const,
  verdict_delta: 0,
};

export const S1_PACK2_RACE_CARDS: readonly CardDefinition[] = [
  pack2_race_demagi_foot_soldier,
  pack2_race_demagi_war_priest,
  pack2_race_demagi_xethraal_archlord,
  pack2_race_human_citizen_of_atarion,
  pack2_race_human_final_potential,
  pack2_race_human_senate_legionary,
  pack2_race_neyon_adept,
  pack2_race_neyon_bondwalker,
  pack2_race_neyon_kael_first,
  pack2_race_quarchon_archivist,
  pack2_race_quarchon_crystal_senator,
  pack2_race_quarchon_latticework,
  pack2_race_synthetic_loyal_instrument,
  pack2_race_synthetic_watchtower,
  pack2_race_synthetic_worker,
];
