/**
 * S2 — Hierarchy of the Damned · Directors (14 epic · 5-cost · 5/5).
 * AUTO-GENERATED by scripts/_gen-s2-hierarchy-cards.mjs from the
 * producer-slug list. Hand-edit individual cards in this file if
 * design wants finer tuning; the generator is idempotent on re-run
 * (overwrites this file, so move custom edits into the generator's
 * per-slug overrides if you need them sticky).
 */
import type { CardDefinition } from "../../../index";
import { art, HIERARCHY_FACTION as F } from "./_art";

const RULES = "1.1.0";

export const dir_bottom_line_decimator: CardDefinition = {
  id: "s2_hierarchy_dir_bottom_line_decimator" as CardDefinition["id"],
  name: "Bottom Line Decimator",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["blast"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "bottom_line_decimator_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: {
        op: "deal_damage",
        amount: { kind: "const", value: 2 },
        to: { kind: "enemy_general" },
      },
    },
  ],
  art: art("s2_hierarchy_dir_bottom_line_decimator"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_compliance_inquisitor: CardDefinition = {
  id: "s2_hierarchy_dir_compliance_inquisitor" as CardDefinition["id"],
  name: "Compliance Inquisitor",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["dispel"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "compliance_inquisitor_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "silence", to: { kind: "trigger_source" } },
    },
  ],
  art: art("s2_hierarchy_dir_compliance_inquisitor"),
  flavorText: "The audit is procedural. The findings are not.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_cross_functional_predator: CardDefinition = {
  id: "s2_hierarchy_dir_cross_functional_predator" as CardDefinition["id"],
  name: "Cross Functional Predator",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["drain"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "cross_functional_predator_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_damage_dealt", by: "self" },
      effect: { op: "heal", amount: { kind: "const", value: 1 }, to: { kind: "self" } },
    },
  ],
  art: art("s2_hierarchy_dir_cross_functional_predator"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_fenra: CardDefinition = {
  id: "s2_hierarchy_dir_fenra" as CardDefinition["id"],
  name: "Fenra",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],
  art: art("s2_hierarchy_dir_fenra"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_jira_ghoul: CardDefinition = {
  id: "s2_hierarchy_dir_jira_ghoul" as CardDefinition["id"],
  name: "Jira Ghoul",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_dir_jira_ghoul"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_metrics_oracle: CardDefinition = {
  id: "s2_hierarchy_dir_metrics_oracle" as CardDefinition["id"],
  name: "Metrics Oracle",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["ranged"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "metrics_oracle_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "draw", amount: { kind: "const", value: 1 }, who: "self" },
    },
  ],
  art: art("s2_hierarchy_dir_metrics_oracle"),
  flavorText: "The dashboard speaks. The dashboard is always speaking. You stopped listening years ago.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_okr_specter: CardDefinition = {
  id: "s2_hierarchy_dir_okr_specter" as CardDefinition["id"],
  name: "Okr Specter",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_dir_okr_specter"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_pivot_demon: CardDefinition = {
  id: "s2_hierarchy_dir_pivot_demon" as CardDefinition["id"],
  name: "Pivot Demon",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["fury"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "pivot_demon_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_turn_end", owner: "self" },
      effect: {
        op: "buff",
        stats: { power: 1, health: 0 },
        duration: { kind: "permanent" },
        to: { kind: "self" },
      },
    },
  ],
  art: art("s2_hierarchy_dir_pivot_demon"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_q4_ritualist: CardDefinition = {
  id: "s2_hierarchy_dir_q4_ritualist" as CardDefinition["id"],
  name: "Q4 Ritualist",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [
    {
      // AUTO-DRAFT
      id: "q4_ritualist_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_turn_end", owner: "self" },
      effect: {
        op: "buff",
        stats: { power: 1, health: 0 },
        duration: { kind: "permanent" },
        to: { kind: "self" },
      },
    },
  ],
  art: art("s2_hierarchy_dir_q4_ritualist"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_rif_custodian: CardDefinition = {
  id: "s2_hierarchy_dir_rif_custodian" as CardDefinition["id"],
  name: "Rif Custodian",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [
    {
      // AUTO-DRAFT
      id: "rif_custodian_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_any_unit_dies", filter: { faction: [F] } },
      effect: { op: "draw", amount: { kind: "const", value: 1 }, who: "self" },
    },
  ],
  art: art("s2_hierarchy_dir_rif_custodian"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_synergy_vampire: CardDefinition = {
  id: "s2_hierarchy_dir_synergy_vampire" as CardDefinition["id"],
  name: "Synergy Vampire",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["drain"],
  abilities: [
    {
      // AUTO-DRAFT
      id: "synergy_vampire_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_damage_dealt", by: "self" },
      effect: { op: "heal", amount: { kind: "const", value: 1 }, to: { kind: "self" } },
    },
  ],
  art: art("s2_hierarchy_dir_synergy_vampire"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_townhall_phantom: CardDefinition = {
  id: "s2_hierarchy_dir_townhall_phantom" as CardDefinition["id"],
  name: "Townhall Phantom",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_dir_townhall_phantom"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_velm_acrith: CardDefinition = {
  id: "s2_hierarchy_dir_velm_acrith" as CardDefinition["id"],
  name: "Velm Acrith",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: [],
  abilities: [],
  art: art("s2_hierarchy_dir_velm_acrith"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const dir_velocity_wraith: CardDefinition = {
  id: "s2_hierarchy_dir_velocity_wraith" as CardDefinition["id"],
  name: "Velocity Wraith",
  faction: F,
  cardType: "unit",
  rarity: "epic",
  cost: 5,
  baseStats: { power: 5, health: 5 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_dir_velocity_wraith"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const S2_HIERARCHY_DIRECTORS: readonly CardDefinition[] = [
  dir_bottom_line_decimator,
  dir_compliance_inquisitor,
  dir_cross_functional_predator,
  dir_fenra,
  dir_jira_ghoul,
  dir_metrics_oracle,
  dir_okr_specter,
  dir_pivot_demon,
  dir_q4_ritualist,
  dir_rif_custodian,
  dir_synergy_vampire,
  dir_townhall_phantom,
  dir_velm_acrith,
  dir_velocity_wraith,
];
