/**
 * S2 — Hierarchy of the Damned · Managers (18 rare · 4-cost · 4/4).
 * AUTO-GENERATED by scripts/_gen-s2-hierarchy-cards.mjs.
 */
import type { CardDefinition } from "../../../index";
import { hierarchyOfDamnedArtUrl } from "../../../../expansionArt/hierarchyOfDamned";

const RULES = "1.0.0";
const F = "hierarchy_of_damned" as const;

function art(id: string): string {
  const url = hierarchyOfDamnedArtUrl(id);
  if (!url) throw new Error(`hierarchyOfDamnedArtUrl missing for ${id}`);
  return url;
}

export const mgr_backlog_maw: CardDefinition = {
  id: "s2_hierarchy_mgr_backlog_maw" as CardDefinition["id"],
  name: "Backlog Maw",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["provoke"],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "backlog_maw_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "discard", amount: { kind: "const", value: 1 }, from: "opponent", mode: "random" },
    },
  ],
  art: art("s2_hierarchy_mgr_backlog_maw"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_burndown_imp: CardDefinition = {
  id: "s2_hierarchy_mgr_burndown_imp" as CardDefinition["id"],
  name: "Burndown Imp",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [],
  art: art("s2_hierarchy_mgr_burndown_imp"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_calendar_demon: CardDefinition = {
  id: "s2_hierarchy_mgr_calendar_demon" as CardDefinition["id"],
  name: "Calendar Demon",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [],
  art: art("s2_hierarchy_mgr_calendar_demon"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_channel_conflict_goblin: CardDefinition = {
  id: "s2_hierarchy_mgr_channel_conflict_goblin" as CardDefinition["id"],
  name: "Channel Conflict Goblin",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [],
  art: art("s2_hierarchy_mgr_channel_conflict_goblin"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_demand_gen_phantom: CardDefinition = {
  id: "s2_hierarchy_mgr_demand_gen_phantom" as CardDefinition["id"],
  name: "Demand Gen Phantom",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "demand_gen_phantom_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "discard", amount: { kind: "const", value: 1 }, from: "opponent", mode: "random" },
    },
  ],
  art: art("s2_hierarchy_mgr_demand_gen_phantom"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_estimation_goblin: CardDefinition = {
  id: "s2_hierarchy_mgr_estimation_goblin" as CardDefinition["id"],
  name: "Estimation Goblin",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "estimation_goblin_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "discard", amount: { kind: "const", value: 1 }, from: "opponent", mode: "random" },
    },
  ],
  art: art("s2_hierarchy_mgr_estimation_goblin"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_midyear_adjuster: CardDefinition = {
  id: "s2_hierarchy_mgr_midyear_adjuster" as CardDefinition["id"],
  name: "Midyear Adjuster",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: [],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "midyear_adjuster_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_turn_end", owner: "self" },
      effect: {
        op: "buff",
        stats: { power: 1, health: 0 },
        duration: { kind: "permanent" },
        to: { kind: "self" },
      },
    },
  ],
  art: art("s2_hierarchy_mgr_midyear_adjuster"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_perf_review_wraith: CardDefinition = {
  id: "s2_hierarchy_mgr_perf_review_wraith" as CardDefinition["id"],
  name: "Perf Review Wraith",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_mgr_perf_review_wraith"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_pivot_memo_phantom: CardDefinition = {
  id: "s2_hierarchy_mgr_pivot_memo_phantom" as CardDefinition["id"],
  name: "Pivot Memo Phantom",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "pivot_memo_phantom_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_turn_end", owner: "self" },
      effect: {
        op: "buff",
        stats: { power: 1, health: 0 },
        duration: { kind: "permanent" },
        to: { kind: "self" },
      },
    },
  ],
  art: art("s2_hierarchy_mgr_pivot_memo_phantom"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_process_imp: CardDefinition = {
  id: "s2_hierarchy_mgr_process_imp" as CardDefinition["id"],
  name: "Process Imp",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [],
  art: art("s2_hierarchy_mgr_process_imp"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_quarterly_forecaster: CardDefinition = {
  id: "s2_hierarchy_mgr_quarterly_forecaster" as CardDefinition["id"],
  name: "Quarterly Forecaster",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: [],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "quarterly_forecaster_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_deploy" },
      effect: { op: "draw", amount: { kind: "const", value: 1 }, who: "self" },
    },
  ],
  art: art("s2_hierarchy_mgr_quarterly_forecaster"),
  flavorText: "The dashboard speaks. The dashboard is always speaking. You stopped listening years ago.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_reorg_specter: CardDefinition = {
  id: "s2_hierarchy_mgr_reorg_specter" as CardDefinition["id"],
  name: "Reorg Specter",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [
    {
      // AUTO-DRAFT — slug-derived ability template
      id: "reorg_specter_signature" as CardDefinition["abilities"][number]["id"],
      trigger: { kind: "on_turn_end", owner: "self" },
      effect: {
        op: "buff",
        stats: { power: 1, health: 0 },
        duration: { kind: "permanent" },
        to: { kind: "self" },
      },
    },
  ],
  art: art("s2_hierarchy_mgr_reorg_specter"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_roadmap_banshee: CardDefinition = {
  id: "s2_hierarchy_mgr_roadmap_banshee" as CardDefinition["id"],
  name: "Roadmap Banshee",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ranged"],
  abilities: [],
  art: art("s2_hierarchy_mgr_roadmap_banshee"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_slack_phantom: CardDefinition = {
  id: "s2_hierarchy_mgr_slack_phantom" as CardDefinition["id"],
  name: "Slack Phantom",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_mgr_slack_phantom"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_stakeholder_wrangler: CardDefinition = {
  id: "s2_hierarchy_mgr_stakeholder_wrangler" as CardDefinition["id"],
  name: "Stakeholder Wrangler",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["provoke"],
  abilities: [],
  art: art("s2_hierarchy_mgr_stakeholder_wrangler"),
  flavorText: "Another seat at another table that did not need to exist.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_stand_up_wraith: CardDefinition = {
  id: "s2_hierarchy_mgr_stand_up_wraith" as CardDefinition["id"],
  name: "Stand Up Wraith",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_mgr_stand_up_wraith"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_token_economy_imp: CardDefinition = {
  id: "s2_hierarchy_mgr_token_economy_imp" as CardDefinition["id"],
  name: "Token Economy Imp",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["fury"],
  abilities: [],
  art: art("s2_hierarchy_mgr_token_economy_imp"),
  flavorText: "Small. Persistent. Erodes by attrition. Already on your calendar.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const mgr_vendor_mgmt_wraith: CardDefinition = {
  id: "s2_hierarchy_mgr_vendor_mgmt_wraith" as CardDefinition["id"],
  name: "Vendor Mgmt Wraith",
  faction: F,
  cardType: "unit",
  rarity: "rare",
  cost: 4,
  baseStats: { power: 4, health: 4 },
  keywords: ["ephemeral"],
  abilities: [],
  art: art("s2_hierarchy_mgr_vendor_mgmt_wraith"),
  flavorText: "It does not haunt the meeting. It IS the meeting.",
  rulesVersion: RULES,
  trial_categories: ["evidence"] as const,
  verdict_delta: -1,
};

export const S2_HIERARCHY_MANAGERS: readonly CardDefinition[] = [
  mgr_backlog_maw,
  mgr_burndown_imp,
  mgr_calendar_demon,
  mgr_channel_conflict_goblin,
  mgr_demand_gen_phantom,
  mgr_estimation_goblin,
  mgr_midyear_adjuster,
  mgr_perf_review_wraith,
  mgr_pivot_memo_phantom,
  mgr_process_imp,
  mgr_quarterly_forecaster,
  mgr_reorg_specter,
  mgr_roadmap_banshee,
  mgr_slack_phantom,
  mgr_stakeholder_wrangler,
  mgr_stand_up_wraith,
  mgr_token_economy_imp,
  mgr_vendor_mgmt_wraith,
];
