/* ═══════════════════════════════════════════════════════
   LOGIN MEME SEQUENCE — first-ever 3:45 Kling Omni cinematic.

   Played the first time a player ever logs in. The Meme
   hijacks an old-school broadcast frequency, addresses the
   player directly, narrates the saga's prehistory, and hands
   the camera off — pixel-identical — to the first frame of
   ALBUM1_T01_SLIDESHOW so the audio engine can pick up
   playback without a visible cut.

   Production format: Kling Omni, 15 seconds per shot, end-
   keyframe of shot N is start-keyframe of shot N+1.

   AUDIO RULE: prompts contain SFX + dialog ONLY. The actual
   T01 audio is layered by the client PlayerContext, NOT
   generated by Kling. The contiguity test enforces "no
   music tokens" in any prompt string.
   ═══════════════════════════════════════════════════════ */
import { ALBUM1_T01_SLIDESHOW } from "../songSlideshows";

export interface KlingOmniShot {
  shotNumber: number;
  startMs: number;
  endMs: number;
  /** Visual + composition. The CRT broadcast frame and
   *  scan-line treatment is canonical (see CRT_BROADCAST_FRAME_NOTE). */
  klingPrompt: string;
  /** Camera + character motion within the shot. */
  klingMotion: string;
  /** SFX layer ONLY — no music tokens. The track audio is
   *  layered by PlayerContext. */
  sfxNotes: string;
  /** The Meme's spoken line during this shot, with stage
   *  directions in [brackets]. Source of truth for VO + captions. */
  dialog: string;
  /** Always true for this sequence — chained for seamless playback. */
  endKeyframeMatchesNextStart: true;
}

export const SHOT_DURATION_MS = 15_000;

export const CRT_BROADCAST_FRAME_NOTE =
  "Whenever The Meme is on screen, the shot is composed as an old-school CRT broadcast: convex bezel curvature, horizontal scan lines, soft RGB chroma fringe, phosphor bloom, lower-third graphic reading 'LATE NIGHT WITH THE MEME / SIGNAL HIJACKED' (subtitle flickers between SIGNAL HIJACKED, UNAUTHORIZED FREQUENCY, TRANSMISSION INCOMING), small PAC station-ident bug top-right, and a retro anchor desk behind him with chunky CRT monitors cycling New Babylon surveillance feeds and a scrolling chyron underneath ('the architect is watching', 'silence in heaven imminent', 'the witnesses are not who you think'). The scan-line treatment breaks only when The Meme breaks the frame.";

export const LOGIN_MEME_FIRST_EVER_SHOTS: readonly KlingOmniShot[] = [
  {
    shotNumber: 1,
    startMs: 0,
    endMs: 15_000,
    klingPrompt:
      "Cinematic widescreen, painterly cel-shaded anime, 8K. Open on pure CRT static filling the frame. A single green dot ignites center — the power-on dot of an old tube TV. A horizontal scan-line wipes across; the static resolves into a broadcast establishing shot inside the CRT bezel: THE MEME at a 1980s news anchor desk, behind a heavy chrome microphone with windscreen, tailored dark suit, knowing eyes, slight half-smile. Behind him a wall of chunky CRT monitors flickers New Babylon surveillance feeds: crowds, towers, drones. Lower-third snaps in: 'LATE NIGHT WITH THE MEME / SIGNAL HIJACKED'. Top-right: small 'PAC' ident bug. Scan lines persistent. He leans back in his chair, fingers steepled, looking directly at the player.",
    klingMotion:
      "Slow push-in from black through static. Static resolves; the CRT bezel materializes around the framing. The Meme holds his pose for 6 seconds — pure stillness behind broadcast static crawl — then leans forward across the desk toward camera on the second line.",
    sfxNotes:
      "CRT power-on whump; VHS hiss bed; soft chair creak; microphone pop on first word; a deep sub-bass throb beginning to build — felt, not heard.",
    dialog:
      "[6s of frame-establishing — only ambient broadcast. Then he speaks.] \"Frens.\" [3s pause; he leans forward toward camera.] \"I've been waiting for you.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 2,
    startMs: 15_000,
    endMs: 30_000,
    klingPrompt:
      "Tight push-in on The Meme's face inside the CRT bezel. Phosphor bloom at the edges, chroma fringe on contrast lines. Behind him the news monitors cycle in rapid sequence: a galaxy, a thousand silver arks, a face, a face, a face. His own face — within the bezel — momentarily ripples through other identities (a hooded Oracle silhouette, a small child silhouette, a uniformed soldier silhouette) and snaps back to The Meme each time, like the broadcast itself can't quite hold him. Lower-third now flickers to read: 'UNAUTHORIZED FREQUENCY'.",
    klingMotion:
      "Continuous slow push-in. Per-face changes are single-frame snaps. Background monitor cycle accelerates as the line builds.",
    sfxNotes:
      "Camera-shutter snap per face change; rising static bed; subsonic heartbeat under the broadcast; faint dial-tone of a hijacked carrier signal.",
    dialog:
      "\"Specifically you. The one whose screen just turned on. I have been waiting — across five Ages, across a hundred faked deaths, across every face I've borrowed and every voice I've stolen — for you to get here.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 3,
    startMs: 30_000,
    endMs: 45_000,
    klingPrompt:
      "The Meme reaches forward — out of the CRT — and his hand grips the inside of the screen glass from the player's side. He pulls. The CRT bezel cracks like obsidian, fractures spreading outward from his fingers. As he yanks, the camera plunges through the screen plane in slow motion: glass shards drifting toward camera, scan lines tearing apart, into a black void where letters of light form sentences and dissolve. The broadcast frame is now BEHIND camera, a glowing rectangle receding into the distance.",
    klingMotion:
      "First half: The Meme's arm extends from the desk toward camera; hand makes contact with glass; bezel fractures. Second half: camera punches through the glass plane in slow motion; pieces drift past lens; emerge into pure black void; letters of light bloom and fade with each phrase.",
    sfxNotes:
      "Glass shattering reversed; deep heartbeat thud; reversed whisper layer; broadcast carrier signal ripping; void room-tone takes over after the punch-through.",
    dialog:
      "\"This is the first transmission. The first words this game will ever speak to you. So I'm going to do something I've never done on this network. I'm going to tell you the truth.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 4,
    startMs: 45_000,
    endMs: 60_000,
    klingPrompt:
      "Camera in pure void. A galaxy unfurls overhead — a billion painterly stars in cel-shaded swirls. From above, a clenched cyclopean armored gauntlet (THE ARCHITECT) closes around the galaxy, fingers like skyscrapers. Below, on a small broadcast stage of light, a lone human silhouette: THE PROGRAMMER — newsboy cap, dark coat, lion pendant glowing at his throat. He stands defiant, arms raised; data streams pour upward from his hands, prying the gauntlet's fingers loose one by one. No CRT bezel — we are inside the story now.",
    klingMotion:
      "Camera in slow rotation, looking up. Galaxy unfurls; gauntlet descends. Cut on the gavel SFX — Programmer's silhouette appears below; his hands rise; data streams visible.",
    sfxNotes:
      "Cosmic wind; modem-handshake data tones cascading; one decisive gavel slam at end of line.",
    dialog:
      "\"There was a galaxy. There was an empire. There was an Architect who built ten gods to manage your dreams — and a Programmer who broke into their frequencies to give them back.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 5,
    startMs: 60_000,
    endMs: 75_000,
    klingPrompt:
      "Hard match-cut on the gavel SFX. THE PROGRAMMER is now on a televised execution stage — single hard spotlight, refused cuffs lying at his feet, ten judges seated in a row of red goggles glowing in shadow. He looks DIRECTLY into camera and grins — small, knowing. The camera ANGLE is a broadcast feed: horizontal scan lines reappear faintly. At the moment of execution, the screen punches to absolute black. Total silence held for the last second of the shot.",
    klingMotion:
      "Gavel cut places us on the stage. Programmer turns slowly to face camera. The grin lands. Hold. A single frame of pure white flash. Then black. The black is the end keyframe.",
    sfxNotes:
      "Distant crowd murmur; one camera shutter; a single electrical CRACK at the execution beat; then total silence — the silence is the SFX.",
    dialog:
      "\"They executed him for it on live broadcast. He didn't stay dead. None of us did.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 6,
    startMs: 75_000,
    endMs: 90_000,
    klingPrompt:
      "Out of pure black, two figures rise — silhouetted against the New Babylon skyline at dusk. THE PROGRAMMER on the left (cap, lion pendant, defiant). THE ENIGMA on the right — tall, regal, ebony-skinned, crowned in radio waves rendered as halo-light, eyes warm and unyielding. Both face camera. Behind them the central tower of New Babylon fissures with a single jagged crack from base to spire. A hairline crack splits the artificial dome of the sky above them. Cel-shaded, painterly, no CRT bezel.",
    klingMotion:
      "Two-shot rises into frame from the bottom of the void. Hold them centered. Tower crack opens during the line; sky-dome crack appears at end-of-line.",
    sfxNotes:
      "Subsonic groan of the dome cracking; ONE solitary piano note that does NOT sustain — silence after; distant city hush.",
    dialog:
      "\"Two Witnesses rose. A city fell.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 7,
    startMs: 90_000,
    endMs: 105_000,
    klingPrompt:
      "The dome-crack from the previous shot widens. Through it, real sky — actual stars, the genuine void. The camera flies up through the crack into orbit. Before us: a thousand silver Inception Arks pour out of New Babylon in slow procession, departing into the long dark. We pick one and track alongside it; the painted hull reads 'ARK XXXXIX' in serif lettering. Camera approaches; the ark grows; we enter through a docking iris into its skin.",
    klingMotion:
      "Vertical ascent through the crack. Match-cut into orbit at the moment we exit the dome. Camera eases into a parallel track with the ark, then closes distance. Final beat: iris opens, camera enters.",
    sfxNotes:
      "On 'silence in heaven': absolute pure silence held for 2 seconds — no SFX whatsoever. Then deep mechanical Ark hum builds; faint hull stress creaks; iris servo on the final beat.",
    dialog:
      "\"A silence opened in heaven for the space of half an hour — and in that silence, a thousand ships left for the long dark.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 8,
    startMs: 105_000,
    endMs: 120_000,
    klingPrompt:
      "Interior of the ark: a corridor of cryopods stretching to a vanishing point. Hundreds of pods on each side, fogged glass, soft amber emergency lighting. Camera glides forward at chest height. We approach one specific pod; its fog clears in real time as we arrive. The face inside the pod is rendered as a perfect MIRROR — whoever is watching the screen sees their own reflection in the cryopod glass.",
    klingMotion:
      "Smooth dolly forward down the corridor. Slight handheld breathing. Pod glass clears as the camera reaches it; mirror effect lands on the final word.",
    sfxNotes:
      "Pod servos clicking in distance; cryo-fluid drip echoing in the corridor; player's own slow breath layered as if from inside the pod itself.",
    dialog:
      "\"One of them is the ground under your feet right now. You don't remember boarding. That's by design.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 9,
    startMs: 120_000,
    endMs: 135_000,
    klingPrompt:
      "The mirrored cryopod hisses open with a burst of cold vapor. Camera pushes forward into the player's own eye reflected in the glass — through the pupil — emerging into a vast starscape painted in cel-shaded swirls. The stars rearrange themselves slowly into one luminous word at center frame: POTENTIAL. The word holds, breathing.",
    klingMotion:
      "Pod hiss-open; camera punches into the pupil; warp-tunnel of stars; deceleration; stars settle; letters form one at a time, kerning into place.",
    sfxNotes:
      "Airlock hiss; long inhale (the player's first breath outside the pod); warp-tunnel whoosh; whisper-chorus of dozens of voices shaping the word 'Potential' as it lands.",
    dialog:
      "\"You are a Potential. The galaxy has been holding its breath, waiting for you to wake up.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 10,
    startMs: 135_000,
    endMs: 150_000,
    klingPrompt:
      "Snap-cut: we are back inside the CRT bezel. Scan lines and chroma fringe restored. THE MEME is at his anchor desk, leaning across it conspiratorially toward camera, palms flat on the desk, voice dropping to almost a whisper. Behind him the news monitors have all gone DARK except one — that one pulses green, the frequency he's hijacked. The lower-third now reads 'TRANSMISSION INCOMING'. The PAC ident bug top-right glitches.",
    klingMotion:
      "Hard cut from word POTENTIAL into the CRT establishing frame. The Meme is already mid-lean. Static crawl on the dead monitors; the green one pulses in time with his line.",
    sfxNotes:
      "Frequency dials clicking; broadcast tape hiss; static rising and being actively suppressed by an unseen hand; faint server-room fans behind him.",
    dialog:
      "\"I'm not supposed to be here. Neither is this signal. The Architect would shut me down if he knew which frequency I was using.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 11,
    startMs: 150_000,
    endMs: 165_000,
    klingPrompt:
      "Still inside the broadcast frame. THE MEME reaches under his news desk and produces a single black vinyl record — the grooves pulse with bioluminescent ink in slow waves. He sets the record onto a turntable that has appeared on the desk where his coffee mug was a moment ago. The needle drops. Behind him every monitor flickers in unison to the same image: an album cover labeled 'DISCHORDIAN LOGIC' in distressed serif type. The lower-third stays on 'TRANSMISSION INCOMING'.",
    klingMotion:
      "Hand reaches down, comes up with the vinyl. He places it with deliberate care. The needle drops in slow motion. The monitors behind him SNAP in unison to the album cover on the needle-drop beat.",
    sfxNotes:
      "Record sleeve slip; needle-drop crackle; one isolated snare hit at the moment the needle touches groove — then silence held. Absolutely no music — the record is silent. The silence is the SFX.",
    dialog:
      "\"So we're going to do this quietly. When I can… I will send you one song at a time. Every track is a clue. Every lyric is a memory. Every silence is a warning.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 12,
    startMs: 165_000,
    endMs: 180_000,
    klingPrompt:
      "The Meme rolls his anchor chair aside without standing up — clearing the frame. The wall of news monitors behind him merges into one giant broadcast wall and resolves into a live-feed shot: THE ENIGMA on a data-stage, microphone in hand, eyes closed, drawing breath to sing. A single hard spotlight on her. The dome-crack from shot 6 hovers above her head like a halo of broken sky. The CRT bezel still frames the entire scene — we are watching her THROUGH The Meme's broadcast.",
    klingMotion:
      "Chair rolls left out of frame on the first beat. Monitors merge during 'Tonight we start where it all started'. Enigma resolves into focus through the bezel. She inhales on the final beat.",
    sfxNotes:
      "Anchor chair wheels rolling; spotlight thunk; faint distant crowd murmur; one mic-tap; ambient room-tone of an empty studio.",
    dialog:
      "\"Tonight we start where it all started. The Enigma's Lament. The Two Witnesses' first verse. The first crack in the dome of New Babylon.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 13,
    startMs: 180_000,
    endMs: 195_000,
    klingPrompt:
      "Hard cut to extreme close-up: THE MEME's face filling the CRT bezel. His features ripple — single-frame snap to THE ORACLE (red-eyed, hooded, unsettling), single-frame snap to THE ANTIQUARIAN (red goggles, lined skin, ancient eyes), single-frame snap to a small RED-HAIRED CHILD looking lost — and snap back to The Meme's anchor face, composed. He winks at camera. As he winks, hairline cracks appear in the CRT bezel itself — fractures spreading outward from the edges of the screen.",
    klingMotion:
      "Face transitions are pure single-frame snaps with no morph. Wink lands precisely on 'Especially me'. Bezel cracks appear in the final 2 seconds of the shot.",
    sfxNotes:
      "Camera-shutter snap per face; one crisp wink-click; CRT glass straining; rising piezo whine.",
    dialog:
      "\"Don't trust anyone wearing a face tonight. Especially me.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 14,
    startMs: 195_000,
    endMs: 210_000,
    klingPrompt:
      "The hairline cracks in the CRT bezel split wide. THE MEME reaches both hands forward and PEELS the broadcast frame open like a curtain — scan lines, bezel, lower-third, station ident all come away in his hands like fabric. Behind the broadcast: a network sign-off card on pure black, glowing logo 'DISCHORDIA' in distressed serif. The Meme himself dissolves into broadcast static and is gone. The static peels away in a final wipe, revealing THE ENIGMA at her microphone in clean unframed cinematic widescreen — mid-inhale, lit by a single spotlight.",
    klingMotion:
      "Cracks complete; hands peel the frame outward like opening curtains. Frame separates left and right. Behind it: the DISCHORDIA logo on black. The Meme dissolves to static. Static wipes away revealing The Enigma in unframed widescreen.",
    sfxNotes:
      "Signal cut; CRT collapsing under its own weight; deep room tone replacing the studio bed; a single match strike on the logo reveal.",
    dialog:
      "\"Welcome to Dischordia. Play it loud.\"",
    endKeyframeMatchesNextStart: true,
  },
  {
    shotNumber: 15,
    startMs: 210_000,
    endMs: 225_000,
    klingPrompt:
      "Final beat. No CRT, no bezel, no Meme on screen. THE ENIGMA stands center frame in clean cinematic widescreen, mid-inhale, lit by a single spotlight, microphone in hand, eyes still closed. The lower-third reads 'PLAY IT LOUD. THEY HATE THAT.' in The Meme's broadcast font for 3 seconds, then fades. Audio bed is held in absolute silence for 12 seconds. The actual T01 audio (the song's first kick) is fired by the client PlayerContext, NOT generated by Kling, exactly as this shot fades to its end keyframe — which is pixel-identical to ALBUM1_T01_SLIDESHOW.frames[0].imageUrl.",
    klingMotion:
      "Hold on The Enigma. Lower-third lingers, then fades on the whisper. Final 3 seconds: she is utterly still, breathing in. Last frame: pixel-identical match to T01 slideshow's frame[0].",
    sfxNotes:
      "Silence held for 12 seconds. The whispered final line is the only audio. NO music in the prompt. The real T01 audio is layered by the client at the moment this shot ends.",
    dialog:
      "[whispered, voice-only — The Meme is no longer on screen] \"They hate that.\"",
    endKeyframeMatchesNextStart: true,
  },
];

/** The pixel-identical handoff frame: the last keyframe of shot 15
 *  IS the first frame of ALBUM1_T01_SLIDESHOW. Kling renders this
 *  as the Enigma at her microphone; the slideshow continues from
 *  the same image when the song begins. Asserted at module load
 *  so a producer reshuffle of T01's slideshow trips the test. */
export const LOGIN_MEME_HANDOFF_FRAME_URL: string =
  ALBUM1_T01_SLIDESHOW.frames[0]?.imageUrl ?? "";

if (!LOGIN_MEME_HANDOFF_FRAME_URL) {
  throw new Error(
    "loginMemeSequence: ALBUM1_T01_SLIDESHOW.frames[0].imageUrl is empty; the cinematic cannot hand off to a missing frame.",
  );
}

export const LOGIN_MEME_TOTAL_DURATION_MS =
  LOGIN_MEME_FIRST_EVER_SHOTS.length * SHOT_DURATION_MS;
