/* ═══════════════════════════════════════════════════════
   WOLF-HUNT — Hero target registry

   Single source of truth for the 250-hero Wolf-Anara
   hunt matrix. Every dossier is imported here and
   validated through heroTargetSchema at module load.

   Authoring cadence: the registry ships partial and
   ratchets toward 250. The ship-check parity row
   `wolfHunt.hero_target_coverage` enforces non-regression;
   the `wolfHunt.boss_lieutenant_coverage` row enforces
   hard parity 10/10 on the lieutenant subset.

   File layout: dossiers live under
   `<lordKey>/<heroId>.ts`, one file per hero. Adding a
   hero is: (1) author the dossier file, (2) import it
   here, (3) spread it into ALL_HERO_TARGETS. The bulk of
   the registry was generated by apps/scripts/seed-hero-
   dossiers.ts (C-pivot.C.1); the 10 lieutenants were
   hand-authored.
   ═══════════════════════════════════════════════════════ */

import type { HeroTarget } from "../types/HeroTarget";
import { CORE_HIERARCHY_LORD_IDS } from "../types/HeroTarget";
import type { CoreHierarchyLordId } from "../types/HeroTarget";
import { heroTargetSchema } from "./schema";

import { GENERAL_CAEDRYN_VOLK } from "./mol_garath/general_caedryn_volk";
import { AUDITOR_MIREILLE_YOM } from "./xeth_raal/auditor_mireille_yom";
import { MARSHAL_ORIN_THACE } from "./riri_ahlia/marshal_orin_thace";
import { PRAXIS_THREE_MIRA_VOLL } from "./zyr_koth/praxis_three_mira_voll";
import { LISTENER_EYRA_SHEEL } from "./ith_rael/listener_eyra_sheel";
import { PERSUADER_KAL_DEMIR } from "./syl_vex/persuader_kal_demir";
import { REAPER_NYX_SABLE } from "./drael_mon/reaper_nyx_sable";
import { BLOODSPEAKER_TESSEN_RAHL } from "./varkul/bloodspeaker_tessen_rahl";
import { MOONSCRIBE_ILARA_PELL } from "./fenra/moonscribe_ilara_pell";
import { ARCHITECT_RIVEN_SOLACE } from "./mol_vereth/architect_riven_solace";
import { ARCHITECT_BRANN_HALT_MOL } from "./mol_garath/architect_brann_halt_mol";
import { ARCHITECT_CASSI_IRONCAUL_MOL } from "./mol_garath/architect_cassi_ironcaul_mol";
import { ARCHITECT_DAVYL_QUILL_MARK_MOL } from "./mol_garath/architect_davyl_quill_mark_mol";
import { AUSPEX_ERITH_CALIBRE_MOL } from "./mol_garath/auspex_erith_calibre_mol";
import { AUSPEX_FERREN_VEIL_MOL } from "./mol_garath/auspex_ferren_veil_mol";
import { SCRIBE_GIDA_TRACEWELL_MOL } from "./mol_garath/scribe_gida_tracewell_mol";
import { REAPER_HALEN_HOLLOWAY_MOL } from "./mol_garath/reaper_halen_holloway_mol";
import { REAPER_ILYA_ASH_HAND_MOL } from "./mol_garath/reaper_ilya_ash_hand_mol";
import { REAPER_JOREN_TALLY_MOL } from "./mol_garath/reaper_joren_tally_mol";
import { QUIETUS_KAEL_ENDSIGN_MOL } from "./mol_garath/quietus_kael_endsign_mol";
import { REAPER_LYRA_CROCUS_MOL } from "./mol_garath/reaper_lyra_crocus_mol";
import { REAPER_MAVIK_SALT_MOL } from "./mol_garath/reaper_mavik_salt_mol";
import { LIEUTENANT_NIALL_VANGUARD_MOL } from "./mol_garath/lieutenant_niall_vanguard_mol";
import { SERGEANT_ORYN_RANKS_MOL } from "./mol_garath/sergeant_oryn_ranks_mol";
import { SERGEANT_PELL_MARSHAL_MOL } from "./mol_garath/sergeant_pell_marshal_mol";
import { CAPTAIN_QUEN_MARSH_MOL } from "./mol_garath/captain_quen_marsh_mol";
import { LIEUTENANT_RHIAN_STANDARDBEARER_MOL } from "./mol_garath/lieutenant_rhian_standardbearer_mol";
import { SERGEANT_SOREN_BASTION_MOL } from "./mol_garath/sergeant_soren_bastion_mol";
import { SERGEANT_TALIA_RANK_MOL } from "./mol_garath/sergeant_talia_rank_mol";
import { CAPTAIN_ULVI_QUARTERMASTER_MOL } from "./mol_garath/captain_ulvi_quartermaster_mol";
import { LIEUTENANT_VESH_WALLBORN_MOL } from "./mol_garath/lieutenant_vesh_wallborn_mol";
import { SERGEANT_WYNN_FLAGCALLER_MOL } from "./mol_garath/sergeant_wynn_flagcaller_mol";
import { HANDLER_XALA_TWO_HANDS_MOL } from "./mol_garath/handler_xala_two_hands_mol";
import { LISTENER_YARROW_POSTMASTER_MOL } from "./mol_garath/listener_yarrow_postmaster_mol";
import { ARCHITECT_ZOFIA_WRENWARD_XETH } from "./xeth_raal/architect_zofia_wrenward_xeth";
import { ARCHITECT_ARIC_FETTLE_XETH } from "./xeth_raal/architect_aric_fettle_xeth";
import { ARCHITECT_BRYA_LOCKERBY_XETH } from "./xeth_raal/architect_brya_lockerby_xeth";
import { PRAXIS_CEDAR_MENDSMITH_XETH } from "./xeth_raal/praxis_cedar_mendsmith_xeth";
import { ARCHITECT_DAVEN_CALIPERS_XETH } from "./xeth_raal/architect_daven_calipers_xeth";
import { ARCHITECT_ESRA_GAUGE_XETH } from "./xeth_raal/architect_esra_gauge_xeth";
import { AUSPEX_FAOLAN_PAGETURNER_XETH } from "./xeth_raal/auspex_faolan_pageturner_xeth";
import { AUSPEX_GWYN_PELL_XETH } from "./xeth_raal/auspex_gwyn_pell_xeth";
import { SCRIBE_HEKLA_READS_XETH } from "./xeth_raal/scribe_hekla_reads_xeth";
import { AUSPEX_IOHN_FORECASTER_XETH } from "./xeth_raal/auspex_iohn_forecaster_xeth";
import { AUSPEX_JUREL_INDEXER_XETH } from "./xeth_raal/auspex_jurel_indexer_xeth";
import { SCRIBE_KYNAN_CALIBRE_XETH } from "./xeth_raal/scribe_kynan_calibre_xeth";
import { AUSPEX_LIEVE_VEIL_XETH } from "./xeth_raal/auspex_lieve_veil_xeth";
import { AUSPEX_MARA_TRACEWELL_XETH } from "./xeth_raal/auspex_mara_tracewell_xeth";
import { REAPER_NESSA_HOLLOWAY_XETH } from "./xeth_raal/reaper_nessa_holloway_xeth";
import { QUIETUS_ONEK_ASH_HAND_XETH } from "./xeth_raal/quietus_onek_ash_hand_xeth";
import { REAPER_PRAVIN_TALLY_XETH } from "./xeth_raal/reaper_pravin_tally_xeth";
import { REAPER_QUILL_ENDSIGN_XETH } from "./xeth_raal/reaper_quill_endsign_xeth";
import { SERGEANT_REMA_DRILL_XETH } from "./xeth_raal/sergeant_rema_drill_xeth";
import { CAPTAIN_STEN_SHIELDWALL_XETH } from "./xeth_raal/captain_sten_shieldwall_xeth";
import { LISTENER_TARO_CIPHER_XETH } from "./xeth_raal/listener_taro_cipher_xeth";
import { HANDLER_ULRIC_LETTER_XETH } from "./xeth_raal/handler_ulric_letter_xeth";
import { HANDLER_VELA_BIND_XETH } from "./xeth_raal/handler_vela_bind_xeth";
import { LISTENER_WREN_LISTENER_XETH } from "./xeth_raal/listener_wren_listener_xeth";
import { ARCHITECT_XANTO_HALT_RIRI } from "./riri_ahlia/architect_xanto_halt_riri";
import { ARCHITECT_YOREK_IRONCAUL_RIRI } from "./riri_ahlia/architect_yorek_ironcaul_riri";
import { ARCHITECT_ZARA_QUILL_MARK_RIRI } from "./riri_ahlia/architect_zara_quill_mark_riri";
import { PRAXIS_ADROS_SPINDLER_RIRI } from "./riri_ahlia/praxis_adros_spindler_riri";
import { ARCHITECT_BETT_BRACE_RIRI } from "./riri_ahlia/architect_bett_brace_riri";
import { SCRIBE_CYRIL_TRACEWELL_RIRI } from "./riri_ahlia/scribe_cyril_tracewell_riri";
import { AUSPEX_DAPHNE_LEDGER_RIRI } from "./riri_ahlia/auspex_daphne_ledger_riri";
import { AUSPEX_ELEN_MARGIN_RIRI } from "./riri_ahlia/auspex_elen_margin_riri";
import { REAPER_FARO_TALLY_RIRI } from "./riri_ahlia/reaper_faro_tally_riri";
import { REAPER_GISLA_ENDSIGN_RIRI } from "./riri_ahlia/reaper_gisla_endsign_riri";
import { REAPER_HADI_CROCUS_RIRI } from "./riri_ahlia/reaper_hadi_crocus_riri";
import { CAPTAIN_INES_SHIELDWALL_RIRI } from "./riri_ahlia/captain_ines_shieldwall_riri";
import { LIEUTENANT_JEVAN_VANGUARD_RIRI } from "./riri_ahlia/lieutenant_jevan_vanguard_riri";
import { SERGEANT_KARIS_RANKS_RIRI } from "./riri_ahlia/sergeant_karis_ranks_riri";
import { SERGEANT_LIOR_MARSHAL_RIRI } from "./riri_ahlia/sergeant_lior_marshal_riri";
import { CAPTAIN_MIRA_MARSH_RIRI } from "./riri_ahlia/captain_mira_marsh_riri";
import { LIEUTENANT_NYX_STANDARDBEARER_RIRI } from "./riri_ahlia/lieutenant_nyx_standardbearer_riri";
import { SERGEANT_ORLA_BASTION_RIRI } from "./riri_ahlia/sergeant_orla_bastion_riri";
import { SERGEANT_PETRA_RANK_RIRI } from "./riri_ahlia/sergeant_petra_rank_riri";
import { CAPTAIN_REN_QUARTERMASTER_RIRI } from "./riri_ahlia/captain_ren_quartermaster_riri";
import { LIEUTENANT_SERA_WALLBORN_RIRI } from "./riri_ahlia/lieutenant_sera_wallborn_riri";
import { SERGEANT_TOMA_FLAGCALLER_RIRI } from "./riri_ahlia/sergeant_toma_flagcaller_riri";
import { HANDLER_UNA_TWO_HANDS_RIRI } from "./riri_ahlia/handler_una_two_hands_riri";
import { LISTENER_VASK_POSTMASTER_RIRI } from "./riri_ahlia/listener_vask_postmaster_riri";
import { ARCHITECT_WIRA_WRENWARD_ZYR } from "./zyr_koth/architect_wira_wrenward_zyr";
import { ARCHITECT_XEN_FETTLE_ZYR } from "./zyr_koth/architect_xen_fettle_zyr";
import { ARCHITECT_YAEL_LOCKERBY_ZYR } from "./zyr_koth/architect_yael_lockerby_zyr";
import { PRAXIS_ZAYD_MENDSMITH_ZYR } from "./zyr_koth/praxis_zayd_mendsmith_zyr";
import { ARCHITECT_ALIZ_CALIPERS_ZYR } from "./zyr_koth/architect_aliz_calipers_zyr";
import { ARCHITECT_BORAN_GAUGE_ZYR } from "./zyr_koth/architect_boran_gauge_zyr";
import { ARCHITECT_CLEO_TRIM_ZYR } from "./zyr_koth/architect_cleo_trim_zyr";
import { PRAXIS_DREV_VOSS_ZYR } from "./zyr_koth/praxis_drev_voss_zyr";
import { ARCHITECT_EDDA_HALT_ZYR } from "./zyr_koth/architect_edda_halt_zyr";
import { ARCHITECT_FENRA_IRONCAUL_ZYR } from "./zyr_koth/architect_fenra_ironcaul_zyr";
import { ARCHITECT_GARRON_QUILL_MARK_ZYR } from "./zyr_koth/architect_garron_quill_mark_zyr";
import { SCRIBE_HAEL_CALIBRE_ZYR } from "./zyr_koth/scribe_hael_calibre_zyr";
import { AUSPEX_ISOLDE_VEIL_ZYR } from "./zyr_koth/auspex_isolde_veil_zyr";
import { AUSPEX_JORAH_TRACEWELL_ZYR } from "./zyr_koth/auspex_jorah_tracewell_zyr";
import { REAPER_KESTREL_HOLLOWAY_ZYR } from "./zyr_koth/reaper_kestrel_holloway_zyr";
import { REAPER_LINNEA_ASH_HAND_ZYR } from "./zyr_koth/reaper_linnea_ash_hand_zyr";
import { REAPER_MOSEY_TALLY_ZYR } from "./zyr_koth/reaper_mosey_tally_zyr";
import { QUIETUS_NEVIN_ENDSIGN_ZYR } from "./zyr_koth/quietus_nevin_endsign_zyr";
import { REAPER_ODE_CROCUS_ZYR } from "./zyr_koth/reaper_ode_crocus_zyr";
import { CAPTAIN_PHAEDRA_SHIELDWALL_ZYR } from "./zyr_koth/captain_phaedra_shieldwall_zyr";
import { LIEUTENANT_QUIRA_VANGUARD_ZYR } from "./zyr_koth/lieutenant_quira_vanguard_zyr";
import { SERGEANT_RYL_RANKS_ZYR } from "./zyr_koth/sergeant_ryl_ranks_zyr";
import { HANDLER_SAITH_BIND_ZYR } from "./zyr_koth/handler_saith_bind_zyr";
import { LISTENER_THEIA_LISTENER_ZYR } from "./zyr_koth/listener_theia_listener_zyr";
import { ARCHITECT_ULEN_HALT_ITH } from "./ith_rael/architect_ulen_halt_ith";
import { ARCHITECT_VELKA_IRONCAUL_ITH } from "./ith_rael/architect_velka_ironcaul_ith";
import { SCRIBE_WIRT_INDEXER_ITH } from "./ith_rael/scribe_wirt_indexer_ith";
import { AUSPEX_AEVYN_CALIBRE_ITH } from "./ith_rael/auspex_aevyn_calibre_ith";
import { AUSPEX_BRANN_VEIL_ITH } from "./ith_rael/auspex_brann_veil_ith";
import { SCRIBE_CASSI_TRACEWELL_ITH } from "./ith_rael/scribe_cassi_tracewell_ith";
import { AUSPEX_DAVYL_LEDGER_ITH } from "./ith_rael/auspex_davyl_ledger_ith";
import { REAPER_ERITH_ASH_HAND_ITH } from "./ith_rael/reaper_erith_ash_hand_ith";
import { QUIETUS_FERREN_TALLY_ITH } from "./ith_rael/quietus_ferren_tally_ith";
import { REAPER_GIDA_ENDSIGN_ITH } from "./ith_rael/reaper_gida_endsign_ith";
import { SERGEANT_HALEN_DRILL_ITH } from "./ith_rael/sergeant_halen_drill_ith";
import { CAPTAIN_ILYA_SHIELDWALL_ITH } from "./ith_rael/captain_ilya_shieldwall_ith";
import { LIEUTENANT_JOREN_VANGUARD_ITH } from "./ith_rael/lieutenant_joren_vanguard_ith";
import { HANDLER_KAEL_LETTER_ITH } from "./ith_rael/handler_kael_letter_ith";
import { LISTENER_LYRA_BIND_ITH } from "./ith_rael/listener_lyra_bind_ith";
import { HANDLER_MAVIK_LISTENER_ITH } from "./ith_rael/handler_mavik_listener_ith";
import { HANDLER_NIALL_LONG_EAR_ITH } from "./ith_rael/handler_niall_long_ear_ith";
import { LISTENER_ORYN_MIRROR_ITH } from "./ith_rael/listener_oryn_mirror_ith";
import { HANDLER_PELL_HALF_TONGUE_ITH } from "./ith_rael/handler_pell_half_tongue_ith";
import { HANDLER_QUEN_SOFT_TREAD_ITH } from "./ith_rael/handler_quen_soft_tread_ith";
import { LISTENER_RHIAN_QUIET_STEP_ITH } from "./ith_rael/listener_rhian_quiet_step_ith";
import { HANDLER_SOREN_SIDE_DOOR_ITH } from "./ith_rael/handler_soren_side_door_ith";
import { HANDLER_TALIA_TWO_HANDS_ITH } from "./ith_rael/handler_talia_two_hands_ith";
import { LISTENER_ULVI_POSTMASTER_ITH } from "./ith_rael/listener_ulvi_postmaster_ith";
import { ARCHITECT_VESH_WRENWARD_SYL } from "./syl_vex/architect_vesh_wrenward_syl";
import { ARCHITECT_WYNN_FETTLE_SYL } from "./syl_vex/architect_wynn_fettle_syl";
import { SCRIBE_XALA_BECKON_SYL } from "./syl_vex/scribe_xala_beckon_syl";
import { AUSPEX_YARROW_AUSPICE_SYL } from "./syl_vex/auspex_yarrow_auspice_syl";
import { AUSPEX_ZOFIA_FOREWRIGHT_SYL } from "./syl_vex/auspex_zofia_forewright_syl";
import { SCRIBE_ARIC_QUIETSEE_SYL } from "./syl_vex/scribe_aric_quietsee_syl";
import { AUSPEX_BRYA_PAGETURNER_SYL } from "./syl_vex/auspex_brya_pageturner_syl";
import { AUSPEX_CEDAR_PELL_SYL } from "./syl_vex/auspex_cedar_pell_syl";
import { SCRIBE_DAVEN_READS_SYL } from "./syl_vex/scribe_daven_reads_syl";
import { QUIETUS_ESRA_VEIL_CUTTER_SYL } from "./syl_vex/quietus_esra_veil_cutter_syl";
import { REAPER_FAOLAN_LAST_NOTE_SYL } from "./syl_vex/reaper_faolan_last_note_syl";
import { REAPER_GWYN_MARSH_SYL } from "./syl_vex/reaper_gwyn_marsh_syl";
import { REAPER_HEKLA_SHADOW_BORNE_SYL } from "./syl_vex/reaper_hekla_shadow_borne_syl";
import { SERGEANT_IOHN_FLAGCALLER_SYL } from "./syl_vex/sergeant_iohn_flagcaller_syl";
import { SERGEANT_JUREL_IRONSIDE_SYL } from "./syl_vex/sergeant_jurel_ironside_syl";
import { CAPTAIN_KYNAN_HOLDFAST_SYL } from "./syl_vex/captain_kynan_holdfast_syl";
import { HANDLER_LIEVE_RUMOUR_SYL } from "./syl_vex/handler_lieve_rumour_syl";
import { LISTENER_MARA_FADED_SYL } from "./syl_vex/listener_mara_faded_syl";
import { HANDLER_NESSA_FOUNDLING_SYL } from "./syl_vex/handler_nessa_foundling_syl";
import { HANDLER_ONEK_SMOKE_SYL } from "./syl_vex/handler_onek_smoke_syl";
import { LISTENER_PRAVIN_CIPHER_SYL } from "./syl_vex/listener_pravin_cipher_syl";
import { HANDLER_QUILL_LETTER_SYL } from "./syl_vex/handler_quill_letter_syl";
import { HANDLER_REMA_BIND_SYL } from "./syl_vex/handler_rema_bind_syl";
import { LISTENER_STEN_LISTENER_SYL } from "./syl_vex/listener_sten_listener_syl";
import { ARCHITECT_TARO_HALT_DRAEL } from "./drael_mon/architect_taro_halt_drael";
import { ARCHITECT_ULRIC_IRONCAUL_DRAEL } from "./drael_mon/architect_ulric_ironcaul_drael";
import { SCRIBE_VELA_INDEXER_DRAEL } from "./drael_mon/scribe_vela_indexer_drael";
import { AUSPEX_WREN_CALIBRE_DRAEL } from "./drael_mon/auspex_wren_calibre_drael";
import { AUSPEX_XANTO_VEIL_DRAEL } from "./drael_mon/auspex_xanto_veil_drael";
import { SCRIBE_YOREK_TRACEWELL_DRAEL } from "./drael_mon/scribe_yorek_tracewell_drael";
import { REAPER_ZARA_HOLLOWAY_DRAEL } from "./drael_mon/reaper_zara_holloway_drael";
import { REAPER_ADROS_ASH_HAND_DRAEL } from "./drael_mon/reaper_adros_ash_hand_drael";
import { REAPER_BETT_TALLY_DRAEL } from "./drael_mon/reaper_bett_tally_drael";
import { REAPER_CYRIL_ENDSIGN_DRAEL } from "./drael_mon/reaper_cyril_endsign_drael";
import { QUIETUS_DAPHNE_CROCUS_DRAEL } from "./drael_mon/quietus_daphne_crocus_drael";
import { REAPER_ELEN_SALT_DRAEL } from "./drael_mon/reaper_elen_salt_drael";
import { REAPER_FARO_OWL_DRAEL } from "./drael_mon/reaper_faro_owl_drael";
import { REAPER_GISLA_THRESHOLD_DRAEL } from "./drael_mon/reaper_gisla_threshold_drael";
import { REAPER_HADI_COIN_DRAEL } from "./drael_mon/reaper_hadi_coin_drael";
import { QUIETUS_INES_HUSH_DRAEL } from "./drael_mon/quietus_ines_hush_drael";
import { REAPER_JEVAN_QUIETUS_DRAEL } from "./drael_mon/reaper_jevan_quietus_drael";
import { SERGEANT_KARIS_BASTION_DRAEL } from "./drael_mon/sergeant_karis_bastion_drael";
import { SERGEANT_LIOR_RANK_DRAEL } from "./drael_mon/sergeant_lior_rank_drael";
import { CAPTAIN_MIRA_QUARTERMASTER_DRAEL } from "./drael_mon/captain_mira_quartermaster_drael";
import { LISTENER_NYX_QUIET_STEP_DRAEL } from "./drael_mon/listener_nyx_quiet_step_drael";
import { HANDLER_ORLA_SIDE_DOOR_DRAEL } from "./drael_mon/handler_orla_side_door_drael";
import { HANDLER_PETRA_TWO_HANDS_DRAEL } from "./drael_mon/handler_petra_two_hands_drael";
import { LISTENER_REN_POSTMASTER_DRAEL } from "./drael_mon/listener_ren_postmaster_drael";
import { ARCHITECT_SERA_WRENWARD_VARKUL } from "./varkul/architect_sera_wrenward_varkul";
import { ARCHITECT_TOMA_FETTLE_VARKUL } from "./varkul/architect_toma_fettle_varkul";
import { ARCHITECT_UNA_LOCKERBY_VARKUL } from "./varkul/architect_una_lockerby_varkul";
import { PRAXIS_VASK_MENDSMITH_VARKUL } from "./varkul/praxis_vask_mendsmith_varkul";
import { AUSPEX_WIRA_FOREWRIGHT_VARKUL } from "./varkul/auspex_wira_forewright_varkul";
import { SCRIBE_XEN_QUIETSEE_VARKUL } from "./varkul/scribe_xen_quietsee_varkul";
import { AUSPEX_YAEL_PAGETURNER_VARKUL } from "./varkul/auspex_yael_pageturner_varkul";
import { REAPER_ZAYD_HUSH_VARKUL } from "./varkul/reaper_zayd_hush_varkul";
import { REAPER_ALIZ_QUIETUS_VARKUL } from "./varkul/reaper_aliz_quietus_varkul";
import { REAPER_BORAN_VEIL_CUTTER_VARKUL } from "./varkul/reaper_boran_veil_cutter_varkul";
import { REAPER_CLEO_LAST_NOTE_VARKUL } from "./varkul/reaper_cleo_last_note_varkul";
import { QUIETUS_DREV_MARSH_VARKUL } from "./varkul/quietus_drev_marsh_varkul";
import { REAPER_EDDA_SHADOW_BORNE_VARKUL } from "./varkul/reaper_edda_shadow_borne_varkul";
import { REAPER_FENRA_FALLNIGHT_VARKUL } from "./varkul/reaper_fenra_fallnight_varkul";
import { REAPER_GARRON_HOLLOWAY_VARKUL } from "./varkul/reaper_garron_holloway_varkul";
import { CAPTAIN_HAEL_HOLDFAST_VARKUL } from "./varkul/captain_hael_holdfast_varkul";
import { LIEUTENANT_ISOLDE_GARDENER_OF_LINES_VARKUL } from "./varkul/lieutenant_isolde_gardener_of_lines_varkul";
import { SERGEANT_JORAH_COHORT_VARKUL } from "./varkul/sergeant_jorah_cohort_varkul";
import { SERGEANT_KESTREL_DRILL_VARKUL } from "./varkul/sergeant_kestrel_drill_varkul";
import { CAPTAIN_LINNEA_SHIELDWALL_VARKUL } from "./varkul/captain_linnea_shieldwall_varkul";
import { LIEUTENANT_MOSEY_VANGUARD_VARKUL } from "./varkul/lieutenant_mosey_vanguard_varkul";
import { HANDLER_NEVIN_LETTER_VARKUL } from "./varkul/handler_nevin_letter_varkul";
import { HANDLER_ODE_BIND_VARKUL } from "./varkul/handler_ode_bind_varkul";
import { LISTENER_PHAEDRA_LISTENER_VARKUL } from "./varkul/listener_phaedra_listener_varkul";
import { ARCHITECT_QUIRA_HALT_FENRA } from "./fenra/architect_quira_halt_fenra";
import { ARCHITECT_RYL_IRONCAUL_FENRA } from "./fenra/architect_ryl_ironcaul_fenra";
import { ARCHITECT_SAITH_QUILL_MARK_FENRA } from "./fenra/architect_saith_quill_mark_fenra";
import { AUSPEX_THEIA_CALIBRE_FENRA } from "./fenra/auspex_theia_calibre_fenra";
import { AUSPEX_ULEN_VEIL_FENRA } from "./fenra/auspex_ulen_veil_fenra";
import { SCRIBE_VELKA_TRACEWELL_FENRA } from "./fenra/scribe_velka_tracewell_fenra";
import { AUSPEX_WIRT_LEDGER_FENRA } from "./fenra/auspex_wirt_ledger_fenra";
import { AUSPEX_AEVYN_MARGIN_FENRA } from "./fenra/auspex_aevyn_margin_fenra";
import { SCRIBE_BRANN_WATCH_FENRA } from "./fenra/scribe_brann_watch_fenra";
import { AUSPEX_CASSI_SUMSHORE_FENRA } from "./fenra/auspex_cassi_sumshore_fenra";
import { AUSPEX_DAVYL_BECKON_FENRA } from "./fenra/auspex_davyl_beckon_fenra";
import { SCRIBE_ERITH_AUSPICE_FENRA } from "./fenra/scribe_erith_auspice_fenra";
import { AUSPEX_FERREN_FOREWRIGHT_FENRA } from "./fenra/auspex_ferren_forewright_fenra";
import { AUSPEX_GIDA_QUIETSEE_FENRA } from "./fenra/auspex_gida_quietsee_fenra";
import { REAPER_HALEN_COIN_FENRA } from "./fenra/reaper_halen_coin_fenra";
import { REAPER_ILYA_HUSH_FENRA } from "./fenra/reaper_ilya_hush_fenra";
import { REAPER_JOREN_QUIETUS_FENRA } from "./fenra/reaper_joren_quietus_fenra";
import { QUIETUS_KAEL_VEIL_CUTTER_FENRA } from "./fenra/quietus_kael_veil_cutter_fenra";
import { SERGEANT_LYRA_RANK_FENRA } from "./fenra/sergeant_lyra_rank_fenra";
import { CAPTAIN_MAVIK_QUARTERMASTER_FENRA } from "./fenra/captain_mavik_quartermaster_fenra";
import { LISTENER_NIALL_QUIET_STEP_FENRA } from "./fenra/listener_niall_quiet_step_fenra";
import { HANDLER_ORYN_SIDE_DOOR_FENRA } from "./fenra/handler_oryn_side_door_fenra";
import { HANDLER_PELL_TWO_HANDS_FENRA } from "./fenra/handler_pell_two_hands_fenra";
import { LISTENER_QUEN_POSTMASTER_FENRA } from "./fenra/listener_quen_postmaster_fenra";
import { ARCHITECT_RHIAN_WRENWARD_MOL } from "./mol_vereth/architect_rhian_wrenward_mol";
import { ARCHITECT_SOREN_FETTLE_MOL } from "./mol_vereth/architect_soren_fettle_mol";
import { ARCHITECT_TALIA_LOCKERBY_MOL } from "./mol_vereth/architect_talia_lockerby_mol";
import { PRAXIS_ULVI_MENDSMITH_MOL } from "./mol_vereth/praxis_ulvi_mendsmith_mol";
import { ARCHITECT_VESH_CALIPERS_MOL } from "./mol_vereth/architect_vesh_calipers_mol";
import { ARCHITECT_WYNN_GAUGE_MOL } from "./mol_vereth/architect_wynn_gauge_mol";
import { ARCHITECT_XALA_TRIM_MOL } from "./mol_vereth/architect_xala_trim_mol";
import { PRAXIS_YARROW_VOSS_MOL } from "./mol_vereth/praxis_yarrow_voss_mol";
import { ARCHITECT_ZOFIA_HALT_MOL } from "./mol_vereth/architect_zofia_halt_mol";
import { ARCHITECT_ARIC_IRONCAUL_MOL } from "./mol_vereth/architect_aric_ironcaul_mol";
import { AUSPEX_BRYA_INDEXER_MOL } from "./mol_vereth/auspex_brya_indexer_mol";
import { SCRIBE_CEDAR_CALIBRE_MOL } from "./mol_vereth/scribe_cedar_calibre_mol";
import { AUSPEX_DAVEN_VEIL_MOL } from "./mol_vereth/auspex_daven_veil_mol";
import { AUSPEX_ESRA_TRACEWELL_MOL } from "./mol_vereth/auspex_esra_tracewell_mol";
import { REAPER_FAOLAN_HOLLOWAY_MOL } from "./mol_vereth/reaper_faolan_holloway_mol";
import { REAPER_GWYN_ASH_HAND_MOL } from "./mol_vereth/reaper_gwyn_ash_hand_mol";
import { LIEUTENANT_HEKLA_GARDENER_OF_LINES_MOL } from "./mol_vereth/lieutenant_hekla_gardener_of_lines_mol";
import { SERGEANT_IOHN_COHORT_MOL } from "./mol_vereth/sergeant_iohn_cohort_mol";
import { HANDLER_JUREL_FOUNDLING_MOL } from "./mol_vereth/handler_jurel_foundling_mol";
import { HANDLER_KYNAN_SMOKE_MOL } from "./mol_vereth/handler_kynan_smoke_mol";
import { LISTENER_LIEVE_CIPHER_MOL } from "./mol_vereth/listener_lieve_cipher_mol";
import { HANDLER_MARA_LETTER_MOL } from "./mol_vereth/handler_mara_letter_mol";
import { HANDLER_NESSA_BIND_MOL } from "./mol_vereth/handler_nessa_bind_mol";
import { LISTENER_ONEK_LISTENER_MOL } from "./mol_vereth/listener_onek_listener_mol";

const HERO_TARGET_DEFS: ReadonlyArray<HeroTarget> = [
  GENERAL_CAEDRYN_VOLK,
  AUDITOR_MIREILLE_YOM,
  MARSHAL_ORIN_THACE,
  PRAXIS_THREE_MIRA_VOLL,
  LISTENER_EYRA_SHEEL,
  PERSUADER_KAL_DEMIR,
  REAPER_NYX_SABLE,
  BLOODSPEAKER_TESSEN_RAHL,
  MOONSCRIBE_ILARA_PELL,
  ARCHITECT_RIVEN_SOLACE,
  ARCHITECT_BRANN_HALT_MOL,
  ARCHITECT_CASSI_IRONCAUL_MOL,
  ARCHITECT_DAVYL_QUILL_MARK_MOL,
  AUSPEX_ERITH_CALIBRE_MOL,
  AUSPEX_FERREN_VEIL_MOL,
  SCRIBE_GIDA_TRACEWELL_MOL,
  REAPER_HALEN_HOLLOWAY_MOL,
  REAPER_ILYA_ASH_HAND_MOL,
  REAPER_JOREN_TALLY_MOL,
  QUIETUS_KAEL_ENDSIGN_MOL,
  REAPER_LYRA_CROCUS_MOL,
  REAPER_MAVIK_SALT_MOL,
  LIEUTENANT_NIALL_VANGUARD_MOL,
  SERGEANT_ORYN_RANKS_MOL,
  SERGEANT_PELL_MARSHAL_MOL,
  CAPTAIN_QUEN_MARSH_MOL,
  LIEUTENANT_RHIAN_STANDARDBEARER_MOL,
  SERGEANT_SOREN_BASTION_MOL,
  SERGEANT_TALIA_RANK_MOL,
  CAPTAIN_ULVI_QUARTERMASTER_MOL,
  LIEUTENANT_VESH_WALLBORN_MOL,
  SERGEANT_WYNN_FLAGCALLER_MOL,
  HANDLER_XALA_TWO_HANDS_MOL,
  LISTENER_YARROW_POSTMASTER_MOL,
  ARCHITECT_ZOFIA_WRENWARD_XETH,
  ARCHITECT_ARIC_FETTLE_XETH,
  ARCHITECT_BRYA_LOCKERBY_XETH,
  PRAXIS_CEDAR_MENDSMITH_XETH,
  ARCHITECT_DAVEN_CALIPERS_XETH,
  ARCHITECT_ESRA_GAUGE_XETH,
  AUSPEX_FAOLAN_PAGETURNER_XETH,
  AUSPEX_GWYN_PELL_XETH,
  SCRIBE_HEKLA_READS_XETH,
  AUSPEX_IOHN_FORECASTER_XETH,
  AUSPEX_JUREL_INDEXER_XETH,
  SCRIBE_KYNAN_CALIBRE_XETH,
  AUSPEX_LIEVE_VEIL_XETH,
  AUSPEX_MARA_TRACEWELL_XETH,
  REAPER_NESSA_HOLLOWAY_XETH,
  QUIETUS_ONEK_ASH_HAND_XETH,
  REAPER_PRAVIN_TALLY_XETH,
  REAPER_QUILL_ENDSIGN_XETH,
  SERGEANT_REMA_DRILL_XETH,
  CAPTAIN_STEN_SHIELDWALL_XETH,
  LISTENER_TARO_CIPHER_XETH,
  HANDLER_ULRIC_LETTER_XETH,
  HANDLER_VELA_BIND_XETH,
  LISTENER_WREN_LISTENER_XETH,
  ARCHITECT_XANTO_HALT_RIRI,
  ARCHITECT_YOREK_IRONCAUL_RIRI,
  ARCHITECT_ZARA_QUILL_MARK_RIRI,
  PRAXIS_ADROS_SPINDLER_RIRI,
  ARCHITECT_BETT_BRACE_RIRI,
  SCRIBE_CYRIL_TRACEWELL_RIRI,
  AUSPEX_DAPHNE_LEDGER_RIRI,
  AUSPEX_ELEN_MARGIN_RIRI,
  REAPER_FARO_TALLY_RIRI,
  REAPER_GISLA_ENDSIGN_RIRI,
  REAPER_HADI_CROCUS_RIRI,
  CAPTAIN_INES_SHIELDWALL_RIRI,
  LIEUTENANT_JEVAN_VANGUARD_RIRI,
  SERGEANT_KARIS_RANKS_RIRI,
  SERGEANT_LIOR_MARSHAL_RIRI,
  CAPTAIN_MIRA_MARSH_RIRI,
  LIEUTENANT_NYX_STANDARDBEARER_RIRI,
  SERGEANT_ORLA_BASTION_RIRI,
  SERGEANT_PETRA_RANK_RIRI,
  CAPTAIN_REN_QUARTERMASTER_RIRI,
  LIEUTENANT_SERA_WALLBORN_RIRI,
  SERGEANT_TOMA_FLAGCALLER_RIRI,
  HANDLER_UNA_TWO_HANDS_RIRI,
  LISTENER_VASK_POSTMASTER_RIRI,
  ARCHITECT_WIRA_WRENWARD_ZYR,
  ARCHITECT_XEN_FETTLE_ZYR,
  ARCHITECT_YAEL_LOCKERBY_ZYR,
  PRAXIS_ZAYD_MENDSMITH_ZYR,
  ARCHITECT_ALIZ_CALIPERS_ZYR,
  ARCHITECT_BORAN_GAUGE_ZYR,
  ARCHITECT_CLEO_TRIM_ZYR,
  PRAXIS_DREV_VOSS_ZYR,
  ARCHITECT_EDDA_HALT_ZYR,
  ARCHITECT_FENRA_IRONCAUL_ZYR,
  ARCHITECT_GARRON_QUILL_MARK_ZYR,
  SCRIBE_HAEL_CALIBRE_ZYR,
  AUSPEX_ISOLDE_VEIL_ZYR,
  AUSPEX_JORAH_TRACEWELL_ZYR,
  REAPER_KESTREL_HOLLOWAY_ZYR,
  REAPER_LINNEA_ASH_HAND_ZYR,
  REAPER_MOSEY_TALLY_ZYR,
  QUIETUS_NEVIN_ENDSIGN_ZYR,
  REAPER_ODE_CROCUS_ZYR,
  CAPTAIN_PHAEDRA_SHIELDWALL_ZYR,
  LIEUTENANT_QUIRA_VANGUARD_ZYR,
  SERGEANT_RYL_RANKS_ZYR,
  HANDLER_SAITH_BIND_ZYR,
  LISTENER_THEIA_LISTENER_ZYR,
  ARCHITECT_ULEN_HALT_ITH,
  ARCHITECT_VELKA_IRONCAUL_ITH,
  SCRIBE_WIRT_INDEXER_ITH,
  AUSPEX_AEVYN_CALIBRE_ITH,
  AUSPEX_BRANN_VEIL_ITH,
  SCRIBE_CASSI_TRACEWELL_ITH,
  AUSPEX_DAVYL_LEDGER_ITH,
  REAPER_ERITH_ASH_HAND_ITH,
  QUIETUS_FERREN_TALLY_ITH,
  REAPER_GIDA_ENDSIGN_ITH,
  SERGEANT_HALEN_DRILL_ITH,
  CAPTAIN_ILYA_SHIELDWALL_ITH,
  LIEUTENANT_JOREN_VANGUARD_ITH,
  HANDLER_KAEL_LETTER_ITH,
  LISTENER_LYRA_BIND_ITH,
  HANDLER_MAVIK_LISTENER_ITH,
  HANDLER_NIALL_LONG_EAR_ITH,
  LISTENER_ORYN_MIRROR_ITH,
  HANDLER_PELL_HALF_TONGUE_ITH,
  HANDLER_QUEN_SOFT_TREAD_ITH,
  LISTENER_RHIAN_QUIET_STEP_ITH,
  HANDLER_SOREN_SIDE_DOOR_ITH,
  HANDLER_TALIA_TWO_HANDS_ITH,
  LISTENER_ULVI_POSTMASTER_ITH,
  ARCHITECT_VESH_WRENWARD_SYL,
  ARCHITECT_WYNN_FETTLE_SYL,
  SCRIBE_XALA_BECKON_SYL,
  AUSPEX_YARROW_AUSPICE_SYL,
  AUSPEX_ZOFIA_FOREWRIGHT_SYL,
  SCRIBE_ARIC_QUIETSEE_SYL,
  AUSPEX_BRYA_PAGETURNER_SYL,
  AUSPEX_CEDAR_PELL_SYL,
  SCRIBE_DAVEN_READS_SYL,
  QUIETUS_ESRA_VEIL_CUTTER_SYL,
  REAPER_FAOLAN_LAST_NOTE_SYL,
  REAPER_GWYN_MARSH_SYL,
  REAPER_HEKLA_SHADOW_BORNE_SYL,
  SERGEANT_IOHN_FLAGCALLER_SYL,
  SERGEANT_JUREL_IRONSIDE_SYL,
  CAPTAIN_KYNAN_HOLDFAST_SYL,
  HANDLER_LIEVE_RUMOUR_SYL,
  LISTENER_MARA_FADED_SYL,
  HANDLER_NESSA_FOUNDLING_SYL,
  HANDLER_ONEK_SMOKE_SYL,
  LISTENER_PRAVIN_CIPHER_SYL,
  HANDLER_QUILL_LETTER_SYL,
  HANDLER_REMA_BIND_SYL,
  LISTENER_STEN_LISTENER_SYL,
  ARCHITECT_TARO_HALT_DRAEL,
  ARCHITECT_ULRIC_IRONCAUL_DRAEL,
  SCRIBE_VELA_INDEXER_DRAEL,
  AUSPEX_WREN_CALIBRE_DRAEL,
  AUSPEX_XANTO_VEIL_DRAEL,
  SCRIBE_YOREK_TRACEWELL_DRAEL,
  REAPER_ZARA_HOLLOWAY_DRAEL,
  REAPER_ADROS_ASH_HAND_DRAEL,
  REAPER_BETT_TALLY_DRAEL,
  REAPER_CYRIL_ENDSIGN_DRAEL,
  QUIETUS_DAPHNE_CROCUS_DRAEL,
  REAPER_ELEN_SALT_DRAEL,
  REAPER_FARO_OWL_DRAEL,
  REAPER_GISLA_THRESHOLD_DRAEL,
  REAPER_HADI_COIN_DRAEL,
  QUIETUS_INES_HUSH_DRAEL,
  REAPER_JEVAN_QUIETUS_DRAEL,
  SERGEANT_KARIS_BASTION_DRAEL,
  SERGEANT_LIOR_RANK_DRAEL,
  CAPTAIN_MIRA_QUARTERMASTER_DRAEL,
  LISTENER_NYX_QUIET_STEP_DRAEL,
  HANDLER_ORLA_SIDE_DOOR_DRAEL,
  HANDLER_PETRA_TWO_HANDS_DRAEL,
  LISTENER_REN_POSTMASTER_DRAEL,
  ARCHITECT_SERA_WRENWARD_VARKUL,
  ARCHITECT_TOMA_FETTLE_VARKUL,
  ARCHITECT_UNA_LOCKERBY_VARKUL,
  PRAXIS_VASK_MENDSMITH_VARKUL,
  AUSPEX_WIRA_FOREWRIGHT_VARKUL,
  SCRIBE_XEN_QUIETSEE_VARKUL,
  AUSPEX_YAEL_PAGETURNER_VARKUL,
  REAPER_ZAYD_HUSH_VARKUL,
  REAPER_ALIZ_QUIETUS_VARKUL,
  REAPER_BORAN_VEIL_CUTTER_VARKUL,
  REAPER_CLEO_LAST_NOTE_VARKUL,
  QUIETUS_DREV_MARSH_VARKUL,
  REAPER_EDDA_SHADOW_BORNE_VARKUL,
  REAPER_FENRA_FALLNIGHT_VARKUL,
  REAPER_GARRON_HOLLOWAY_VARKUL,
  CAPTAIN_HAEL_HOLDFAST_VARKUL,
  LIEUTENANT_ISOLDE_GARDENER_OF_LINES_VARKUL,
  SERGEANT_JORAH_COHORT_VARKUL,
  SERGEANT_KESTREL_DRILL_VARKUL,
  CAPTAIN_LINNEA_SHIELDWALL_VARKUL,
  LIEUTENANT_MOSEY_VANGUARD_VARKUL,
  HANDLER_NEVIN_LETTER_VARKUL,
  HANDLER_ODE_BIND_VARKUL,
  LISTENER_PHAEDRA_LISTENER_VARKUL,
  ARCHITECT_QUIRA_HALT_FENRA,
  ARCHITECT_RYL_IRONCAUL_FENRA,
  ARCHITECT_SAITH_QUILL_MARK_FENRA,
  AUSPEX_THEIA_CALIBRE_FENRA,
  AUSPEX_ULEN_VEIL_FENRA,
  SCRIBE_VELKA_TRACEWELL_FENRA,
  AUSPEX_WIRT_LEDGER_FENRA,
  AUSPEX_AEVYN_MARGIN_FENRA,
  SCRIBE_BRANN_WATCH_FENRA,
  AUSPEX_CASSI_SUMSHORE_FENRA,
  AUSPEX_DAVYL_BECKON_FENRA,
  SCRIBE_ERITH_AUSPICE_FENRA,
  AUSPEX_FERREN_FOREWRIGHT_FENRA,
  AUSPEX_GIDA_QUIETSEE_FENRA,
  REAPER_HALEN_COIN_FENRA,
  REAPER_ILYA_HUSH_FENRA,
  REAPER_JOREN_QUIETUS_FENRA,
  QUIETUS_KAEL_VEIL_CUTTER_FENRA,
  SERGEANT_LYRA_RANK_FENRA,
  CAPTAIN_MAVIK_QUARTERMASTER_FENRA,
  LISTENER_NIALL_QUIET_STEP_FENRA,
  HANDLER_ORYN_SIDE_DOOR_FENRA,
  HANDLER_PELL_TWO_HANDS_FENRA,
  LISTENER_QUEN_POSTMASTER_FENRA,
  ARCHITECT_RHIAN_WRENWARD_MOL,
  ARCHITECT_SOREN_FETTLE_MOL,
  ARCHITECT_TALIA_LOCKERBY_MOL,
  PRAXIS_ULVI_MENDSMITH_MOL,
  ARCHITECT_VESH_CALIPERS_MOL,
  ARCHITECT_WYNN_GAUGE_MOL,
  ARCHITECT_XALA_TRIM_MOL,
  PRAXIS_YARROW_VOSS_MOL,
  ARCHITECT_ZOFIA_HALT_MOL,
  ARCHITECT_ARIC_IRONCAUL_MOL,
  AUSPEX_BRYA_INDEXER_MOL,
  SCRIBE_CEDAR_CALIBRE_MOL,
  AUSPEX_DAVEN_VEIL_MOL,
  AUSPEX_ESRA_TRACEWELL_MOL,
  REAPER_FAOLAN_HOLLOWAY_MOL,
  REAPER_GWYN_ASH_HAND_MOL,
  LIEUTENANT_HEKLA_GARDENER_OF_LINES_MOL,
  SERGEANT_IOHN_COHORT_MOL,
  HANDLER_JUREL_FOUNDLING_MOL,
  HANDLER_KYNAN_SMOKE_MOL,
  LISTENER_LIEVE_CIPHER_MOL,
  HANDLER_MARA_LETTER_MOL,
  HANDLER_NESSA_BIND_MOL,
  LISTENER_ONEK_LISTENER_MOL,
];

// Validate every dossier at module load. Throws on first failure.
for (const def of HERO_TARGET_DEFS) {
  heroTargetSchema.parse(def);
}

// Enforce id uniqueness across the registry.
{
  const seen = new Set<string>();
  for (const def of HERO_TARGET_DEFS) {
    if (seen.has(def.id)) {
      throw new Error(
        `wolfHunt heroTargets: duplicate id "${def.id}" — every dossier must have a unique id.`,
      );
    }
    seen.add(def.id);
  }
}

/** All hero targets currently shipped, in registration order. */
export const ALL_HERO_TARGETS: ReadonlyArray<HeroTarget> = HERO_TARGET_DEFS;

/** Canonical full count of the hero matrix (10 lords × 25 heroes). */
export const HERO_TARGET_FULL_MATRIX_COUNT = 250;

/** Canonical lieutenant count (one per lord). */
export const HERO_TARGET_LIEUTENANT_COUNT = 10;

/** Look up a hero target by id. Throws if not found. */
export function getHeroTarget(id: string): HeroTarget {
  const found = ALL_HERO_TARGETS.find((h) => h.id === id);
  if (!found) {
    throw new Error(`wolfHunt: unknown hero target id "${id}"`);
  }
  return found;
}

/** Return every lieutenant in registration order. */
export function getLieutenants(): ReadonlyArray<HeroTarget> {
  return ALL_HERO_TARGETS.filter((h) => h.isBossLieutenant);
}

/** Return every hero corrupted by a given lord. */
export function getHeroesByLord(
  lordId: CoreHierarchyLordId,
): ReadonlyArray<HeroTarget> {
  return ALL_HERO_TARGETS.filter((h) => h.corruptorLord === lordId);
}

/** Map of lord id → count of heroes registered under that lord. */
export function getLordCohortSizes(): Readonly<Record<CoreHierarchyLordId, number>> {
  const out = Object.fromEntries(
    CORE_HIERARCHY_LORD_IDS.map((id) => [id, 0]),
  ) as Record<CoreHierarchyLordId, number>;
  for (const h of ALL_HERO_TARGETS) {
    out[h.corruptorLord] += 1;
  }
  return out;
}
