/**
 * generate-baseline-migration — DBA runbook for the
 * 0071_baseline_v1 cutover described in
 * apps/db/migrations/README.md (Step 2).
 *
 * What this does:
 *   1. Connects to a target DATABASE_URL (must be a CLEAN database).
 *   2. Runs `drizzle-kit push` to bring the DB up to current schema.
 *   3. Uses `mysqldump` to capture the resulting schema.
 *   4. Writes apps/db/0071_baseline_v1.sql + a journal entry.
 *
 * What this does NOT do (intentional — the DBA owns the cutover):
 *   - It does not delete the existing 81 .sql migration files. That's
 *     a follow-up commit on a separate branch where the DBA also
 *     prunes meta/_journal.json + meta/*_snapshot.json + bootstrap*
 *     IIFEs in apps/server/db.ts that are no longer needed.
 *   - It does not run against production. The intent is: a DBA runs
 *     this against a CLEAN MySQL instance, commits the resulting
 *     0071_baseline_v1.sql, and then a separate apply-via-existing-
 *     prod-data PR marks the migration applied via the
 *     __drizzle_migrations table (Step 3 in the README).
 *
 * Run:
 *   DATABASE_URL=mysql://root:pw@127.0.0.1/empty_baseline_db \
 *     pnpm tsx scripts/generate-baseline-migration.ts
 */
import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { createHash } from "crypto";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const TAG = "0071_baseline_v1";
const SQL_OUT = path.join(REPO_ROOT, "apps/db", `${TAG}.sql`);
const JOURNAL_PATH = path.join(REPO_ROOT, "apps/db/meta/_journal.json");

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing required env: ${name}`);
    process.exit(2);
  }
  return v;
}

function step(label: string, fn: () => void) {
  console.log(`\n──── ${label} ────`);
  fn();
}

function main() {
  const url = requireEnv("DATABASE_URL");
  const u = new URL(url);
  const dbName = u.pathname.replace(/^\//, "");

  step("1. Verify the target DB is empty (no user tables)", () => {
    // We use mysql CLI directly; failing here saves the DBA from
    // accidentally generating a baseline against a populated DB.
    const cmd = `mysql --protocol=TCP -h '${u.hostname}' -P '${u.port || 3306}' -u '${decodeURIComponent(u.username)}' -p'${decodeURIComponent(u.password)}' -e 'SHOW TABLES;' '${dbName}' 2>/dev/null`;
    const out = execSync(cmd, { encoding: "utf8" }).trim();
    if (out.split("\n").length > 1) {
      // mysql emits a header line; >1 means at least one user table.
      console.error(
        `Target database '${dbName}' has tables already. The baseline must be generated against a CLEAN database.`,
      );
      console.error(`Got:\n${out}`);
      process.exit(3);
    }
  });

  step("2. Apply current schema via drizzle-kit push", () => {
    execSync("pnpm drizzle-kit push", {
      cwd: REPO_ROOT,
      stdio: "inherit",
      env: { ...process.env, DATABASE_URL: url },
    });
  });

  step("3. Capture schema via mysqldump", () => {
    const cmd = `mysqldump --protocol=TCP --no-data --skip-add-drop-table --skip-comments --skip-extended-insert -h '${u.hostname}' -P '${u.port || 3306}' -u '${decodeURIComponent(u.username)}' -p'${decodeURIComponent(u.password)}' '${dbName}'`;
    const dump = execSync(cmd, { encoding: "utf8" });
    // Strip the noisy header lines + trailing blank lines. Inject
    // statement-breakpoint markers between top-level statements so
    // drizzle-kit migrate splits them correctly (its parser keys on
    // those markers when the journal entry has `breakpoints: true`).
    // Wrap the body in SET FOREIGN_KEY_CHECKS=0/1 so the dump can be
    // applied in alphabetical order — mysqldump emits CONSTRAINT
    // clauses inline in CREATE TABLE, which would otherwise fail
    // whenever a table references one that hasn't been created yet.
    const body = dump
      .split("\n")
      .filter((l) => !l.startsWith("/*!"))
      .filter((l) => !l.startsWith("--"))
      .join("\n")
      .trim();

    const statements = body.split("\n");
    const withBreakpoints: string[] = [];
    for (let i = 0; i < statements.length; i++) {
      withBreakpoints.push(statements[i]);
      if (/;\s*$/.test(statements[i]) && i < statements.length - 1) {
        let j = i + 1;
        while (j < statements.length && statements[j].trim() === "") j++;
        if (j < statements.length && /^(CREATE|ALTER|DROP|INSERT|UPDATE)/.test(statements[j])) {
          withBreakpoints.push("--> statement-breakpoint");
        }
      }
    }

    const cleaned =
      `-- Drizzle baseline migration: ${TAG}\n` +
      "-- Generated by scripts/generate-baseline-migration.ts\n" +
      "-- DO NOT EDIT BY HAND. Regenerate via the same script.\n\n" +
      "SET FOREIGN_KEY_CHECKS = 0;\n" +
      "--> statement-breakpoint\n" +
      withBreakpoints.join("\n").trim() + "\n" +
      "--> statement-breakpoint\n" +
      "SET FOREIGN_KEY_CHECKS = 1;\n";

    fs.writeFileSync(SQL_OUT, cleaned);
    console.log(`Wrote ${SQL_OUT} (${cleaned.length} bytes).`);
  });

  step("4. Compute hash + append journal entry", () => {
    const sql = fs.readFileSync(SQL_OUT, "utf8");
    const hash = createHash("sha256").update(sql).digest("hex");
    const journal = JSON.parse(fs.readFileSync(JOURNAL_PATH, "utf8")) as {
      version: string;
      dialect: string;
      entries: Array<{
        idx: number;
        version: string;
        when: number;
        tag: string;
        breakpoints: boolean;
      }>;
    };
    const nextIdx = journal.entries.length;
    journal.entries.push({
      idx: nextIdx,
      version: "5",
      when: Date.now(),
      tag: TAG,
      breakpoints: true,
    });
    fs.writeFileSync(JOURNAL_PATH, JSON.stringify(journal, null, 2));
    console.log(`Appended journal entry: idx=${nextIdx} tag=${TAG} hash=${hash.slice(0, 12)}…`);
  });

  step("5. Manual follow-up checklist", () => {
    console.log(`
After committing, the DBA must (separate PR — see
apps/db/migrations/README.md):

  a) Move existing apps/db/0000_*.sql … apps/db/0070_*.sql into
     apps/db/_archive/ (or delete; the journal no longer references
     them).
  b) Reset migration-drift.baseline.json to:
       { "driftedSqlFiles": [], "knownPrefixCollisions": [] }
  c) On every existing prod-shaped DB, mark the baseline as applied:
       INSERT INTO __drizzle_migrations (hash, created_at)
       VALUES ('<hash from journal>', UNIX_TIMESTAMP() * 1000);
  d) Drop the bootstrap* IIFEs in apps/server/db.ts that compensated
     for journal drift.
  e) Switch CI deploy command from db:push to db:migrate.
`);
  });
}

main();
