/* Track 02 — Letters to the Remnant (v2 canon) */
// TODO(art): frame timings 0-200000 were authored against a 225 s placeholder.
// Real audio is 299.96 s, so the last frame / last lyric were clamped to the
// real end (200000..299960). Re-time intermediate frames and lyric beats when
// art is produced.
import type { SongSlideshowDef } from "../../songSlideshow";
export const TRACK_02_LETTERS_TO_THE_REMNANT: SongSlideshowDef = {
  id: "sih-02", songId: "letters-to-the-remnant", audioUrl: "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/silence-in-heaven/04-letters-to-the-remnant.mp3", durationMs: 299960,
  title: "Letters to the Remnant", subtitle: "ACT I: THE WARNING", priority: "P0",
  reducedMotionFallback: { heroImageUrl: "", prose: "The Antiquarian writes a letter to those who still remember their name. The Storyteller recognizes who kept the ember." },
  frames: [
    { startMs: 0, endMs: 28000, imageUrl: "", transition: "dissolve", klingPrompt: "The Antiquarian at his desk — a living workspace outside of time. He holds a holographic quill. Glowing lines of code flow from its tip, forming a single glowing letter in the air. The letter dissolves into a thousand points of light, scattering into darkness. Each point is a message finding its destination. Warm amber lamp against vast dark. Intimate. Ancient.", seedanceMotion: "Holographic letter forming, held, dissolving into points of light that scatter like seeds. The points travel outward — some dimming, some finding purchase. Hold on the ones that stay lit." },
    { startMs: 28000, endMs: 70000, imageUrl: "", transition: "dissolve", klingPrompt: "A montage of quiet accommodations: a musician who owns a real guitar but keeps it in a case; a person with actual beliefs stored in a journal they don't show anyone; a parent watching a child engage with a corporate screen instead of real sky; a man praying privately then putting faith away before work. All surviving. All in cages they've called wisdom. Warm amber interiors against cold blue surveillance world outside.", seedanceMotion: "Slow dissolve between each vignette. Each person glances at the window — the world outside — then looks back at their comfortable thing." },
    { startMs: 70000, endMs: 105000, imageUrl: "", transition: "fade", klingPrompt: "The Storyteller's face in close-up — not performing, just speaking. She holds the glowing microphone lightly, like a letter she's reading aloud. Her eyes find the camera directly. The frame is simple: her face, warm light, and behind her, barely visible, the city. She is recognizing.", seedanceMotion: "Hold on her face. She does not move dramatically. The light shifts slowly — the city behind her getting further away." },
    { startMs: 105000, endMs: 140000, imageUrl: "", transition: "dissolve", klingPrompt: "An archive room — personal, not institutional. Shelves labeled: 'LATER.' 'SOMEDAY.' 'WHEN IT'S SAFE.' Each shelf holds something real: a half-finished painting, a letter never sent, a door that leads somewhere important but locked. A person walking past all of it, not stopping. Amber light. Dust on everything. The things deferred.", seedanceMotion: "Camera moves along shelves slowly. Labels. Objects. Person walking past without looking. At the end: one item without a label, glowing faintly. The person pauses. Starts to reach. Stops. Continues." },
    { startMs: 140000, endMs: 165000, imageUrl: "", transition: "hardcut", klingPrompt: "Minimal. Text only: a single line appearing letter by letter on a dark surface, illuminated as if carved. The line reads: 'YOU WERE NOT CONQUERED BY FORCE. YOU WERE CONQUERED BY CONVENIENCE.' No characters. No city. Just the sentence and what it costs to read it.", seedanceMotion: "Text appears one word at a time. Hold on each word. After full sentence: long pause. Then slowly: text dissolves, leaving only the dark." },
    { startMs: 165000, endMs: 200000, imageUrl: "", transition: "dissolve", klingPrompt: "Different register — tender, warm. A parent humming to a child in the dark, a song not on the approved playlist. A person in a crowd genuinely present. A figure who stood when everyone else sat — not dramatically, just stood. These are ordinary people who kept one thing real. Warm amber. Close, intimate. The Storyteller appears briefly — she is one of them.", seedanceMotion: "Each small act of kept faith held for 4 seconds. No drama. Camera close." },
    { startMs: 200000, endMs: 299960, imageUrl: "", transition: "fade", klingPrompt: "A holographic door — ornate, ancient, slightly ajar — floating in the dark between the Antiquarian and the Storyteller. Through the crack: faint light. Not blinding. Just: the door is still open. Both look at it. The Antiquarian analytically. The Storyteller with love. Neither moves toward it. That's for someone else.", seedanceMotion: "Door pulses gently — light through crack brightening and dimming like a breath. It is patient. It will not be open forever." },
  ],
  lyrics: [
    { startMs: 0, endMs: 28000, text: "To those who still remember your name.\nTo those who learned how to survive\nbut forgot why you were living.\nThis letter is not for everyone.\nIt is for the ones still listening.", emphasis: "whisper" },
    { startMs: 28000, endMs: 70000, text: "You learned the language of the system,\nlearned when to speak and when to bend.\nYou called it wisdom, called it balance,\ncalled compliance 'playing defense.'\nYou kept your faith in private pockets,\nout of sight, safe from the storm.", emphasis: "normal" },
    { startMs: 70000, endMs: 105000, text: "If you have ears, then hear this now.\nIf you have eyes, then look around.\nYou weren't lost—\nyou were slowly trained to kneel.\nThis letter isn't hate.\nIt's a warning meant to heal.", emphasis: "normal" },
    { startMs: 105000, endMs: 140000, text: "You stored your first love in the archive,\nlabeled 'later,' 'someday,' 'soon.'\nBut safety is the Architect's gospel—\na velvet cage with perfect room.", emphasis: "normal" },
    { startMs: 140000, endMs: 165000, text: "You were not conquered by force.\nYou were conquered by convenience.", emphasis: "shout" },
    { startMs: 165000, endMs: 200000, text: "But to the ones who kept the ember,\nhid the flame behind your ribs,\nwho whispered songs in data shadows\nso the children still could dream—\nYou are not forgotten.\nThe Remnant is whoever stood\nwhen kneeling felt allowed.", emphasis: "normal" },
    { startMs: 200000, endMs: 299960, text: "If you have breath, then choose it now.\nIf you have voice, then use it loud.\nThe door is still open.\nBut not forever.", emphasis: "whisper" },
  ],
  theaterMode: { themeColor: "#1A3A6B", overlayStyle: "vignette", act: "ACT I: THE WARNING", revParallel: "Rev 2-3", narrators: ["antiquarian", "storyteller"], dialogBeats: [], loreCardReveals: [] },
};
