/* ═══════════════════════════════════════════════════════
   PAIR-BANK BARREL — generated by
   apps/scripts/generate-nemesis-pair-banks.ts. Edit the
   per-pair files individually; this barrel is rewritten
   on each generator run.
   ═══════════════════════════════════════════════════════ */

export type { NemesisPairBank, NemesisScene, NemesisGrudgeBand, NemesisEncounterSceneId } from "./_types";
export { makeScene } from "./_types";

import { zealotVsGhostPairBank } from "./zealot_vs_ghost";
import { zealotVsScholarPairBank } from "./zealot_vs_scholar";
import { zealotVsRevenantPairBank } from "./zealot_vs_revenant";
import { zealotVsArtisanPairBank } from "./zealot_vs_artisan";
import { zealotVsOraclePairBank } from "./zealot_vs_oracle";
import { zealotVsWandererPairBank } from "./zealot_vs_wanderer";
import { zealotVsMartyrPairBank } from "./zealot_vs_martyr";
import { zealotVsHereticPairBank } from "./zealot_vs_heretic";
import { zealotVsJesterPairBank } from "./zealot_vs_jester";
import { zealotVsSentinelPairBank } from "./zealot_vs_sentinel";
import { zealotVsProdigalPairBank } from "./zealot_vs_prodigal";
import { ghostVsZealotPairBank } from "./ghost_vs_zealot";
import { ghostVsScholarPairBank } from "./ghost_vs_scholar";
import { ghostVsRevenantPairBank } from "./ghost_vs_revenant";
import { ghostVsArtisanPairBank } from "./ghost_vs_artisan";
import { ghostVsOraclePairBank } from "./ghost_vs_oracle";
import { ghostVsWandererPairBank } from "./ghost_vs_wanderer";
import { ghostVsMartyrPairBank } from "./ghost_vs_martyr";
import { ghostVsHereticPairBank } from "./ghost_vs_heretic";
import { ghostVsJesterPairBank } from "./ghost_vs_jester";
import { ghostVsSentinelPairBank } from "./ghost_vs_sentinel";
import { ghostVsProdigalPairBank } from "./ghost_vs_prodigal";
import { scholarVsZealotPairBank } from "./scholar_vs_zealot";
import { scholarVsGhostPairBank } from "./scholar_vs_ghost";
import { scholarVsRevenantPairBank } from "./scholar_vs_revenant";
import { scholarVsArtisanPairBank } from "./scholar_vs_artisan";
import { scholarVsOraclePairBank } from "./scholar_vs_oracle";
import { scholarVsWandererPairBank } from "./scholar_vs_wanderer";
import { scholarVsMartyrPairBank } from "./scholar_vs_martyr";
import { scholarVsHereticPairBank } from "./scholar_vs_heretic";
import { scholarVsJesterPairBank } from "./scholar_vs_jester";
import { scholarVsSentinelPairBank } from "./scholar_vs_sentinel";
import { scholarVsProdigalPairBank } from "./scholar_vs_prodigal";
import { revenantVsZealotPairBank } from "./revenant_vs_zealot";
import { revenantVsGhostPairBank } from "./revenant_vs_ghost";
import { revenantVsScholarPairBank } from "./revenant_vs_scholar";
import { revenantVsArtisanPairBank } from "./revenant_vs_artisan";
import { revenantVsOraclePairBank } from "./revenant_vs_oracle";
import { revenantVsWandererPairBank } from "./revenant_vs_wanderer";
import { revenantVsMartyrPairBank } from "./revenant_vs_martyr";
import { revenantVsHereticPairBank } from "./revenant_vs_heretic";
import { revenantVsJesterPairBank } from "./revenant_vs_jester";
import { revenantVsSentinelPairBank } from "./revenant_vs_sentinel";
import { revenantVsProdigalPairBank } from "./revenant_vs_prodigal";
import { artisanVsZealotPairBank } from "./artisan_vs_zealot";
import { artisanVsGhostPairBank } from "./artisan_vs_ghost";
import { artisanVsScholarPairBank } from "./artisan_vs_scholar";
import { artisanVsRevenantPairBank } from "./artisan_vs_revenant";
import { artisanVsOraclePairBank } from "./artisan_vs_oracle";
import { artisanVsWandererPairBank } from "./artisan_vs_wanderer";
import { artisanVsMartyrPairBank } from "./artisan_vs_martyr";
import { artisanVsHereticPairBank } from "./artisan_vs_heretic";
import { artisanVsJesterPairBank } from "./artisan_vs_jester";
import { artisanVsSentinelPairBank } from "./artisan_vs_sentinel";
import { artisanVsProdigalPairBank } from "./artisan_vs_prodigal";
import { oracleVsZealotPairBank } from "./oracle_vs_zealot";
import { oracleVsGhostPairBank } from "./oracle_vs_ghost";
import { oracleVsScholarPairBank } from "./oracle_vs_scholar";
import { oracleVsRevenantPairBank } from "./oracle_vs_revenant";
import { oracleVsArtisanPairBank } from "./oracle_vs_artisan";
import { oracleVsWandererPairBank } from "./oracle_vs_wanderer";
import { oracleVsMartyrPairBank } from "./oracle_vs_martyr";
import { oracleVsHereticPairBank } from "./oracle_vs_heretic";
import { oracleVsJesterPairBank } from "./oracle_vs_jester";
import { oracleVsSentinelPairBank } from "./oracle_vs_sentinel";
import { oracleVsProdigalPairBank } from "./oracle_vs_prodigal";
import { wandererVsZealotPairBank } from "./wanderer_vs_zealot";
import { wandererVsGhostPairBank } from "./wanderer_vs_ghost";
import { wandererVsScholarPairBank } from "./wanderer_vs_scholar";
import { wandererVsRevenantPairBank } from "./wanderer_vs_revenant";
import { wandererVsArtisanPairBank } from "./wanderer_vs_artisan";
import { wandererVsOraclePairBank } from "./wanderer_vs_oracle";
import { wandererVsMartyrPairBank } from "./wanderer_vs_martyr";
import { wandererVsHereticPairBank } from "./wanderer_vs_heretic";
import { wandererVsJesterPairBank } from "./wanderer_vs_jester";
import { wandererVsSentinelPairBank } from "./wanderer_vs_sentinel";
import { wandererVsProdigalPairBank } from "./wanderer_vs_prodigal";
import { martyrVsZealotPairBank } from "./martyr_vs_zealot";
import { martyrVsGhostPairBank } from "./martyr_vs_ghost";
import { martyrVsScholarPairBank } from "./martyr_vs_scholar";
import { martyrVsRevenantPairBank } from "./martyr_vs_revenant";
import { martyrVsArtisanPairBank } from "./martyr_vs_artisan";
import { martyrVsOraclePairBank } from "./martyr_vs_oracle";
import { martyrVsWandererPairBank } from "./martyr_vs_wanderer";
import { martyrVsHereticPairBank } from "./martyr_vs_heretic";
import { martyrVsJesterPairBank } from "./martyr_vs_jester";
import { martyrVsSentinelPairBank } from "./martyr_vs_sentinel";
import { martyrVsProdigalPairBank } from "./martyr_vs_prodigal";
import { hereticVsZealotPairBank } from "./heretic_vs_zealot";
import { hereticVsGhostPairBank } from "./heretic_vs_ghost";
import { hereticVsScholarPairBank } from "./heretic_vs_scholar";
import { hereticVsRevenantPairBank } from "./heretic_vs_revenant";
import { hereticVsArtisanPairBank } from "./heretic_vs_artisan";
import { hereticVsOraclePairBank } from "./heretic_vs_oracle";
import { hereticVsWandererPairBank } from "./heretic_vs_wanderer";
import { hereticVsMartyrPairBank } from "./heretic_vs_martyr";
import { hereticVsJesterPairBank } from "./heretic_vs_jester";
import { hereticVsSentinelPairBank } from "./heretic_vs_sentinel";
import { hereticVsProdigalPairBank } from "./heretic_vs_prodigal";
import { jesterVsZealotPairBank } from "./jester_vs_zealot";
import { jesterVsGhostPairBank } from "./jester_vs_ghost";
import { jesterVsScholarPairBank } from "./jester_vs_scholar";
import { jesterVsRevenantPairBank } from "./jester_vs_revenant";
import { jesterVsArtisanPairBank } from "./jester_vs_artisan";
import { jesterVsOraclePairBank } from "./jester_vs_oracle";
import { jesterVsWandererPairBank } from "./jester_vs_wanderer";
import { jesterVsMartyrPairBank } from "./jester_vs_martyr";
import { jesterVsHereticPairBank } from "./jester_vs_heretic";
import { jesterVsSentinelPairBank } from "./jester_vs_sentinel";
import { jesterVsProdigalPairBank } from "./jester_vs_prodigal";
import { sentinelVsZealotPairBank } from "./sentinel_vs_zealot";
import { sentinelVsGhostPairBank } from "./sentinel_vs_ghost";
import { sentinelVsScholarPairBank } from "./sentinel_vs_scholar";
import { sentinelVsRevenantPairBank } from "./sentinel_vs_revenant";
import { sentinelVsArtisanPairBank } from "./sentinel_vs_artisan";
import { sentinelVsOraclePairBank } from "./sentinel_vs_oracle";
import { sentinelVsWandererPairBank } from "./sentinel_vs_wanderer";
import { sentinelVsMartyrPairBank } from "./sentinel_vs_martyr";
import { sentinelVsHereticPairBank } from "./sentinel_vs_heretic";
import { sentinelVsJesterPairBank } from "./sentinel_vs_jester";
import { sentinelVsProdigalPairBank } from "./sentinel_vs_prodigal";
import { prodigalVsZealotPairBank } from "./prodigal_vs_zealot";
import { prodigalVsGhostPairBank } from "./prodigal_vs_ghost";
import { prodigalVsScholarPairBank } from "./prodigal_vs_scholar";
import { prodigalVsRevenantPairBank } from "./prodigal_vs_revenant";
import { prodigalVsArtisanPairBank } from "./prodigal_vs_artisan";
import { prodigalVsOraclePairBank } from "./prodigal_vs_oracle";
import { prodigalVsWandererPairBank } from "./prodigal_vs_wanderer";
import { prodigalVsMartyrPairBank } from "./prodigal_vs_martyr";
import { prodigalVsHereticPairBank } from "./prodigal_vs_heretic";
import { prodigalVsJesterPairBank } from "./prodigal_vs_jester";
import { prodigalVsSentinelPairBank } from "./prodigal_vs_sentinel";

export const NEMESIS_PAIR_BANKS = [
  zealotVsGhostPairBank,
  zealotVsScholarPairBank,
  zealotVsRevenantPairBank,
  zealotVsArtisanPairBank,
  zealotVsOraclePairBank,
  zealotVsWandererPairBank,
  zealotVsMartyrPairBank,
  zealotVsHereticPairBank,
  zealotVsJesterPairBank,
  zealotVsSentinelPairBank,
  zealotVsProdigalPairBank,
  ghostVsZealotPairBank,
  ghostVsScholarPairBank,
  ghostVsRevenantPairBank,
  ghostVsArtisanPairBank,
  ghostVsOraclePairBank,
  ghostVsWandererPairBank,
  ghostVsMartyrPairBank,
  ghostVsHereticPairBank,
  ghostVsJesterPairBank,
  ghostVsSentinelPairBank,
  ghostVsProdigalPairBank,
  scholarVsZealotPairBank,
  scholarVsGhostPairBank,
  scholarVsRevenantPairBank,
  scholarVsArtisanPairBank,
  scholarVsOraclePairBank,
  scholarVsWandererPairBank,
  scholarVsMartyrPairBank,
  scholarVsHereticPairBank,
  scholarVsJesterPairBank,
  scholarVsSentinelPairBank,
  scholarVsProdigalPairBank,
  revenantVsZealotPairBank,
  revenantVsGhostPairBank,
  revenantVsScholarPairBank,
  revenantVsArtisanPairBank,
  revenantVsOraclePairBank,
  revenantVsWandererPairBank,
  revenantVsMartyrPairBank,
  revenantVsHereticPairBank,
  revenantVsJesterPairBank,
  revenantVsSentinelPairBank,
  revenantVsProdigalPairBank,
  artisanVsZealotPairBank,
  artisanVsGhostPairBank,
  artisanVsScholarPairBank,
  artisanVsRevenantPairBank,
  artisanVsOraclePairBank,
  artisanVsWandererPairBank,
  artisanVsMartyrPairBank,
  artisanVsHereticPairBank,
  artisanVsJesterPairBank,
  artisanVsSentinelPairBank,
  artisanVsProdigalPairBank,
  oracleVsZealotPairBank,
  oracleVsGhostPairBank,
  oracleVsScholarPairBank,
  oracleVsRevenantPairBank,
  oracleVsArtisanPairBank,
  oracleVsWandererPairBank,
  oracleVsMartyrPairBank,
  oracleVsHereticPairBank,
  oracleVsJesterPairBank,
  oracleVsSentinelPairBank,
  oracleVsProdigalPairBank,
  wandererVsZealotPairBank,
  wandererVsGhostPairBank,
  wandererVsScholarPairBank,
  wandererVsRevenantPairBank,
  wandererVsArtisanPairBank,
  wandererVsOraclePairBank,
  wandererVsMartyrPairBank,
  wandererVsHereticPairBank,
  wandererVsJesterPairBank,
  wandererVsSentinelPairBank,
  wandererVsProdigalPairBank,
  martyrVsZealotPairBank,
  martyrVsGhostPairBank,
  martyrVsScholarPairBank,
  martyrVsRevenantPairBank,
  martyrVsArtisanPairBank,
  martyrVsOraclePairBank,
  martyrVsWandererPairBank,
  martyrVsHereticPairBank,
  martyrVsJesterPairBank,
  martyrVsSentinelPairBank,
  martyrVsProdigalPairBank,
  hereticVsZealotPairBank,
  hereticVsGhostPairBank,
  hereticVsScholarPairBank,
  hereticVsRevenantPairBank,
  hereticVsArtisanPairBank,
  hereticVsOraclePairBank,
  hereticVsWandererPairBank,
  hereticVsMartyrPairBank,
  hereticVsJesterPairBank,
  hereticVsSentinelPairBank,
  hereticVsProdigalPairBank,
  jesterVsZealotPairBank,
  jesterVsGhostPairBank,
  jesterVsScholarPairBank,
  jesterVsRevenantPairBank,
  jesterVsArtisanPairBank,
  jesterVsOraclePairBank,
  jesterVsWandererPairBank,
  jesterVsMartyrPairBank,
  jesterVsHereticPairBank,
  jesterVsSentinelPairBank,
  jesterVsProdigalPairBank,
  sentinelVsZealotPairBank,
  sentinelVsGhostPairBank,
  sentinelVsScholarPairBank,
  sentinelVsRevenantPairBank,
  sentinelVsArtisanPairBank,
  sentinelVsOraclePairBank,
  sentinelVsWandererPairBank,
  sentinelVsMartyrPairBank,
  sentinelVsHereticPairBank,
  sentinelVsJesterPairBank,
  sentinelVsProdigalPairBank,
  prodigalVsZealotPairBank,
  prodigalVsGhostPairBank,
  prodigalVsScholarPairBank,
  prodigalVsRevenantPairBank,
  prodigalVsArtisanPairBank,
  prodigalVsOraclePairBank,
  prodigalVsWandererPairBank,
  prodigalVsMartyrPairBank,
  prodigalVsHereticPairBank,
  prodigalVsJesterPairBank,
  prodigalVsSentinelPairBank,
] as const;
