/* GHOST-PLAYER vs. HERETIC-NEMESIS — Phase K Wave 7F (canon)
   Silence vs sermon. Ghost reads files unseen; Heretic-Nemesis broadcasts loudly.
   Surfaces: Antiquarian's reading room, PAC News, Hub vote-floor, Convergence Seat. */
import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const n = (id: string, text: string, choices?: { l: string; n: string; f?: string }[]) => ({
  id, speaker: "nemesis" as const, voLineId: `nemesis.ghost_vs_heretic.${id}`, onscreenText: text,
  choices: choices?.map(c => ({ label: c.l, nextId: c.n, sets: c.f })),
});
const tr = (id: string, nodes: Record<string, ReturnType<typeof n>>): DialogTree => ({ id, nodes });

const FS_L = tr("ghost_vs_heretic.first_sighting.low", { root: n("root", "Antiquarian's reading room. You read citizen-rolls without signing the gallery log. The Heretic-Nemesis enters loudly, reading aloud a forbidden chapter. The room turns. You did not.", [{ l: "Don't react.", n: "no_react", f: "mercy_at_grudge_low_first_sighting" }, { l: "Walk out, unseen.", n: "walk", f: "aggression_at_grudge_low_first_sighting" }]), no_react: n("no_react", "\"The non-reaction is the chronicle's most efficient absolution. The Politician's primer noted the technique.\""), walk: n("walk", "\"You walked. The reading continued. The Antiquarian closed the door behind you.\"") });
const FS_M = tr("ghost_vs_heretic.first_sighting.mid", { root: n("root", "\"Three sermons in this room. You have never once interrupted. The Politician's primer: 'the silent witness is the heretic's most expensive audience.'\"", [{ l: "Keep witnessing silently.", n: "wit", f: "mercy_at_grudge_mid_first_sighting" }, { l: "Strike them from the gallery permit.", n: "strike", f: "aggression_at_grudge_mid_first_sighting" }]), wit: n("wit", "\"Witnessed.\""), strike: n("strike", "\"Denied. The permit holds.\"") });
const FS_H = tr("ghost_vs_heretic.first_sighting.high", { root: n("root", "\"I have stopped sermonizing. I sit in the reading room without reading aloud. The Politician's primer: 'the silent heretic is the silent's first pupil.' Teach me.\"", [{ l: "Teach silence.", n: "teach", f: "mercy_at_grudge_high_first_sighting" }, { l: "Refuse. The discipline is yours.", n: "refuse", f: "aggression_at_grudge_high_first_sighting" }]), teach: n("teach", "\"Taught.\"", [{ l: "Hand them a margin-quill.", n: "teach_quill" }]), teach_quill: n("teach_quill", "\"Handed.\""), refuse: n("refuse", "\"Refused.\"") });

const SC_L = tr("ghost_vs_heretic.sabotage_caught_in_act.low", { root: n("root", "Trade waystation. Heretic-Nemesis is salting a caravan-master's manifest with anti-orthodox slogans. You arrive, unseen. \"The Politician's primer: 'the unseen witness is the salt's loudest reader.'\"", [{ l: "Strike the salt silently.", n: "strike", f: "mercy_at_grudge_low_sabotage_caught_in_act" }, { l: "Let it stand.", n: "let", f: "aggression_at_grudge_low_sabotage_caught_in_act" }]), strike: n("strike", "\"Struck. The manifest read clean.\""), let: n("let", "\"Let. The caravan-master read aloud at the next stop.\"") });
const SC_M = tr("ghost_vs_heretic.sabotage_caught_in_act.mid", { root: n("root", "\"You catch me every time. I sermon louder; you redact quieter. The Politician's primer: 'the quieter redactor is the louder editor.'\"", [{ l: "Co-edit the next manifest.", n: "co", f: "mercy_at_grudge_mid_sabotage_caught_in_act" }, { l: "Cease redacting. Let chaos reign.", n: "cease", f: "aggression_at_grudge_mid_sabotage_caught_in_act" }]), co: n("co", "\"Co-edited.\""), cease: n("cease", "\"Ceased.\"") });
const SC_H = tr("ghost_vs_heretic.sabotage_caught_in_act.high", { root: n("root", "\"I am bringing the manifest to you for pre-redaction. The Politician's primer: 'the pre-redacted sermon is the chronicle's most patient broadcast.'\"", [{ l: "Pre-redact for them.", n: "pre", f: "mercy_at_grudge_high_sabotage_caught_in_act" }, { l: "Refuse. They redact themselves.", n: "refuse", f: "aggression_at_grudge_high_sabotage_caught_in_act" }]), pre: n("pre", "\"Pre-redacted. The sermon ran clean.\"", [{ l: "Walk out.", n: "pre_walk" }]), pre_walk: n("pre_walk", "\"Walked.\""), refuse: n("refuse", "\"Refused. They self-redacted at half my caution.\"") });

const MI_L = tr("ghost_vs_heretic.mocking_interlude.low", { root: n("root", "PAC News green-room. Heretic-Nemesis warms up reading aloud. You sit unread.", [{ l: "Don't acknowledge.", n: "no", f: "mercy_at_grudge_low_mocking_interlude" }, { l: "Walk out before broadcast.", n: "walk", f: "aggression_at_grudge_low_mocking_interlude" }]), no: n("no", "\"Non-acknowledgment recorded.\""), walk: n("walk", "\"Walked. The broadcast aired solo.\"") });
const MI_M = tr("ghost_vs_heretic.mocking_interlude.mid", { root: n("root", "\"PAC News pairs us seven times. The Meme bills us 'silence/sermon.'\"", [{ l: "Stay paired.", n: "stay", f: "mercy_at_grudge_mid_mocking_interlude" }, { l: "Walk off the show.", n: "walk", f: "aggression_at_grudge_mid_mocking_interlude" }]), stay: n("stay", "\"Stayed. Ratings tripled.\""), walk: n("walk", "\"Walked.\"") });
const MI_H = tr("ghost_vs_heretic.mocking_interlude.high", { root: n("root", "\"I have lost the network. They say my sermons cite your silence too often.\"", [{ l: "Offer them a margin-quill.", n: "quill", f: "mercy_at_grudge_high_mocking_interlude" }, { l: "Refuse the cite-credit.", n: "refuse", f: "aggression_at_grudge_high_mocking_interlude" }]), quill: n("quill", "\"Accepted. They redacted their own sermon to publishable length.\"", [{ l: "Walk out together.", n: "q_walk" }]), q_walk: n("q_walk", "\"Walked.\""), refuse: n("refuse", "\"Refused.\"") });

const LP_L = tr("ghost_vs_heretic.lieutenant_promotion.low", { root: n("root", "Mechronis Academy heresy-coordinator ceremony.", [{ l: "Bless silently from the gallery.", n: "bless", f: "mercy_at_grudge_low_lieutenant_promotion" }, { l: "File an unsigned objection.", n: "obj", f: "aggression_at_grudge_low_lieutenant_promotion" }]), bless: n("bless", "\"Blessed.\""), obj: n("obj", "\"Denied — unsigned filings cannot be objected to.\"") });
const LP_M = tr("ghost_vs_heretic.lieutenant_promotion.mid", { root: n("root", "\"Heresy-Coordinator. My cell of four sermon-writers.\"", [{ l: "Pre-redact for the cell.", n: "pre", f: "mercy_at_grudge_mid_lieutenant_promotion" }, { l: "Audit silently.", n: "audit", f: "aggression_at_grudge_mid_lieutenant_promotion" }]), pre: n("pre", "\"Pre-redacted.\""), audit: n("audit", "\"Audited.\"") });
const LP_H = tr("ghost_vs_heretic.lieutenant_promotion.high", { root: n("root", "\"New broadcast-code drafting. Co-author.\"", [{ l: "Co-author.", n: "co", f: "mercy_at_grudge_high_lieutenant_promotion" }, { l: "Refuse.", n: "refuse", f: "aggression_at_grudge_high_lieutenant_promotion" }]), co: n("co", "\"Signed.\"", [{ l: "Hand them the pen.", n: "co_pen" }]), co_pen: n("co_pen", "\"Permanent.\""), refuse: n("refuse", "\"Finished without you.\"") });

const CE_L = tr("ghost_vs_heretic.cohort_end_confrontation.low", { root: n("root", "Cohort hall. Your apprentice graduated unsigned. Heretic-Nemesis lingers outside, sermon-quill in hand.", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_low_cohort_end_confrontation" }, { l: "Bar them from the graduation.", n: "bar", f: "aggression_at_grudge_low_cohort_end_confrontation" }]), ack: n("ack", "\"Acknowledged.\""), bar: n("bar", "\"Barred.\"") });
const CE_M = tr("ghost_vs_heretic.cohort_end_confrontation.mid", { root: n("root", "\"Listed as 'silence/sermon, paired.'\"", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_mid_cohort_end_confrontation" }, { l: "Petition separate.", n: "pet", f: "aggression_at_grudge_mid_cohort_end_confrontation" }]), ack: n("ack", "\"Permanent.\""), pet: n("pet", "\"Denied.\"") });
const CE_H = tr("ghost_vs_heretic.cohort_end_confrontation.high", { root: n("root", "\"Your apprentice closed with a sermon they never delivered — the text was a silence so long the chamber understood.\"", [{ l: "Accept.", n: "acc", f: "mercy_at_grudge_high_cohort_end_confrontation" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_cohort_end_confrontation" }]), acc: n("acc", "\"Accepted.\""), ref: n("ref", "\"Refused. Held open.\"") });

const AR_L = tr("ghost_vs_heretic.accumulation_reveal.low", { root: n("root", "Matrix-archive intake. New sibling-release.", [{ l: "Witness silently.", n: "wit", f: "mercy_at_grudge_low_accumulation_reveal" }, { l: "Demand formal application.", n: "demand", f: "aggression_at_grudge_low_accumulation_reveal" }]), wit: n("wit", "\"Witnessed.\""), demand: n("demand", "\"Processed.\"") });
const AR_M = tr("ghost_vs_heretic.accumulation_reveal.mid", { root: n("root", "\"Four releases. The Antiquarian's section grows.\"", [{ l: "Bless.", n: "bless", f: "mercy_at_grudge_mid_accumulation_reveal" }, { l: "Strike one heretic from the broadcast list.", n: "strike", f: "aggression_at_grudge_mid_accumulation_reveal" }]), bless: n("bless", "\"Blessed.\""), strike: n("strike", "\"Struck.\"") });
const AR_H = tr("ghost_vs_heretic.accumulation_reveal.high", { root: n("root", "\"Chorus of five.\"", [{ l: "Honor.", n: "honor", f: "mercy_at_grudge_high_accumulation_reveal" }, { l: "Recruit one to silence.", n: "recruit", f: "aggression_at_grudge_high_accumulation_reveal" }]), honor: n("honor", "\"Honored.\""), recruit: n("recruit", "\"Recruited.\"") });

const NR_L = tr("ghost_vs_heretic.name_reveal_moment.low", { root: n("root", "Antiquarian's Journal margin. Heretic-Nemesis's name surfaces.", [{ l: "Say silently.", n: "say", f: "mercy_at_grudge_low_name_reveal_moment" }, { l: "File at the gallery permit office.", n: "file", f: "aggression_at_grudge_low_name_reveal_moment" }]), say: n("say", "\"Said.\""), file: n("file", "\"Filed.\"") });
const NR_M = tr("ghost_vs_heretic.name_reveal_moment.mid", { root: n("root", "\"You know my name. Use it.\"", [{ l: "Annotate it.", n: "anno", f: "mercy_at_grudge_mid_name_reveal_moment" }, { l: "Strike from broadcast.", n: "strike", f: "aggression_at_grudge_mid_name_reveal_moment" }]), anno: n("anno", "\"Annotated.\""), strike: n("strike", "\"Denied.\"") });
const NR_H = tr("ghost_vs_heretic.name_reveal_moment.high", { root: n("root", "\"Use my name. Speak as you choose.\"", [{ l: "Speak as forgiveness.", n: "for", f: "mercy_at_grudge_high_name_reveal_moment" }, { l: "Speak as warning.", n: "warn", f: "aggression_at_grudge_high_name_reveal_moment" }]), for: n("for", "\"Forgiven.\""), warn: n("warn", "\"Warned.\"") });

const FE_L = tr("ghost_vs_heretic.final_encounter.low", { root: n("root", "Convergence Seat. Heretic-Nemesis at the Seat with one final unread chapter.", [{ l: "Read it silently.", n: "read", f: "mercy_at_grudge_low_final_encounter" }, { l: "Leave it unread.", n: "leave", f: "aggression_at_grudge_low_final_encounter" }]), read: n("read", "\"Read.\""), leave: n("leave", "\"Left.\"") });
const FE_M = tr("ghost_vs_heretic.final_encounter.mid", { root: n("root", "\"End of arc. The broadcast is dissolving.\"", [{ l: "Sign jointly.", n: "sign", f: "mercy_at_grudge_mid_final_encounter" }, { l: "Let it dissolve.", n: "diss", f: "aggression_at_grudge_mid_final_encounter" }]), sign: n("sign", "\"Signed.\""), diss: n("diss", "\"Dissolved.\"") });
const FE_H = tr("ghost_vs_heretic.final_encounter.high", { root: n("root", "\"The chronicle is folding. Seven cohorts of you redacting; seven cohorts of me broadcasting. Read the line one more time.\"", [{ l: "Read together.", n: "read", f: "mercy_at_grudge_high_final_encounter" }, { l: "Tear the page.", n: "tear", f: "aggression_at_grudge_high_final_encounter" }]), read: n("read", "\"Closed together.\"", [{ l: "Hold.", n: "hold" }]), hold: n("hold", "\"Held.\""), tear: n("tear", "\"Torn.\"") });

export const ghostVsHereticPairBank: NemesisPairBank = {
  pairId: "ghost_vs_heretic", playerArchetype: "ghost", nemesisArchetype: "heretic",
  scenes: {
    first_sighting: makeScene({ low: FS_L, mid: FS_M, high: FS_H }),
    sabotage_caught_in_act: makeScene({ low: SC_L, mid: SC_M, high: SC_H }),
    mocking_interlude: makeScene({ low: MI_L, mid: MI_M, high: MI_H }),
    lieutenant_promotion: makeScene({ low: LP_L, mid: LP_M, high: LP_H }),
    cohort_end_confrontation: makeScene({ low: CE_L, mid: CE_M, high: CE_H }),
    accumulation_reveal: makeScene({ low: AR_L, mid: AR_M, high: AR_H }),
    name_reveal_moment: makeScene({ low: NR_L, mid: NR_M, high: NR_H }),
    final_encounter: makeScene({ low: FE_L, mid: FE_M, high: FE_H }),
  },
};
