/* ═══════════════════════════════════════════════════════
   Ghost-PLAYER vs. Artisan-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.artisan.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "ghost_vs_artisan.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.low.opening",
      onscreenText: "You break what I shaped. The break tells me what I should have built instead. Hello.",
      choices: [
        { label: "Watch them.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Mark them.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.low.to_mercy",
      onscreenText: "Soft hand. The rework benefits from a soft hand at this stage.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.low.to_aggression",
      onscreenText: "Hard blow. Useful — I needed to test the joint anyway.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "ghost_vs_artisan.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.mid.opening",
      onscreenText: "I have built three iterations of you in my head. None of them flatter you. Hello.",
      choices: [
        { label: "Look away.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Step closer.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.mid.to_mercy",
      onscreenText: "Mercy as a design choice. I will incorporate it. Reluctantly.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.mid.to_aggression",
      onscreenText: "Force the seam. I want to know where you actually fail.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "ghost_vs_artisan.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.high.opening",
      onscreenText: "Final iteration. I built it from your worst week. You will recognize it; you'll just be inside it.",
      choices: [
        { label: "Walk past them.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Give the kill.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.high.to_mercy",
      onscreenText: "The mercy joint holds. Surprising. You may yet survive your own design.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_artisan.first_sighting.high.to_aggression",
      onscreenText: "Yes. The break I designed for. Symmetric to the bone.",
    },
  },
};

export const ghostVsArtisanPairBank: NemesisPairBank = {
  pairId: "ghost_vs_artisan",
  playerArchetype: "ghost",
  nemesisArchetype: "artisan",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
