/* ═══════════════════════════════════════════════════════
   Ghost-PLAYER vs. Revenant-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.revenant.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "ghost_vs_revenant.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.low.opening",
      onscreenText: "You owe me a debt you don't remember incurring. The principal compounds. Hello.",
      choices: [
        { label: "Watch them.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Mark them.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.low.to_mercy",
      onscreenText: "Mercy. Noted as an interest payment. The principal remains.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.low.to_aggression",
      onscreenText: "Add it to the ledger. I'll come back richer for it.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "ghost_vs_revenant.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.mid.opening",
      onscreenText: "The debt has tripled. You are making me wealthy in ways that do not show on either of our faces.",
      choices: [
        { label: "Look away.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Step closer.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.mid.to_mercy",
      onscreenText: "Partial payment accepted. I will be back. Same time. Larger figure.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.mid.to_aggression",
      onscreenText: "Yes. The interest rate prefers violence. You're a generous debtor in this sense.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "ghost_vs_revenant.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.high.opening",
      onscreenText: "Final notice. The debt is mine to forgive or collect. The chronicle is taking notes either way.",
      choices: [
        { label: "Walk past them.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Give the kill.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.high.to_mercy",
      onscreenText: "You have settled. The debt closes. Do not open a new account with me. I will remember the rate.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.ghost_vs_revenant.first_sighting.high.to_aggression",
      onscreenText: "Foreclosure. Acceptable. The Politician's books taught me how to take it back in kind.",
    },
  },
};

export const ghostVsRevenantPairBank: NemesisPairBank = {
  pairId: "ghost_vs_revenant",
  playerArchetype: "ghost",
  nemesisArchetype: "revenant",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
