/* HERETIC-PLAYER vs. GHOST-NEMESIS — Phase K Wave 7F (canon, reverse)
   Sermon vs silence. You broadcast; Ghost-Nemesis annotates unseen.
   Surfaces: Hub vote-floor, PAC News, Antiquarian's reading room, Convergence Seat. */
import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";
const n = (id: string, text: string, choices?: { l: string; n: string; f?: string }[]) => ({ id, speaker: "nemesis" as const, voLineId: `nemesis.heretic_vs_ghost.${id}`, onscreenText: text, choices: choices?.map(c => ({ label: c.l, nextId: c.n, sets: c.f })) });
const tr = (id: string, nodes: Record<string, ReturnType<typeof n>>): DialogTree => ({ id, nodes });

const FS_L = tr("heretic_vs_ghost.first_sighting.low", { root: n("root", "Hub vote-floor. You deliver an anti-orthodoxy sermon. A margin-note appears on your podium copy in unfamiliar hand: 'cited at page 14; the citation was wrong by one word.' The Ghost-Nemesis is not in the chamber. They were here earlier.", [{ l: "Correct the citation aloud.", n: "correct", f: "mercy_at_grudge_low_first_sighting" }, { l: "Ignore the margin-note.", n: "ignore", f: "aggression_at_grudge_low_first_sighting" }]), correct: n("correct", "\"Corrected. The Antiquarian's clerks noted the in-flight correction.\""), ignore: n("ignore", "\"Ignored. The wrong citation entered the record.\"") });
const FS_M = tr("heretic_vs_ghost.first_sighting.mid", { root: n("root", "\"Three sermons; three margin-notes. The Politician's primer: 'the unseen annotator is the loudest critic.'\"", [{ l: "Read the notes aloud.", n: "read", f: "mercy_at_grudge_mid_first_sighting" }, { l: "Burn them.", n: "burn", f: "aggression_at_grudge_mid_first_sighting" }]), read: n("read", "\"Read. The chamber understood.\""), burn: n("burn", "\"Burned. The next note appeared in the same hand, with the same correction.\"") });
const FS_H = tr("heretic_vs_ghost.first_sighting.high", { root: n("root", "\"I have stopped annotating. The reading room is empty. The Politician's primer: 'the silent critic who stops is the silent critic who has joined.' Invite me to your next sermon.\"", [{ l: "Invite them.", n: "inv", f: "mercy_at_grudge_high_first_sighting" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_first_sighting" }]), inv: n("inv", "\"Invited.\"", [{ l: "Hand them a margin-quill.", n: "inv_q" }]), inv_q: n("inv_q", "\"Handed.\""), ref: n("ref", "\"Refused.\"") });

const SC_L = tr("heretic_vs_ghost.sabotage_caught_in_act.low", { root: n("root", "PAC News studio. You broadcast a heresy. A redaction appears on your script live, in unfamiliar hand. \"The Politician's primer: 'the live redaction is the chronicle's most disciplined edit.'\"", [{ l: "Read the redacted version.", n: "redact", f: "mercy_at_grudge_low_sabotage_caught_in_act" }, { l: "Read the original anyway.", n: "orig", f: "aggression_at_grudge_low_sabotage_caught_in_act" }]), redact: n("redact", "\"Read clean. Ratings held.\""), orig: n("orig", "\"Read raw. The Hierarchy filed a complaint.\"") });
const SC_M = tr("heretic_vs_ghost.sabotage_caught_in_act.mid", { root: n("root", "\"Every broadcast, redacted on the page. The Politician's primer: 'the redaction the heretic accepts is the heretic's truest pulpit.'\"", [{ l: "Accept the redactions.", n: "acc", f: "mercy_at_grudge_mid_sabotage_caught_in_act" }, { l: "Strike through them.", n: "strike", f: "aggression_at_grudge_mid_sabotage_caught_in_act" }]), acc: n("acc", "\"Accepted.\""), strike: n("strike", "\"Struck. The chamber filed the strike-through.\"") });
const SC_H = tr("heretic_vs_ghost.sabotage_caught_in_act.high", { root: n("root", "\"I am at the studio in person. I want to redact alongside you, with my hand visible.\"", [{ l: "Welcome the visible redactor.", n: "wel", f: "mercy_at_grudge_high_sabotage_caught_in_act" }, { l: "Refuse the partnership.", n: "ref", f: "aggression_at_grudge_high_sabotage_caught_in_act" }]), wel: n("wel", "\"Welcomed.\"", [{ l: "Co-edit the broadcast.", n: "wel_co" }]), wel_co: n("wel_co", "\"Co-edited.\""), ref: n("ref", "\"Refused.\"") });

const MI_L = tr("heretic_vs_ghost.mocking_interlude.low", { root: n("root", "Antiquarian's reading room, after hours. A note slips under the door in unfamiliar hand: 'i am here. just here.'", [{ l: "Send a note back.", n: "send", f: "mercy_at_grudge_low_mocking_interlude" }, { l: "Burn the note.", n: "burn", f: "aggression_at_grudge_low_mocking_interlude" }]), send: n("send", "\"Sent. A reply appeared within the hour.\""), burn: n("burn", "\"Burned. The next note appeared anyway.\"") });
const MI_M = tr("heretic_vs_ghost.mocking_interlude.mid", { root: n("root", "\"Three rooms of correspondence. The Antiquarian frames our exchanges.\"", [{ l: "Continue.", n: "co", f: "mercy_at_grudge_mid_mocking_interlude" }, { l: "Stop writing back.", n: "stop", f: "aggression_at_grudge_mid_mocking_interlude" }]), co: n("co", "\"Continued.\""), stop: n("stop", "\"Stopped. The notes kept coming.\"") });
const MI_H = tr("heretic_vs_ghost.mocking_interlude.high", { root: n("root", "\"I am here in person tonight. I would like to read with you, silently, until dawn.\"", [{ l: "Read together.", n: "read", f: "mercy_at_grudge_high_mocking_interlude" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_mocking_interlude" }]), read: n("read", "\"Read together.\"", [{ l: "Until dawn.", n: "read_dawn" }]), read_dawn: n("read_dawn", "\"Dawn.\""), ref: n("ref", "\"Refused.\"") });

const LP_L = tr("heretic_vs_ghost.lieutenant_promotion.low", { root: n("root", "Adjudicator's silence-coordinator ceremony.", [{ l: "Bless from the broadcast desk.", n: "bless", f: "mercy_at_grudge_low_lieutenant_promotion" }, { l: "Object.", n: "obj", f: "aggression_at_grudge_low_lieutenant_promotion" }]), bless: n("bless", "\"Blessed.\""), obj: n("obj", "\"Denied.\"") });
const LP_M = tr("heretic_vs_ghost.lieutenant_promotion.mid", { root: n("root", "\"Silence-Coordinator. Four annotators.\"", [{ l: "Send them broadcasts to redact.", n: "send", f: "mercy_at_grudge_mid_lieutenant_promotion" }, { l: "Audit.", n: "aud", f: "aggression_at_grudge_mid_lieutenant_promotion" }]), send: n("send", "\"Sent.\""), aud: n("aud", "\"Audited.\"") });
const LP_H = tr("heretic_vs_ghost.lieutenant_promotion.high", { root: n("root", "\"New annotation code drafting. Co-author.\"", [{ l: "Co-author.", n: "co", f: "mercy_at_grudge_high_lieutenant_promotion" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_lieutenant_promotion" }]), co: n("co", "\"Signed.\"", [{ l: "Pen.", n: "co_pen" }]), co_pen: n("co_pen", "\"Permanent.\""), ref: n("ref", "\"Finished without you.\"") });

const CE_L = tr("heretic_vs_ghost.cohort_end_confrontation.low", { root: n("root", "Cohort hall. Your apprentice graduated; the Ghost left an unsigned commendation in the margin of their diploma.", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_low_cohort_end_confrontation" }, { l: "Tear the margin.", n: "tear", f: "aggression_at_grudge_low_cohort_end_confrontation" }]), ack: n("ack", "\"Acknowledged.\""), tear: n("tear", "\"Torn.\"") });
const CE_M = tr("heretic_vs_ghost.cohort_end_confrontation.mid", { root: n("root", "\"Listed as 'sermon/silence, paired.'\"", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_mid_cohort_end_confrontation" }, { l: "Petition separate.", n: "pet", f: "aggression_at_grudge_mid_cohort_end_confrontation" }]), ack: n("ack", "\"Permanent.\""), pet: n("pet", "\"Denied.\"") });
const CE_H = tr("heretic_vs_ghost.cohort_end_confrontation.high", { root: n("root", "\"Your apprentice's final sermon was a long silence the chamber understood.\"", [{ l: "Accept.", n: "acc", f: "mercy_at_grudge_high_cohort_end_confrontation" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_cohort_end_confrontation" }]), acc: n("acc", "\"Accepted.\""), ref: n("ref", "\"Refused.\"") });

const AR_L = tr("heretic_vs_ghost.accumulation_reveal.low", { root: n("root", "Matrix-archive intake. New sibling-release.", [{ l: "Welcome.", n: "wel", f: "mercy_at_grudge_low_accumulation_reveal" }, { l: "Demand they declare.", n: "demand", f: "aggression_at_grudge_low_accumulation_reveal" }]), wel: n("wel", "\"Welcomed.\""), demand: n("demand", "\"Declared.\"") });
const AR_M = tr("heretic_vs_ghost.accumulation_reveal.mid", { root: n("root", "\"Four releases.\"", [{ l: "Bless.", n: "bless", f: "mercy_at_grudge_mid_accumulation_reveal" }, { l: "Strike a silent annotator.", n: "strike", f: "aggression_at_grudge_mid_accumulation_reveal" }]), bless: n("bless", "\"Blessed.\""), strike: n("strike", "\"Struck.\"") });
const AR_H = tr("heretic_vs_ghost.accumulation_reveal.high", { root: n("root", "\"Chorus of five.\"", [{ l: "Honor.", n: "honor", f: "mercy_at_grudge_high_accumulation_reveal" }, { l: "Recruit one to broadcast.", n: "recruit", f: "aggression_at_grudge_high_accumulation_reveal" }]), honor: n("honor", "\"Honored.\""), recruit: n("recruit", "\"Recruited.\"") });

const NR_L = tr("heretic_vs_ghost.name_reveal_moment.low", { root: n("root", "Antiquarian's Journal margin. Ghost-Nemesis's name surfaces.", [{ l: "Say softly.", n: "say", f: "mercy_at_grudge_low_name_reveal_moment" }, { l: "Broadcast the name.", n: "broadcast", f: "aggression_at_grudge_low_name_reveal_moment" }]), say: n("say", "\"Said.\""), broadcast: n("broadcast", "\"Broadcast. The Hierarchy filed.\"") });
const NR_M = tr("heretic_vs_ghost.name_reveal_moment.mid", { root: n("root", "\"You know my name. Use it.\"", [{ l: "Annotate it.", n: "anno", f: "mercy_at_grudge_mid_name_reveal_moment" }, { l: "Strike it.", n: "strike", f: "aggression_at_grudge_mid_name_reveal_moment" }]), anno: n("anno", "\"Annotated.\""), strike: n("strike", "\"Denied.\"") });
const NR_H = tr("heretic_vs_ghost.name_reveal_moment.high", { root: n("root", "\"Use my name. Speak as you choose.\"", [{ l: "Speak as absolution.", n: "abs", f: "mercy_at_grudge_high_name_reveal_moment" }, { l: "Speak as denunciation.", n: "den", f: "aggression_at_grudge_high_name_reveal_moment" }]), abs: n("abs", "\"Absolved.\""), den: n("den", "\"Denounced.\"") });

const FE_L = tr("heretic_vs_ghost.final_encounter.low", { root: n("root", "Convergence Seat. Ghost-Nemesis at the Seat with a final unsigned annotation.", [{ l: "Read it aloud.", n: "read", f: "mercy_at_grudge_low_final_encounter" }, { l: "Leave it unread.", n: "leave", f: "aggression_at_grudge_low_final_encounter" }]), read: n("read", "\"Read.\""), leave: n("leave", "\"Left.\"") });
const FE_M = tr("heretic_vs_ghost.final_encounter.mid", { root: n("root", "\"End of arc. The broadcast is dissolving.\"", [{ l: "Sign jointly.", n: "sign", f: "mercy_at_grudge_mid_final_encounter" }, { l: "Let it dissolve.", n: "diss", f: "aggression_at_grudge_mid_final_encounter" }]), sign: n("sign", "\"Signed.\""), diss: n("diss", "\"Dissolved.\"") });
const FE_H = tr("heretic_vs_ghost.final_encounter.high", { root: n("root", "\"The chronicle is folding. Seven cohorts of you broadcasting; seven cohorts of me annotating. Read together.\"", [{ l: "Read together.", n: "read", f: "mercy_at_grudge_high_final_encounter" }, { l: "Walk away from the page.", n: "walk", f: "aggression_at_grudge_high_final_encounter" }]), read: n("read", "\"Closed together.\"", [{ l: "Hold.", n: "hold" }]), hold: n("hold", "\"Held.\""), walk: n("walk", "\"Walked.\"") });

export const hereticVsGhostPairBank: NemesisPairBank = {
  pairId: "heretic_vs_ghost", playerArchetype: "heretic", nemesisArchetype: "ghost",
  scenes: {
    first_sighting: makeScene({ low: FS_L, mid: FS_M, high: FS_H }),
    sabotage_caught_in_act: makeScene({ low: SC_L, mid: SC_M, high: SC_H }),
    mocking_interlude: makeScene({ low: MI_L, mid: MI_M, high: MI_H }),
    lieutenant_promotion: makeScene({ low: LP_L, mid: LP_M, high: LP_H }),
    cohort_end_confrontation: makeScene({ low: CE_L, mid: CE_M, high: CE_H }),
    accumulation_reveal: makeScene({ low: AR_L, mid: AR_M, high: AR_H }),
    name_reveal_moment: makeScene({ low: NR_L, mid: NR_M, high: NR_H }),
    final_encounter: makeScene({ low: FE_L, mid: FE_M, high: FE_H }),
  },
};
