/* ═══════════════════════════════════════════════════════
   Heretic-PLAYER vs. Zealot-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.zealot.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "heretic_vs_zealot.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.low.opening",
      onscreenText: "I have served longer, harder, and with cleaner hands than you. Mark this meeting; you will revisit it.",
      choices: [
        { label: "Engage the doctrine.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Excommunicate.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.low.to_mercy",
      onscreenText: "Mercy from a half-trained acolyte. The Politician would have noted the gesture and filed it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.low.to_aggression",
      onscreenText: "Threat received. The doctrine survives threats. So do I.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "heretic_vs_zealot.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.mid.opening",
      onscreenText: "We have history now. Most of it written in your delays. The cause is patient; I am less so.",
      choices: [
        { label: "Trade orthodoxies.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Burn the gospel.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.mid.to_mercy",
      onscreenText: "You ask me to step back. The cause does not step back. But I can pause. Today.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.mid.to_aggression",
      onscreenText: "Strike, then. The cause has martyrs to spare. I will not be the first.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "heretic_vs_zealot.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.high.opening",
      onscreenText: "This ends one of two ways and I have prepared for both. Welcome to the conclusion.",
      choices: [
        { label: "Confess parity.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Witness their pyre.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.high.to_mercy",
      onscreenText: "Mercy at this point is theatre. I will accept the role only if you commit to playing the audience.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.heretic_vs_zealot.first_sighting.high.to_aggression",
      onscreenText: "Yes. Yes. The cause needs this image of you.",
    },
  },
};

export const hereticVsZealotPairBank: NemesisPairBank = {
  pairId: "heretic_vs_zealot",
  playerArchetype: "heretic",
  nemesisArchetype: "zealot",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
