/* ═══════════════════════════════════════════════════════
   Jester-PLAYER vs. Revenant-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Scenes: first_sighting (Wave 3 hand-authored) + 7 new
   scenes (Wave 4: sabotage_caught_in_act, mocking_interlude,
   lieutenant_promotion, cohort_end_confrontation,
   accumulation_reveal, name_reveal_moment, final_encounter).
   New scenes composed from per-archetype voice
   (NEMESIS_VOICE) and per-scene framing
   (NEMESIS_SCENE_FRAMES).
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "jester_vs_revenant.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.low.opening",
      onscreenText: "You owe me a debt you don't remember incurring. The principal compounds. Hello.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.low.to_mercy",
      onscreenText: "Mercy. Noted as an interest payment. The principal remains.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.low.to_aggression",
      onscreenText: "Add it to the ledger. I'll come back richer for it.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "jester_vs_revenant.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.mid.opening",
      onscreenText: "The debt has tripled. You are making me wealthy in ways that do not show on either of our faces.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.mid.to_mercy",
      onscreenText: "Partial payment accepted. I will be back. Same time. Larger figure.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.mid.to_aggression",
      onscreenText: "Yes. The interest rate prefers violence. You're a generous debtor in this sense.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "jester_vs_revenant.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.high.opening",
      onscreenText: "Final notice. The debt is mine to forgive or collect. The chronicle is taking notes either way.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.high.to_mercy",
      onscreenText: "You have settled. The debt closes. Do not open a new account with me. I will remember the rate.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.first_sighting.high.to_aggression",
      onscreenText: "Foreclosure. Acceptable. The Politician's books taught me how to take it back in kind.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_LOW: DialogTree = {
  id: "jester_vs_revenant.sabotage_caught_in_act.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.low.opening",
      onscreenText: "The ledger sees you. You crossed my work mid-step. Awkward, for both of us.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_sabotage_caught_in_act" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.low.to_mercy",
      onscreenText: "Partial payment. You let me finish. That is unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.low.to_aggression",
      onscreenText: "Default. Interest accrues. You broke what I was making. The break tells me what to do next.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_MID: DialogTree = {
  id: "jester_vs_revenant.sabotage_caught_in_act.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.mid.opening",
      onscreenText: "Outstanding balance: large. You knew where to look. Annotate that.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_sabotage_caught_in_act" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.mid.to_mercy",
      onscreenText: "Account paid. For today. You stepped past instead of through. Annotate that too.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.mid.to_aggression",
      onscreenText: "Account remains. Largely. You stepped through. Annotated.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_HIGH: DialogTree = {
  id: "jester_vs_revenant.sabotage_caught_in_act.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.high.opening",
      onscreenText: "Final notice. You caught me in the act of catching you.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_sabotage_caught_in_act" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. You let it stand. The chronicle frames this generously.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.sabotage_caught_in_act.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. You finished it for me. The chronicle frames this cleanly.",
    },
  },
};

const MOCKING_INTERLUDE_LOW: DialogTree = {
  id: "jester_vs_revenant.mocking_interlude.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.low.opening",
      onscreenText: "The ledger sees you. Just passing. Wanted you to see me passing.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_mocking_interlude" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.low.to_mercy",
      onscreenText: "Partial payment. You waved. I will remember.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.low.to_aggression",
      onscreenText: "Default. Interest accrues. You growled. I will quote you back.",
    },
  },
};

const MOCKING_INTERLUDE_MID: DialogTree = {
  id: "jester_vs_revenant.mocking_interlude.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.mid.opening",
      onscreenText: "Outstanding balance: large. A visit. No agenda. Mostly.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_mocking_interlude" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.mid.to_mercy",
      onscreenText: "Account paid. For today. Mercy on the mid-grudge cycle. Noted.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.mid.to_aggression",
      onscreenText: "Account remains. Largely. A heckle on the mid-grudge cycle. Predictable.",
    },
  },
};

const MOCKING_INTERLUDE_HIGH: DialogTree = {
  id: "jester_vs_revenant.mocking_interlude.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.high.opening",
      onscreenText: "Final notice. I came to watch you not see me. You saw me.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_mocking_interlude" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. Mercy from this distance? Unusual.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.mocking_interlude.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. Aggression from this distance? Familiar.",
    },
  },
};

const LIEUTENANT_PROMOTION_LOW: DialogTree = {
  id: "jester_vs_revenant.lieutenant_promotion.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.low.opening",
      onscreenText: "The ledger sees you. I am being given subordinates. The Politician's books call this 'cohort coordination.'",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_lieutenant_promotion" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.low.to_mercy",
      onscreenText: "Partial payment. You bless the promotion. The cohort notes it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.low.to_aggression",
      onscreenText: "Default. Interest accrues. You curse the promotion. The cohort notes it.",
    },
  },
};

const LIEUTENANT_PROMOTION_MID: DialogTree = {
  id: "jester_vs_revenant.lieutenant_promotion.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.mid.opening",
      onscreenText: "Outstanding balance: large. I am elevated. The cohort answers to me now.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_lieutenant_promotion" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.mid.to_mercy",
      onscreenText: "Account paid. For today. Mercy on a Lieutenant is rare. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.mid.to_aggression",
      onscreenText: "Account remains. Largely. You will fight me harder for the promotion. Filed.",
    },
  },
};

const LIEUTENANT_PROMOTION_HIGH: DialogTree = {
  id: "jester_vs_revenant.lieutenant_promotion.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.high.opening",
      onscreenText: "Final notice. Lieutenant. The hierarchy is mine to shape.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_lieutenant_promotion" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. You bow to the rank. The Politician would have smiled.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.lieutenant_promotion.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. You burn the rank. The Politician would have allowed it.",
    },
  },
};

const COHORT_END_CONFRONTATION_LOW: DialogTree = {
  id: "jester_vs_revenant.cohort_end_confrontation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.low.opening",
      onscreenText: "The ledger sees you. Your apprentice has finished, or finished us. Either way: this cohort closes.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_cohort_end_confrontation" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.low.to_mercy",
      onscreenText: "Partial payment. You spare the closing. I close in silence.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.low.to_aggression",
      onscreenText: "Default. Interest accrues. You demand a closing line. I provide it.",
    },
  },
};

const COHORT_END_CONFRONTATION_MID: DialogTree = {
  id: "jester_vs_revenant.cohort_end_confrontation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.mid.opening",
      onscreenText: "Outstanding balance: large. The cohort closes around you. I was watching the whole way.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_cohort_end_confrontation" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.mid.to_mercy",
      onscreenText: "Account paid. For today. Mercy at the close. Filed under 'unexpected.'",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.mid.to_aggression",
      onscreenText: "Account remains. Largely. Aggression at the close. Filed under 'expected.'",
    },
  },
};

const COHORT_END_CONFRONTATION_HIGH: DialogTree = {
  id: "jester_vs_revenant.cohort_end_confrontation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.high.opening",
      onscreenText: "Final notice. The chronicle closes this cohort with my name in it.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_cohort_end_confrontation" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. You let me be in the chronicle. Unprecedented.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.cohort_end_confrontation.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. You strike my name from the chronicle. Anticipated.",
    },
  },
};

const ACCUMULATION_REVEAL_LOW: DialogTree = {
  id: "jester_vs_revenant.accumulation_reveal.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.low.opening",
      onscreenText: "The ledger sees you. I am no longer alone with you. The chronicle notes my new sibling.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_accumulation_reveal" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.low.to_mercy",
      onscreenText: "Partial payment. You acknowledge the new one. Generous.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.low.to_aggression",
      onscreenText: "Default. Interest accrues. You threaten the new one. Predictable.",
    },
  },
};

const ACCUMULATION_REVEAL_MID: DialogTree = {
  id: "jester_vs_revenant.accumulation_reveal.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.mid.opening",
      onscreenText: "Outstanding balance: large. We are several now. The Politician's roster widens.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_accumulation_reveal" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.mid.to_mercy",
      onscreenText: "Account paid. For today. Mercy across the roster. Logged.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.mid.to_aggression",
      onscreenText: "Account remains. Largely. Aggression across the roster. Logged.",
    },
  },
};

const ACCUMULATION_REVEAL_HIGH: DialogTree = {
  id: "jester_vs_revenant.accumulation_reveal.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.high.opening",
      onscreenText: "Final notice. We are a chorus. You may want to count us.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_accumulation_reveal" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. Mercy at the chorus is gracious.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.accumulation_reveal.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. Aggression at the chorus is exhausting. For you.",
    },
  },
};

const NAME_REVEAL_MOMENT_LOW: DialogTree = {
  id: "jester_vs_revenant.name_reveal_moment.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.low.opening",
      onscreenText: "The ledger sees you. You have read what you needed. My name surfaces. Use it carefully.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_name_reveal_moment" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.low.to_mercy",
      onscreenText: "Partial payment. You speak it gently. The chronicle records the gentleness.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.low.to_aggression",
      onscreenText: "Default. Interest accrues. You spit it. The chronicle records the spit.",
    },
  },
};

const NAME_REVEAL_MOMENT_MID: DialogTree = {
  id: "jester_vs_revenant.name_reveal_moment.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.mid.opening",
      onscreenText: "Outstanding balance: large. My name. You earned the surface, not the depth.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_name_reveal_moment" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.mid.to_mercy",
      onscreenText: "Account paid. For today. You honor the name. Unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.mid.to_aggression",
      onscreenText: "Account remains. Largely. You weaponize the name. Expected.",
    },
  },
};

const NAME_REVEAL_MOMENT_HIGH: DialogTree = {
  id: "jester_vs_revenant.name_reveal_moment.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.high.opening",
      onscreenText: "Final notice. Use my name. It is the last thing in this chronicle that is fully mine.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_name_reveal_moment" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. You say it like an apology. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.name_reveal_moment.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. You say it like a verdict. Filed.",
    },
  },
};

const FINAL_ENCOUNTER_LOW: DialogTree = {
  id: "jester_vs_revenant.final_encounter.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.low.opening",
      onscreenText: "The ledger sees you. Act Seven. The Convergence Seat has fallen. So have most of my plans.",
      choices: [
        { label: "Workshop the bit.", nextId: "soft", sets: "mercy_at_grudge_low_final_encounter" },
        { label: "Heckle.", nextId: "hard", sets: "aggression_at_grudge_low_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.low.to_mercy",
      onscreenText: "Partial payment. Mercy at the end is the longer chronicle.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.low.to_aggression",
      onscreenText: "Default. Interest accrues. An ending. Quick. Clean.",
    },
  },
};

const FINAL_ENCOUNTER_MID: DialogTree = {
  id: "jester_vs_revenant.final_encounter.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.mid.opening",
      onscreenText: "Outstanding balance: large. End of the arc. Most of mine, anyway.",
      choices: [
        { label: "Tip them.", nextId: "soft", sets: "mercy_at_grudge_mid_final_encounter" },
        { label: "Cut the mic.", nextId: "hard", sets: "aggression_at_grudge_mid_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.mid.to_mercy",
      onscreenText: "Account paid. For today. You let me close my own file.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.mid.to_aggression",
      onscreenText: "Account remains. Largely. You close my file for me.",
    },
  },
};

const FINAL_ENCOUNTER_HIGH: DialogTree = {
  id: "jester_vs_revenant.final_encounter.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.high.opening",
      onscreenText: "Final notice. The chronicle is folding this story shut around both of us.",
      choices: [
        { label: "Standing ovation.", nextId: "soft", sets: "mercy_at_grudge_high_final_encounter" },
        { label: "Storm the stage.", nextId: "hard", sets: "aggression_at_grudge_high_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.high.to_mercy",
      onscreenText: "Account closed. Do not reopen. You spare the rival. The chronicle takes note in italics.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.jester_vs_revenant.final_encounter.high.to_aggression",
      onscreenText: "Foreclosure. Accepted. You finish the rival. The chronicle takes note in plain script.",
    },
  },
};

export const jesterVsRevenantPairBank: NemesisPairBank = {
  pairId: "jester_vs_revenant",
  playerArchetype: "jester",
  nemesisArchetype: "revenant",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
    sabotage_caught_in_act: makeScene({
      low: SABOTAGE_CAUGHT_IN_ACT_LOW,
      mid: SABOTAGE_CAUGHT_IN_ACT_MID,
      high: SABOTAGE_CAUGHT_IN_ACT_HIGH,
    }),
    mocking_interlude: makeScene({
      low: MOCKING_INTERLUDE_LOW,
      mid: MOCKING_INTERLUDE_MID,
      high: MOCKING_INTERLUDE_HIGH,
    }),
    lieutenant_promotion: makeScene({
      low: LIEUTENANT_PROMOTION_LOW,
      mid: LIEUTENANT_PROMOTION_MID,
      high: LIEUTENANT_PROMOTION_HIGH,
    }),
    cohort_end_confrontation: makeScene({
      low: COHORT_END_CONFRONTATION_LOW,
      mid: COHORT_END_CONFRONTATION_MID,
      high: COHORT_END_CONFRONTATION_HIGH,
    }),
    accumulation_reveal: makeScene({
      low: ACCUMULATION_REVEAL_LOW,
      mid: ACCUMULATION_REVEAL_MID,
      high: ACCUMULATION_REVEAL_HIGH,
    }),
    name_reveal_moment: makeScene({
      low: NAME_REVEAL_MOMENT_LOW,
      mid: NAME_REVEAL_MOMENT_MID,
      high: NAME_REVEAL_MOMENT_HIGH,
    }),
    final_encounter: makeScene({
      low: FINAL_ENCOUNTER_LOW,
      mid: FINAL_ENCOUNTER_MID,
      high: FINAL_ENCOUNTER_HIGH,
    }),
  },
};
