/* MARTYR-PLAYER vs. SENTINEL-NEMESIS — Phase K Wave 7I (canon)
   Sacrifice-the-self vs. hold-the-post. Cost-bearer dual.
   Surfaces: Memorial Wall, Adjudicator's house, Hub vote-floor, Mechronis post, Convergence Seat. */
import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";
const n = (id: string, text: string, choices?: { l: string; n: string; f?: string }[]) => ({ id, speaker: "nemesis" as const, voLineId: `nemesis.martyr_vs_sentinel.${id}`, onscreenText: text, choices: choices?.map(c => ({ label: c.l, nextId: c.n, sets: c.f })) });
const tr = (id: string, nodes: Record<string, ReturnType<typeof n>>): DialogTree => ({ id, nodes });

const FS_L = tr("martyr_vs_sentinel.first_sighting.low", { root: n("root", "Memorial Wall. You light a candle for the ones you carried. Sentinel-Nemesis at her post hasn't moved in three watches. \"You'll keep dying for them. I'll keep standing for them. The Politician taught us both — only the count changes.\"", [{ l: "Acknowledge the post.", n: "ac", f: "mercy_at_grudge_low_first_sighting" }, { l: "Refuse the equivalence.", n: "rf", f: "aggression_at_grudge_low_first_sighting" }]), ac: n("ac", "\"Acknowledged.\""), rf: n("rf", "\"Refused. Same wall.\"") });
const FS_M = tr("martyr_vs_sentinel.first_sighting.mid", { root: n("root", "\"Six candles. Six watches. Same wall.\"", [{ l: "Take the watch with her.", n: "tw", f: "mercy_at_grudge_mid_first_sighting" }, { l: "Walk past the post.", n: "wp", f: "aggression_at_grudge_mid_first_sighting" }]), tw: n("tw", "\"Held.\""), wp: n("wp", "\"Walked. She held alone.\"") });
const FS_H = tr("martyr_vs_sentinel.first_sighting.high", { root: n("root", "\"I have stood while you fell. Teach me to fall.\"", [{ l: "Teach her.", n: "tc", f: "mercy_at_grudge_high_first_sighting" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_first_sighting" }]), tc: n("tc", "\"Taught.\"", [{ l: "Hand her your candle.", n: "tc_c" }]), tc_c: n("tc_c", "\"Held.\""), ref: n("ref", "\"Refused. She held.\"") });

const SC_L = tr("martyr_vs_sentinel.sabotage_caught_in_act.low", { root: n("root", "Adjudicator's house. Sentinel-Nemesis stands between your sacrifice and the door.", [{ l: "Ask her to step aside.", n: "as", f: "mercy_at_grudge_low_sabotage_caught_in_act" }, { l: "Push past.", n: "ps", f: "aggression_at_grudge_low_sabotage_caught_in_act" }]), as: n("as", "\"Stepped.\""), ps: n("ps", "\"Pushed.\"") });
const SC_M = tr("martyr_vs_sentinel.sabotage_caught_in_act.mid", { root: n("root", "\"Every door I hold. Every door you walk through. The Politician's primer: 'cost is the only honest currency between us.'\"", [{ l: "Pay her the watch.", n: "py", f: "mercy_at_grudge_mid_sabotage_caught_in_act" }, { l: "Walk through anyway.", n: "wt", f: "aggression_at_grudge_mid_sabotage_caught_in_act" }]), py: n("py", "\"Paid.\""), wt: n("wt", "\"Walked. Logged.\"") });
const SC_H = tr("martyr_vs_sentinel.sabotage_caught_in_act.high", { root: n("root", "\"I want to fall once. Help me find the right door.\"", [{ l: "Help.", n: "hp", f: "mercy_at_grudge_high_sabotage_caught_in_act" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_sabotage_caught_in_act" }]), hp: n("hp", "\"Helped.\"", [{ l: "Stand the watch in her place.", n: "hp_w" }]), hp_w: n("hp_w", "\"Held.\""), ref: n("ref", "\"Refused. She kept standing.\"") });

const MI_L = tr("martyr_vs_sentinel.mocking_interlude.low", { root: n("root", "Hub vote-floor. Sentinel-Nemesis logs your latest sacrifice as a procedural infraction.", [{ l: "Sign the log.", n: "sg", f: "mercy_at_grudge_low_mocking_interlude" }, { l: "Tear the log.", n: "tr", f: "aggression_at_grudge_low_mocking_interlude" }]), sg: n("sg", "\"Signed.\""), tr: n("tr", "\"Refiled.\"") });
const MI_M = tr("martyr_vs_sentinel.mocking_interlude.mid", { root: n("root", "\"You die. I file. The chronicle accepts both.\"", [{ l: "Co-sign the next entry.", n: "cs", f: "mercy_at_grudge_mid_mocking_interlude" }, { l: "Strike from record.", n: "st", f: "aggression_at_grudge_mid_mocking_interlude" }]), cs: n("cs", "\"Co-signed.\""), st: n("st", "\"Denied.\"") });
const MI_H = tr("martyr_vs_sentinel.mocking_interlude.high", { root: n("root", "\"Let me carry one of your watches. Quietly.\"", [{ l: "Pass the watch.", n: "pw", f: "mercy_at_grudge_high_mocking_interlude" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_mocking_interlude" }]), pw: n("pw", "\"Passed.\""), ref: n("ref", "\"Refused.\"") });

const LP_L = tr("martyr_vs_sentinel.lieutenant_promotion.low", { root: n("root", "Watch-Captain ceremony at the Adjudicator's house.", [{ l: "Bless from the wall.", n: "bl", f: "mercy_at_grudge_low_lieutenant_promotion" }, { l: "Object.", n: "ob", f: "aggression_at_grudge_low_lieutenant_promotion" }]), bl: n("bl", "\"Blessed.\""), ob: n("ob", "\"Denied.\"") });
const LP_M = tr("martyr_vs_sentinel.lieutenant_promotion.mid", { root: n("root", "\"Watch-Captain. Four posts.\"", [{ l: "Send a candle.", n: "cn", f: "mercy_at_grudge_mid_lieutenant_promotion" }, { l: "Audit the watch.", n: "au", f: "aggression_at_grudge_mid_lieutenant_promotion" }]), cn: n("cn", "\"Sent.\""), au: n("au", "\"Audited.\"") });
const LP_H = tr("martyr_vs_sentinel.lieutenant_promotion.high", { root: n("root", "\"New watch-code. Co-author.\"", [{ l: "Co-author.", n: "co", f: "mercy_at_grudge_high_lieutenant_promotion" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_lieutenant_promotion" }]), co: n("co", "\"Signed.\"", [{ l: "Hold the post.", n: "co_h" }]), co_h: n("co_h", "\"Permanent.\""), ref: n("ref", "\"Finished without you.\"") });

const CE_L = tr("martyr_vs_sentinel.cohort_end_confrontation.low", { root: n("root", "Cohort hall. Your apprentice graduated. Sentinel-Nemesis logged the cost.", [{ l: "Accept.", n: "ac", f: "mercy_at_grudge_low_cohort_end_confrontation" }, { l: "Detach.", n: "dt", f: "aggression_at_grudge_low_cohort_end_confrontation" }]), ac: n("ac", "\"Accepted.\""), dt: n("dt", "\"Refiled.\"") });
const CE_M = tr("martyr_vs_sentinel.cohort_end_confrontation.mid", { root: n("root", "\"Cohort registered as 'cost paid in two columns.'\"", [{ l: "Sign both columns.", n: "sb", f: "mercy_at_grudge_mid_cohort_end_confrontation" }, { l: "Petition separate.", n: "pt", f: "aggression_at_grudge_mid_cohort_end_confrontation" }]), sb: n("sb", "\"Permanent.\""), pt: n("pt", "\"Denied.\"") });
const CE_H = tr("martyr_vs_sentinel.cohort_end_confrontation.high", { root: n("root", "\"Your apprentice did neither. They stood AND fell. Surpassed both columns.\"", [{ l: "Accept.", n: "ac", f: "mercy_at_grudge_high_cohort_end_confrontation" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_cohort_end_confrontation" }]), ac: n("ac", "\"Accepted.\""), ref: n("ref", "\"Refused.\"") });

const AR_L = tr("martyr_vs_sentinel.accumulation_reveal.low", { root: n("root", "Matrix-archive intake. New sibling-release at her post.", [{ l: "Welcome.", n: "wl", f: "mercy_at_grudge_low_accumulation_reveal" }, { l: "Demand declaration.", n: "dm", f: "aggression_at_grudge_low_accumulation_reveal" }]), wl: n("wl", "\"Welcomed.\""), dm: n("dm", "\"Declared.\"") });
const AR_M = tr("martyr_vs_sentinel.accumulation_reveal.mid", { root: n("root", "\"Four sentinels at four posts.\"", [{ l: "Bless.", n: "bl", f: "mercy_at_grudge_mid_accumulation_reveal" }, { l: "Strike one post.", n: "st", f: "aggression_at_grudge_mid_accumulation_reveal" }]), bl: n("bl", "\"Blessed.\""), st: n("st", "\"Struck.\"") });
const AR_H = tr("martyr_vs_sentinel.accumulation_reveal.high", { root: n("root", "\"Chorus of held posts.\"", [{ l: "Honor.", n: "hn", f: "mercy_at_grudge_high_accumulation_reveal" }, { l: "Recruit one to fall.", n: "rc", f: "aggression_at_grudge_high_accumulation_reveal" }]), hn: n("hn", "\"Honored.\""), rc: n("rc", "\"Recruited.\"") });

const NR_L = tr("martyr_vs_sentinel.name_reveal_moment.low", { root: n("root", "Memorial Wall. Sentinel-Nemesis's name is carved beside the names you carried.", [{ l: "Say softly.", n: "sy", f: "mercy_at_grudge_low_name_reveal_moment" }, { l: "Carve over it.", n: "cv", f: "aggression_at_grudge_low_name_reveal_moment" }]), sy: n("sy", "\"Said.\""), cv: n("cv", "\"Carved.\"") });
const NR_M = tr("martyr_vs_sentinel.name_reveal_moment.mid", { root: n("root", "\"Use my name at the wall.\"", [{ l: "Speak.", n: "sp", f: "mercy_at_grudge_mid_name_reveal_moment" }, { l: "Strike.", n: "st", f: "aggression_at_grudge_mid_name_reveal_moment" }]), sp: n("sp", "\"Spoken.\""), st: n("st", "\"Denied.\"") });
const NR_H = tr("martyr_vs_sentinel.name_reveal_moment.high", { root: n("root", "\"Speak my name.\"", [{ l: "As fellow-witness.", n: "fw", f: "mercy_at_grudge_high_name_reveal_moment" }, { l: "As trespass.", n: "tr", f: "aggression_at_grudge_high_name_reveal_moment" }]), fw: n("fw", "\"Witnessed.\""), tr: n("tr", "\"Indicted.\"") });

const FE_L = tr("martyr_vs_sentinel.final_encounter.low", { root: n("root", "Convergence Seat. Sentinel-Nemesis stands one last watch.", [{ l: "Stand beside her.", n: "sb", f: "mercy_at_grudge_low_final_encounter" }, { l: "Walk past.", n: "wp", f: "aggression_at_grudge_low_final_encounter" }]), sb: n("sb", "\"Held.\""), wp: n("wp", "\"Walked.\"") });
const FE_M = tr("martyr_vs_sentinel.final_encounter.mid", { root: n("root", "\"End of arc.\"", [{ l: "Co-sign the wall.", n: "cs", f: "mercy_at_grudge_mid_final_encounter" }, { l: "Let it close.", n: "cl", f: "aggression_at_grudge_mid_final_encounter" }]), cs: n("cs", "\"Signed.\""), cl: n("cl", "\"Closed.\"") });
const FE_H = tr("martyr_vs_sentinel.final_encounter.high", { root: n("root", "\"The chronicle is folding. Stand the last watch with me.\"", [{ l: "Stand together.", n: "st", f: "mercy_at_grudge_high_final_encounter" }, { l: "Fall while she stands.", n: "fl", f: "aggression_at_grudge_high_final_encounter" }]), st: n("st", "\"Closed together.\"", [{ l: "Hold.", n: "st_h" }]), st_h: n("st_h", "\"Held.\""), fl: n("fl", "\"Fell.\"") });

export const martyrVsSentinelPairBank: NemesisPairBank = {
  pairId: "martyr_vs_sentinel", playerArchetype: "martyr", nemesisArchetype: "sentinel",
  scenes: {
    first_sighting: makeScene({ low: FS_L, mid: FS_M, high: FS_H }),
    sabotage_caught_in_act: makeScene({ low: SC_L, mid: SC_M, high: SC_H }),
    mocking_interlude: makeScene({ low: MI_L, mid: MI_M, high: MI_H }),
    lieutenant_promotion: makeScene({ low: LP_L, mid: LP_M, high: LP_H }),
    cohort_end_confrontation: makeScene({ low: CE_L, mid: CE_M, high: CE_H }),
    accumulation_reveal: makeScene({ low: AR_L, mid: AR_M, high: AR_H }),
    name_reveal_moment: makeScene({ low: NR_L, mid: NR_M, high: NR_H }),
    final_encounter: makeScene({ low: FE_L, mid: FE_M, high: FE_H }),
  },
};
