/* ═══════════════════════════════════════════════════════
   Prodigal-PLAYER vs. Ghost-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.ghost.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "prodigal_vs_ghost.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.low.opening",
      onscreenText: "You see me now. You shouldn't. I will note when you stop.",
      choices: [
        { label: "Welcome them in.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Bar the door.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.low.to_mercy",
      onscreenText: "Mercy. Filed. Returned in kind, perhaps.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.low.to_aggression",
      onscreenText: "I do not respond to threats. I respond to angles. Yours has improved.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "prodigal_vs_ghost.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.mid.opening",
      onscreenText: "We are getting too familiar. I will be less visible after this.",
      choices: [
        { label: "Hold the family seat.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Sell the keys.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.mid.to_mercy",
      onscreenText: "Acknowledged. Tomorrow I will be quieter than tonight.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.mid.to_aggression",
      onscreenText: "You want me dead in the open. I will die in private. Sorry.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "prodigal_vs_ghost.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.high.opening",
      onscreenText: "You can see all of me now. I have nothing left to hide. This was never my preferred pose.",
      choices: [
        { label: "Write the deed jointly.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Burn the house.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.high.to_mercy",
      onscreenText: "You let me go. I will go. You will see me again only when you cannot prevent it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.prodigal_vs_ghost.first_sighting.high.to_aggression",
      onscreenText: "Yes. Make it loud. The Politician would have hated that, which is reason enough.",
    },
  },
};

export const prodigalVsGhostPairBank: NemesisPairBank = {
  pairId: "prodigal_vs_ghost",
  playerArchetype: "prodigal",
  nemesisArchetype: "ghost",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
