/* SCHOLAR-PLAYER vs. JESTER-NEMESIS — Phase K Wave 7G (canon)
   Analysis vs improvisation. You plan annotations; Jester-Nemesis writes by ear.
   Surfaces: Mechronis lecture, Antiquarian's reading room, PAC News, Hub, Convergence Seat. */
import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";
const n = (id: string, text: string, choices?: { l: string; n: string; f?: string }[]) => ({ id, speaker: "nemesis" as const, voLineId: `nemesis.scholar_vs_jester.${id}`, onscreenText: text, choices: choices?.map(c => ({ label: c.l, nextId: c.n, sets: c.f })) });
const tr = (id: string, nodes: Record<string, ReturnType<typeof n>>): DialogTree => ({ id, nodes });

const FS_L = tr("scholar_vs_jester.first_sighting.low", { root: n("root", "Mechronis Academy lecture hall. You finish a careful annotation. The Jester-Nemesis at the rear improvises a counter-thesis aloud, with no notes. \"Improvisation cited yours by name. The Politician's primer: 'the unnoted citation is the chronicle's loudest plagiarism.'\"", [{ l: "Acknowledge the citation.", n: "ack", f: "mercy_at_grudge_low_first_sighting" }, { l: "File a plagiarism complaint.", n: "pl", f: "aggression_at_grudge_low_first_sighting" }]), ack: n("ack", "\"Acknowledged.\""), pl: n("pl", "\"Filed. Denied.\"") });
const FS_M = tr("scholar_vs_jester.first_sighting.mid", { root: n("root", "\"Three lectures. Three improvised counter-theses. The Academy's stenographer has begun transcribing me.\"", [{ l: "Co-teach.", n: "co", f: "mercy_at_grudge_mid_first_sighting" }, { l: "Refuse co-teaching.", n: "ref", f: "aggression_at_grudge_mid_first_sighting" }]), co: n("co", "\"Co-taught.\""), ref: n("ref", "\"Refused.\"") });
const FS_H = tr("scholar_vs_jester.first_sighting.high", { root: n("root", "\"I have stopped improvising. I have begun annotating. Train me.\"", [{ l: "Train them at the desk.", n: "train", f: "mercy_at_grudge_high_first_sighting" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_first_sighting" }]), train: n("train", "\"Trained.\"", [{ l: "Hand them a quill.", n: "train_q" }]), train_q: n("train_q", "\"Handed.\""), ref: n("ref", "\"Refused.\"") });

const SC_L = tr("scholar_vs_jester.sabotage_caught_in_act.low", { root: n("root", "PAC News studio. The Jester-Nemesis goes off-script on your researched segment.", [{ l: "Acknowledge the riff.", n: "ack", f: "mercy_at_grudge_low_sabotage_caught_in_act" }, { l: "Cut to commercial.", n: "cut", f: "aggression_at_grudge_low_sabotage_caught_in_act" }]), ack: n("ack", "\"Acknowledged.\""), cut: n("cut", "\"Cut.\"") });
const SC_M = tr("scholar_vs_jester.sabotage_caught_in_act.mid", { root: n("root", "\"You catch every riff and footnote it. The Politician's primer: 'the footnoted improvisation is the most rigorous improvisation.'\"", [{ l: "Continue footnoting.", n: "co", f: "mercy_at_grudge_mid_sabotage_caught_in_act" }, { l: "Refuse to footnote.", n: "ref", f: "aggression_at_grudge_mid_sabotage_caught_in_act" }]), co: n("co", "\"Continued.\""), ref: n("ref", "\"Refused.\"") });
const SC_H = tr("scholar_vs_jester.sabotage_caught_in_act.high", { root: n("root", "\"I want to broadcast a fully scripted segment. Help me draft.\"", [{ l: "Draft together.", n: "draft", f: "mercy_at_grudge_high_sabotage_caught_in_act" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_sabotage_caught_in_act" }]), draft: n("draft", "\"Drafted.\"", [{ l: "Sign the script.", n: "draft_sign" }]), draft_sign: n("draft_sign", "\"Signed.\""), ref: n("ref", "\"Refused.\"") });

const MI_L = tr("scholar_vs_jester.mocking_interlude.low", { root: n("root", "Antiquarian's reading room. Jester-Nemesis pages through your annotation stack making improvised commentary aloud.", [{ l: "Ignore.", n: "ig", f: "mercy_at_grudge_low_mocking_interlude" }, { l: "Eject them.", n: "eject", f: "aggression_at_grudge_low_mocking_interlude" }]), ig: n("ig", "\"Ignored.\""), eject: n("eject", "\"Ejected.\"") });
const MI_M = tr("scholar_vs_jester.mocking_interlude.mid", { root: n("root", "\"Reading-room visits are now a weekly bit.\"", [{ l: "Allow.", n: "allow", f: "mercy_at_grudge_mid_mocking_interlude" }, { l: "Revoke their permit.", n: "rev", f: "aggression_at_grudge_mid_mocking_interlude" }]), allow: n("allow", "\"Allowed.\""), rev: n("rev", "\"Revoked. Denied on appeal.\"") });
const MI_H = tr("scholar_vs_jester.mocking_interlude.high", { root: n("root", "\"I would like to apprentice. Quietly.\"", [{ l: "Apprentice.", n: "app", f: "mercy_at_grudge_high_mocking_interlude" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_mocking_interlude" }]), app: n("app", "\"Apprenticed.\""), ref: n("ref", "\"Refused.\"") });

const LP_L = tr("scholar_vs_jester.lieutenant_promotion.low", { root: n("root", "PAC News producer-coordinator ceremony.", [{ l: "Bless from the desk.", n: "bless", f: "mercy_at_grudge_low_lieutenant_promotion" }, { l: "Object.", n: "obj", f: "aggression_at_grudge_low_lieutenant_promotion" }]), bless: n("bless", "\"Blessed.\""), obj: n("obj", "\"Denied.\"") });
const LP_M = tr("scholar_vs_jester.lieutenant_promotion.mid", { root: n("root", "\"Producer-Coordinator. Four broadcast desks.\"", [{ l: "Send research.", n: "send", f: "mercy_at_grudge_mid_lieutenant_promotion" }, { l: "Audit.", n: "aud", f: "aggression_at_grudge_mid_lieutenant_promotion" }]), send: n("send", "\"Sent.\""), aud: n("aud", "\"Audited.\"") });
const LP_H = tr("scholar_vs_jester.lieutenant_promotion.high", { root: n("root", "\"New broadcast code. Co-author.\"", [{ l: "Co-author.", n: "co", f: "mercy_at_grudge_high_lieutenant_promotion" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_lieutenant_promotion" }]), co: n("co", "\"Signed.\"", [{ l: "Pen.", n: "co_pen" }]), co_pen: n("co_pen", "\"Permanent.\""), ref: n("ref", "\"Finished without you.\"") });

const CE_L = tr("scholar_vs_jester.cohort_end_confrontation.low", { root: n("root", "Cohort hall. Your apprentice graduated with a research-paper. Jester-Nemesis improvised the introduction.", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_low_cohort_end_confrontation" }, { l: "Strike the intro.", n: "strike", f: "aggression_at_grudge_low_cohort_end_confrontation" }]), ack: n("ack", "\"Acknowledged.\""), strike: n("strike", "\"Struck.\"") });
const CE_M = tr("scholar_vs_jester.cohort_end_confrontation.mid", { root: n("root", "\"Listed as 'analysis/improvisation, paired.'\"", [{ l: "Acknowledge.", n: "ack", f: "mercy_at_grudge_mid_cohort_end_confrontation" }, { l: "Petition separate.", n: "pet", f: "aggression_at_grudge_mid_cohort_end_confrontation" }]), ack: n("ack", "\"Permanent.\""), pet: n("pet", "\"Denied.\"") });
const CE_H = tr("scholar_vs_jester.cohort_end_confrontation.high", { root: n("root", "\"Your apprentice's final paper had no improvised lines and no Jester-citations. They surpassed both of us.\"", [{ l: "Accept.", n: "acc", f: "mercy_at_grudge_high_cohort_end_confrontation" }, { l: "Refuse.", n: "ref", f: "aggression_at_grudge_high_cohort_end_confrontation" }]), acc: n("acc", "\"Accepted.\""), ref: n("ref", "\"Refused.\"") });

const AR_L = tr("scholar_vs_jester.accumulation_reveal.low", { root: n("root", "Matrix-archive intake. New sibling-release.", [{ l: "Welcome.", n: "wel", f: "mercy_at_grudge_low_accumulation_reveal" }, { l: "Demand declaration.", n: "demand", f: "aggression_at_grudge_low_accumulation_reveal" }]), wel: n("wel", "\"Welcomed.\""), demand: n("demand", "\"Declared.\"") });
const AR_M = tr("scholar_vs_jester.accumulation_reveal.mid", { root: n("root", "\"Four releases.\"", [{ l: "Bless.", n: "bless", f: "mercy_at_grudge_mid_accumulation_reveal" }, { l: "Strike a jester.", n: "strike", f: "aggression_at_grudge_mid_accumulation_reveal" }]), bless: n("bless", "\"Blessed.\""), strike: n("strike", "\"Struck.\"") });
const AR_H = tr("scholar_vs_jester.accumulation_reveal.high", { root: n("root", "\"Chorus of five.\"", [{ l: "Honor.", n: "honor", f: "mercy_at_grudge_high_accumulation_reveal" }, { l: "Recruit one to analysis.", n: "recruit", f: "aggression_at_grudge_high_accumulation_reveal" }]), honor: n("honor", "\"Honored.\""), recruit: n("recruit", "\"Recruited.\"") });

const NR_L = tr("scholar_vs_jester.name_reveal_moment.low", { root: n("root", "Antiquarian's Journal margin. Jester-Nemesis's name surfaces.", [{ l: "Say softly.", n: "say", f: "mercy_at_grudge_low_name_reveal_moment" }, { l: "Cite in your next annotation.", n: "cite", f: "aggression_at_grudge_low_name_reveal_moment" }]), say: n("say", "\"Said.\""), cite: n("cite", "\"Cited.\"") });
const NR_M = tr("scholar_vs_jester.name_reveal_moment.mid", { root: n("root", "\"You know my name. Use it.\"", [{ l: "Cite.", n: "cite", f: "mercy_at_grudge_mid_name_reveal_moment" }, { l: "Strike.", n: "strike", f: "aggression_at_grudge_mid_name_reveal_moment" }]), cite: n("cite", "\"Cited.\""), strike: n("strike", "\"Denied.\"") });
const NR_H = tr("scholar_vs_jester.name_reveal_moment.high", { root: n("root", "\"Speak my name.\"", [{ l: "As bibliographic credit.", n: "bib", f: "mercy_at_grudge_high_name_reveal_moment" }, { l: "As denunciation.", n: "den", f: "aggression_at_grudge_high_name_reveal_moment" }]), bib: n("bib", "\"Credited.\""), den: n("den", "\"Denounced.\"") });

const FE_L = tr("scholar_vs_jester.final_encounter.low", { root: n("root", "Convergence Seat. Jester-Nemesis with a final improvised line.", [{ l: "Annotate it.", n: "anno", f: "mercy_at_grudge_low_final_encounter" }, { l: "Strike.", n: "strike", f: "aggression_at_grudge_low_final_encounter" }]), anno: n("anno", "\"Annotated.\""), strike: n("strike", "\"Struck.\"") });
const FE_M = tr("scholar_vs_jester.final_encounter.mid", { root: n("root", "\"End of arc.\"", [{ l: "Sign jointly.", n: "sign", f: "mercy_at_grudge_mid_final_encounter" }, { l: "Let it close.", n: "close", f: "aggression_at_grudge_mid_final_encounter" }]), sign: n("sign", "\"Signed.\""), close: n("close", "\"Closed.\"") });
const FE_H = tr("scholar_vs_jester.final_encounter.high", { root: n("root", "\"The chronicle is folding. Read the line one more time.\"", [{ l: "Read together.", n: "read", f: "mercy_at_grudge_high_final_encounter" }, { l: "Tear the page.", n: "tear", f: "aggression_at_grudge_high_final_encounter" }]), read: n("read", "\"Closed together.\"", [{ l: "Hold.", n: "hold" }]), hold: n("hold", "\"Held.\""), tear: n("tear", "\"Torn.\"") });

export const scholarVsJesterPairBank: NemesisPairBank = {
  pairId: "scholar_vs_jester", playerArchetype: "scholar", nemesisArchetype: "jester",
  scenes: {
    first_sighting: makeScene({ low: FS_L, mid: FS_M, high: FS_H }),
    sabotage_caught_in_act: makeScene({ low: SC_L, mid: SC_M, high: SC_H }),
    mocking_interlude: makeScene({ low: MI_L, mid: MI_M, high: MI_H }),
    lieutenant_promotion: makeScene({ low: LP_L, mid: LP_M, high: LP_H }),
    cohort_end_confrontation: makeScene({ low: CE_L, mid: CE_M, high: CE_H }),
    accumulation_reveal: makeScene({ low: AR_L, mid: AR_M, high: AR_H }),
    name_reveal_moment: makeScene({ low: NR_L, mid: NR_M, high: NR_H }),
    final_encounter: makeScene({ low: FE_L, mid: FE_M, high: FE_H }),
  },
};
