/* ═══════════════════════════════════════════════════════
   Scholar-PLAYER vs. Heretic-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Scenes: first_sighting (Wave 3 hand-authored) + 7 new
   scenes (Wave 4: sabotage_caught_in_act, mocking_interlude,
   lieutenant_promotion, cohort_end_confrontation,
   accumulation_reveal, name_reveal_moment, final_encounter).
   New scenes composed from per-archetype voice
   (NEMESIS_VOICE) and per-scene framing
   (NEMESIS_SCENE_FRAMES).
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "scholar_vs_heretic.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.low.opening",
      onscreenText: "Welcome to the truer cause. You have not heard it preached, only countered. Let me correct the imbalance.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.low.to_mercy",
      onscreenText: "Mercy from the orthodoxy. Interesting. The truer cause permits this — even encourages it, between heretics.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.low.to_aggression",
      onscreenText: "Persecution, then. The cause requires it; you are merely the mechanism.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "scholar_vs_heretic.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.mid.opening",
      onscreenText: "Your orthodoxy is my heresy. We could trade and both be right. Or we can keep killing about it.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.mid.to_mercy",
      onscreenText: "You are listening. The cause notes this. So do I.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image of you. Thank you.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "scholar_vs_heretic.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.high.opening",
      onscreenText: "I have stopped trying to convert you. I came here to tell you that. Welcome to the truer cause — but you are the cause now, aren't you. Welcome.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.high.to_mercy",
      onscreenText: "Mercy. From the orthodoxy I called heresy. The truer cause was always going to find one of us in the other.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.first_sighting.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken by a smaller mouth. Welcome to the truer cause.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_LOW: DialogTree = {
  id: "scholar_vs_heretic.sabotage_caught_in_act.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.low.opening",
      onscreenText: "Welcome to the truer cause. You crossed my work mid-step. Awkward, for both of us.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_sabotage_caught_in_act" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You let me finish. That is unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You broke what I was making. The break tells me what to do next.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_MID: DialogTree = {
  id: "scholar_vs_heretic.sabotage_caught_in_act.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.mid.opening",
      onscreenText: "Doctrinal contact. You knew where to look. Annotate that.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_sabotage_caught_in_act" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.mid.to_mercy",
      onscreenText: "Listening recorded. You stepped past instead of through. Annotate that too.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. You stepped through. Annotated.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_HIGH: DialogTree = {
  id: "scholar_vs_heretic.sabotage_caught_in_act.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.high.opening",
      onscreenText: "End of conversion. You caught me in the act of catching you.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_sabotage_caught_in_act" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. You let it stand. The chronicle frames this generously.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.sabotage_caught_in_act.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. You finished it for me. The chronicle frames this cleanly.",
    },
  },
};

const MOCKING_INTERLUDE_LOW: DialogTree = {
  id: "scholar_vs_heretic.mocking_interlude.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.low.opening",
      onscreenText: "Welcome to the truer cause. Just passing. Wanted you to see me passing.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_mocking_interlude" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You waved. I will remember.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You growled. I will quote you back.",
    },
  },
};

const MOCKING_INTERLUDE_MID: DialogTree = {
  id: "scholar_vs_heretic.mocking_interlude.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.mid.opening",
      onscreenText: "Doctrinal contact. A visit. No agenda. Mostly.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_mocking_interlude" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.mid.to_mercy",
      onscreenText: "Listening recorded. Mercy on the mid-grudge cycle. Noted.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. A heckle on the mid-grudge cycle. Predictable.",
    },
  },
};

const MOCKING_INTERLUDE_HIGH: DialogTree = {
  id: "scholar_vs_heretic.mocking_interlude.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.high.opening",
      onscreenText: "End of conversion. I came to watch you not see me. You saw me.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_mocking_interlude" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. Mercy from this distance? Unusual.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.mocking_interlude.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. Aggression from this distance? Familiar.",
    },
  },
};

const LIEUTENANT_PROMOTION_LOW: DialogTree = {
  id: "scholar_vs_heretic.lieutenant_promotion.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.low.opening",
      onscreenText: "Welcome to the truer cause. I am being given subordinates. The Politician's books call this 'cohort coordination.'",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_lieutenant_promotion" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You bless the promotion. The cohort notes it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You curse the promotion. The cohort notes it.",
    },
  },
};

const LIEUTENANT_PROMOTION_MID: DialogTree = {
  id: "scholar_vs_heretic.lieutenant_promotion.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.mid.opening",
      onscreenText: "Doctrinal contact. I am elevated. The cohort answers to me now.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_lieutenant_promotion" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.mid.to_mercy",
      onscreenText: "Listening recorded. Mercy on a Lieutenant is rare. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. You will fight me harder for the promotion. Filed.",
    },
  },
};

const LIEUTENANT_PROMOTION_HIGH: DialogTree = {
  id: "scholar_vs_heretic.lieutenant_promotion.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.high.opening",
      onscreenText: "End of conversion. Lieutenant. The hierarchy is mine to shape.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_lieutenant_promotion" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. You bow to the rank. The Politician would have smiled.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.lieutenant_promotion.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. You burn the rank. The Politician would have allowed it.",
    },
  },
};

const COHORT_END_CONFRONTATION_LOW: DialogTree = {
  id: "scholar_vs_heretic.cohort_end_confrontation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.low.opening",
      onscreenText: "Welcome to the truer cause. Your apprentice has finished, or finished us. Either way: this cohort closes.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_cohort_end_confrontation" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You spare the closing. I close in silence.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You demand a closing line. I provide it.",
    },
  },
};

const COHORT_END_CONFRONTATION_MID: DialogTree = {
  id: "scholar_vs_heretic.cohort_end_confrontation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.mid.opening",
      onscreenText: "Doctrinal contact. The cohort closes around you. I was watching the whole way.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_cohort_end_confrontation" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.mid.to_mercy",
      onscreenText: "Listening recorded. Mercy at the close. Filed under 'unexpected.'",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. Aggression at the close. Filed under 'expected.'",
    },
  },
};

const COHORT_END_CONFRONTATION_HIGH: DialogTree = {
  id: "scholar_vs_heretic.cohort_end_confrontation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.high.opening",
      onscreenText: "End of conversion. The chronicle closes this cohort with my name in it.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_cohort_end_confrontation" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. You let me be in the chronicle. Unprecedented.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.cohort_end_confrontation.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. You strike my name from the chronicle. Anticipated.",
    },
  },
};

const ACCUMULATION_REVEAL_LOW: DialogTree = {
  id: "scholar_vs_heretic.accumulation_reveal.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.low.opening",
      onscreenText: "Welcome to the truer cause. I am no longer alone with you. The chronicle notes my new sibling.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_accumulation_reveal" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You acknowledge the new one. Generous.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You threaten the new one. Predictable.",
    },
  },
};

const ACCUMULATION_REVEAL_MID: DialogTree = {
  id: "scholar_vs_heretic.accumulation_reveal.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.mid.opening",
      onscreenText: "Doctrinal contact. We are several now. The Politician's roster widens.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_accumulation_reveal" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.mid.to_mercy",
      onscreenText: "Listening recorded. Mercy across the roster. Logged.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. Aggression across the roster. Logged.",
    },
  },
};

const ACCUMULATION_REVEAL_HIGH: DialogTree = {
  id: "scholar_vs_heretic.accumulation_reveal.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.high.opening",
      onscreenText: "End of conversion. We are a chorus. You may want to count us.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_accumulation_reveal" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. Mercy at the chorus is gracious.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.accumulation_reveal.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. Aggression at the chorus is exhausting. For you.",
    },
  },
};

const NAME_REVEAL_MOMENT_LOW: DialogTree = {
  id: "scholar_vs_heretic.name_reveal_moment.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.low.opening",
      onscreenText: "Welcome to the truer cause. You have read what you needed. My name surfaces. Use it carefully.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_name_reveal_moment" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. You speak it gently. The chronicle records the gentleness.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. You spit it. The chronicle records the spit.",
    },
  },
};

const NAME_REVEAL_MOMENT_MID: DialogTree = {
  id: "scholar_vs_heretic.name_reveal_moment.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.mid.opening",
      onscreenText: "Doctrinal contact. My name. You earned the surface, not the depth.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_name_reveal_moment" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.mid.to_mercy",
      onscreenText: "Listening recorded. You honor the name. Unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. You weaponize the name. Expected.",
    },
  },
};

const NAME_REVEAL_MOMENT_HIGH: DialogTree = {
  id: "scholar_vs_heretic.name_reveal_moment.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.high.opening",
      onscreenText: "End of conversion. Use my name. It is the last thing in this chronicle that is fully mine.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_name_reveal_moment" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. You say it like an apology. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.name_reveal_moment.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. You say it like a verdict. Filed.",
    },
  },
};

const FINAL_ENCOUNTER_LOW: DialogTree = {
  id: "scholar_vs_heretic.final_encounter.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.low.opening",
      onscreenText: "Welcome to the truer cause. Act Seven. The Convergence Seat has fallen. So have most of my plans.",
      choices: [
        { label: "Cross-reference.", nextId: "soft", sets: "mercy_at_grudge_low_final_encounter" },
        { label: "Annotate the threat.", nextId: "hard", sets: "aggression_at_grudge_low_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.low.to_mercy",
      onscreenText: "Mercy from orthodoxy. Interesting. Mercy at the end is the longer chronicle.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.low.to_aggression",
      onscreenText: "Persecution. The cause requires it. An ending. Quick. Clean.",
    },
  },
};

const FINAL_ENCOUNTER_MID: DialogTree = {
  id: "scholar_vs_heretic.final_encounter.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.mid.opening",
      onscreenText: "Doctrinal contact. End of the arc. Most of mine, anyway.",
      choices: [
        { label: "Revise the file.", nextId: "soft", sets: "mercy_at_grudge_mid_final_encounter" },
        { label: "Close the chapter.", nextId: "hard", sets: "aggression_at_grudge_mid_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.mid.to_mercy",
      onscreenText: "Listening recorded. You let me close my own file.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.mid.to_aggression",
      onscreenText: "Yes. The cause needed this image. You close my file for me.",
    },
  },
};

const FINAL_ENCOUNTER_HIGH: DialogTree = {
  id: "scholar_vs_heretic.final_encounter.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.high.opening",
      onscreenText: "End of conversion. The chronicle is folding this story shut around both of us.",
      choices: [
        { label: "Co-author the ending.", nextId: "soft", sets: "mercy_at_grudge_high_final_encounter" },
        { label: "Write their obituary.", nextId: "hard", sets: "aggression_at_grudge_high_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.high.to_mercy",
      onscreenText: "Mercy from the orthodoxy I called heresy. You spare the rival. The chronicle takes note in italics.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.scholar_vs_heretic.final_encounter.high.to_aggression",
      onscreenText: "The cause cannot be killed; only re-spoken. You finish the rival. The chronicle takes note in plain script.",
    },
  },
};

export const scholarVsHereticPairBank: NemesisPairBank = {
  pairId: "scholar_vs_heretic",
  playerArchetype: "scholar",
  nemesisArchetype: "heretic",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
    sabotage_caught_in_act: makeScene({
      low: SABOTAGE_CAUGHT_IN_ACT_LOW,
      mid: SABOTAGE_CAUGHT_IN_ACT_MID,
      high: SABOTAGE_CAUGHT_IN_ACT_HIGH,
    }),
    mocking_interlude: makeScene({
      low: MOCKING_INTERLUDE_LOW,
      mid: MOCKING_INTERLUDE_MID,
      high: MOCKING_INTERLUDE_HIGH,
    }),
    lieutenant_promotion: makeScene({
      low: LIEUTENANT_PROMOTION_LOW,
      mid: LIEUTENANT_PROMOTION_MID,
      high: LIEUTENANT_PROMOTION_HIGH,
    }),
    cohort_end_confrontation: makeScene({
      low: COHORT_END_CONFRONTATION_LOW,
      mid: COHORT_END_CONFRONTATION_MID,
      high: COHORT_END_CONFRONTATION_HIGH,
    }),
    accumulation_reveal: makeScene({
      low: ACCUMULATION_REVEAL_LOW,
      mid: ACCUMULATION_REVEAL_MID,
      high: ACCUMULATION_REVEAL_HIGH,
    }),
    name_reveal_moment: makeScene({
      low: NAME_REVEAL_MOMENT_LOW,
      mid: NAME_REVEAL_MOMENT_MID,
      high: NAME_REVEAL_MOMENT_HIGH,
    }),
    final_encounter: makeScene({
      low: FINAL_ENCOUNTER_LOW,
      mid: FINAL_ENCOUNTER_MID,
      high: FINAL_ENCOUNTER_HIGH,
    }),
  },
};
