/* ═══════════════════════════════════════════════════════
   Sentinel-PLAYER vs. Martyr-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Scenes: first_sighting (Wave 3 hand-authored) + 7 new
   scenes (Wave 4: sabotage_caught_in_act, mocking_interlude,
   lieutenant_promotion, cohort_end_confrontation,
   accumulation_reveal, name_reveal_moment, final_encounter).
   New scenes composed from per-archetype voice
   (NEMESIS_VOICE) and per-scene framing
   (NEMESIS_SCENE_FRAMES).
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "sentinel_vs_martyr.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.low.opening",
      onscreenText: "I welcome what you bring. I came here knowing it would cost me everything. Hello.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.low.to_mercy",
      onscreenText: "Mercy. Wasted on me. I am not the one who needed it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.low.to_aggression",
      onscreenText: "Yes. The price was always going to be paid. By me. Today is acceptable.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "sentinel_vs_martyr.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.mid.opening",
      onscreenText: "We are nearer to the cost than you realize. I am content. I came here for this.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.mid.to_mercy",
      onscreenText: "You are denying me what I came for. That, too, has a cost. I will pay it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.mid.to_aggression",
      onscreenText: "Closer to the conclusion. The chronicle will record me first. That is sufficient.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.high.opening",
      onscreenText: "Now. Now is good. Make it loud. Let the chronicle remember the pitch.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.high.to_mercy",
      onscreenText: "You want me to live. That is harder than the alternative. I will try, for the cause's sake.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.first_sighting.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. I receive an end. Both of us, fed.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_LOW: DialogTree = {
  id: "sentinel_vs_martyr.sabotage_caught_in_act.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.low.opening",
      onscreenText: "I welcome this. You crossed my work mid-step. Awkward, for both of us.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_sabotage_caught_in_act" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.low.to_mercy",
      onscreenText: "Mercy delays the cost. You let me finish. That is unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.low.to_aggression",
      onscreenText: "The cost was always coming. You broke what I was making. The break tells me what to do next.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_MID: DialogTree = {
  id: "sentinel_vs_martyr.sabotage_caught_in_act.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.mid.opening",
      onscreenText: "We approach the price. You knew where to look. Annotate that.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_sabotage_caught_in_act" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. You stepped past instead of through. Annotate that too.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.mid.to_aggression",
      onscreenText: "Closer to the conclusion. You stepped through. Annotated.",
    },
  },
};

const SABOTAGE_CAUGHT_IN_ACT_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.sabotage_caught_in_act.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.high.opening",
      onscreenText: "Now is acceptable. You caught me in the act of catching you.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_sabotage_caught_in_act" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_sabotage_caught_in_act" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.high.to_mercy",
      onscreenText: "I will live, for the cause. You let it stand. The chronicle frames this generously.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.sabotage_caught_in_act.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. You finished it for me. The chronicle frames this cleanly.",
    },
  },
};

const MOCKING_INTERLUDE_LOW: DialogTree = {
  id: "sentinel_vs_martyr.mocking_interlude.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.low.opening",
      onscreenText: "I welcome this. Just passing. Wanted you to see me passing.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_mocking_interlude" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.low.to_mercy",
      onscreenText: "Mercy delays the cost. You waved. I will remember.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.low.to_aggression",
      onscreenText: "The cost was always coming. You growled. I will quote you back.",
    },
  },
};

const MOCKING_INTERLUDE_MID: DialogTree = {
  id: "sentinel_vs_martyr.mocking_interlude.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.mid.opening",
      onscreenText: "We approach the price. A visit. No agenda. Mostly.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_mocking_interlude" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. Mercy on the mid-grudge cycle. Noted.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.mid.to_aggression",
      onscreenText: "Closer to the conclusion. A heckle on the mid-grudge cycle. Predictable.",
    },
  },
};

const MOCKING_INTERLUDE_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.mocking_interlude.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.high.opening",
      onscreenText: "Now is acceptable. I came to watch you not see me. You saw me.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_mocking_interlude" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_mocking_interlude" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.high.to_mercy",
      onscreenText: "I will live, for the cause. Mercy from this distance? Unusual.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.mocking_interlude.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. Aggression from this distance? Familiar.",
    },
  },
};

const LIEUTENANT_PROMOTION_LOW: DialogTree = {
  id: "sentinel_vs_martyr.lieutenant_promotion.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.low.opening",
      onscreenText: "I welcome this. I am being given subordinates. The Politician's books call this 'cohort coordination.'",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_lieutenant_promotion" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.low.to_mercy",
      onscreenText: "Mercy delays the cost. You bless the promotion. The cohort notes it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.low.to_aggression",
      onscreenText: "The cost was always coming. You curse the promotion. The cohort notes it.",
    },
  },
};

const LIEUTENANT_PROMOTION_MID: DialogTree = {
  id: "sentinel_vs_martyr.lieutenant_promotion.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.mid.opening",
      onscreenText: "We approach the price. I am elevated. The cohort answers to me now.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_lieutenant_promotion" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. Mercy on a Lieutenant is rare. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.mid.to_aggression",
      onscreenText: "Closer to the conclusion. You will fight me harder for the promotion. Filed.",
    },
  },
};

const LIEUTENANT_PROMOTION_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.lieutenant_promotion.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.high.opening",
      onscreenText: "Now is acceptable. Lieutenant. The hierarchy is mine to shape.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_lieutenant_promotion" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_lieutenant_promotion" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.high.to_mercy",
      onscreenText: "I will live, for the cause. You bow to the rank. The Politician would have smiled.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.lieutenant_promotion.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. You burn the rank. The Politician would have allowed it.",
    },
  },
};

const COHORT_END_CONFRONTATION_LOW: DialogTree = {
  id: "sentinel_vs_martyr.cohort_end_confrontation.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.low.opening",
      onscreenText: "I welcome this. Your apprentice has finished, or finished us. Either way: this cohort closes.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_cohort_end_confrontation" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.low.to_mercy",
      onscreenText: "Mercy delays the cost. You spare the closing. I close in silence.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.low.to_aggression",
      onscreenText: "The cost was always coming. You demand a closing line. I provide it.",
    },
  },
};

const COHORT_END_CONFRONTATION_MID: DialogTree = {
  id: "sentinel_vs_martyr.cohort_end_confrontation.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.mid.opening",
      onscreenText: "We approach the price. The cohort closes around you. I was watching the whole way.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_cohort_end_confrontation" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. Mercy at the close. Filed under 'unexpected.'",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.mid.to_aggression",
      onscreenText: "Closer to the conclusion. Aggression at the close. Filed under 'expected.'",
    },
  },
};

const COHORT_END_CONFRONTATION_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.cohort_end_confrontation.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.high.opening",
      onscreenText: "Now is acceptable. The chronicle closes this cohort with my name in it.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_cohort_end_confrontation" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_cohort_end_confrontation" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.high.to_mercy",
      onscreenText: "I will live, for the cause. You let me be in the chronicle. Unprecedented.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.cohort_end_confrontation.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. You strike my name from the chronicle. Anticipated.",
    },
  },
};

const ACCUMULATION_REVEAL_LOW: DialogTree = {
  id: "sentinel_vs_martyr.accumulation_reveal.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.low.opening",
      onscreenText: "I welcome this. I am no longer alone with you. The chronicle notes my new sibling.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_accumulation_reveal" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.low.to_mercy",
      onscreenText: "Mercy delays the cost. You acknowledge the new one. Generous.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.low.to_aggression",
      onscreenText: "The cost was always coming. You threaten the new one. Predictable.",
    },
  },
};

const ACCUMULATION_REVEAL_MID: DialogTree = {
  id: "sentinel_vs_martyr.accumulation_reveal.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.mid.opening",
      onscreenText: "We approach the price. We are several now. The Politician's roster widens.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_accumulation_reveal" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. Mercy across the roster. Logged.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.mid.to_aggression",
      onscreenText: "Closer to the conclusion. Aggression across the roster. Logged.",
    },
  },
};

const ACCUMULATION_REVEAL_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.accumulation_reveal.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.high.opening",
      onscreenText: "Now is acceptable. We are a chorus. You may want to count us.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_accumulation_reveal" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_accumulation_reveal" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.high.to_mercy",
      onscreenText: "I will live, for the cause. Mercy at the chorus is gracious.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.accumulation_reveal.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. Aggression at the chorus is exhausting. For you.",
    },
  },
};

const NAME_REVEAL_MOMENT_LOW: DialogTree = {
  id: "sentinel_vs_martyr.name_reveal_moment.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.low.opening",
      onscreenText: "I welcome this. You have read what you needed. My name surfaces. Use it carefully.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_name_reveal_moment" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.low.to_mercy",
      onscreenText: "Mercy delays the cost. You speak it gently. The chronicle records the gentleness.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.low.to_aggression",
      onscreenText: "The cost was always coming. You spit it. The chronicle records the spit.",
    },
  },
};

const NAME_REVEAL_MOMENT_MID: DialogTree = {
  id: "sentinel_vs_martyr.name_reveal_moment.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.mid.opening",
      onscreenText: "We approach the price. My name. You earned the surface, not the depth.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_name_reveal_moment" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. You honor the name. Unexpected.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.mid.to_aggression",
      onscreenText: "Closer to the conclusion. You weaponize the name. Expected.",
    },
  },
};

const NAME_REVEAL_MOMENT_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.name_reveal_moment.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.high.opening",
      onscreenText: "Now is acceptable. Use my name. It is the last thing in this chronicle that is fully mine.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_name_reveal_moment" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_name_reveal_moment" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.high.to_mercy",
      onscreenText: "I will live, for the cause. You say it like an apology. Filed.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.name_reveal_moment.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. You say it like a verdict. Filed.",
    },
  },
};

const FINAL_ENCOUNTER_LOW: DialogTree = {
  id: "sentinel_vs_martyr.final_encounter.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.low.opening",
      onscreenText: "I welcome this. Act Seven. The Convergence Seat has fallen. So have most of my plans.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low_final_encounter" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.low.to_mercy",
      onscreenText: "Mercy delays the cost. Mercy at the end is the longer chronicle.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.low.to_aggression",
      onscreenText: "The cost was always coming. An ending. Quick. Clean.",
    },
  },
};

const FINAL_ENCOUNTER_MID: DialogTree = {
  id: "sentinel_vs_martyr.final_encounter.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.mid.opening",
      onscreenText: "We approach the price. End of the arc. Most of mine, anyway.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid_final_encounter" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.mid.to_mercy",
      onscreenText: "Mercy is denial of my purpose. You let me close my own file.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.mid.to_aggression",
      onscreenText: "Closer to the conclusion. You close my file for me.",
    },
  },
};

const FINAL_ENCOUNTER_HIGH: DialogTree = {
  id: "sentinel_vs_martyr.final_encounter.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.high.opening",
      onscreenText: "Now is acceptable. The chronicle is folding this story shut around both of us.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high_final_encounter" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high_final_encounter" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.high.to_mercy",
      onscreenText: "I will live, for the cause. You spare the rival. The chronicle takes note in italics.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_martyr.final_encounter.high.to_aggression",
      onscreenText: "Thank you. The cause receives a witness. You finish the rival. The chronicle takes note in plain script.",
    },
  },
};

export const sentinelVsMartyrPairBank: NemesisPairBank = {
  pairId: "sentinel_vs_martyr",
  playerArchetype: "sentinel",
  nemesisArchetype: "martyr",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
    sabotage_caught_in_act: makeScene({
      low: SABOTAGE_CAUGHT_IN_ACT_LOW,
      mid: SABOTAGE_CAUGHT_IN_ACT_MID,
      high: SABOTAGE_CAUGHT_IN_ACT_HIGH,
    }),
    mocking_interlude: makeScene({
      low: MOCKING_INTERLUDE_LOW,
      mid: MOCKING_INTERLUDE_MID,
      high: MOCKING_INTERLUDE_HIGH,
    }),
    lieutenant_promotion: makeScene({
      low: LIEUTENANT_PROMOTION_LOW,
      mid: LIEUTENANT_PROMOTION_MID,
      high: LIEUTENANT_PROMOTION_HIGH,
    }),
    cohort_end_confrontation: makeScene({
      low: COHORT_END_CONFRONTATION_LOW,
      mid: COHORT_END_CONFRONTATION_MID,
      high: COHORT_END_CONFRONTATION_HIGH,
    }),
    accumulation_reveal: makeScene({
      low: ACCUMULATION_REVEAL_LOW,
      mid: ACCUMULATION_REVEAL_MID,
      high: ACCUMULATION_REVEAL_HIGH,
    }),
    name_reveal_moment: makeScene({
      low: NAME_REVEAL_MOMENT_LOW,
      mid: NAME_REVEAL_MOMENT_MID,
      high: NAME_REVEAL_MOMENT_HIGH,
    }),
    final_encounter: makeScene({
      low: FINAL_ENCOUNTER_LOW,
      mid: FINAL_ENCOUNTER_MID,
      high: FINAL_ENCOUNTER_HIGH,
    }),
  },
};
