/* ═══════════════════════════════════════════════════════
   Sentinel-PLAYER vs. Wanderer-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.wanderer.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "sentinel_vs_wanderer.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.low.opening",
      onscreenText: "Every road I've taken came back through you. I've stopped being surprised. Hello.",
      choices: [
        { label: "Salute the post.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Force the gate.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.low.to_mercy",
      onscreenText: "Mercy. The road forks. I know which one you want me on. I'll consider it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.low.to_aggression",
      onscreenText: "The other road. Steeper. Acceptable.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "sentinel_vs_wanderer.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.mid.opening",
      onscreenText: "I have walked too many of these conversations. They feel like the same town with slightly different lighting.",
      choices: [
        { label: "Relieve their watch.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Storm the gate.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.mid.to_mercy",
      onscreenText: "Mercy here is unusual lighting. I will note it and move on.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.mid.to_aggression",
      onscreenText: "Familiar lighting. Goodnight, then. I'll be on the next road by morning.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "sentinel_vs_wanderer.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.high.opening",
      onscreenText: "Last station. There is no further road. I have walked them all. Yours is the only one left to me.",
      choices: [
        { label: "Stand the watch with them.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Burn the post.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.high.to_mercy",
      onscreenText: "You're letting me start over. I don't believe in starts. But I'll walk into one if you keep your word.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.sentinel_vs_wanderer.first_sighting.high.to_aggression",
      onscreenText: "End of the road. I was tired of walking it anyway.",
    },
  },
};

export const sentinelVsWandererPairBank: NemesisPairBank = {
  pairId: "sentinel_vs_wanderer",
  playerArchetype: "sentinel",
  nemesisArchetype: "wanderer",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
