/* ═══════════════════════════════════════════════════════
   Wanderer-PLAYER vs. Sentinel-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.sentinel.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "wanderer_vs_sentinel.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.low.opening",
      onscreenText: "I have stood this watch longer than you have been awake. Pass, or be marked. Hello.",
      choices: [
        { label: "Share the road.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Block the road.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.low.to_mercy",
      onscreenText: "Mercy at the gate. Logged. I will note it in the watch report.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.low.to_aggression",
      onscreenText: "You are forcing the gate. Logged. The relief shift will see your face.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "wanderer_vs_sentinel.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.mid.opening",
      onscreenText: "I know your gait now. The watch can hear you coming three blocks out. You are not stealthy, you are routine.",
      choices: [
        { label: "Walk with them.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Burn their map.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.mid.to_mercy",
      onscreenText: "Mercy. The watch records it. I do not change shifts for it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.mid.to_aggression",
      onscreenText: "Forcing the gate again. The watch is patient. Eventually one of us tires.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "wanderer_vs_sentinel.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.high.opening",
      onscreenText: "Gate is closed for the night. By order of the watch — me. I will not move. We can do this either way.",
      choices: [
        { label: "Show them home.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "End the road here.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.high.to_mercy",
      onscreenText: "The gate opens. The watch stands down. You have my respect, briefly. Walk through quickly.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.wanderer_vs_sentinel.first_sighting.high.to_aggression",
      onscreenText: "Then we test the gate. The watch has stood longer sieges than this.",
    },
  },
};

export const wandererVsSentinelPairBank: NemesisPairBank = {
  pairId: "wanderer_vs_sentinel",
  playerArchetype: "wanderer",
  nemesisArchetype: "sentinel",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
