/* ═══════════════════════════════════════════════════════
   Zealot-PLAYER vs. Jester-NEMESIS — Phase K5.2

   Generated by apps/scripts/generate-nemesis-pair-banks.ts.
   Authoring waterfall starter — refine in place per pairing.

   Voice register (nemesis side): see K4
   NEMESIS_ARCHETYPE_BEHAVIORS.jester.voiceRegister.
   Choice register (player side): K5 archetype-flavored
   mercy/aggression labels.
   ═══════════════════════════════════════════════════════ */

import type { NemesisPairBank } from "./_types";
import { makeScene } from "./_types";
import type { DialogTree } from "../../../dialogTree";

const FIRST_SIGHTING_LOW: DialogTree = {
  id: "zealot_vs_jester.first_sighting.low",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.low.opening",
      onscreenText: "You're funnier when you're losing. Don't deprive me. Hello.",
      choices: [
        { label: "Acknowledge the work.", nextId: "soft", sets: "mercy_at_grudge_low" },
        { label: "Question the cause.", nextId: "hard", sets: "aggression_at_grudge_low" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.low.to_mercy",
      onscreenText: "Mercy! From the punchline! The setup did not see this coming.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.low.to_aggression",
      onscreenText: "Yes — go on, hit the punchline. I'll workshop it later.",
    },
  },
};

const FIRST_SIGHTING_MID: DialogTree = {
  id: "zealot_vs_jester.first_sighting.mid",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.mid.opening",
      onscreenText: "We have a routine now. You play it straight. I do crowd work. The audience tips both of us.",
      choices: [
        { label: "Honor the watch.", nextId: "soft", sets: "mercy_at_grudge_mid" },
        { label: "Curse the cause.", nextId: "hard", sets: "aggression_at_grudge_mid" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.mid.to_mercy",
      onscreenText: "Mercy. Saving the bit. Generous. The next set will be stronger for it.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.mid.to_aggression",
      onscreenText: "Yes! The closer! I'll dedicate this one to you in my obituary.",
    },
  },
};

const FIRST_SIGHTING_HIGH: DialogTree = {
  id: "zealot_vs_jester.first_sighting.high",
  nodes: {
    root: {
      id: "root",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.high.opening",
      onscreenText: "End of the bit. Curtain. Last bow. You're funnier than I gave you credit for; I will be remembered for the warm-up.",
      choices: [
        { label: "Bow to the cause.", nextId: "soft", sets: "mercy_at_grudge_high" },
        { label: "Burn the altar.", nextId: "hard", sets: "aggression_at_grudge_high" },
      ],
    },
    soft: {
      id: "soft",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.high.to_mercy",
      onscreenText: "Mercy. The kindest possible review. I'll quote it in the next billing.",
    },
    hard: {
      id: "hard",
      speaker: "nemesis",
      voLineId: "nemesis.zealot_vs_jester.first_sighting.high.to_aggression",
      onscreenText: "Big finish. Loud one. The chronicle will love this footage.",
    },
  },
};

export const zealotVsJesterPairBank: NemesisPairBank = {
  pairId: "zealot_vs_jester",
  playerArchetype: "zealot",
  nemesisArchetype: "jester",
  scenes: {
    first_sighting: makeScene({
      low: FIRST_SIGHTING_LOW,
      mid: FIRST_SIGHTING_MID,
      high: FIRST_SIGHTING_HIGH,
    }),
  },
};
