/**
 * Vitest suite for the expansion cutscenes manifest (NEW_CUTSCENES_67.zip).
 *
 * Verifies:
 * - Manifest entry count matches producer drop (67 mp4 clips)
 * - All entries fall under the 10 declared categories
 * - Every videoRelPath starts with `art/cutscenes/`
 * - Every entry has a unique id
 * - Producer-supplied poster paths (a subset of entries) end in
 *   `_start.png`
 * - URL resolvers compose canonical CDN paths
 * - Category-bucket lookups are exhaustive
 */
import { describe, expect, it } from "vitest";

import {
  EXPANSION_CUTSCENES,
  EXPANSION_CUTSCENE_TOTAL,
  expansionCutscenePosterUrl,
  expansionCutscenesByCategory,
  expansionCutsceneVideoUrl,
  type ExpansionCutsceneCategory,
} from "../cinematicsManifest";

describe("expansionCutscenes (NEW_CUTSCENES_67.zip + chess roster)", () => {
  it("loads 92 mp4 entries (67 NEW_CUTSCENES_67 + 25 chess)", () => {
    expect(EXPANSION_CUTSCENE_TOTAL).toBe(92);
    expect(EXPANSION_CUTSCENES.length).toBe(92);
  });

  it("every entry has a unique id", () => {
    const ids = new Set<string>();
    for (const c of EXPANSION_CUTSCENES) {
      expect(ids.has(c.id)).toBe(false);
      ids.add(c.id);
    }
    expect(ids.size).toBe(92);
  });

  it("every videoRelPath is under art/cutscenes/<category>/", () => {
    for (const c of EXPANSION_CUTSCENES) {
      expect(c.videoRelPath.startsWith(`art/cutscenes/${c.category}/`)).toBe(
        true,
      );
      expect(c.videoRelPath.endsWith(".mp4")).toBe(true);
    }
  });

  it("every posterRelPath (when set) ends in _start.png", () => {
    let posterCount = 0;
    for (const c of EXPANSION_CUTSCENES) {
      if (c.posterRelPath) {
        posterCount += 1;
        expect(c.posterRelPath.endsWith("_start.png")).toBe(true);
        expect(c.posterRelPath.startsWith(`art/cutscenes/${c.category}/`)).toBe(
          true,
        );
      }
    }
    // Every cutscene now declares a canonical `<stem>_start.png`
    // poster path: 9 producer-supplied NEW_CUTSCENES_67 + 58 ffmpeg-
    // generated via apps/scripts/extract_cutscene_posters.sh + 25
    // chess cutscenes (producer-supplied; both _start.png and
    // _end.png available on CDN for the chess set).
    expect(posterCount).toBe(92);
  });

  it("covers the 13 declared categories with the expected counts", () => {
    const expected: Record<ExpansionCutsceneCategory, number> = {
      berth: 4,
      cohort_park: 4,
      comm_screen: 5,
      doctrine_binding: 7,
      forge: 5,
      guild_room: 21,
      mechronis_audit: 6,
      memory_card: 4,
      mission: 7,
      wardens_dock: 4,
      chess_tutorial: 9,
      chess_ladder: 12,
      chess_climb: 4,
    };
    for (const [cat, count] of Object.entries(expected) as [
      ExpansionCutsceneCategory,
      number,
    ][]) {
      expect(expansionCutscenesByCategory(cat).length).toBe(count);
    }
    const totalByCat = Object.values(expected).reduce((a, b) => a + b, 0);
    expect(totalByCat).toBe(92);
  });

  it("expansionCutsceneVideoUrl returns canonical CDN URL for a known clip", () => {
    const url = expansionCutsceneVideoUrl("cs_forge_first_creation");
    expect(url).toBe(
      "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/client-public/art/cutscenes/forge/cs_forge_first_creation.mp4",
    );
  });

  it("expansionCutscenePosterUrl returns the producer-supplied poster", () => {
    const url = expansionCutscenePosterUrl("cs_forge_first_creation");
    // Producer stem mismatch: cs_forge_first_start.png is the poster
    // for cs_forge_first_creation.mp4 (prefix match in the generator).
    expect(url).toBe(
      "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/client-public/art/cutscenes/forge/cs_forge_first_start.png",
    );
  });

  it("expansionCutscenePosterUrl resolves a canonical _start.png for every NEW_CUTSCENES_67 cutscene", () => {
    // Post-2026-05-12: every cutscene has a declared posterRelPath
    // (9 producer-supplied + 58 to be generated by
    // apps/scripts/extract_cutscene_posters.sh + uploaded via the
    // standard wrapper). The 25 chess cutscenes (chessCutscenes.data.ts)
    // do not yet carry a posterRelPath — they intentionally return
    // undefined until the producer renders them.
    expect(expansionCutscenePosterUrl("cs_forge_failure")).toBe(
      "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/client-public/art/cutscenes/forge/cs_forge_failure_start.png",
    );
    expect(expansionCutscenePosterUrl("cs_berth_sleep")).toBe(
      "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/client-public/art/cutscenes/berth/cs_berth_sleep_start.png",
    );
    // Chess cutscene (poster now declared after producer delivery).
    expect(expansionCutscenePosterUrl("cs_chess_tut_g1_intro")).toBe(
      "https://dgrsart.s3.us-east-2.amazonaws.com/cdn/client-public/art/cutscenes/chess_tutorial/cs_chess_tut_g1_intro_start.png",
    );
  });
});
