import { describe, expect, it } from "vitest";
import {
  CRT_BROADCAST_FRAME_NOTE,
  LOGIN_MEME_FIRST_EVER_SHOTS,
  LOGIN_MEME_HANDOFF_FRAME_URL,
  LOGIN_MEME_TOTAL_DURATION_MS,
  SHOT_DURATION_MS,
} from "../loginMemeSequence";
import { ALBUM1_T01_SLIDESHOW } from "../../songSlideshows";

const MUSIC_TOKEN_REGEX =
  /\b(music|score|soundtrack|theme song|orchestral|melody|harmony|chord|drum kit|bassline|synth pad)\b/i;

describe("loginMemeSequence", () => {
  it("contains exactly 15 shots", () => {
    expect(LOGIN_MEME_FIRST_EVER_SHOTS).toHaveLength(15);
  });

  it("declares a total runtime of 3:45 (225 seconds)", () => {
    expect(LOGIN_MEME_TOTAL_DURATION_MS).toBe(225_000);
  });

  it("uses 15-second shots throughout", () => {
    for (const shot of LOGIN_MEME_FIRST_EVER_SHOTS) {
      expect(shot.endMs - shot.startMs).toBe(SHOT_DURATION_MS);
    }
  });

  it("chains end-keyframe of shot N to start of shot N+1", () => {
    for (let i = 0; i < LOGIN_MEME_FIRST_EVER_SHOTS.length - 1; i++) {
      expect(LOGIN_MEME_FIRST_EVER_SHOTS[i]!.endMs).toBe(
        LOGIN_MEME_FIRST_EVER_SHOTS[i + 1]!.startMs,
      );
    }
  });

  it("numbers shots 1..15 in order", () => {
    LOGIN_MEME_FIRST_EVER_SHOTS.forEach((shot, idx) => {
      expect(shot.shotNumber).toBe(idx + 1);
    });
  });

  it("never contains music tokens in any prompt or sfx field", () => {
    // The cinematic is SFX + dialog only. The actual song audio is
    // layered by the client PlayerContext, not generated by Kling.
    // If a producer ever sneaks 'music' or 'score' into a prompt,
    // Kling will generate music and the layered T01 audio will collide.
    for (const shot of LOGIN_MEME_FIRST_EVER_SHOTS) {
      for (const [field, value] of Object.entries({
        klingPrompt: shot.klingPrompt,
        klingMotion: shot.klingMotion,
        sfxNotes: shot.sfxNotes,
      })) {
        if (MUSIC_TOKEN_REGEX.test(value)) {
          throw new Error(
            `Shot ${shot.shotNumber} field "${field}" contains a music token: ${value.match(MUSIC_TOKEN_REGEX)?.[0]}`,
          );
        }
      }
    }
  });

  it("every shot has non-empty prompt, motion, sfx, and dialog", () => {
    for (const shot of LOGIN_MEME_FIRST_EVER_SHOTS) {
      expect(shot.klingPrompt.length).toBeGreaterThan(50);
      expect(shot.klingMotion.length).toBeGreaterThan(20);
      expect(shot.sfxNotes.length).toBeGreaterThan(15);
      expect(shot.dialog.length).toBeGreaterThan(0);
    }
  });

  it("CRT_BROADCAST_FRAME_NOTE describes the canonical broadcast treatment", () => {
    expect(CRT_BROADCAST_FRAME_NOTE).toMatch(/CRT/i);
    expect(CRT_BROADCAST_FRAME_NOTE).toMatch(/scan line/i);
    expect(CRT_BROADCAST_FRAME_NOTE).toMatch(/lower-third/i);
  });

  it("the final shot hands off to ALBUM1_T01_SLIDESHOW.frames[0]", () => {
    const finalShot =
      LOGIN_MEME_FIRST_EVER_SHOTS[LOGIN_MEME_FIRST_EVER_SHOTS.length - 1]!;
    expect(finalShot.shotNumber).toBe(15);
    // The handoff URL is asserted at module load — the export here
    // is just a sentinel for downstream consumers.
    expect(LOGIN_MEME_HANDOFF_FRAME_URL).toBe(
      ALBUM1_T01_SLIDESHOW.frames[0]!.imageUrl,
    );
    expect(LOGIN_MEME_HANDOFF_FRAME_URL.length).toBeGreaterThan(0);
  });

  it("opens with the player's first words from The Meme: 'Frens'", () => {
    expect(LOGIN_MEME_FIRST_EVER_SHOTS[0]!.dialog).toMatch(/Frens/);
  });

  it("closes with 'They hate that.' as a whisper after Welcome to Dischordia", () => {
    const second_to_last = LOGIN_MEME_FIRST_EVER_SHOTS[13]!;
    const last = LOGIN_MEME_FIRST_EVER_SHOTS[14]!;
    expect(second_to_last.dialog).toMatch(/Welcome to Dischordia/);
    expect(second_to_last.dialog).toMatch(/Play it loud/);
    expect(last.dialog).toMatch(/They hate that/);
  });

  it("never promises a daily-login experience in dialog", () => {
    const forbidden = /every login|every time you log in|each day|daily/i;
    for (const shot of LOGIN_MEME_FIRST_EVER_SHOTS) {
      expect(shot.dialog).not.toMatch(forbidden);
    }
  });
});
